### ISSUE TITLE
【缺陷】0.8.5订阅深度删除plex不存在的资源出错

### ISSUE THREAD

**Issue by BruceSuen720** [pofey/movie_robot#105]
0.8.5版本，连接媒体库为plex时，plex媒体库中电影已经删除的情况下，在机器人webUI中删除订阅勾选深度删除时，提示

`2022/05/11 09:47:02 - SubRequestConsumer - ERROR: 处理订阅请求消息出错：(404) not_found; http://192.168.1.200:32400/library/metadata/68477 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
Traceback (most recent call last):
  File "yee/consumer/subrequestconsumer.py", line 54, in yee.consumer.subrequestconsumer.SubRequestConsumer.run
  File "yee/consumer/subrequestconsumer.py", line 82, in yee.consumer.subrequestconsumer.SubRequestConsumer.delete_sub
  File "yee/core/plexmediaserver.py", line 68, in yee.core.plexmediaserver.PlexMediaServer.delete_movie
  File "/dependencies/plexapi/base.py", line 574, in delete
    return self._server.query(self.key, method=self._server._session.delete)
  File "/dependencies/plexapi/server.py", line 680, in query
    raise NotFound(message)
plexapi.exceptions.NotFound: (404) not_found; http://192.168.1.200:32400/library/metadata/68477 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>`

**Comment by pofey** [comment]
0.8.6已经解决了
