### ISSUE TITLE
【BUG】字幕下载出错，提示Cannot find working tool

### ISSUE THREAD

**Issue by elecxwr** [pofey/movie_robot#109]
版本: latest 0.8.8
平台: QNAP TS453D mini
字幕任务log如下:
```
2022-05-11 12:20:00,014 - MainThread - INFO: 收到字幕处理消息：{'task_id': 1, 'content_path': '/share/CACHEDEV3_DATA/video/movie/emby_movie/监守自盗 (2010) [tmdbid=44639]', 'media_info': {'tmdb_id': 44639, 'type': 'Movie', 'name': '监守自盗', 'year': 2010, 'season_year': None, 'season_index': None, 'episodes': None}}
2022-05-11 12:20:00,046 - MainThread - INFO: 开始在Zimuku搜索 监守自盗
2022-05-11 12:20:04,335 - MainThread - INFO: 开始在Subhd搜索 监守自盗
2022-05-11 12:20:05,694 - MainThread - INFO: 搜索到11条字幕信息
2022-05-11 12:20:05,706 - MainThread - INFO: 开始下载监守自盗(2010) 的字幕: 监守自盗.Inside.Job.2010.720p.BluRay.
2022-05-11 12:25:05,937 - MainThread - INFO: 字幕保存路径：/data/subtitle/监守自盗.rar
2022-05-11 12:25:05,992 - MainThread - ERROR: 下载字幕出错：Cannot find working tool
Traceback (most recent call last):
  File "yee/process/downloadsubtitleprocess.py", line 169, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.run
  File "yee/process/downloadsubtitleprocess.py", line 96, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.__download_movie_sub__
  File "yee/subtitle/subdownloader.py", line 69, in yee.subtitle.subdownloader.SubDownloader.download
  File "yee/subtitle/subextract.py", line 113, in yee.subtitle.subextract.SubFileHandle.__init__
  File "yee/subtitle/subextract.py", line 68, in yee.subtitle.subextract.SubExtract.extract_file
  File "yee/subtitle/subextract.py", line 45, in yee.subtitle.subextract.SubExtract.extract_rar
  File "yee/subtitle/subextract.py", line 46, in yee.subtitle.subextract.SubExtract.extract_rar
  File "/dependencies/rarfile.py", line 847, in extractall
    dst = self._extract_one(inf, path, pwd, not inf.is_dir())
  File "/dependencies/rarfile.py", line 912, in _extract_one
    return self._make_file(info, dstfn, pwd, set_attrs)
  File "/dependencies/rarfile.py", line 925, in _make_file
    with self.open(info, "r", pwd) as src:
  File "/dependencies/rarfile.py", line 783, in open
    return self._file_parser.open(inf, pwd)
  File "/dependencies/rarfile.py", line 1237, in open
    return self._open_hack(inf, pwd)
  File "/dependencies/rarfile.py", line 1621, in _open_hack
    return self._open_hack_core(inf, pwd, prefix, b"")
  File "/dependencies/rarfile.py", line 1275, in _open_hack_core
    return self._open_unrar(tmpname, inf, pwd, tmpname)
  File "/dependencies/rarfile.py", line 1286, in _open_unrar
    setup = tool_setup()
  File "/dependencies/rarfile.py", line 3331, in tool_setup
    raise RarCannotExec("Cannot find working tool")
rarfile.RarCannotExec: Cannot find working tool
```
[task_subtitle.log](https://github.com/pofey/movie_robot/files/8676651/task_subtitle.log)

**Comment by Howardnm** [comment]
- 版本：0.93
- synology docker
- 目测原因：rar文件解压失败

![image](https://user-images.githubusercontent.com/55622355/168216851-2ee4c869-9c3a-410e-8f92-73ae84f8847d.png)

```
2022-05-13 08:23:10,474 - MainThread - INFO: 开始下载感谢你抽烟(2005) 的字幕: 本字幕按 感谢你抽烟.Thank.You.For.Smoking.2005.HDTV.720P 版本分割
2022-05-13 08:23:23,311 - MainThread - INFO: 字幕保存路径：/data/subtitle/感谢你抽烟.Thank.You.For.Smoking.2005.HDTV.x264.aac.720P-SDHF.NORMTEAM.GV-Sir.rar
2022-05-13 08:23:23,395 - MainThread - ERROR: 下载字幕出错：Cannot find working tool
Traceback (most recent call last):
  File "yee/process/downloadsubtitleprocess.py", line 168, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.run
  File "yee/process/downloadsubtitleprocess.py", line 96, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.__download_movie_sub__
  File "yee/subtitle/subdownloader.py", line 68, in yee.subtitle.subdownloader.SubDownloader.download
  File "yee/subtitle/subextract.py", line 114, in yee.subtitle.subextract.SubFileHandle.__init__
  File "yee/subtitle/subextract.py", line 69, in yee.subtitle.subextract.SubExtract.extract_file
  File "yee/subtitle/subextract.py", line 46, in yee.subtitle.subextract.SubExtract.extract_rar
  File "yee/subtitle/subextract.py", line 47, in yee.subtitle.subextract.SubExtract.extract_rar
  File "/dependencies/rarfile.py", line 847, in extractall
    dst = self._extract_one(inf, path, pwd, not inf.is_dir())
  File "/dependencies/rarfile.py", line 912, in _extract_one
    return self._make_file(info, dstfn, pwd, set_attrs)
  File "/dependencies/rarfile.py", line 925, in _make_file
    with self.open(info, "r", pwd) as src:
  File "/dependencies/rarfile.py", line 783, in open
    return self._file_parser.open(inf, pwd)
  File "/dependencies/rarfile.py", line 1237, in open
    return self._open_hack(inf, pwd)
  File "/dependencies/rarfile.py", line 1621, in _open_hack
    return self._open_hack_core(inf, pwd, prefix, b"")
  File "/dependencies/rarfile.py", line 1275, in _open_hack_core
    return self._open_unrar(tmpname, inf, pwd, tmpname)
  File "/dependencies/rarfile.py", line 1286, in _open_unrar
    setup = tool_setup()
  File "/dependencies/rarfile.py", line 3331, in tool_setup
    raise RarCannotExec("Cannot find working tool")
rarfile.RarCannotExec: Cannot find working tool
```

**Comment by pofey** [comment]
是的，发现了不能解压rar，这个手动搞定吧，我在镜像里打包一个unrar试一下
