### ISSUE TITLE
【BUG】豆瓣信息无法拉取

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#110]
升级到0.9.3后，豆瓣信息无法拉取
报错信息如下
AttributeError: 'NoneType' object has no attribute 'ranking_list'
2022/05/13 11:58:27 - Thread-35 - ERROR: 请求出错：'NoneType' object has no attribute 'ranking_list'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 32, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/moviecontroller.py", line 177, in yee.controller.moviecontroller.douban_rank_list
AttributeError: 'NoneType' object has no attribute 'ranking_list'

**Comment by pofey** [comment]
你这是没配置豆瓣吧 截图豆瓣配置我看看
