### ISSUE TITLE
rarbg直接搜索下载失败

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#128]
2022/05/15 14:41:14 - DownloadConsumer - INFO: 开始处理来自Web的下载: [rarbg]The.Platform.2019.SPANISH.1080p.WEBRip.x264-VXT
2022/05/15 14:43:41 - DownloadConsumer - ERROR: 处理下载任务失败：
Traceback (most recent call last):
  File "yee/consumer/downloadconsumer.py", line 28, in yee.consumer.downloadconsumer.DownloadConsumer.run
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/dependencies/tenacity/__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/service/downloadservice.py", line 295, in yee.service.downloadservice.DownloadService.download_from_web
  File "yee/site/rarbg.py", line 68, in yee.site.rarbg.Rarbg.download
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "yee/site/rarbg.py", line 64, in fetch_that_torrent
  File "/dependencies/magnet2torrent/magnet2torrent.py", line 171, in retrieve_torrent
    raise FailedToFetchException()
magnet2torrent.exceptions.FailedToFetchException

**Comment by elic6699** [comment]
订阅后通过rarbg下载也不成功，log显示成功发送下载任务，但是qbittorrent里没有新建任务
2022/05/15 15:35:01 - SubConsumer - INFO: 黑钱胜地(2017) 第1季 全集 品质：WEB-Rip 1080p x264 资源: https://torrentapi.org/redirect_to_info.php?token=0uk78negba&p=1_6_2_7_0_4_2__c78eb35a86 已经提交下载。
 2022/05/15 15:35:01 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [rarbg]Ozark.S01.1080p.NF.WEBRip.DD5.1.x264-NTb[rartv]
 2022/05/15 15:35:01 - SubConsumer - INFO: 黑钱胜地(2017) 第1季 本次下载的种子中，包含有全集字样信息，将默认本剧完结，停止订阅不再智能下载。

**Comment by pofey** [comment]
磁力链拉失败，你把这两个磁力链搜出来发到这我找时间试试

**Comment by elic6699** [comment]
magnet:?xt=urn:btih:c78eb35a86ce81e5c80d8b296f8e588f296eb406&dn=Ozark.S01.1080p.NF.WEBRip.DD5.1.x264-NTb%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2840&tr=udp%3A%2F%2F9.rarbg.to%3A2940

**Comment by elic6699** [comment]
magnet:?xt=urn:btih:e92299ff895592ed16a2e107597fff8dbc8d469d&dn=The.Platform.2019.SPANISH.1080p.WEBRip.x264-VXT&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2860&tr=udp%3A%2F%2F9.rarbg.to%3A2790

**Comment by elic6699** [comment]
发现magnet2torrent，相同的磁力链接有时候转换失败有时成功，是不是可能和网络有关，建议提交一次后缓存任务，失败就隔时间反复提交。否则还要不停到后台自己去看是否成功。
