### ISSUE TITLE
magnet2torrent 磁力链接总是出错

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#135]
2022/05/16 10:39:02 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [rarbg]Gone.Girl.2014.PROPER.1080p.BluRay.H264.AAC-RARBG
 2022/05/16 10:41:29 - DownloadConsumer - ERROR: 处理下载任务失败：
Traceback (most recent call last):
  File "yee/consumer/downloadconsumer.py", line 32, in yee.consumer.downloadconsumer.DownloadConsumer.run
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/dependencies/tenacity/__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/service/downloadservice.py", line 406, in yee.service.downloadservice.DownloadService.download_from_sub
  File "yee/site/rarbg.py", line 68, in yee.site.rarbg.Rarbg.download
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "yee/site/rarbg.py", line 64, in fetch_that_torrent
  File "/dependencies/magnet2torrent/magnet2torrent.py", line 171, in retrieve_torrent
    raise FailedToFetchException()
magnet2torrent.exceptions.FailedToFetchException

**Comment by pofey** [comment]
下一版本把提交到qbit的bt种子，变成磁力链提交模式，机器人自己不在转种子了。
