### ISSUE TITLE
首次启动报错，提示max_workers must be greater than 0

### ISSUE THREAD

**Issue by Totobo** [pofey/movie_robot#136]
我是新建了一个系统，新安装的mr，下面是输出的日志
```

启动升级脚本
完成系统默认配置初始化。
完成数据表升级。
2022/05/16 18:53:23 - MainThread - INFO: 首次启动应用，请尽快访问页面进行初始化设置http://ip:1329/setup/admin
2022/05/16 18:53:37 - MainThread - ERROR: Uncaught exception
Traceback (most recent call last):
  File "/app/start.py", line 27, in <module>
    import yee.app as app
  File "yee/app.py", line 46, in init yee.app
  File "yee/register/service_register.py", line 43, in yee.register.service_register.init_service
  File "yee/service/siteservice.py", line 43, in yee.service.siteservice.SiteService.init_service
  File "yee/service/siteservice.py", line 47, in yee.service.siteservice.SiteService.get_site_thread_pool
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 141, in __init__
    raise ValueError("max_workers must be greater than 0")
ValueError: max_workers must be greater than 0

```

操作系统是unraid，主要从报错看不出来需要从哪些地方排查，衣大帮忙看下

**Comment by pofey** [comment]
是个bug 我修复一下

**Comment by Totobo** [comment]
> 是个bug 我修复一下

好，新版本发布了麻烦说一下，我测试看看。

**Comment by pofey** [comment]
发完了
