### ISSUE TITLE
整季下载的电视剧没有集信息就无法下载字幕

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#158]
一个种子为整季电视剧没有集号信息就无法下载字幕
种子名称：
[Breaking.Bad.S03.1080p.BluRay.x265-RARBG]
(https://torrentapi.org/redirect_to_info.php?token=vyitrmhan6&p=2_6_8_0_0_0_5__3d98251afd)

2022-05-18 17:27:00,008 - MainThread - INFO: 收到字幕处理消息：{'task_id': 21, 'content_path': '/video/电视剧-jellyfin/绝命毒师 (2008) [tmdbid=1396]/Season 3', 'media_info': {'tmdb_id': 1396, 'type': 'TV', 'name': '绝命毒师', 'year': 2008, 'season_year': 2011, 'season_index': 4, 'episodes': None}}
2022-05-18 17:27:00,008 - MainThread - INFO: 绝命毒师 第3季 (2011) 缺少集号，终止下载。
2022-05-18 17:27:00,043 - MainThread - ERROR: 下载字幕出错：'NoneType' object is not iterable
Traceback (most recent call last):
  File "yee/process/downloadsubtitleprocess.py", line 168, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.run
  File "yee/process/downloadsubtitleprocess.py", line 116, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.__download_tv_sub__
TypeError: 'NoneType' object is not iterable

请问该情况是否可以优化，谢谢

**Comment by pofey** [comment]
你这个是手动在web搜索后下载的吧？

**Comment by pofey** [comment]
0.9.10修复这个问题，对下载完的记录做一次实际集数分析

**Comment by elic6699** [comment]
不是，是jellyseerr订阅的
