### ISSUE TITLE
字幕下载错误

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#182]
Log如下：
2022-05-21 08:07:00,006 - MainThread - INFO: 收到字幕处理消息：{'task_id': 37, 'content_path': '/video/电影-jellyfin/锈与骨 (2012) [tmdbid=97365]', 'media_info': {'tmdb_id': 97365, 'type': 'Movie', 'name': '锈与骨', 'year': 2012, 'season_year': None, 'season_index': None, 'episodes': None}}
2022-05-21 08:07:00,007 - MainThread - ERROR: 下载字幕出错：'NoneType' object has no attribute 'search_by_id'
Traceback (most recent call last):
  File "yee/process/downloadsubtitleprocess.py", line 168, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.run
  File "yee/process/downloadsubtitleprocess.py", line 81, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.__download_movie_sub__
AttributeError: 'NoneType' object has no attribute 'search_by_id'
2022-05-21 09:38:00,011 - MainThread - INFO: 收到字幕处理消息：{'task_id': 39, 'content_path': '/video/电影-jellyfin/玫瑰岛的不可思议的历史 (2020) [tmdbid=636565]', 'media_info': {'tmdb_id': 636565, 'type': 'Movie', 'name': '玫瑰岛的不可思议的历史', 'year': 2020, 'season_year': None, 'season_index': None, 'episodes': None}}
2022-05-21 09:38:00,011 - MainThread - ERROR: 下载字幕出错：'NoneType' object has no attribute 'search_by_id'
Traceback (most recent call last):
  File "yee/process/downloadsubtitleprocess.py", line 168, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.run
  File "yee/process/downloadsubtitleprocess.py", line 81, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.__download_movie_sub__
AttributeError: 'NoneType' object has no attribute 'search_by_id'

**Comment by pofey** [comment]
你自己的媒体服务器挂了

**Comment by elic6699** [comment]
没挂，jellfin一切正常，movierobot日志中也没显示媒体服务器错误
昨天重启jellyfin，token换了，会不会这个原因？

**Comment by elic6699** [comment]
2022/05/21 09:38:00 - SubRequestConsumer - INFO: 玫瑰岛的不可思议的历史(2020)字幕下载 下次运行时间：2022-05-21 10:08:00
 2022/05/21 09:41:24 - ThreadPoolExecutor-1_3 - INFO: 开始同步站点资源信息...
 2022/05/21 09:41:36 - MainThread - INFO: 站点并发线程数：6
 2022/05/21 09:41:36 - MainThread - INFO: Jellyfin连接正常，9918610a33e0版本为10.7.7

**Comment by elic6699** [comment]
好像把token换成api key就解决了
