### ISSUE TITLE
手动硬链接报错

### ISSUE THREAD

**Issue by u93724** [pofey/movie_robot#216]
在下完一步剧后，发现没有自动硬链接便尝试手动硬链接，报错如下
python commandapp.py -w=/data -a=moviesmanager --source-type=tv --source-dir=/source/downloaded/tv --target-dir=/source/personal/Download/tv --file-mode=link
2022/05/27 15:16:29 - MainThread - INFO: 开始处理剧集目录 /source/downloaded/tv 目标目录：/source/personal/Download/tv
2022/05/27 15:16:29 - MainThread - ERROR: Uncaught exception
Traceback (most recent call last):
  File "commandapp.py", line 68, in <module>
    CommandActions.movies_manager(tmdb_config['api_key'],base_config.movie_metadata.get('proxies'), args.file_mode, args.use_country_folder,
  File "yee/commandactions.py", line 21, in yee.commandactions.CommandActions.movies_manager
  File "yee/core/moviefilemanager.py", line 111, in yee.core.moviefilemanager.MovieFileManager.walk_tv_folder
  File "yee/core/moviefilemanager.py", line 129, in yee.core.moviefilemanager.MovieFileManager.handle_tv
  File "yee/movie/movieanalyze.py", line 153, in yee.movie.movieanalyze.MovieAnalyze.analyze_tv
  File "yee/movie/movieanalyze.py", line 86, in yee.movie.movieanalyze.MovieAnalyze.analyze_tv_name
  File "yee/movie/tmdbapi.py", line 53, in yee.movie.tmdbapi.TmdbApi.multi_search
  File "yee/movie/tmdbapi.py", line 79, in yee.movie.tmdbapi.TmdbApi.search
  File "/usr/local/lib/python3.8/urllib/parse.py", line 866, in quote_plus
    string = quote(string, safe + space, encoding, errors)
  File "/usr/local/lib/python3.8/urllib/parse.py", line 844, in quote
    string = string.encode(encoding, errors)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb3' in position 32: surrogates not allowed

种子名称为
[BDrip] Kiseijuu -Sei no Kakuritsu- [JP][7³ACG@OurBits]

日志为
2022/05/27 11:38:18 - SubConsumer - INFO: 已经开始在站点: 馒头,北洋园 搜索: 寄生兽：生命的准则,Parasyte -the maxim-,tt3358020
2022/05/27 11:38:31 - SubConsumer - INFO: 共在2个站点搜索到4条结果，其中北洋园最慢，耗费12.34秒
2022/05/27 11:38:31 - SubConsumer - INFO: 寄生兽：生命的准则(2014) 第1季 第[24]集 品质：Blu-ray 1080p x265 资源: https://tjupt.org/details.php?id=292625&hit=1 已经提交下载。
2022/05/27 11:38:31 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [tjupt][日剧][寄生兽][Parasyte: The Maxim 2014 1080p Blu-ray x265 FLAC-7³ACG@OurBits]
2022/05/27 11:38:31 - DownloadConsumer - INFO: [tjupt][日剧][寄生兽][Parasyte: The Maxim 2014 1080p Blu-ray x265 FLAC-7³ACG@OurBits]已经开始下载,路径：/home/downloaded/tv 分类：未设置 
2022/05/27 12:00:00 - ThreadPoolExecutor-1_0 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
2022/05/27 12:08:40 - Thread-1098 - INFO: 已经开始在站点: 馒头,北洋园 搜索: 鬼怪
2022/05/27 12:08:46 - Thread-1098 - INFO: 共在2个站点搜索到39条结果，其中馒头最慢，耗费6.17秒
2022/05/27 12:30:00 - ThreadPoolExecutor-1_0 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
2022/05/27 13:00:00 - ThreadPoolExecutor-1_1 - INFO: 本次豆瓣想看同步到订阅任务已经完成。

**Comment by pofey** [comment]
日漫程序没做优化，加上有特殊字符，搞不定的，你可以把名字改成标准中文名再处理
