### ISSUE TITLE
0.9.36  更新后【应用设置】页面空白报错

### ISSUE THREAD

**Issue by Kev1nT** [pofey/movie_robot#231]
2022/05/29 22:34:24 - MainThread - INFO: 当前版本: 0.9.36
 2022/05/29 22:34:52 - Thread-27 - ERROR: 请求出错：'list' object has no attribute 'values'Traceback (most recent call last):
  File "yee/register/bp_register.py", line 32, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/downloadcontroller.py", line 24, in yee.controller.downloadcontroller.downloading
AttributeError: 'list' object has no attribute 'values'
 2022/05/29 22:35:24 - Thread-69 - ERROR: 请求出错：'type'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 32, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/settingcontroller.py", line 163, in yee.controller.settingcontroller.get_download_client.lambda
  File "yee/controller/settingcontroller.py", line 163, in yee.controller.settingcontroller.get_download_client.lambda
KeyError: 'type'

0.9.36 BETA   
更新前正常
请问是哪里出了错？

**Comment by pofey** [comment]
base config配置文件中 download client部分 应该有一条配置缺少type，再升级过程升坏了，可以打开配置文件手动补上type，修复掉，或者干掉这条

**Comment by pofey** [comment]
新版兼容了这个错误
