### ISSUE TITLE
字幕下载出错   版本号  0.9.50

### ISSUE THREAD

**Issue by yubonijin** [pofey/movie_robot#273]
2022-06-07 10:12:00,007 - MainThread - INFO: 收到字幕处理消息：{'task_id': 14, 'content_path': '/share/CACHEDEV2_DATA/emby/电影/Everything Everywhere All at Once (2022) [tmdbid=545611]', 'media_info': {'tmdb_id': 545611, 'type': 'Movie', 'name': 'Everything Everywhere All at Once', 'year': 2022, 'season_year': None, 'season_index': None, 'episodes': None}}
2022-06-07 10:12:00,027 - MainThread - INFO: 开始在Zimuku搜索 Everything Everywhere All at Once
2022-06-07 10:12:00,998 - MainThread - INFO: 开始在Subhd搜索 Everything Everywhere All at Once
2022-06-07 10:12:02,005 - MainThread - INFO: 搜索到25条字幕信息
2022-06-07 10:12:02,006 - MainThread - INFO: 开始下载Everything Everywhere All at Once(2022) 的字幕: 【增加双语特效】Everything.Everywhere.All.At.Once.2022.1080p.WEB-DL.DDP5.1.H.264-EVO
2022-06-07 10:13:17,393 - MainThread - ERROR: 下载字幕出错：Message: 
Stacktrace:
#0 0x55b25434ce89 <unknown>
Traceback (most recent call last):
  File "yee/process/downloadsubtitleprocess.py", line 174, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.run
  File "yee/process/downloadsubtitleprocess.py", line 102, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.__download_movie_sub__
  File "yee/subtitle/subdownloader.py", line 80, in yee.subtitle.subdownloader.SubDownloader.download
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/dependencies/tenacity/__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/subtitle/find/subhd.py", line 178, in yee.subtitle.find.subhd.Subhd.download
  File "/dependencies/selenium/webdriver/support/wait.py", line 87, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55b25434ce89 <unknown>

**Comment by pofey** [comment]
看着是subhd下载超时了 手动访问检查下网络联通性先
