### ISSUE TITLE
【ERROR】订阅下载出错

### ISSUE THREAD

**Issue by nicedc** [pofey/movie_robot#288]
版本9.53
从9.44版本升级至9.53版本 几部订阅中的剧集出现一样的报错 
新订阅同样提示类似以下SubConsumer - ERROR
完整log
2022/06/09 09:26:49 - SubConsumer - ERROR: 警察荣誉(2022) 订阅下载出错！
Traceback (most recent call last):
  File "yee/consumer/subconsumer.py", line 276, in yee.consumer.subconsumer.SubConsumer.handle_sub
  File "yee/service/smartdownloadservice.py", line 59, in yee.service.smartdownloadservice.SmartDownloadService.get_missing_episodes
  File "yee/core/embymediaserver.py", line 136, in yee.core.embymediaserver.EmbyMediaServer.search_by_id
  File "/dependencies/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

同时发现这个数据库问题 看到已经有一个以关闭的提到了，不知道是不是这个原因 一并附上日志
2022/06/09 09:30:17 - Thread-674 - ERROR: 请求出错：(sqlite3.OperationalError) database is locked
[SQL: UPDATE notification SET status=? WHERE notification.id = ?]
[parameters: (1, 178)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/dependencies/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yee/register/bp_register.py", line 32, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/usercontroller.py", line 84, in yee.controller.usercontroller.get_all_sys_notify
  File "yee/service/notifyservice.py", line 80, in yee.service.notifyservice.NotifyService.get_all_sys_notify
  File "yee/common/basemodel.py", line 99, in yee.common.basemodel.BaseModel.update
  File "yee/common/basemodel.py", line 96, in yee.common.basemodel.BaseModel.update
  File "<string>", line 2, in commit
  File "/dependencies/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/dependencies/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/dependencies/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/dependencies/sqlalchemy/orm/session.py", line 3383, in flush
    self._flush(objects)
  File "/dependencies/sqlalchemy/orm/session.py", line 3523, in _flush
    transaction.rollback(_capture_exception=True)
  File "/dependencies/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/orm/session.py", line 3483, in _flush
    flush_context.execute()
  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/dependencies/sqlalchemy/orm/persistence.py", line 237, in save_obj
    _emit_update_statements(
  File "/dependencies/sqlalchemy/orm/persistence.py", line 1001, in _emit_update_statements
    c = connection._execute_20(
  File "/dependencies/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/dependencies/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/dependencies/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/dependencies/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/dependencies/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: UPDATE notification SET status=? WHERE notification.id = ?]
[parameters: (1, 178)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by pofey** [comment]
1、订阅是你的emby连接有问题
2、报锁超时是你硬盘io不稳定，把docker启动和配置目录换到ssd
