### ISSUE TITLE
「bug」多通知渠道挂一个导致全部不通知

### ISSUE THREAD

**Issue by M-chacha** [pofey/movie_robot#294]
同时设置了bark和企微通知，当bark通知挂了发不出的时候，导致企微也不通知了。
版本：test 0.9.54
相关log：
2022/06/10 03:45:00 - ThreadPoolExecutor-3_0 - INFO: 开始为电影 黑暗侵袭 (2005)做文件转移 源路径：/downloads/电影/国外电影/The.Descent.2005.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-CHD 链接路径：/downloads/link/电影/国外电影
 2022/06/10 03:45:00 - ThreadPoolExecutor-3_0 - INFO: 已处理：黑暗侵袭 (2005) 源路径: /downloads/电影/国外电影/The.Descent.2005.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-CHD/The.Descent.2005.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-CHD.mkv, 目的路径: /downloads/link/电影/国外电影/黑暗侵袭 (2005) [tmdbid=9392]/黑暗侵袭 (2005) [tmdbid=9392] - 1080p x265 10bit DTS-HD.mkv 
 2022/06/10 03:45:02 - ThreadPoolExecutor-3_0 - INFO: 黑暗侵袭(2005)字幕下载 任务已经创建。
 2022/06/10 03:45:12 - ThreadPoolExecutor-3_0 - INFO: 错误信息：HTTPSConnectionPool(host='api.day.app', port=443): Read timed out. (read timeout=10)
 2022/06/10 03:45:12 - ThreadPoolExecutor-3_0 - ERROR: 监控种子任务出现错误：'NoneType' object has no attribute 'json'
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 363, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/notifyservice.py", line 235, in yee.service.notifyservice.NotifyService.notify_by_movie
  File "yee/notify/barknotify.py", line 68, in yee.notify.barknotify.BarkNotify.send
AttributeError: 'NoneType' object has no attribute 'json'
 2022/06/10 03:47:00 - ThreadPoolExecutor-3_2 - INFO: 黑暗侵袭(2005)字幕下载已经提交启动。

此时bark及企微都没有收到通知，但是硬链接已经完成。

**Comment by pofey** [comment]
test 已经修复
