### ISSUE TITLE
字幕下载出错求解

### ISSUE THREAD

**Issue by apple4105** [pofey/movie_robot#300]
你好，字幕下载出错，日志如下，看不出什么问题。
```
2022-06-11 15:03:00,008 - MainThread - INFO: 收到字幕处理消息：{'task_id': 8, 'content_path': '/video/emby/movie/Everything Everywhere All at Once (2022) [tmdbid=545611]', 'media_info': {'tmdb_id': 545611, 'type': 'Movie', 'name': 'Everything Everywhere All at Once', 'year': 2022, 'season_year': None, 'season_index': None, 'episodes': None}}
2022-06-11 15:03:00,069 - MainThread - INFO: Zimuku存在Everything Everywhere All at Once缓存，直接读取。
2022-06-11 15:03:00,070 - MainThread - INFO: Subhd存在Everything Everywhere All at Once缓存，直接读取。
2022-06-11 15:03:00,070 - MainThread - INFO: 搜索到29条字幕信息
2022-06-11 15:03:00,072 - MainThread - INFO: 开始下载Everything Everywhere All at Once(2022) 的字幕: 【增加双语特效】Everything.Everywhere.All.At.Once.2022.1080p.WEB-DL.DDP5.1.H.264-EVO
2022-06-11 15:04:22,672 - MainThread - ERROR: 下载字幕出错：Message: 
Stacktrace:
#0 0x55ee1d1c9e89 <unknown>
Traceback (most recent call last):
  File "yee/process/downloadsubtitleprocess.py", line 174, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.run
  File "yee/process/downloadsubtitleprocess.py", line 102, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.__download_movie_sub__
  File "yee/subtitle/subdownloader.py", line 80, in yee.subtitle.subdownloader.SubDownloader.download
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/dependencies/tenacity/__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/subtitle/find/subhd.py", line 178, in yee.subtitle.find.subhd.Subhd.download
  File "/dependencies/selenium/webdriver/support/wait.py", line 87, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55ee1d1c9e89 <unknown>
```

**Comment by pofey** [comment]
subhd 下载超时

**Comment by pofey** [comment]
我后面把程序这个下载超时时间改大一些

**Comment by kriskwok** [comment]
@pofey  最新版本还是有这个问题：
2022-06-19 16:52:47,502 - MainThread - ERROR: 下载字幕出错：Message: 
Stacktrace:
#0 0x7f5a0c06ce89 <unknown>
Traceback (most recent call last):
  File "yee/task/process/downloadsubtitleprocess.py", line 174, in yee.task.process.downloadsubtitleprocess.DownloadSubtitleProcess.run
  File "yee/task/process/downloadsubtitleprocess.py", line 102, in yee.task.process.downloadsubtitleprocess.DownloadSubtitleProcess.__download_movie_sub__
  File "yee/subtitle/subdownloader.py", line 80, in yee.subtitle.subdownloader.SubDownloader.download
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/dependencies/tenacity/__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/subtitle/find/subhd.py", line 199, in yee.subtitle.find.subhd.Subhd.download
  File "/dependencies/selenium/webdriver/support/wait.py", line 87, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x7f5a0c06ce89 <unknown>

**Comment by pofey** [comment]
要检查自己容器访问subhd的稳定性了 不行你就把subhd关了只下zimuku

**Comment by pofey** [comment]
当前版本的下载页等待时间是5秒，对一个国内网站来说很慢了
