### ISSUE TITLE
【求助】观众站获取种子哈希失败

### ISSUE THREAD

**Issue by haha6311** [pofey/movie_robot#302]
版 本：0.9.53
媒体库：PLEX
运行环境：OPENWRT-by FLIPPY docker arm64
说 明：观众站获取种子哈希失败，其他站点不会

```
2022/06/12 10:12:00 - DownloadConsumer - INFO: 开始处理免费种子下载任务: [audiences]Da Shen Hou S01 2020 2160p WEB-DL H265 AAC-ADWeb
 2022/06/12 10:12:00 - DownloadConsumer - ERROR: 获取种子hash失败：/data/torrent/bedfe8739251b65046d8810f69a85c79.torrent
 2022/06/12 10:12:00 - DownloadConsumer - ERROR: 处理下载任务失败：
Traceback (most recent call last):
  File "yee/consumer/downloadconsumer.py", line 39, in yee.consumer.downloadconsumer.DownloadConsumer.run
  File "yee/service/downloadservice.py", line 640, in yee.service.downloadservice.DownloadService.download_to_free_record
  File "yee/core/downloadclient.py", line 109, in yee.core.downloadclient.DownloadClient.info_hash
  File "yee/core/downloadclient.py", line 103, in yee.core.downloadclient.DownloadClient.info_hash
  File "yee/core/downloadclient.py", line 104, in yee.core.downloadclient.DownloadClient.info_hash
  File "/dependencies/bencoder.py", line 93, in decode
    ret, rest = decode_first(s)
  File "/dependencies/bencoder.py", line 88, in decode_first
    assert False
AssertionError
```

**Comment by pofey** [comment]
手动去下载检查吧
