### ISSUE TITLE
ERROR: 处理免费种子淘汰任务出错

### ISSUE THREAD

**Issue by haha6311** [pofey/movie_robot#305]
` 2022/06/12 20:58:00 - ThreadPoolExecutor-1_1 - ERROR: 处理免费种子淘汰任务出错：'NoneType' object has no attribute 'exists_hash'
Traceback (most recent call last):
  File "yee/task/freedownloadmonitortask.py", line 163, in yee.task.freedownloadmonitortask.FreeDownloadMonitor.run
  File "yee/task/freedownloadmonitortask.py", line 39, in yee.task.freedownloadmonitortask.FreeDownloadMonitor.update_data
AttributeError: 'NoneType' object has no attribute 'exists_hash'
`

**Comment by pofey** [comment]
整好自己的下载器吧

**Comment by haha6311** [comment]
如果有遇到和我一样问题的可以看一下开发大大的wiki：
[https://yee329.notion.site/e73e20b466104ca486ac37a26d81587d](url)
