### ISSUE TITLE
文件转移硬连接失败 timeout

### ISSUE THREAD

**Issue by nicedc** [pofey/movie_robot#309]
看见几个已关闭的同一问题，但是他们提示是转移失败：id 我这个是time out，所以不清楚是不是同一问题，是不是我自己环境有问题，麻烦衣总帮忙看下。

版本0.9.53，之前正常。

2022/06/13 21:06:01 - ThreadPoolExecutor-2_0 - INFO: 开始为剧集 警察荣誉 (2022)做文件转移 源路径：/vedio/download-t/警察荣誉.Ordinary.Greatness.2022.V2.1080p.WEB-DL.H264.AAC-OurTV 链接路径：/vedio/tv_p
2022/06/13 21:06:37 - ThreadPoolExecutor-2_0 - ERROR: 文件转移失败：timed out
2022/06/13 21:07:13 - ThreadPoolExecutor-2_0 - ERROR: 监控种子任务出现错误：timed out
Traceback (most recent call last):
  File "/dependencies/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/dependencies/httpcore/backends/sync.py", line 82, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/dependencies/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/dependencies/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/dependencies/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/dependencies/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/dependencies/httpcore/_sync/connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/dependencies/httpcore/backends/sync.py", line 82, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 57, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 363, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/notifyservice.py", line 215, in yee.service.notifyservice.NotifyService.notify_by_movie
  File "yee/movie/tmdbapi.py", line 118, in yee.movie.tmdbapi.TmdbApi.get_by_id
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/dependencies/tenacity/__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/movie/tmdbapi.py", line 73, in yee.movie.tmdbapi.TmdbApi.__do_get__
  File "/dependencies/httpx/_api.py", line 189, in get
    return request(
  File "/dependencies/httpx/_api.py", line 100, in request
    return client.request(
  File "/dependencies/httpx/_client.py", line 802, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/dependencies/httpx/_client.py", line 889, in send
    response = self._send_handling_auth(
  File "/dependencies/httpx/_client.py", line 917, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/dependencies/httpx/_client.py", line 954, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/dependencies/httpx/_client.py", line 990, in _send_single_request
    response = transport.handle_request(request)
  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: timed out

**Comment by pofey** [comment]
tmdb访问不稳定 弄dns
