### ISSUE TITLE
字幕下载出错

### ISSUE THREAD

**Issue by haha6311** [pofey/movie_robot#313]
版 本：`latest 0.9.53`
媒体库：`PLEX`
运行环境：`OPENWRT docker arm64`

你好，字幕下载出错，日志如下，看不出什么问题。

```
2022-06-15 13:53:00,068 - MainThread - INFO: 收到字幕处理消息：{'task_id': 21, 'content_path': '/video/电影/烈日灼人 (1994) [tmdbid=50797]', 'media_info': {'tmdb_id': 50797, 'type': 'Movie', 'name': '烈日灼人', 'year': 1994, 'season_year': None, 'season_index': None, 'episodes': None}}
2022-06-15 13:53:02,285 - MainThread - INFO: 开始在Zimuku搜索 烈日灼人
2022-06-15 13:53:07,303 - MainThread - INFO: 开始在Subhd搜索 烈日灼人
2022-06-15 13:53:08,747 - MainThread - INFO: 搜索到12条字幕信息
2022-06-15 13:53:08,754 - MainThread - INFO: 开始下载烈日灼人(1994) 的字幕: Utomlyonnye.solntsem.1994.1080p.WEB
2022-06-15 13:54:09,084 - MainThread - ERROR: 下载字幕出错：[Errno 8] Exec format error: 'chromedriver'
Traceback (most recent call last):
  File "yee/process/downloadsubtitleprocess.py", line 174, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.run
  File "yee/process/downloadsubtitleprocess.py", line 102, in yee.process.downloadsubtitleprocess.DownloadSubtitleProcess.__download_movie_sub__
  File "yee/subtitle/subdownloader.py", line 80, in yee.subtitle.subdownloader.SubDownloader.download
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/dependencies/tenacity/__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/subtitle/find/subhd.py", line 176, in yee.subtitle.find.subhd.Subhd.download
  File "/dependencies/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/dependencies/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/dependencies/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'chromedriver'
```

**Comment by haha6311** [comment]
<html>
<body>


架构 | AArch64 Processor : Cortex-A55 * 4

固件版本 | OpenWrt R22.5.5 / LuCI Master (git-22.155.62538-041a223)


</body>
</html>

**Comment by pofey** [comment]
这个坑没见过，是模拟浏览器的坑，我没设备也不好测。不过你可以通过关subhd，只用字幕库，当然要到beta版，或者等几天的latest了。
