### ISSUE TITLE
资源整理无法设置媒体路径和整理后路径

### ISSUE THREAD

**Issue by asd2003asd** [pofey/movie_robot#317]
资源整理点击选择媒体路径或者整理后路径会跳转到一个空白网页。日志：
2022/06/16 14:09:25 - Thread-37 - ERROR: 请求出错：'utf-8' codec can't encode characters in position 126-127: surrogates not allowed
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 32, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/commoncontroller.py", line 161, in yee.controller.commoncontroller.get_dirs
  File "yee/common/apiresult.py", line 28, in yee.common.apiresult.api_result
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 126-127: surrogates not allowed

**Comment by pofey** [comment]
你的文件夹或者名称中有什么特殊字符吗？

**Comment by asd2003asd** [comment]
![捕获](https://user-images.githubusercontent.com/19873779/174008093-0e9bcf79-6a7a-424d-9b56-264d91480deb.PNG)

**Comment by pofey** [comment]
说的是你所选择的那个路径下 会有特殊编码 你找找看

**Comment by asd2003asd** [comment]
谢谢，问题已经解决，刚才检查了一下/mnt下面确实有个带特殊字符的文件夹，命令行下面这个文件夹名称显示为 ''$'\343\200' ； rm -rf ''$'\343\200' 删除这个文件夹就正常了 。
