### ISSUE TITLE
[缺陷]: 电影、电视下载后无法匹配、转移至整理目录

### ISSUE THREAD

**Issue by zhengppeng** [pofey/movie_robot#343]
### 当前程序版本

0.9.44

### 问题描述

电影、电视下载后无法匹配、转移至整理目录

### 重现步骤

![image](https://user-images.githubusercontent.com/7529962/174703718-12fb9a51-342f-4c0a-93e2-230ccdbe49ed.png)

### 发生问题时系统日志

2022/06/21 10:26:36 - ThreadPoolExecutor-2_0 - ERROR: 文件转移失败：timed out
2022/06/21 10:26:36 - ThreadPoolExecutor-2_0 - ERROR: 监控种子任务出现错误：timed out
Traceback (most recent call last):
  File "/dependencies/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/dependencies/httpcore/backends/sync.py", line 82, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/dependencies/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/dependencies/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/dependencies/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/dependencies/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/dependencies/httpcore/_sync/connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/dependencies/httpcore/backends/sync.py", line 82, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 353, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 342, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 78, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/medialink.py", line 134, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 125, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 133, in yee.media.link.tvlink.TvLink.__handle__
  File "yee/metadata/mediarecognize.py", line 285, in yee.metadata.mediarecognize.MediaRecognize.recognize_tv
  File "yee/metadata/mediarecognize.py", line 189, in yee.metadata.mediarecognize.MediaRecognize.__search_query__
  File "yee/media/tmdbapi.py", line 131, in yee.media.tmdbapi.TmdbApi.get_by_id
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/dependencies/tenacity/__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/media/tmdbapi.py", line 86, in yee.media.tmdbapi.TmdbApi.__do_get__
  File "/dependencies/httpx/_api.py", line 189, in get
    return request(
  File "/dependencies/httpx/_api.py", line 100, in request
    return client.request(
  File "/dependencies/httpx/_client.py", line 802, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/dependencies/httpx/_client.py", line 889, in send
    response = self._send_handling_auth(
  File "/dependencies/httpx/_client.py", line 917, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/dependencies/httpx/_client.py", line 954, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/dependencies/httpx/_client.py", line 990, in _send_single_request
    response = transport.handle_request(request)
  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: timed out

**Comment by pofey** [comment]
访问tmdb超时，无法识别转移，另外你版本有点低还升级了
