### ISSUE TITLE
[缺陷]: log出现大量signature 过期报错

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#349]
### 当前程序版本

0.9.78

### 问题描述

log出现大量signature 过期报错，请问是何原因有无不良影响

### 重现步骤

查看日志

### 发生问题时系统日志

```shell
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 22, in yee.register.bp_register.login_required.wrapper.decorator
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 69, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 296, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/dependencies/flask_jwt_extended/utils.py", line 122, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/dependencies/flask_jwt_extended/jwt_manager.py", line 536, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/dependencies/flask_jwt_extended/tokens.py", line 87, in _decode_jwt
    decoded_token = jwt.decode(
  File "/dependencies/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 116, in decode_complete
    self._validate_claims(payload, merged_options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 152, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/dependencies/jwt/api_jwt.py", line 187, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
 2022/06/21 22:59:45 - Thread-179 - ERROR: 请求出错：Signature has expired
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 22, in yee.register.bp_register.login_required.wrapper.decorator
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 69, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 296, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/dependencies/flask_jwt_extended/utils.py", line 122, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/dependencies/flask_jwt_extended/jwt_manager.py", line 536, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/dependencies/flask_jwt_extended/tokens.py", line 87, in _decode_jwt
    decoded_token = jwt.decode(
  File "/dependencies/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 116, in decode_complete
    self._validate_claims(payload, merged_options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 152, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/dependencies/jwt/api_jwt.py", line 187, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
```

**Comment by elic6699** [comment]
最早是今天 19：38开始，前面没有该错误
 2022/06/21 19:38:35 - SubConsumer - INFO: 黑袍纠察队(2019) 已经有搜索结果，但经过你设定的过滤器后，无任何结果。
 2022/06/21 19:38:38 - HDHome-downloader - INFO: 开始处理免费种子下载任务: [HDHome]Healer Girl S01 1080p CR WEB-DL AAC2 0 x264-SubsPlease
 2022/06/21 19:38:41 - Thread-953 - ERROR: 请求出错：Signature has expired
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 22, in yee.register.bp_register.login_required.wrapper.decorator
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 69, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 296, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/dependencies/flask_jwt_extended/utils.py", line 122, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/dependencies/flask_jwt_extended/jwt_manager.py", line 536, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/dependencies/flask_jwt_extended/tokens.py", line 87, in _decode_jwt
    decoded_token = jwt.decode(
  File "/dependencies/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 116, in decode_complete
    self._validate_claims(payload, merged_options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 152, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/dependencies/jwt/api_jwt.py", line 187, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")

**Comment by elic6699** [comment]
查出来了，是家里一台旧的mac mini好久没开昨天开机，以前用这台电脑登录过，应该是登录过期了
