### ISSUE TITLE
[缺陷]: ERROR: 文件转移失败

### ISSUE THREAD

**Issue by MouLv** [pofey/movie_robot#359]
### 当前程序版本

0.9.81B

### 问题描述

做种盘满了，导致下载任务暂停。
我做了下面的操作
1、清理做种硬盘腾出空间
2、重新校验下载失败的文件
3、重新下载。

然后就开始报这个错了。随后我把订阅记录，下载记录，和相关下载的种子文件删掉之后重启movie-robot还是没有恢复。

### 重现步骤

推测是做种盘满了，然后我重新校验失败任务导致的一些判断异常。
条件比较复杂，暂时没有尝试复现。

帮忙看下怎么把这个报错清理掉就行

### 发生问题时系统日志

```shell
2022/06/22 14:53:00 - ThreadPoolExecutor-2_3 - ERROR: 文件转移失败：Expecting value: line 1 column 1 (char 0)
2022/06/22 14:53:00 - ThreadPoolExecutor-2_3 - ERROR: 监控种子任务出现错误：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 368, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 356, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 51, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/movielink.py", line 17, in yee.media.link.movielink.MovieLink.__init__
  File "yee/media/link/medialink.py", line 78, in yee.media.link.medialink.MediaLink.__init__
  File "yee/media/medialibrary.py", line 171, in yee.media.medialibrary.MediaLibrary.init_media_item
  File "yee/media/medialibrary.py", line 156, in yee.media.medialibrary.MediaLibrary.parse_path
  File "yee/media/medialibrary.py", line 38, in yee.media.medialibrary.MediaLibraryItemMeta.__init__
  File "yee/media/medialibrary.py", line 75, in yee.media.medialibrary.MediaLibraryItemMeta.load_meta
  File "yee/common/configparser.py", line 35, in yee.common.configparser.ConfigParser.load_json_config
  File "yee/common/configparser.py", line 36, in yee.common.configparser.ConfigParser.load_json_config
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by MouLv** [comment]
解决了，删了挨个删最近的订阅解决的。一直删到侏罗纪世界不报错了。。

**Comment by pofey** [comment]
这里我加了个容错
