### ISSUE TITLE
[缺陷]: 更新0.9.81B后，不拖ttg新种

### ISSUE THREAD

**Issue by leverule** [pofey/movie_robot#360]
### 当前程序版本

0.9.81B以及0.9.83

### 问题描述

 2022/06/22 08:25  从0.9.77更新0.9.81B的，更完不拖ttg新种，日志里不显示同步ttg，db里也没种子数据

cookie没问题，添加ttg未报错，web也能搜到ttg种子

完整日志：
[robot.log](https://github.com/pofey/movie_robot/files/8956859/robot.log)

db：
![image](https://user-images.githubusercontent.com/57491211/175012147-e7d60423-53c5-4704-8f42-bc02beee6a83.png)

站点设置：
![image](https://user-images.githubusercontent.com/57491211/175013132-e4951526-b50b-4035-b5c7-77107e9b74c1.png)

### 重现步骤

上面是另一台异地群晖的mr，我手边这台unraid的mr也不同步ttg了

### 发生问题时系统日志

```shell
更新前：

2022/06/22 04:38:35 - MainThread - INFO: 站点并发线程数：6
 2022/06/22 04:38:35 - MainThread - INFO: Emby连接正常，embyserver版本为4.6.7.0
 2022/06/22 04:38:37 - MainThread - INFO: 新增任务：PT站点登陆有效性检查及分享数据更新任务
 2022/06/22 04:38:37 - MainThread - INFO: 新增任务：免费下载种子监测任务
 2022/06/22 04:38:37 - MainThread - INFO: 新增任务：站点资源同步任务
 2022/06/22 04:38:37 - MainThread - INFO: 新增任务：同步豆瓣想看到订阅列表
 2022/06/22 04:38:37 - MainThread - INFO: 新增任务：自定义任务调度
 2022/06/22 04:38:37 - MainThread - INFO: 新增任务：监听下载客户端下载状态
 2022/06/22 04:38:37 - MainThread - INFO: 新增任务：订阅元数据检查更新任务
 2022/06/22 04:38:37 - MainThread - INFO: Emby连接正常，embyserver版本为4.6.7.0
 2022/06/22 04:38:37 - MainThread - INFO: 已经启动字幕下载处理任务。
 2022/06/22 04:38:37 - MainThread - INFO: 当前版本: 0.9.77
 2022/06/22 04:39:37 - ThreadPoolExecutor-2_1 - INFO: 金田一少年の事件簿 EP05 720p HDTV x264 AAC-DoA.mkv 保存目录已经和免费保存路径不符，将脱离免费任务监控，现保存路径：/volumeSATA1/satashare1-1/temp/
 2022/06/22 04:40:17 - Thread-52 - ERROR: 请求出错：Signature has expired
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 22, in yee.register.bp_register.login_required.wrapper.decorator
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 69, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 296, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/dependencies/flask_jwt_extended/utils.py", line 122, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/dependencies/flask_jwt_extended/jwt_manager.py", line 536, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/dependencies/flask_jwt_extended/tokens.py", line 87, in _decode_jwt
    decoded_token = jwt.decode(
  File "/dependencies/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 116, in decode_complete
    self._validate_claims(payload, merged_options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 152, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/dependencies/jwt/api_jwt.py", line 187, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
 2022/06/22 04:45:17 - Thread-53 - ERROR: 请求出错：Signature has expired
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 22, in yee.register.bp_register.login_required.wrapper.decorator
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 69, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 296, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/dependencies/flask_jwt_extended/utils.py", line 122, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/dependencies/flask_jwt_extended/jwt_manager.py", line 536, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/dependencies/flask_jwt_extended/tokens.py", line 87, in _decode_jwt
    decoded_token = jwt.decode(
  File "/dependencies/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 116, in decode_complete
    self._validate_claims(payload, merged_options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 152, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/dependencies/jwt/api_jwt.py", line 187, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
 2022/06/22 04:59:23 - ThreadPoolExecutor-2_1 - INFO: 开始同步站点资源信息...
 2022/06/22 04:59:35 - ThreadPoolExecutor-2_1 - INFO: 朋友最新种子同步完成。
 2022/06/22 04:59:57 - ThreadPoolExecutor-2_1 - INFO: 彩虹岛最新种子同步完成。
 2022/06/22 05:00:00 - ThreadPoolExecutor-2_1 - INFO: 听听歌最新种子同步完成。
 2022/06/22 05:00:03 - ThreadPoolExecutor-2_1 - INFO: 观众最新种子同步完成。
 2022/06/22 05:00:07 - ThreadPoolExecutor-2_1 - INFO: 家园最新种子同步完成。
 2022/06/22 05:00:07 - ThreadPoolExecutor-2_1 - INFO: 所有站点资源信息已经更新完毕。
 2022/06/22 05:00:07 - ThreadPoolExecutor-2_1 - INFO: 没有任何订阅记录需要进行智能下载。
 2022/06/22 05:00:09 - ThreadPoolExecutor-2_1 - INFO: 开始筛选免费种子。
 2022/06/22 05:00:09 - ThreadPoolExecutor-2_1 - INFO: 有1个免费种子需要下载，开始提交到下载器。
 2022/06/22 05:00:09 - ThreadPoolExecutor-2_1 - INFO: 免费种子提交下载队列完成。
 2022/06/22 05:00:09 - audiences-downloader - INFO: 开始处理免费种子下载任务: [audiences]Maple Leaf Red S01 2020 1080p WEB-DL H265 AAC-ADWeb
 2022/06/22 05:20:10 - ThreadPoolExecutor-2_0 - INFO: 开始同步站点资源信息...
 2022/06/22 05:20:25 - ThreadPoolExecutor-2_0 - INFO: 朋友最新种子同步完成。
 2022/06/22 05:20:49 - ThreadPoolExecutor-2_0 - INFO: 彩虹岛最新种子同步完成。
 2022/06/22 05:20:52 - ThreadPoolExecutor-2_0 - INFO: 听听歌最新种子同步完成。
 2022/06/22 05:20:56 - ThreadPoolExecutor-2_0 - INFO: 观众最新种子同步完成。
 2022/06/22 05:20:59 - ThreadPoolExecutor-2_0 - INFO: 家园最新种子同步完成。
 2022/06/22 05:20:59 - ThreadPoolExecutor-2_0 - INFO: 所有站点资源信息已经更新完毕。
 2022/06/22 05:20:59 - ThreadPoolExecutor-2_0 - INFO: 没有任何订阅记录需要进行智能下载。
 2022/06/22 05:21:00 - ThreadPoolExecutor-2_0 - INFO: 开始筛选免费种子。
 2022/06/22 05:21:00 - ThreadPoolExecutor-2_0 - INFO: 经过筛选后没有需要下载的免费任务。
 2022/06/22 05:40:55 - ThreadPoolExecutor-2_2 - INFO: 开始同步站点资源信息...
 2022/06/22 05:41:14 - ThreadPoolExecutor-2_2 - INFO: 朋友最新种子同步完成。
 2022/06/22 05:41:22 - ThreadPoolExecutor-2_2 - INFO: 彩虹岛最新种子同步完成。
 2022/06/22 05:41:25 - ThreadPoolExecutor-2_2 - INFO: 听听歌最新种子同步完成。
 2022/06/22 05:41:28 - ThreadPoolExecutor-2_2 - INFO: 观众最新种子同步完成。
 2022/06/22 05:41:32 - ThreadPoolExecutor-2_2 - INFO: 家园最新种子同步完成。
 2022/06/22 05:41:32 - ThreadPoolExecutor-2_2 - INFO: 所有站点资源信息已经更新完毕。
 2022/06/22 05:41:32 - ThreadPoolExecutor-2_2 - INFO: 没有任何订阅记录需要进行智能下载。
 2022/06/22 05:41:33 - ThreadPoolExecutor-2_2 - INFO: 开始筛选免费种子。
 2022/06/22 05:41:33 - ThreadPoolExecutor-2_2 - INFO: 经过筛选后没有需要下载的免费任务。
 2022/06/22 05:50:18 - Thread-89 - ERROR: 请求出错：Signature has expired
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 22, in yee.register.bp_register.login_required.wrapper.decorator
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 69, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 296, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/dependencies/flask_jwt_extended/utils.py", line 122, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/dependencies/flask_jwt_extended/jwt_manager.py", line 536, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/dependencies/flask_jwt_extended/tokens.py", line 87, in _decode_jwt
    decoded_token = jwt.decode(
  File "/dependencies/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 116, in decode_complete
    self._validate_claims(payload, merged_options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 152, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/dependencies/jwt/api_jwt.py", line 187, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

更新后：

 2022/06/22 08:21:58 - Thread-92 - ERROR: 请求出错：Signature has expired
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 22, in yee.register.bp_register.login_required.wrapper.decorator
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 69, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 296, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/dependencies/flask_jwt_extended/utils.py", line 122, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/dependencies/flask_jwt_extended/jwt_manager.py", line 536, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/dependencies/flask_jwt_extended/tokens.py", line 87, in _decode_jwt
    decoded_token = jwt.decode(
  File "/dependencies/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 116, in decode_complete
    self._validate_claims(payload, merged_options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 152, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/dependencies/jwt/api_jwt.py", line 187, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
 2022/06/22 08:22:07 - Thread-96 - ERROR: 请求出错：Signature has expired
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 22, in yee.register.bp_register.login_required.wrapper.decorator
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 69, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 296, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/dependencies/flask_jwt_extended/utils.py", line 122, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/dependencies/flask_jwt_extended/jwt_manager.py", line 536, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/dependencies/flask_jwt_extended/tokens.py", line 87, in _decode_jwt
    decoded_token = jwt.decode(
  File "/dependencies/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 116, in decode_complete
    self._validate_claims(payload, merged_options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 152, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/dependencies/jwt/api_jwt.py", line 187, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
 2022/06/22 08:22:17 - Thread-98 - ERROR: 请求出错：Signature has expired
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 22, in yee.register.bp_register.login_required.wrapper.decorator
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 69, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/dependencies/flask_jwt_extended/view_decorators.py", line 296, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/dependencies/flask_jwt_extended/utils.py", line 122, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/dependencies/flask_jwt_extended/jwt_manager.py", line 536, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/dependencies/flask_jwt_extended/tokens.py", line 87, in _decode_jwt
    decoded_token = jwt.decode(
  File "/dependencies/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 116, in decode_complete
    self._validate_claims(payload, merged_options, **kwargs)
  File "/dependencies/jwt/api_jwt.py", line 152, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/dependencies/jwt/api_jwt.py", line 187, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
 2022/06/22 08:25:50 - MainThread - INFO: 站点并发线程数：6
 2022/06/22 08:25:50 - MainThread - INFO: Emby连接正常，embyserver版本为4.6.7.0
 2022/06/22 08:25:52 - MainThread - INFO: 新增任务：PT站点登陆有效性检查及分享数据更新任务
 2022/06/22 08:25:52 - MainThread - INFO: 新增任务：免费下载种子监测任务
 2022/06/22 08:25:52 - MainThread - INFO: 新增任务：站点资源同步任务
 2022/06/22 08:25:52 - MainThread - INFO: 新增任务：同步豆瓣想看到订阅列表
 2022/06/22 08:25:52 - MainThread - INFO: 新增任务：自定义任务调度
 2022/06/22 08:25:52 - MainThread - INFO: 新增任务：监听下载客户端下载状态
 2022/06/22 08:25:52 - MainThread - INFO: 新增任务：订阅元数据检查更新任务
 2022/06/22 08:25:53 - MainThread - INFO: Emby连接正常，embyserver版本为4.6.7.0
 2022/06/22 08:25:53 - MainThread - INFO: 已经启动字幕下载处理任务。
 2022/06/22 08:25:53 - MainThread - INFO: 当前版本: 0.9.81B
 2022/06/22 08:30:00 - ThreadPoolExecutor-2_2 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
 2022/06/22 08:46:44 - ThreadPoolExecutor-2_2 - INFO: 开始同步站点资源信息...
 2022/06/22 08:46:54 - ThreadPoolExecutor-2_2 - INFO: 朋友最新种子同步完成。
 2022/06/22 08:47:12 - ThreadPoolExecutor-2_2 - INFO: 彩虹岛最新种子同步完成。
 2022/06/22 08:47:15 - ThreadPoolExecutor-2_2 - INFO: 家园最新种子同步完成。
 2022/06/22 08:47:18 - ThreadPoolExecutor-2_2 - INFO: 观众最新种子同步完成。
 2022/06/22 08:47:18 - ThreadPoolExecutor-2_2 - INFO: 所有站点资源信息已经更新完毕。
 2022/06/22 08:47:18 - ThreadPoolExecutor-2_2 - INFO: 没有任何订阅记录需要进行智能下载。
 2022/06/22 08:47:20 - ThreadPoolExecutor-2_2 - INFO: 开始筛选免费种子。
 2022/06/22 08:47:20 - ThreadPoolExecutor-2_2 - INFO: 经过筛选后没有需要下载的免费任务。
```

**Comment by pofey** [comment]
0.9.84 修复
