### ISSUE TITLE
[提问]: 下载字幕一直报错

### ISSUE THREAD

**Issue by jinfeng1985** [pofey/movie_robot#371]
### 当前程序版本

0.9.86

### 问题

下载字幕一直报错，如下：

2022-06-24 09:36:00,042 - MainThread - INFO: 开始在Zimuku搜索 小说家的电影
2022-06-24 09:36:00,426 - MainThread - INFO: 开始在Subhd搜索 小说家的电影
2022-06-24 09:36:00,978 - MainThread - INFO: 搜索到1条字幕信息
2022-06-24 09:36:00,979 - MainThread - INFO: 开始下载小说家的电影(2022) 的字幕: 小說家的電影 The Novelists Film 2022
2022-06-24 09:37:31,593 - MainThread - ERROR: 下载字幕出错：Message: 
Stacktrace:
#0 0x563f08a78e89 <unknown>
Traceback (most recent call last):
  File "yee/task/process/downloadsubtitleprocess.py", line 174, in yee.task.process.downloadsubtitleprocess.DownloadSubtitleProcess.run
  File "yee/task/process/downloadsubtitleprocess.py", line 102, in yee.task.process.downloadsubtitleprocess.DownloadSubtitleProcess.__download_movie_sub__
  File "yee/subtitle/subdownloader.py", line 80, in yee.subtitle.subdownloader.SubDownloader.download
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/dependencies/tenacity/__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/subtitle/find/subhd.py", line 199, in yee.subtitle.find.subhd.Subhd.download
  File "/dependencies/selenium/webdriver/support/wait.py", line 87, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x563f08a78e89 <unknown>

**Comment by pofey** [comment]
你是被subhd ban了么

**Comment by jinfeng1985** [comment]
> 你是被subhd ban了么

啊…为啥会被ban   它是通过ip  ban的嘛？？？

**Comment by pofey** [comment]
不清楚机制，结论是访问subhd超时，只能自己排查网络联通性。
