### ISSUE TITLE
[缺陷]: 无法删除订阅

### ISSUE THREAD

**Issue by icinessx** [pofey/movie_robot#372]
### 当前程序版本

0.9.86

### 问题描述

我的订阅里面无法删除订阅。

### 重现步骤

选择订阅图片中的删除，提示删除订阅成功，但是刷新后还是在订阅中。

### 发生问题时系统日志

```shell
2022/06/24 10:45:50 - SubRequestConsumer - ERROR: 处理订阅请求消息出错：Expecting value: line 1 column 1 (char 0)                                    
Traceback (most recent call last):                                                                                                                   
  File "yee/task/consumer/subrequestconsumer.py", line 54, in yee.task.consumer.subrequestconsumer.SubRequestConsumer.run                            
  File "yee/task/consumer/subrequestconsumer.py", line 89, in yee.task.consumer.subrequestconsumer.SubRequestConsumer.delete_sub                     
  File "yee/media/server/jellyfinmediaserver.py", line 113, in yee.media.server.jellyfinmediaserver.JellyfinMediaServer.delete_tv                    
  File "yee/media/server/jellyfinmediaserver.py", line 191, in yee.media.server.jellyfinmediaserver.JellyfinMediaServer.search_by_id                 
  File "yee/media/server/jellyfinmediaserver.py", line 183, in yee.media.server.jellyfinmediaserver.JellyfinMediaServer.__get_all__                  
  File "/dependencies/requests/models.py", line 910, in json                                                                                         
    return complexjson.loads(self.text, **kwargs)                                                                                                    
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads                                                                               
    return _default_decoder.decode(s)                                                                                                                
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode                                                                               
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode                                                                           
    raise JSONDecodeError("Expecting value", s, err.value) from None                                                                                 
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by pofey** [comment]
自己的jellyfin连接是不是正常，自己能不能检查一下？
