### ISSUE TITLE
[提问]: 刚从0.9.85更新到0.9.86，movie-robot就直接启动不了

### ISSUE THREAD

**Issue by zxq321zxq** [pofey/movie_robot#374]
### 当前程序版本

0.9.86

### 问题

2022.06.24中午刚从0.9.85更新到0.9.86，movie-robot就直接启动不了。0.9.85的时候使用正常。无从下手。
错误代码
File "start.py", line 26, in <module>
    init_config(base_path, workdir)
  File "yee/register/config_register.py", line 78, in yee.register.config_register.init_config
  File "yee/config/config.py", line 55, in yee.config.config.BaseConfig.init_config
  File "yee/config/config.py", line 74, in yee.config.config.BaseConfig.load
  File "yee/config/config.py", line 76, in yee.config.config.BaseConfig.load
  File "/dependencies/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/dependencies/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/dependencies/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/dependencies/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/dependencies/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/dependencies/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/dependencies/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/dependencies/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/dependencies/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/dependencies/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/dependencies/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/dependencies/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/dependencies/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/dependencies/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/dependencies/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/dependencies/yaml/scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "/data/conf/base_config.yml", line 80, column 3
could not find expected ':'
  in "/data/conf/base_config.yml", line 81, column 3
2022-06-24 13:09:05,952 INFO exited: mbots (exit status 1; not expected)
2022-06-24 13:09:08,957 INFO spawned: 'mbots' with pid 19
2022/06/24 13:09:09 - MainThread - ERROR: Uncaught exception
Traceback (most recent call last):
  File "start.py", line 26, in <module>
    init_config(base_path, workdir)
  File "yee/register/config_register.py", line 78, in yee.register.config_register.init_config
  File "yee/config/config.py", line 55, in yee.config.config.BaseConfig.init_config
  File "yee/config/config.py", line 74, in yee.config.config.BaseConfig.load
  File "yee/config/config.py", line 76, in yee.config.config.BaseConfig.load
  File "/dependencies/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/dependencies/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/dependencies/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/dependencies/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/dependencies/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/dependencies/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/dependencies/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/dependencies/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/dependencies/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/dependencies/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/dependencies/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/dependencies/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/dependencies/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/dependencies/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/dependencies/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/dependencies/yaml/scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "/data/conf/base_config.yml", line 80, column 3
could not find expected ':'
  in "/data/conf/base_config.yml", line 81, column 3
2022-06-24 13:09:10,047 INFO exited: mbots (exit status 1; not expected)
2022-06-24 13:09:11,048 INFO gave up: mbots entered FATAL state, too many start retries too quickly

**Comment by pofey** [comment]
不知道你对配置文件做了什么 看起来是坏掉了，重新配置吧。正常升级是不会有任何问题的。

**Comment by zxq321zxq** [comment]
> 不知道你对配置文件做了什么看起来是坏掉了，重新配置吧。正常升级是不会有任何问题的。

找到原因了,有的qb下载分类没空着,清空就可以启动了
qbit_cate: []改成qbit_cate:
