### ISSUE TITLE
[缺陷]: 订阅《一线生机》时提示订阅错误，豆瓣演员信息解析出错

### ISSUE THREAD

**Issue by elle007011** [pofey/movie_robot#390]
### 当前程序版本

0.9.88

### 问题描述

无法完成订阅，提示订阅出错，请查看日志

### 重现步骤

重新选择订阅，结果一样，日志也一样

### 发生问题时系统日志

```shell
2022/06/27 07:16:48 - SubRequestConsumer - ERROR: douban_id: 35382383 订阅失败，请查看日志分析原因。
stdout
07:16:48
Traceback (most recent call last):
stdout
07:16:48
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
stdout
07:16:48
    result = fn(*args, **kwargs)
stdout
07:16:48
  File "yee/media/douban.py", line 208, in yee.media.douban.DoubanMovie.get_movie_by_id
stdout
07:16:48
  File "yee/media/douban.py", line 230, in yee.media.douban.DoubanMovie.get_movie_by_id
stdout
07:16:48
  File "yee/media/douban.py", line 182, in yee.media.douban.DoubanMovie.__parse_actor__
stdout
07:16:48
AttributeError: 'NoneType' object has no attribute 'attrs'
stdout
07:16:48
stdout
07:16:48
The above exception was the direct cause of the following exception:
stdout
07:16:48
stdout
07:16:48
Traceback (most recent call last):
stdout
07:16:48
  File "yee/service/smartdownloadservice.py", line 235, in yee.service.smartdownloadservice.SmartDownloadService.sub_from_douban
stdout
07:16:48
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
stdout
07:16:48
    return self(f, *args, **kw)
stdout
07:16:48
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
stdout
07:16:48
    do = self.iter(retry_state=retry_state)
stdout
07:16:48
  File "/dependencies/tenacity/__init__.py", line 361, in iter
stdout
07:16:48
    raise retry_exc from fut.exception()
stdout
07:16:48
tenacity.RetryError: RetryError[<Future at 0x7f08d85c26a0 state=finished raised AttributeError>]
stdout
07:16:48
2022/06/27 07:16:48 - SubRequestConsumer - ERROR: douban_id: 35382383 订阅失败，请查看日志分析原因。
```

### 其他信息

依赖系统健康
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/105756846/175837732-8e6d2d3b-8b45-4e53-b666-edef717b5ed8.png">

**Comment by pofey** [comment]
新增豆瓣演员解析逻辑的BUG，晚上更新一下修复

**Comment by pofey** [comment]
0.9.89发布中，将会解决这个问题
