### ISSUE TITLE
[缺陷]: 字幕自动下载任务下次启动时间出错

### ISSUE THREAD

**Issue by haha6311** [pofey/movie_robot#406]
### 当前程序版本

0.9.90x

### 问题描述

通过订阅方式下载了人面兽心的电影，因为没中文字幕，按照过滤器设定自动添加字幕下载任务（**20:17**），之后就如日志所示。

当天**21:52**在webUI手动添加下载字幕任务操作
![image](https://user-images.githubusercontent.com/36618980/176453656-6cb25898-6f73-4b94-a96a-a2f512c9694c.png)

得到提示：
"这个影片已经有字幕下载任务在进行中了，预计**下次**开始时间：2022-06-29 **20:16:26**"

这个时间还是**上次**的运行时间。

### 重现步骤

如上所述

### 发生问题时系统日志

```shell
2022-06-29 20:17:00,052 - MainThread - INFO: 收到字幕处理消息：{'task_id': 46, 'content_path': '/video/电影/人面兽心 (2001) [tmdbid=11090]', 'media_info': {'tmdb_id': 11090, 'type': 'Movie', 'name': '人面兽心', 'year': 2001, 'season_year': None, 'season_index': None, 'episodes': None}}
2022-06-29 20:17:05,040 - MainThread - INFO: 开始在Zimuku搜索 人面兽心
2022-06-29 20:17:09,787 - MainThread - INFO: 搜索到2条字幕信息
2022-06-29 20:17:09,792 - MainThread - INFO: 开始下载人面兽心(2001) 的字幕: 人面兽心 The Animal (2001) 獸性大發
2022-06-29 21:35:00,066 - MainThread - INFO: 收到字幕处理消息：{'task_id': 45, 'content_path': '/video1/剧集/老友记 (1994) [tmdbid=1668]/Season 1', 'media_info': {'tmdb_id': 1668, 'type': 'TV', 'name': '老友记', 'year': 1994, 'season_year': 1994, 'season_index': 1, 'episodes': None}}
2022-06-29 21:35:00,083 - MainThread - INFO: 老友记 第1季 (1994) 缺少集号，终止下载。
2022-06-29 21:35:11,244 - MainThread - ERROR: 下载字幕出错：'NoneType' object is not iterable
Traceback (most recent call last):
  File "yee/task/process/downloadsubtitleprocess.py", line 174, in yee.task.process.downloadsubtitleprocess.DownloadSubtitleProcess.run
  File "yee/task/process/downloadsubtitleprocess.py", line 122, in yee.task.process.downloadsubtitleprocess.DownloadSubtitleProcess.__download_tv_sub__
TypeError: 'NoneType' object is not iterable
2022-06-29 21:42:00,059 - MainThread - INFO: 收到字幕处理消息：{'task_id': 47, 'content_path': '/video1/电影/Winnebago Man (2010) [tmdbid=42918]', 'media_info': {'tmdb_id': 42918, 'type': 'Movie', 'name': 'Winnebago Man', 'year': 2010, 'season_year': None, 'season_index': None, 'episodes': None}}
2022-06-29 21:42:01,090 - MainThread - INFO: 开始在Zimuku搜索 Winnebago Man
2022-06-29 21:42:05,536 - MainThread - INFO: 搜索到0条字幕信息
2022-06-29 21:42:05,540 - MainThread - INFO: Winnebago Man (2010) 现在搜索不到字幕，晚点继续下。
```

### 其他信息

![image](https://user-images.githubusercontent.com/36618980/176454808-18bcfdc1-f4a7-41d8-be46-afadbd2c45e0.png)
箭头所示为当天20时

**Comment by pofey** [comment]
老友记为什么没解析到集数信息呢 你把这个种子发出来我试试

**Comment by haha6311** [comment]
> 老友记为什么没解析到集数信息呢 你把这个种子发出来我试试

老友记全十季.Friends.The.Complete.Series.1994-2003.BluRay.1080p.x265.10bit.MNHD-FRDS

**Comment by pofey** [comment]
> > 老友记为什么没解析到集数信息呢 你把这个种子发出来我试试
> 
> 老友记全十季.Friends.The.Complete.Series.1994-2003.BluRay.1080p.x265.10bit.MNHD-FRDS Tosh.0 S01-S12 1080p WEB-DL AC3 H264 这两个都是全集的大包，都被误识别成“第1季”第1季了

不支持大包处理的，尤其是字幕

**Comment by pofey** [comment]
关了，大包问题先不处理。现在机器人的字幕下载设计，不是用来解决存量资源处理的
