### ISSUE TITLE
[BUG REPORT]监控种子出现错误

### ISSUE THREAD

**Issue by dskblh** [pofey/movie_robot#42]
错误日志如下，目前看来主要影响微信通知，因为监控种子出错，所以不能获取种子下载情况。不知道是不是BUG，昨晚是好的，QB崩溃后再打开就是这样了。

Traceback (most recent call last):
File "yee/core/taskmonitortorrent.py", line 112, in yee.core.taskmonitortorrent.TaskMonitorTorrent.run
File "yee/core/downloadclient.py", line 73, in yee.core.downloadclient.QbittorrentClient.exists_hash
File "yee/core/downloadclient.py", line 70, in yee.core.downloadclient.QbittorrentClient.exists_hash
File "/usr/local/lib/python3.9/site-packages/qbittorrent/client.py", line 201, in get_torrent
return self._get('torrents/properties?hash=' + infohash.lower())
File "/usr/local/lib/python3.9/site-packages/qbittorrent/client.py", line 52, in _get
return self._request(endpoint, 'get', **kwargs)
File "/usr/local/lib/python3.9/site-packages/qbittorrent/client.py", line 88, in _request
request.raise_for_status()
File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://192.168.2.185:8080/api/v2/torrents/properties?hash=9e07da5da01a7596f337c2ba11fbc0ebd9b289e1

2022/03/01 14:49:00 - ThreadPoolExecutor-0_0 - ERROR: 监控种子任务出现错误，不过不影响下次运行。

**Comment by pofey** [comment]
你这个报错版本太老了，升级到最新0.1.3吧
