### ISSUE TITLE
[缺陷]:  显示站点失效，检查cookie有效性，其实点击编辑并提交就显示可用了

### ISSUE THREAD

**Issue by ersanre** [pofey/movie_robot#420]
### 当前程序版本

0.99.92

### 问题描述

经常显示站点失效，提示需要检查cookie有效性，
其实点击编辑并提交就显示可用了。
![image](https://user-images.githubusercontent.com/50767444/177020418-94da553b-f9e7-4903-9642-06dd95f1655c.png)

### 重现步骤

偶现，群里也有人有这个问题

**Comment by pofey** [comment]
那就要贴上异常时站点的日志了

**Comment by bobo0810** [comment]
> 

pttime出现过几次这个问题

**Comment by pofey** [comment]
没有站点报错的日志，这个问题就只能不了了之了，有异常一定要提醒关注一下

**Comment by per930** [comment]
2022/07/08 09:02:08 - Thread-3285 - ERROR: 站点设置失败：pt时间登陆失败！
Traceback (most recent call last):
  File "yee/controller/sitecontroller.py", line 33, in yee.controller.sitecontroller.save_site
  File "yee/service/siteservice.py", line 386, in yee.service.siteservice.SiteService.set_site
  File "yee/site/sitehelper.py", line 180, in yee.site.sitehelper.SiteHelper.get_userinfo
  File "yee/site/siteparser.py", line 29, in yee.site.siteparser.SiteParser.parse_userinfo
yee.site.siteexceptions.LoginRequired: pt时间登陆失败！
 2022/07/08 09:02:43 - Thread-3290 - ERROR: 站点设置失败：pt时间登陆失败！
Traceback (most recent call last):
  File "yee/controller/sitecontroller.py", line 33, in yee.controller.sitecontroller.save_site
  File "yee/service/siteservice.py", line 386, in yee.service.siteservice.SiteService.set_site
  File "yee/site/sitehelper.py", line 180, in yee.site.sitehelper.SiteHelper.get_userinfo
  File "yee/site/siteparser.py", line 29, in yee.site.siteparser.SiteParser.parse_userinfo
yee.site.siteexceptions.LoginRequired: pt时间登陆失败！
 2022/07/08 09:03:03 - Thread-3293 - ERROR: 站点设置失败：pt时间登陆失败！
Traceback (most recent call last):
  File "yee/controller/sitecontroller.py", line 33, in yee.controller.sitecontroller.save_site
  File "yee/service/siteservice.py", line 386, in yee.service.siteservice.SiteService.set_site
  File "yee/site/sitehelper.py", line 180, in yee.site.sitehelper.SiteHelper.get_userinfo
  File "yee/site/siteparser.py", line 29, in yee.site.siteparser.SiteParser.parse_userinfo
yee.site.siteexceptions.LoginRequired: pt时间登陆失败！
 2022/07/08 09:05:56 - Thread-3317 - ERROR: pt时间登陆失败，请检查cookie有效性：pt时间登陆失败！

**Comment by pofey** [comment]
> 2022/07/08 09:02:08 - Thread-3285 - ERROR: 站点设置失败：pt时间登陆失败！ Traceback (most recent call last): File "yee/controller/sitecontroller.py", line 33, in yee.controller.sitecontroller.save_site File "yee/service/siteservice.py", line 386, in yee.service.siteservice.SiteService.set_site File "yee/site/sitehelper.py", line 180, in yee.site.sitehelper.SiteHelper.get_userinfo File "yee/site/siteparser.py", line 29, in yee.site.siteparser.SiteParser.parse_userinfo yee.site.siteexceptions.LoginRequired: pt时间登陆失败！ 2022/07/08 09:02:43 - Thread-3290 - ERROR: 站点设置失败：pt时间登陆失败！ Traceback (most recent call last): File "yee/controller/sitecontroller.py", line 33, in yee.controller.sitecontroller.save_site File "yee/service/siteservice.py", line 386, in yee.service.siteservice.SiteService.set_site File "yee/site/sitehelper.py", line 180, in yee.site.sitehelper.SiteHelper.get_userinfo File "yee/site/siteparser.py", line 29, in yee.site.siteparser.SiteParser.parse_userinfo yee.site.siteexceptions.LoginRequired: pt时间登陆失败！ 2022/07/08 09:03:03 - Thread-3293 - ERROR: 站点设置失败：pt时间登陆失败！ Traceback (most recent call last): File "yee/controller/sitecontroller.py", line 33, in yee.controller.sitecontroller.save_site File "yee/service/siteservice.py", line 386, in yee.service.siteservice.SiteService.set_site File "yee/site/sitehelper.py", line 180, in yee.site.sitehelper.SiteHelper.get_userinfo File "yee/site/siteparser.py", line 29, in yee.site.siteparser.SiteParser.parse_userinfo yee.site.siteexceptions.LoginRequired: pt时间登陆失败！ 2022/07/08 09:05:56 - Thread-3317 - ERROR: pt时间登陆失败，请检查cookie有效性：pt时间登陆失败！

这可能是真的登陆失败了，或遇到盾
