### ISSUE TITLE
[提问]: 测试出错：'NoneType' object has no attribute 'find_id'是什么原因呢

### ISSUE THREAD

**Issue by Scolism** [pofey/movie_robot#438]
### 当前程序版本

0.9.93

### 问题

'NoneType' object has no attribute 'find_id'是什么原因呢
![image](https://user-images.githubusercontent.com/43903287/177777351-00de6a60-35ce-4bcb-8798-4df2ca657306.png)

### 发生问题时系统日志

```shell
2022/07/07 20:49:28 - Thread-81 - ERROR: 测试出错
Traceback (most recent call last):
  File "yee/controller/configcontroller.py", line 328, in yee.controller.configcontroller.test_douban_download
  File "yee/service/moviemetadataservice.py", line 30, in yee.service.moviemetadataservice.MovieMetadataService.douban_to_tmdb
  File "yee/metadata/mediarecognize.py", line 264, in yee.metadata.mediarecognize.MediaRecognize.recognize_movie
  File "yee/metadata/mediarecognize.py", line 64, in yee.metadata.mediarecognize.MediaRecognize.__build_query__
AttributeError: 'NoneType' object has no attribute 'find_id'
```

**Comment by pofey** [comment]
健康检查状态截图看一下

**Comment by Scolism** [comment]
![image](https://user-images.githubusercontent.com/43903287/177793093-11b9cc5d-1e95-486c-880f-705c2a17c09a.png)
这个吗

**Comment by pofey** [comment]
很明显了，你根本没有配置tmdb
