### ISSUE TITLE
[缺陷]: MR会遇到连不上QB的情况

### ISSUE THREAD

**Issue by laobanbiefangcu** [pofey/movie_robot#440]
### 当前程序版本

0.9.9

### 问题描述

之前用的QB4.4.0，退回QB4.3.9版本，也还是会碰到，重启就可以正常连接

### 重现步骤

无

### 发生问题时系统日志

```shell
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 40, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/task/monitortorrenttask.py", line 63, in yee.task.monitortorrenttask.MonitorTorrentTask.check_downloading
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1550af5e87f0 state=finished raised AttributeError>]
 2022/07/09 17:18:06 - ThreadPoolExecutor-4_3 - ERROR: 监控种子任务出现错误：RetryError[<Future at 0x1550afee7b50 state=finished raised AttributeError>]
Traceback (most recent call last):
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/service/downloadservice.py", line 170, in yee.service.downloadservice.DownloadService.get_downloading_torrent
AttributeError: 'NoneType' object has no attribute 'submit'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 40, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/task/monitortorrenttask.py", line 63, in yee.task.monitortorrenttask.MonitorTorrentTask.check_downloading
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1550afee7b50 state=finished raised AttributeError>]
 2022/07/09 17:19:06 - ThreadPoolExecutor-4_0 - ERROR: 监控种子任务出现错误：RetryError[<Future at 0x1550ad273f40 state=finished raised AttributeError>]
Traceback (most recent call last):
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/service/downloadservice.py", line 170, in yee.service.downloadservice.DownloadService.get_downloading_torrent
AttributeError: 'NoneType' object has no attribute 'submit'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 40, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/task/monitortorrenttask.py", line 63, in yee.task.monitortorrenttask.MonitorTorrentTask.check_downloading
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1550ad273f40 state=finished raised AttributeError>]
 2022/07/09 17:20:00 - ThreadPoolExecutor-0_1 - INFO: Emby连接正常，10100版本为4.7.5.0
 2022/07/09 17:20:06 - ThreadPoolExecutor-4_4 - ERROR: 监控种子任务出现错误：RetryError[<Future at 0x1550ae2bff10 state=finished raised AttributeError>]
Traceback (most recent call last):
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/service/downloadservice.py", line 170, in yee.service.downloadservice.DownloadService.get_downloading_torrent
AttributeError: 'NoneType' object has no attribute 'submit'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 40, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/task/monitortorrenttask.py", line 63, in yee.task.monitortorrenttask.MonitorTorrentTask.check_downloading
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1550ae2bff10 state=finished raised AttributeError>]
 2022/07/09 17:21:06 - ThreadPoolExecutor-4_0 - ERROR: 监控种子任务出现错误：RetryError[<Future at 0x1550adbf9400 state=finished raised AttributeError>]
Traceback (most recent call last):
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/service/downloadservice.py", line 170, in yee.service.downloadservice.DownloadService.get_downloading_torrent
AttributeError: 'NoneType' object has no attribute 'submit'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 40, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/task/monitortorrenttask.py", line 63, in yee.task.monitortorrenttask.MonitorTorrentTask.check_downloading
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1550adbf9400 state=finished raised AttributeError>]
 2022/07/09 17:22:06 - ThreadPoolExecutor-4_4 - ERROR: 监控种子任务出现错误：RetryError[<Future at 0x1550aeb98a60 state=finished raised AttributeError>]
Traceback (most recent call last):
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/service/downloadservice.py", line 170, in yee.service.downloadservice.DownloadService.get_downloading_torrent
AttributeError: 'NoneType' object has no attribute 'submit'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 40, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/task/monitortorrenttask.py", line 63, in yee.task.monitortorrenttask.MonitorTorrentTask.check_downloading
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1550aeb98a60 state=finished raised AttributeError>]
 2022/07/09 17:23:06 - ThreadPoolExecutor-4_0 - ERROR: 监控种子任务出现错误：RetryError[<Future at 0x1550ad5776a0 state=finished raised AttributeError>]
Traceback (most recent call last):
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/service/downloadservice.py", line 170, in yee.service.downloadservice.DownloadService.get_downloading_torrent
AttributeError: 'NoneType' object has no attribute 'submit'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 40, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/task/monitortorrenttask.py", line 63, in yee.task.monitortorrenttask.MonitorTorrentTask.check_downloading
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1550ad5776a0 state=finished raised AttributeError>]
 2022/07/09 17:24:06 - ThreadPoolExecutor-4_4 - ERROR: 监控种子任务出现错误：RetryError[<Future at 0x1550ad1a97f0 state=finished raised AttributeError>]
Traceback (most recent call last):
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/service/downloadservice.py", line 170, in yee.service.downloadservice.DownloadService.get_downloading_torrent
AttributeError: 'NoneType' object has no attribute 'submit'

The above exception was the direct cause of the following exception:
```

### 其他信息

<a href="https://sm.ms/image/QheN8jVrEcSPsFK" target="_blank"><img src="https://s2.loli.net/2022/07/09/QheN8jVrEcSPsFK.png" /></a>

**Comment by pofey** [comment]
这种问题我能做什么呢？
