### ISSUE TITLE
[Bug Report] 智能下载任务出错

### ISSUE THREAD

**Issue by AAlexDing** [pofey/movie_robot#45]
2022/03/03 14:00:27 - ThreadPoolExecutor-0_0 - INFO: 开始智能下载。
2022/03/03 14:00:27 - ThreadPoolExecutor-0_0 - INFO: 倒数时刻(2021)需要下载，开始在mteam;hdchina寻找最佳种子
2022/03/03 14:00:43 - ThreadPoolExecutor-0_0 - INFO: 倒数时刻(2021)的标签：[] 使用compress策略选种，优先关键字：[]
2022/03/03 14:00:43 - ThreadPoolExecutor-0_0 - INFO: 倒数时刻(2021)在mteam;hdchina搜索结果中最佳选择为：倒数时刻/滴答，滴答……轰隆隆（mteam）
2022/03/03 14:03:04 - ThreadPoolExecutor-0_0 - ERROR: 智能下载任务出错。

Traceback (most recent call last):
File "yee/core/tasksyncmovies.py", line 137, in yee.core.tasksyncmovies.TaskSyncMovies.run
File "yee/core/tasksyncmovies.py", line 207, in yee.core.tasksyncmovies.TaskSyncMovies.download
File "yee/movie/moviemetadata.py", line 41, in yee.movie.moviemetadata.get_thumb_image_url
File "yee/movie/fanartapi.py", line 15, in yee.movie.fanartapi.FanArtApi.get_images
File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by pofey** [comment]
这个看着像你fanart部分配置错了
