### ISSUE TITLE
[缺陷]: 养站出现报错 

### ISSUE THREAD

**Issue by lzl20110** [pofey/movie_robot#456]
### 当前程序版本

0.9.97

### 问题描述

 2022/07/12 07:56:57 - ThreadPoolExecutor-4_0 - ERROR: 处理免费种子淘汰任务出错：'NoneType' object has no attribute 'get_by_hash'
Traceback (most recent call last):
  File "yee/task/freedownloadmonitortask.py", line 182, in yee.task.freedownloadmonitortask.FreeDownloadMonitor.run
  File "yee/task/freedownloadmonitortask.py", line 122, in yee.task.freedownloadmonitortask.FreeDownloadMonitor.can_delete
AttributeError: 'NoneType' object has no attribute 'get_by_hash'

### 重现步骤

下载是正常的,就是不会删除

**Comment by pofey** [comment]
看看健康检查的状态吧，你这下载器估计没初始化成功
