### ISSUE TITLE
[缺陷]:日志一直报两个错，不知道是啥引起的，也没发现有啥功能异常 

### ISSUE THREAD

**Issue by wlkmmmmmm** [pofey/movie_robot#457]
### 当前程序版本

0.9.97

### 问题描述

2022/07/12 20:41:00 - ThreadPoolExecutor-4_3 - ERROR: 文件转移失败：'NoneType' object has no attribute 'get_by_id'
2022/07/12 20:41:00 - ThreadPoolExecutor-4_3 - ERROR: 监控种子任务出现错误：'NoneType' object has no attribute 'get_by_id'
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 395, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 376, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 104, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/medialink.py", line 162, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/movielink.py", line 103, in yee.media.link.movielink.MovieLink.__handle__
  File "yee/metadata/mediarecognize.py", line 283, in yee.metadata.mediarecognize.MediaRecognize.recognize_movie
  File "yee/metadata/mediarecognize.py", line 199, in yee.metadata.mediarecognize.MediaRecognize.__search_query__
AttributeError: 'NoneType' object has no attribute 'get_by_id'

### 重现步骤

一直报这两个错，而且是连在一起出现

**Comment by pofey** [comment]
TMDB都没设置，功能无异常？你将康检查的图呢

**Comment by wlkmmmmmm** [comment]
> TMDB都没设置，功能无异常？你将康检查的图呢

![image](https://user-images.githubusercontent.com/39430893/178507587-a81fe784-fd3b-4d5d-8eb3-20edf1925b01.png)
TMDB是好的，qb有时候红是因为我的缓存满了需要关闭qb执行缓存mover

**Comment by wlkmmmmmm** [comment]
> TMDB都没设置，功能无异常？你将康检查的图呢
确实有异常，媒体文件夹里设置的第三个路径是空的，里面应该是影视信息吧

**Comment by wlkmmmmmm** [comment]
> TMDB都没设置，功能无异常？你将康检查的图呢

我发现还获取不到TMDB那个movie后面的六位数id，都显示的是0。
但是我感觉都设置好了

**Comment by pofey** [comment]
监控最近看着还行 重启完应该没啥事。最多在看看豆瓣
