### ISSUE TITLE
[提问]: 监控种子任务报错

### ISSUE THREAD

**Issue by mymoonyue** [pofey/movie_robot#458]
### 当前程序版本

0.9.97

### 问题

更新最新版本之后，一直报错 **监控种子任务出现错误** 。日志又看不出来是什么错误，我就把所有订阅任务都删了，但还是报错，请教一下什么原因。

### 发生问题时系统日志

```shell
2022/07/12 23:50:01 - ThreadPoolExecutor-5_1 - ERROR: 监控种子任务出现错误：'NoneType' object has no attribute 'season_year'
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 354, in yee.service.downloadservice.DownloadService.download_completed
AttributeError: 'NoneType' object has no attribute 'season_year'
 2022/07/12 23:51:01 - ThreadPoolExecutor-5_4 - ERROR: 监控种子任务出现错误：'NoneType' object has no attribute 'season_year'
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 354, in yee.service.downloadservice.DownloadService.download_completed
AttributeError: 'NoneType' object has no attribute 'season_year'
 2022/07/12 23:52:01 - ThreadPoolExecutor-5_1 - ERROR: 监控种子任务出现错误：'NoneType' object has no attribute 'season_year'
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 354, in yee.service.downloadservice.DownloadService.download_completed
AttributeError: 'NoneType' object has no attribute 'season_year'
 2022/07/12 23:53:00 - ThreadPoolExecutor-5_4 - ERROR: 监控种子任务出现错误：'NoneType' object has no attribute 'season_year'
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 354, in yee.service.downloadservice.DownloadService.download_completed
AttributeError: 'NoneType' object has no attribute 'season_year'
 2022/07/12 23:54:01 - ThreadPoolExecutor-5_1 - ERROR: 监控种子任务出现错误：'NoneType' object has no attribute 'season_year'
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 354, in yee.service.downloadservice.DownloadService.download_completed
AttributeError: 'NoneType' object has no attribute 'season_year'
```

**Comment by pofey** [comment]
是一个bug，新版已经修复了，过几天就发
