### ISSUE TITLE
微信企业接口API报错

### ISSUE THREAD

**Issue by suwill** [pofey/movie_robot#47]
>  2022/03/08 09:11:52 - Thread-1926 - ERROR: Exception on /api/qywx/receive [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "yee/controller/qywxcontroller.py", line 137, in yee.controller.qywxcontroller.receive
AttributeError: 'NoneType' object has no attribute 'text'
 2022/03/08 09:11:52 - Thread-1926 - INFO: 157.148.55.157 - - [08/Mar/2022 09:11:52] "POST /api/qywx/receive?msg_signature=3b0000000000000000000000000000000000f3&timestamp=1646701912&nonce=1640000231 HTTP/1.1" 500 -
 2022/03/08 09:11:52 - Thread-1927 - ERROR: Exception on /api/qywx/receive [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "yee/controller/qywxcontroller.py", line 137, in yee.controller.qywxcontroller.receive
AttributeError: 'NoneType' object has no attribute 'text'
 2022/03/08 09:11:52 - Thread-1927 - INFO: 157.148.55.192 - - [08/Mar/2022 09:11:52] "POST /api/qywx/receive?msg_signature=3b0000000000000000000000000000000000f3&timestamp=1646701912&nonce=1640000231 HTTP/1.1" 500 -
 2022/03/08 09:11:52 - Thread-1928 - ERROR: Exception on /api/qywx/receive [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "yee/controller/qywxcontroller.py", line 137, in yee.controller.qywxcontroller.receive
AttributeError: 'NoneType' object has no attribute 'text'
 2022/03/08 09:11:52 - Thread-1928 - INFO: 157.148.55.192 - - [08/Mar/2022 09:11:52] "POST /api/qywx/receive?msg_signature=3b0000000000000000000000000000000000f3&timestamp=1646701912&nonce=1640000231 HTTP/1.1" 500 

> -不知道为何它走了POST

这个等web出来也许就不算BUG了

**Comment by pofey** [comment]
升级
