### ISSUE TITLE
[缺陷]: 

### ISSUE THREAD

**Issue by KKfile** [pofey/movie_robot#476]
### 当前程序版本

0.9.97

### 问题描述

订阅后下载正常，整理剧集错误，只有5级正常整理，剩下一直报错循环
![image](https://user-images.githubusercontent.com/95568452/179403878-06e529b8-1f47-4f8a-b094-bf16130f6ab0.png)
![image](https://user-images.githubusercontent.com/95568452/179403885-5187ec03-f46d-4960-8a9e-0c4913bcecee.png)

### 重现步骤

1.mr搜索剧集：冰菓
2.订阅

### 发生问题时系统日志

```shell
2022/07/17 22:41:00 - ThreadPoolExecutor-4_4 - INFO: 完成剧集 冰菓(2012) 的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/tvshow.nfo
2022/07/17 22:41:01 - ThreadPoolExecutor-4_1 - INFO: 开始筛选免费种子。
2022/07/17 22:41:01 - ThreadPoolExecutor-4_1 - INFO: 经过筛选后没有需要下载的免费任务。
2022/07/17 22:41:04 - ThreadPoolExecutor-4_4 - INFO: 完成剧集 万人的死角(2012) 第1季第10集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E10 - 1080p HEVC.nfo
2022/07/17 22:41:04 - ThreadPoolExecutor-4_4 - INFO: 完成剧集 参加试映会！(2012) 第1季第8集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E08 - 1080p HEVC.nfo
2022/07/17 22:41:06 - ThreadPoolExecutor-4_4 - INFO: 完成剧集 黄昏现白骨(2012) 第1季第13集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E13 - 1080p HEVC.nfo
2022/07/17 22:41:07 - ThreadPoolExecutor-4_4 - INFO: 完成剧集 最后的目标(2012) 第1季第16集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E16 - 1080p HEVC.nfo
2022/07/17 22:41:11 - ThreadPoolExecutor-4_4 - INFO: 完成剧集 十文字事件(2012) 第1季第15集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E15 - 1080p HEVC.nfo
2022/07/17 22:41:11 - ThreadPoolExecutor-4_4 - ERROR: 文件转移失败：'NoneType' object has no attribute 'get'
2022/07/17 22:41:11 - ThreadPoolExecutor-4_4 - ERROR: 监控种子任务出现错误：'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 395, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 376, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 104, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/medialink.py", line 156, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 133, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 290, in yee.media.link.tvlink.TvLink.__handle__
AttributeError: 'NoneType' object has no attribute 'get'
2022/07/17 22:42:00 - ThreadPoolExecutor-4_2 - INFO: 完成剧集 冰菓(2012) 的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/tvshow.nfo
2022/07/17 22:42:01 - ThreadPoolExecutor-4_2 - INFO: 完成剧集 万人的死角(2012) 第1季第10集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E10 - 1080p HEVC.nfo
2022/07/17 22:42:02 - ThreadPoolExecutor-4_2 - INFO: 完成剧集 参加试映会！(2012) 第1季第8集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E08 - 1080p HEVC.nfo
2022/07/17 22:42:05 - ThreadPoolExecutor-4_2 - INFO: 完成剧集 黄昏现白骨(2012) 第1季第13集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E13 - 1080p HEVC.nfo
2022/07/17 22:42:07 - ThreadPoolExecutor-4_2 - INFO: 完成剧集 最后的目标(2012) 第1季第16集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E16 - 1080p HEVC.nfo
2022/07/17 22:42:12 - ThreadPoolExecutor-4_2 - INFO: 完成剧集 十文字事件(2012) 第1季第15集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E15 - 1080p HEVC.nfo
2022/07/17 22:42:12 - ThreadPoolExecutor-4_2 - ERROR: 文件转移失败：'NoneType' object has no attribute 'get'
2022/07/17 22:42:12 - ThreadPoolExecutor-4_2 - ERROR: 监控种子任务出现错误：'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 395, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 376, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 104, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/medialink.py", line 156, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 133, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 290, in yee.media.link.tvlink.TvLink.__handle__
AttributeError: 'NoneType' object has no attribute 'get'
2022/07/17 22:43:02 - ThreadPoolExecutor-4_4 - INFO: 完成剧集 冰菓(2012) 的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/tvshow.nfo
2022/07/17 22:43:06 - ThreadPoolExecutor-4_4 - INFO: 完成剧集 万人的死角(2012) 第1季第10集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E10 - 1080p HEVC.nfo
2022/07/17 22:43:10 - ThreadPoolExecutor-4_4 - INFO: 完成剧集 参加试映会！(2012) 第1季第8集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E08 - 1080p HEVC.nfo
2022/07/17 22:43:14 - ThreadPoolExecutor-4_4 - INFO: 完成剧集 黄昏现白骨(2012) 第1季第13集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E13 - 1080p HEVC.nfo
2022/07/17 22:43:19 - ThreadPoolExecutor-4_4 - INFO: 完成剧集 最后的目标(2012) 第1季第16集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E16 - 1080p HEVC.nfo
2022/07/17 22:43:20 - ThreadPoolExecutor-4_4 - INFO: 完成剧集 十文字事件(2012) 第1季第15集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E15 - 1080p HEVC.nfo
2022/07/17 22:43:20 - ThreadPoolExecutor-4_4 - ERROR: 文件转移失败：'NoneType' object has no attribute 'get'
2022/07/17 22:43:20 - ThreadPoolExecutor-4_4 - ERROR: 监控种子任务出现错误：'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 395, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 376, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 104, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/medialink.py", line 156, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 133, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 290, in yee.media.link.tvlink.TvLink.__handle__
AttributeError: 'NoneType' object has no attribute 'get'
2022/07/17 22:44:00 - ThreadPoolExecutor-4_2 - INFO: 完成剧集 冰菓(2012) 的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/tvshow.nfo
2022/07/17 22:44:04 - ThreadPoolExecutor-4_2 - INFO: 完成剧集 万人的死角(2012) 第1季第10集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E10 - 1080p HEVC.nfo
2022/07/17 22:44:04 - ThreadPoolExecutor-4_2 - INFO: 完成剧集 参加试映会！(2012) 第1季第8集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E08 - 1080p HEVC.nfo
2022/07/17 22:44:05 - ThreadPoolExecutor-4_2 - INFO: 完成剧集 黄昏现白骨(2012) 第1季第13集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E13 - 1080p HEVC.nfo
2022/07/17 22:44:05 - ThreadPoolExecutor-4_2 - INFO: 完成剧集 最后的目标(2012) 第1季第16集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E16 - 1080p HEVC.nfo
2022/07/17 22:44:06 - ThreadPoolExecutor-4_2 - INFO: 完成剧集 十文字事件(2012) 第1季第15集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E15 - 1080p HEVC.nfo
2022/07/17 22:44:06 - ThreadPoolExecutor-4_2 - ERROR: 文件转移失败：'NoneType' object has no attribute 'get'
2022/07/17 22:44:06 - ThreadPoolExecutor-4_2 - ERROR: 监控种子任务出现错误：'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 395, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 376, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 104, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/medialink.py", line 156, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 133, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 290, in yee.media.link.tvlink.TvLink.__handle__
AttributeError: 'NoneType' object has no attribute 'get'
2022/07/17 22:45:00 - ThreadPoolExecutor-4_3 - INFO: 完成剧集 冰菓(2012) 的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/tvshow.nfo
2022/07/17 22:45:05 - ThreadPoolExecutor-4_3 - INFO: 完成剧集 万人的死角(2012) 第1季第10集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E10 - 1080p HEVC.nfo
2022/07/17 22:45:09 - ThreadPoolExecutor-4_3 - INFO: 完成剧集 参加试映会！(2012) 第1季第8集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E08 - 1080p HEVC.nfo
2022/07/17 22:45:10 - ThreadPoolExecutor-4_3 - INFO: 完成剧集 黄昏现白骨(2012) 第1季第13集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E13 - 1080p HEVC.nfo
2022/07/17 22:45:12 - ThreadPoolExecutor-4_3 - INFO: 完成剧集 最后的目标(2012) 第1季第16集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E16 - 1080p HEVC.nfo
2022/07/17 22:45:13 - ThreadPoolExecutor-4_3 - INFO: 完成剧集 十文字事件(2012) 第1季第15集的NFO文件生成，路径：/video/plex_dongman/冰菓 (2012) [tmdbid=65329]/Season 1/冰菓 S01E15 - 1080p HEVC.nfo
2022/07/17 22:45:13 - ThreadPoolExecutor-4_3 - ERROR: 文件转移失败：'NoneType' object has no attribute 'get'
2022/07/17 22:45:13 - ThreadPoolExecutor-4_3 - ERROR: 监控种子任务出现错误：'NoneType' object has no attribute 'get'
```

### 健康检查

![image](https://user-images.githubusercontent.com/95568452/179403868-034a4b5d-5b9e-493f-8a56-7484aad1efb3.png)

**Comment by pofey** [comment]
先升级 再复现 不查老板问题了

**Comment by KKfile** [comment]
> 先升级 再复现 不查老板问题了

多谢，升级0.9.99解决了

**Comment by KKfile** [comment]
已解决
