### ISSUE TITLE
[缺陷]: 某些订阅剧集自动监控整理失败

### ISSUE THREAD

**Issue by qzbeta** [pofey/movie_robot#484]
### 当前程序版本

0.9.99

### 问题描述

![Shell_20220718-172021-248](https://user-images.githubusercontent.com/48495382/179488944-6ec7b5d6-512f-4b97-8b8c-770de2fda339.png)

某些剧集下载完成后无法整理。
一直报错，无限循环。
导致程序卡顿，webui打开&刷新都很慢。
![Shell_20220718-170140-454](https://user-images.githubusercontent.com/48495382/179488541-b929243d-cd70-4b64-9534-1ff9a7c934ad.png)
订阅的西部世界第四季第四集，早上9点44分自动下载完成以后，自动整理就开始报错。
![Shell_20220718-170059-021](https://user-images.githubusercontent.com/48495382/179488747-8e877384-c689-4631-a8ff-1e0b1967ada9.png)
![Shell_20220718-170116-628](https://user-images.githubusercontent.com/48495382/179488775-0b2f6690-fde8-436b-82fb-3300960625a6.png)
报错无限持续。
在下载记录中删除该集下载记录，才能终止报错。

### 重现步骤

订阅下载西部世界第四季第四集可以100%重现。
尝试过观众组和柠檬组的资源，报错都相同。

### 发生问题时系统日志

```shell
2022/07/18 16:35:10 - ThreadPoolExecutor-5_4 - ERROR: 文件转移失败：can only concatenate list (not "NoneType") to list
 2022/07/18 16:35:10 - ThreadPoolExecutor-5_4 - ERROR: 监控种子任务出现错误：can only concatenate list (not "NoneType") to list
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 397, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 377, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 106, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/medialink.py", line 175, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 133, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 280, in yee.media.link.tvlink.TvLink.__handle__
  File "yee/media/link/tvlink.py", line 156, in yee.media.link.tvlink.TvLink.__create_tv_nfo__
TypeError: can only concatenate list (not "NoneType") to list
 2022/07/18 16:35:45 - SubConsumer - INFO: 菜单(2022) 经过系统分析后，没有搜到有效结果。
 2022/07/18 16:36:10 - ThreadPoolExecutor-5_2 - ERROR: 文件转移失败：can only concatenate list (not "NoneType") to list
 2022/07/18 16:36:10 - ThreadPoolExecutor-5_2 - ERROR: 监控种子任务出现错误：can only concatenate list (not "NoneType") to list
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 397, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 377, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 106, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/medialink.py", line 175, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 133, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 280, in yee.media.link.tvlink.TvLink.__handle__
  File "yee/media/link/tvlink.py", line 156, in yee.media.link.tvlink.TvLink.__create_tv_nfo__
TypeError: can only concatenate list (not "NoneType") to list
 2022/07/18 16:37:10 - ThreadPoolExecutor-5_4 - ERROR: 文件转移失败：can only concatenate list (not "NoneType") to list
 2022/07/18 16:37:10 - ThreadPoolExecutor-5_4 - ERROR: 监控种子任务出现错误：can only concatenate list (not "NoneType") to list
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 397, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 377, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 106, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/medialink.py", line 175, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 133, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 280, in yee.media.link.tvlink.TvLink.__handle__
  File "yee/media/link/tvlink.py", line 156, in yee.media.link.tvlink.TvLink.__create_tv_nfo__
TypeError: can only concatenate list (not "NoneType") to list
 2022/07/18 16:38:11 - ThreadPoolExecutor-5_3 - ERROR: 文件转移失败：can only concatenate list (not "NoneType") to list
 2022/07/18 16:38:11 - ThreadPoolExecutor-5_3 - ERROR: 监控种子任务出现错误：can only concatenate list (not "NoneType") to list
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 397, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 377, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 106, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/medialink.py", line 175, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 133, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 280, in yee.media.link.tvlink.TvLink.__handle__
  File "yee/media/link/tvlink.py", line 156, in yee.media.link.tvlink.TvLink.__create_tv_nfo__
TypeError: can only concatenate list (not "NoneType") to list
 2022/07/18 16:39:12 - ThreadPoolExecutor-5_4 - ERROR: 文件转移失败：can only concatenate list (not "NoneType") to list
 2022/07/18 16:39:12 - ThreadPoolExecutor-5_4 - ERROR: 监控种子任务出现错误：can only concatenate list (not "NoneType") to list
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 397, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 377, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 106, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/medialink.py", line 175, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 133, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 280, in yee.media.link.tvlink.TvLink.__handle__
  File "yee/media/link/tvlink.py", line 156, in yee.media.link.tvlink.TvLink.__create_tv_nfo__
TypeError: can only concatenate list (not "NoneType") to list
 2022/07/18 16:40:00 - ThreadPoolExecutor-0_6 - INFO: Emby连接正常，Embybeta-UNRAID版本为4.8.0.6
 2022/07/18 16:40:12 - ThreadPoolExecutor-5_2 - ERROR: 文件转移失败：can only concatenate list (not "NoneType") to list
 2022/07/18 16:40:12 - ThreadPoolExecutor-5_2 - ERROR: 监控种子任务出现错误：can only concatenate list (not "NoneType") to list
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 397, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 377, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 106, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/medialink.py", line 175, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 133, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 280, in yee.media.link.tvlink.TvLink.__handle__
  File "yee/media/link/tvlink.py", line 156, in yee.media.link.tvlink.TvLink.__create_tv_nfo__
TypeError: can only concatenate list (not "NoneType") to list
 2022/07/18 16:41:11 - ThreadPoolExecutor-5_4 - ERROR: 文件转移失败：can only concatenate list (not "NoneType") to list
 2022/07/18 16:41:11 - ThreadPoolExecutor-5_4 - ERROR: 监控种子任务出现错误：can only concatenate list (not "NoneType") to list
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 397, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 377, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 106, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/medialink.py", line 175, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 133, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 280, in yee.media.link.tvlink.TvLink.__handle__
  File "yee/media/link/tvlink.py", line 156, in yee.media.link.tvlink.TvLink.__create_tv_nfo__
```

### 健康检查

![Shell_20220718-175110-241](https://user-images.githubusercontent.com/48495382/179488271-10571f74-3de1-40da-84fe-8fd0eafa4833.png)

**Comment by pofey** [comment]
你这个代码感觉和我的版本不同步，等升级下一版再看看吧
