### ISSUE TITLE
[BUG REPORT]报错

### ISSUE THREAD

**Issue by dskblh** [pofey/movie_robot#49]
已升级0.1.2，使用过程中报错，不知道是什么错误。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "yee/core/downloadclient.py", line 70, in yee.core.downloadclient.QbittorrentClient.exists_hash
File "/usr/local/lib/python3.9/site-packages/qbittorrent/client.py", line 201, in get_torrent
return self._get('torrents/properties?hash=' + infohash.lower())
File "/usr/local/lib/python3.9/site-packages/qbittorrent/client.py", line 52, in _get
return self._request(endpoint, 'get', **kwargs)
File "/usr/local/lib/python3.9/site-packages/qbittorrent/client.py", line 84, in _request
request = self.session.get(final_url, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by pofey** [comment]
访问qbit的时候出错了呀
