### ISSUE TITLE
[缺陷]: jellyfin下载字幕出错

### ISSUE THREAD

**Issue by kriskwok** [pofey/movie_robot#496]
### 当前程序版本

0.9.99

### 问题描述

下载字幕出错

### 重现步骤

2022-07-20 10:32:00,005 - MainThread - INFO: 收到字幕处理消息：{'task_id': 67, 'content_path': '/video/link/剧集/风骚律师 (2015) [tmdbid=60059]/Season 6', 'media_info': {'tmdb_id': 60059, 'type': 'TV', 'name': '风骚律师', 'year': 2015, 'season_year': 2022, 'season_index': 6, 'episodes': '9'}}
2022-07-20 10:32:00,020 - MainThread - ERROR: 下载字幕出错：invalid literal for int() with base 10: 'tt11630814'
Traceback (most recent call last):
  File "yee/task/process/downloadsubtitleprocess.py", line 174, in yee.task.process.downloadsubtitleprocess.DownloadSubtitleProcess.run
  File "yee/task/process/downloadsubtitleprocess.py", line 110, in yee.task.process.downloadsubtitleprocess.DownloadSubtitleProcess.__download_tv_sub__
  File "yee/media/server/jellyfinmediaserver.py", line 361, in yee.media.server.jellyfinmediaserver.JellyfinMediaServer.get_episodes_from_tmdbid
  File "yee/media/server/jellyfinmediaserver.py", line 208, in yee.media.server.jellyfinmediaserver.JellyfinMediaServer.search_by_id
  File "yee/media/server/jellyfinmediaserver.py", line 92, in yee.media.server.jellyfinmediaserver.JellyfinMediaServer.__trans_to_media__
ValueError: invalid literal for int() with base 10: 'tt11630814'

### 健康检查

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/31760242/179884413-9d2add5b-e647-4b70-9b89-2b8d20cb605b.png">

**Comment by pofey** [comment]
这个问题有点诡异，你能看下你这部剧在jellfyin里 tvdbid 是什么吗，怎么会是个imdbid呢

**Comment by kriskwok** [comment]
> 这个问题有点诡异，你能看下你这部剧在jellfyin里 tvdbid 是什么吗，怎么会是个imdbid呢

<img width="964" alt="image" src="https://user-images.githubusercontent.com/31760242/179987983-b92a7279-4c50-480e-94c2-c71df48180e8.png">
<img width="967" alt="image" src="https://user-images.githubusercontent.com/31760242/179988047-0be524ab-480d-4d74-8405-135e9807bd1c.png">

**Comment by pofey** [comment]
> > 这个问题有点诡异，你能看下你这部剧在jellfyin里 tvdbid 是什么吗，怎么会是个imdbid呢
> 
> <img alt="image" width="964" src="https://user-images.githubusercontent.com/31760242/179987983-b92a7279-4c50-480e-94c2-c71df48180e8.png">
> 
> <img alt="image" width="967" src="https://user-images.githubusercontent.com/31760242/179988047-0be524ab-480d-4d74-8405-135e9807bd1c.png">

没有tmdbid吗

**Comment by kriskwok** [comment]
其他剧好像也会

2022-07-20 22:13:00,003 - MainThread - INFO: 收到字幕处理消息：{'task_id': 62, 'content_path': '/video/link/剧集/西部世界 (2016) [tmdbid=63247]/Season 4', 'media_info': {'tmdb_id': 63247, 'type': 'TV', 'name': '西部世界', 'year': 2016, 'season_year': 2022, 'season_index': 4, 'episodes': '2'}}
2022-07-20 22:13:00,015 - MainThread - ERROR: 下载字幕出错：invalid literal for int() with base 10: 'tt0475784'
Traceback (most recent call last):
  File "yee/task/process/downloadsubtitleprocess.py", line 174, in yee.task.process.downloadsubtitleprocess.DownloadSubtitleProcess.run
  File "yee/task/process/downloadsubtitleprocess.py", line 110, in yee.task.process.downloadsubtitleprocess.DownloadSubtitleProcess.__download_tv_sub__
  File "yee/media/server/jellyfinmediaserver.py", line 361, in yee.media.server.jellyfinmediaserver.JellyfinMediaServer.get_episodes_from_tmdbid
  File "yee/media/server/jellyfinmediaserver.py", line 208, in yee.media.server.jellyfinmediaserver.JellyfinMediaServer.search_by_id
  File "yee/media/server/jellyfinmediaserver.py", line 92, in yee.media.server.jellyfinmediaserver.JellyfinMediaServer.__trans_to_media__
ValueError: invalid literal for int() with base 10: 'tt0475784'

**Comment by pofey** [comment]
media.tvdb_id = int(item.get('ProviderIds').get('Tvdb')) if item.get('ProviderIds').get('Tvdb') else None

报错的代码，这分别读的是tvdb

**Comment by pofey** [comment]
不过我加了个异常控制
