### ISSUE TITLE
jackett好像又出问题了

### ISSUE THREAD

**Issue by AAlexDing** [pofey/movie_robot#50]
2022/03/18 20:01:22 - ThreadPoolExecutor-0_0 - INFO: 请求None 失败，开始准备重试(1/3)
2022/03/18 20:01:22 - ThreadPoolExecutor-0_0 - INFO: 错误信息：Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
2022/03/18 20:01:22 - ThreadPoolExecutor-0_0 - INFO: 请求None 失败，开始准备重试(2/3)
2022/03/18 20:01:22 - ThreadPoolExecutor-0_0 - INFO: 错误信息：Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
2022/03/18 20:01:22 - ThreadPoolExecutor-0_0 - INFO: 请求None 失败，开始准备重试(3/3)
2022/03/18 20:01:22 - ThreadPoolExecutor-0_0 - INFO: 错误信息：Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
2022/03/18 20:01:22 - ThreadPoolExecutor-0_0 - ERROR: 智能下载任务出错。

Traceback (most recent call last):
File "yee/core/tasksyncmovies.py", line 118, in yee.core.tasksyncmovies.TaskSyncMovies.run
File "yee/core/tasksyncmovies.py", line 166, in yee.core.tasksyncmovies.TaskSyncMovies.download
File "yee/service/downloadservice.py", line 240, in yee.service.downloadservice.DownloadService.download
File "yee/service/downloadservice.py", line 254, in yee.service.downloadservice.DownloadService.download
File "yee/pt/jackett.py", line 163, in yee.pt.jackett.Jackett.download_torrent
File "yee/pt/jackett.py", line 148, in yee.pt.jackett.Jackett.parse_download_filename
AttributeError: 'NoneType' object has no attribute 'headers'

**Comment by pofey** [comment]
jackett已经下线
