### ISSUE TITLE
[缺陷]: 监控任务报错

### ISSUE THREAD

**Issue by blood1214** [pofey/movie_robot#500]
### 当前程序版本

0.9.99.0720

### 问题描述

下载完乘风破浪的姐姐第三季的资源，硬链完成后系统日志报错监控种子任务出现错误

### 重现步骤

正常订阅完的出错，其他订阅任务未发生问题。不能确定是什么原因报错

### 发生问题时系统日志

```shell
2022/07/21 13:23:07 - ThreadPoolExecutor-5_0 - INFO: 完成剧集 乘风破浪 的NFO文件生成，路径：/share/电视/综艺/乘风破浪 (2020) [tmdbid=104716]/tvshow.nfo

2022/07/21 13:23:07 - ThreadPoolExecutor-5_0 - INFO: 完成剧集 第3季 季 3 的NFO文件生成，路径：/share/电视/综艺/乘风破浪 (2020) [tmdbid=104716]/Season 3/season.nfo

2022/07/21 13:23:07 - ThreadPoolExecutor-5_0 - INFO: /share/电视/tv/综艺/乘风破浪.Sisters.Who.Make.Waves.2022.S03.1080p.WEB-DL.H264.AAC-ADWeb/乘风破浪.加时营业第8期.Sisters.Who.Make.Waves.2022.1080p.WEB-DL.H264.AAC-ADWeb.mp4 乘风破浪.加时营业第8期.Sisters.Who.Make.Waves.2022.1080p.WEB-DL.H264.AAC-ADWeb.mp4分析不出集号，跳过处理

2022/07/21 13:23:12 - ThreadPoolExecutor-5_0 - INFO: /share/电视/tv/综艺/乘风破浪.Sisters.Who.Make.Waves.2022.S03.1080p.WEB-DL.H264.AAC-ADWeb/乘风破浪.训练室第10期.Sisters.Who.Make.Waves.2022.1080p.WEB-DL.H264.AAC-ADWeb.mp4 乘风破浪.训练室第10期.Sisters.Who.Make.Waves.2022.1080p.WEB-DL.H264.AAC-ADWeb.mp4分析不出集号，跳过处理

2022/07/21 13:23:12 - ThreadPoolExecutor-5_0 - INFO: 通知媒体库刷新完成，tmdb_id: 104716 save_path: /share/电视 item_id: 190881

2022/07/21 13:23:12 - ThreadPoolExecutor-5_0 - INFO: 乘风破浪的姐姐(2020) 发行地区为['中国大陆']，不需要下载字幕。

2022/07/21 13:23:12 - ThreadPoolExecutor-5_0 - ERROR: 监控种子任务出现错误：invalid literal for int() with base 10: '未知'

Traceback (most recent call last):

  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run

  File "yee/service/downloadservice.py", line 411, in yee.service.downloadservice.DownloadService.download_completed

  File "yee/service/notifyservice.py", line 242, in yee.service.notifyservice.NotifyService.notify_by_movie

  File "yee/media/mediaparser.py", line 746, in yee.media.mediaparser.MediaParser.episode_format

ValueError: invalid literal for int() with base 10: '未知'
```

### 健康检查

![image](https://user-images.githubusercontent.com/107973079/180137712-4bc159c2-f254-4165-8309-2a643a959554.png)

**Comment by pofey** [comment]
要提供一下，你所下载的那个种子资源看一下，以及通过什么渠道下载的
