### ISSUE TITLE
[缺陷]: plex媒体库不存在时报错导致下载无法完成

### ISSUE THREAD

**Issue by zsgcgrs** [pofey/movie_robot#512]
### 当前程序版本

0.9.99 0723

### 问题描述

洗版资源下载完成后mr已经删掉了旧资源（旧metadata id），新资源成功硬链接入库也产生了新的metadata id，但是mr还是循环去删旧资源（旧metadata id），由于（旧metadata id）已经删除肯定是删不成的，所以就一直循环删，循环硬链接，循环报错

### 重现步骤

洗版时即出现

### 发生问题时系统日志

```shell
2022/07/23 09:15:38 - ThreadPoolExecutor-5_0 - INFO: 内容：/video/movie/MOV-OT/铁血战士2.1990.1080p.国英双语.中英字幕￡星辰/[铁血战士2].Predator.2.1990.BluRay.1080p.x264.DTS.2Audios.mkv 识别为：铁血战士2 1990-11-20
 2022/07/23 09:15:41 - ThreadPoolExecutor-5_0 - INFO: 完成电影 铁血战士2(1990) 的NFO文件生成，路径：/video/link/movie/MOV-OT/铁血战士2 (1990)/铁血战士2 (1990) - 1080p x264 DTS.nfo
 2022/07/23 09:15:47 - ThreadPoolExecutor-5_2 - INFO: 天空最新种子同步完成。
 2022/07/23 09:15:54 - ThreadPoolExecutor-5_2 - INFO: 北洋最新种子同步完成。
 2022/07/23 09:15:56 - ThreadPoolExecutor-5_0 - ERROR: 监控种子任务出现错误：(404) not_found; http://10.0.0.5:32400/library/metadata/32145?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 406, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/mediaserverservice.py", line 56, in yee.service.mediaserverservice.MediaServerService.refresh_media_server
  File "yee/media/server/plexmediaserver.py", line 179, in yee.media.server.plexmediaserver.PlexMediaServer.search_by_id
  File "yee/media/server/plexmediaserver.py", line 106, in yee.media.server.plexmediaserver.PlexMediaServer.__trans_to_media__
  File "/dependencies/plexapi/base.py", line 341, in reload
    return self._reload(key=key, **kwargs)
  File "/dependencies/plexapi/base.py", line 350, in _reload
    data = self._server.query(key)
  File "/dependencies/plexapi/server.py", line 680, in query
    raise NotFound(message)
plexapi.exceptions.NotFound: (404) not_found; http://10.0.0.5:32400/library/metadata/32145?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
 2022/07/23 09:16:00 - ThreadPoolExecutor-5_2 - INFO: 我堡最新种子同步完成。
 2022/07/23 09:16:06 - ThreadPoolExecutor-5_1 - INFO: 铁血战士2(1990)下完更好的版本，开始删除媒体库旧版并替换为新版。
 2022/07/23 09:16:06 - ThreadPoolExecutor-5_1 - ERROR: 删除plex电影出错：(404) not_found; http://10.0.0.5:32400/library/metadata/32145 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
 2022/07/23 09:16:06 - ThreadPoolExecutor-5_1 - INFO: 内容：/video/movie/MOV-OT/铁血战士2.1990.1080p.国英双语.中英字幕￡星辰/[铁血战士2].Predator.2.1990.BluRay.1080p.x264.DTS.2Audios.mkv 识别为：铁血战士2 1990-11-20
 2022/07/23 09:16:07 - ThreadPoolExecutor-5_1 - INFO: 完成电影 铁血战士2(1990) 的NFO文件生成，路径：/video/link/movie/MOV-OT/铁血战士2 (1990)/铁血战士2 (1990) - 1080p x264 DTS .nfo
 2022/07/23 09:16:07 - ThreadPoolExecutor-5_1 - ERROR: 监控种子任务出现错误：(404) not_found; http://10.0.0.5:32400/library/metadata/32145?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 406, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/mediaserverservice.py", line 56, in yee.service.mediaserverservice.MediaServerService.refresh_media_server
  File "yee/media/server/plexmediaserver.py", line 179, in yee.media.server.plexmediaserver.PlexMediaServer.search_by_id
  File "yee/media/server/plexmediaserver.py", line 106, in yee.media.server.plexmediaserver.PlexMediaServer.__trans_to_media__
  File "/dependencies/plexapi/base.py", line 341, in reload
    return self._reload(key=key, **kwargs)
  File "/dependencies/plexapi/base.py", line 350, in _reload
    data = self._server.query(key)
  File "/dependencies/plexapi/server.py", line 680, in query
    raise NotFound(message)
plexapi.exceptions.NotFound: (404) not_found; http://10.0.0.5:32400/library/metadata/32145?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
```

### 健康检查

木有

**Comment by pofey** [comment]
已经修复
