### ISSUE TITLE
[缺陷]: 订阅失败

### ISSUE THREAD

**Issue by sinosofti** [pofey/movie_robot#518]
### 当前程序版本

0.9.99.0723

### 问题描述

电视榜单点击订阅订阅不上

### 重现步骤

电视榜单点击订阅订阅不上

### 发生问题时系统日志

```shell
2022/07/24 10:17:17 - SubRequestConsumer - INFO: 甘古拜·卡蒂娅瓦迪(2022) 选用过滤器：（默认）新国外电影（自动洗版） 排序规则：compress




2022/07/24 10:18:00 - ThreadPoolExecutor-4_2 - ERROR: 文件转移失败：找不到内容路径或无权限访问：/downloads/tv/Moon.Knight.S01E02.Summon.the.Suit.2160p.WEB-DL.DDP5.1.Atmos.HDR.H.265-NOSiViD.mkv
2022/07/24 10:18:00 - ThreadPoolExecutor-4_2 - ERROR: 监控种子任务出现错误：找不到内容路径或无权限访问：/downloads/tv/Moon.Knight.S01E02.Summon.the.Suit.2160p.WEB-DL.DDP5.1.Atmos.HDR.H.265-NOSiViD.mkv
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 404, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 384, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 80, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/tvlink.py", line 23, in yee.media.link.tvlink.TvLink.__init__
  File "yee/media/link/medialink.py", line 91, in yee.media.link.medialink.MediaLink.__init__
FileNotFoundError: 找不到内容路径或无权限访问：/downloads/tv/Moon.Knight.S01E02.Summon.the.Suit.2160p.WEB-DL.DDP5.1.Atmos.HDR.H.265-NOSiViD.mkv
2022/07/24 10:18:17 - SubRequestConsumer - ERROR: douban_id: 34966922 订阅失败，请查看日志分析原因。
Traceback (most recent call last):
  File "/dependencies/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yee/service/smartdownloadservice.py", line 336, in yee.service.smartdownloadservice.SmartDownloadService.sub_from_douban
  File "yee/common/basemodel.py", line 88, in yee.common.basemodel.BaseModel.save
  File "yee/common/basemodel.py", line 85, in yee.common.basemodel.BaseModel.save
  File "<string>", line 2, in commit
  File "/dependencies/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/dependencies/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/dependencies/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/dependencies/sqlalchemy/orm/session.py", line 3383, in flush
    self._flush(objects)
  File "/dependencies/sqlalchemy/orm/session.py", line 3523, in _flush
    transaction.rollback(_capture_exception=True)
  File "/dependencies/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/orm/session.py", line 3483, in _flush
    flush_context.execute()
  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/dependencies/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/dependencies/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/dependencies/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/dependencies/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/dependencies/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/dependencies/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/dependencies/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO subscribe (gmt_create, gmt_modified, uid, tmdb_id, douban_id, cn_name, en_name, alias, type, "desc", release_year, genres, area, rating, poster_path, thumb_image_path, season_index, season_year, episode_count, choose_rule_name, priority_keywords, status, download_mode, filter_config, remote_search, is_aired, release_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('2022-07-24 10:17:16', '2022-07-24 10:17:16', 1, 664332, 34966922, '甘古拜·卡蒂娅瓦迪', 'Gangubai Kathiawadi', '甘古拜·卡蒂亚瓦迪,孟买女帝,孟买大家姐', 'Movie', '甘加·哈吉万达斯(阿莉雅·布哈特 饰)出生于Kathiawar的一个富裕家庭，她的梦想是成为一名宝莱坞女演员。在16岁时，她爱上了拉姆尼克·拉尔(瓦伦·卡普尔 饰)。拉姆尼克答表示甘加可以在他的姨妈希拉的指导下进入电影行业，因此他们私奔到孟买。但是，她的生活从此发生了翻天覆地的变化。因为他以1000卢比将她卖给了卡马提普拉的一家妓院，她不得不开始卖淫。后来，她成了有势力的妓院老板娘甘古拜·卡蒂亚瓦迪，并赢得了她居住地区（卡马提普拉）的选举。唐·拉希姆·拉拉打了一个强奸她的同伙后，成为她的结拜兄弟。甘谷后来爱上了一个年轻的裁缝阿夫萨恩。她曾经倡导妇女权利和性工作者的平等权利。', 2022, '犯罪,剧情', '印度', 7.7, '/wHPEKlzg7CaJFCjWlMdZKpCRIDl.jpg', 'https://image.tmdb.org/t/p/w1066_and_h600_bestv2/49czdTl4eA6YHrE7hqKUvzgWi5W.jpg', None, None, None, 'compress', None, 0, 2, '{"download_mode": 2, "media_source": [], "resolution": ["4K", "2K", "2160p", "2160i", "1440p", "1440i", "1080p", "1080i"], "media_codec": ["AVC", "H. ... (200 characters truncated) ... yword": "Dovi,DoVi,Dolby,Vision,DSNP,DV,3D,HDR,MiniBD,杜比视界,花絮,预告,偏色,设备,枪版,BDMV, ISO,幕后记录,幕后制作,制作幕后,Pad,iPad,Trailer,Trailers", "include_keyword": ""}', 0, 1, '2022-02-16')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022/07/24 10:18:17 - SubRequestConsumer - ERROR: douban_id: 34966922 订阅失败，请查看日志分析原因。
```

### 健康检查

![image](https://user-images.githubusercontent.com/38282416/180629414-012f203d-354c-4592-aca1-1f190ca859cb.png)

**Comment by pofey** [comment]
1、重启，并把你的机器人配置目录，换到一个稳定的存储区上，不要去和下载目录放一起。
2、另外，解决掉自己的整理报错，配置也有问题。

**Comment by sinosofti** [comment]
回复1 订阅失败通过 重启解决 了

**Comment by pofey** [comment]
> 回复1 订阅失败通过 重启解决 了

保证磁盘io稳定

**Comment by sinosofti** [comment]
好的 辛苦大佬
