### ISSUE TITLE
[缺陷]: 下载的电视剧选择的移动模式日志 一直报错

### ISSUE THREAD

**Issue by sinosofti** [pofey/movie_robot#519]
### 当前程序版本

0.9.99.0723

### 问题描述

下载的电视剧选择的移动模式日志 一直报错

### 重现步骤

1.下载电视剧 模式为移动模式 电视剧可以正常移动过去 
2.定时扫描出错  下图为移动过后的qb文件夹
![image](https://user-images.githubusercontent.com/38282416/180629618-b7f76532-fc32-406c-ae29-5768f1d06f9b.png)

### 发生问题时系统日志

```shell
2022/07/24 10:27:00 - ThreadPoolExecutor-4_0 - ERROR: 文件转移失败：找不到内容路径或无权限访问：/downloads/tv/Moon.Knight.S01E02.Summon.the.Suit.2160p.WEB-DL.DDP5.1.Atmos.HDR.H.265-NOSiViD.mkv
2022/07/24 10:27:00 - ThreadPoolExecutor-4_0 - ERROR: 监控种子任务出现错误：找不到内容路径或无权限访问：/downloads/tv/Moon.Knight.S01E02.Summon.the.Suit.2160p.WEB-DL.DDP5.1.Atmos.HDR.H.265-NOSiViD.mkv
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 404, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 384, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 80, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/tvlink.py", line 23, in yee.media.link.tvlink.TvLink.__init__
  File "yee/media/link/medialink.py", line 91, in yee.media.link.medialink.MediaLink.__init__
```

### 健康检查

![Uploading image.png…]()

**Comment by pofey** [comment]
2022/07/24 10:27:00 - ThreadPoolExecutor-4_0 - ERROR: 监控种子任务出现错误：找不到内容路径或无权限访问：/downloads/tv/Moon.Knight.S01E02.Summon.the.Suit.2160p.WEB-DL.DDP5.1.Atmos.HDR.H.265-NOSiViD.mkv
 这不是说的很清楚了么
