### ISSUE TITLE
[缺陷]: overseerr自动批准后MR报错，无法形成MR订阅

### ISSUE THREAD

**Issue by Jim-CN** [pofey/movie_robot#529]
### 当前程序版本

0.9.99.0725

### 问题描述

Overseerr中搜索影片犯罪都市（2017），点击提交请求，显示已自动批准，可在Overseerr中查看到已批准到请求，但MR中没有相应的订阅和下载，日志如下

### 重现步骤

1、取消overseerr中radarr为默认服务器
2、搜索影片
3、提交请求
4、点击确认自动审批
5、查看overseerr中已有该影片请求记录，显示为已批准
6、MR无响应，日志报错，radarr中可查到该影片记录已提交

7、删除overseerr中radarr配置，删除overseerr中请求记录
8、重复2-5
9、MR无响应，日志报错

### 发生问题时系统日志

```shell
2022/07/26 11:04:03 - Thread-2410 - INFO: 来自Overseerr的订阅，请求参数: {'notification_type': 'MEDIA_AUTO_APPROVED', 'event': 'Movie Request Automatically Approved', 'subject': 'The Outlaws (2017)', 'message': 'In Chinatown, law and order is turned upside down when a trio of feral Chinese gangsters arrive, start terrorizing civilians, and usurping territory. The beleaguered local gangsters team up with the police, lead by the badass loose cannon Ma Seok-do, to bring them down. Based on a true story.', 'image': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/pUd1FYQb5r55RqXpx08dnCbP1fs.jpg', 'media': {'media_type': 'movie', 'tmdbId': '479718', 'tvdbId': '', 'status': 'PENDING', 'status4k': 'UNKNOWN'}, 'request': {'request_id': '42', 'requestedBy_email': 'jim.xie1977@gmail.com', 'requestedBy_username': 'CNJim', 'requestedBy_avatar': 'https://plex.tv/users/2cf984887a85f325/avatar?c=1649478098'}, 'issue': None, 'comment': None, 'extra': []}
 2022/07/26 11:04:15 - ThreadPoolExecutor-4_3 - INFO: RARBG最新种子同步完成。
 2022/07/26 11:04:16 - Thread-2410 - ERROR: 订阅失败，tmdb_id: 479718 movie_type: 电影
Traceback (most recent call last):
  File "/dependencies/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/dependencies/httpcore/backends/sync.py", line 57, in start_tls
    raise exc
  File "/dependencies/httpcore/backends/sync.py", line 52, in start_tls
    sock = ssl_context.wrap_socket(
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/dependencies/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/dependencies/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/dependencies/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/dependencies/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/dependencies/httpcore/_sync/connection.py", line 150, in _connect
    stream = stream.start_tls(**kwargs)
  File "/dependencies/httpcore/backends/sync.py", line 57, in start_tls
    raise exc
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: EOF occurred in violation of protocol (_ssl.c:1125)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yee/controller/subscribecontroller.py", line 66, in yee.controller.subscribecontroller.overseerr_sub
  File "yee/service/smartdownloadservice.py", line 209, in yee.service.smartdownloadservice.SmartDownloadService.sub_from_tmdb
  File "yee/service/moviemetadataservice.py", line 135, in yee.service.moviemetadataservice.MovieMetadataService.get_thumb_image_url
  File "yee/media/tmdbapi.py", line 216, in yee.media.tmdbapi.TmdbApi.get_images
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/dependencies/tenacity/__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "yee/media/tmdbapi.py", line 90, in yee.media.tmdbapi.TmdbApi.__do_get__
  File "/dependencies/httpx/_api.py", line 189, in get
    return request(
  File "/dependencies/httpx/_api.py", line 100, in request
    return client.request(
  File "/dependencies/httpx/_client.py", line 802, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/dependencies/httpx/_client.py", line 889, in send
    response = self._send_handling_auth(
  File "/dependencies/httpx/_client.py", line 917, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/dependencies/httpx/_client.py", line 954, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/dependencies/httpx/_client.py", line 990, in _send_single_request
    response = transport.handle_request(request)
  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:1125)
```

### 健康检查

![1658806054044](https://user-images.githubusercontent.com/86034975/180916693-bc29f641-0d45-4b21-bc82-93dee8119f96.png)
![1658806692297](https://user-images.githubusercontent.com/86034975/180917836-292930e9-87f0-46b7-a2e0-500123928fde.png)

**Comment by pofey** [comment]
健康检查的图呢？

**Comment by Jim-CN** [comment]
你的意思是因为MR访问tmdb失败导致的？ @pofey 这部分也按手册做了smartdns，：（

**Comment by pofey** [comment]
> 你的意思是因为MR访问tmdb失败导致的？ @pofey 这部分也按手册做了smartdns，：（

看日志报错确实是这样 再获取tmdb 封面图片时报错了

**Comment by Jim-CN** [comment]
1、取封面图片不应该是生成订阅的必要条件吧？因这个错误导致订阅不成功是不是不太合理？这点能否优化呢？
2、按指引做了smart，其他还有什么方案可以改善tmdb的访问吗？

**Comment by pofey** [comment]
> 1、取封面图片不应该是生成订阅的必要条件吧？因这个错误导致订阅不成功是不是不太合理？这点能否优化呢？
> 2、按指引做了smart，其他还有什么方案可以改善tmdb的访问吗？

搞完dns 配置完那个防污染，国内绝大多数区域访问应该都足够稳定了。你进容器，看看api tmdb域名的解析稳定和curl看看稳定性吧。是否生效

**Comment by pofey** [comment]
overseer来的订阅只有tmdb数据，这个地方就要强依赖。
网页自己的订阅，tmdb失败会临时降级豆瓣

**Comment by pofey** [comment]
不打算过多优化ov提交过来的请求接口了，现在应该已经没什么人用了，那曾经是个过渡选择

**Comment by Jim-CN** [comment]
明白，可以理解，谢谢，请关闭
