### ISSUE TITLE
[建议]存量电影硬链是否可以支持记录跳过功能

### ISSUE THREAD

**Issue by dskblh** [pofey/movie_robot#53]
存量电影手动硬链，实际使用过程当中碰到如下问题，TMDB的API由于网络波动问题，如果超时就会导致硬链进程无法继续，重新再来又得全部重新硬链一次。
之前用过一个硬链工具hlink，有记录功能，如果源文件已被硬链过会直接跳过不再进行重复操作，不知道是否能增加进机器人的手动硬链功能中，对于电影库大的人来说应该很实用，几千个文件从头硬链一遍，碰到网络问题概率很大啊。
=========================
2022/03/20 00:01:31 - MainThread - INFO: 已处理：黑白魔女库伊拉 (2021) 源路径: /downloads/电影/好莱坞/Cruella.2021.UHD.Blu-ray.Remux.2160p.HEVC.TrueHD.Atmos.7.1-Hares/Cruella.2021.UHD.Blu-ray.Remux.2160p.HEVC.TrueHD.Atmos.7.1-Hares.mkv
2022/03/20 00:01:32 - MainThread - INFO: 请求https://api.themoviedb.org/3/movie/575322?api_key=7a2491682d2f1ca80b666a88a3c3f5f2&language=zh-CN 失败：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/575322?api_key=xxxxxxxxxxxxxxxx&language=zh-CN (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))
2022/03/20 00:01:32 - MainThread - ERROR: 请求TMDB获取影视详情接口失败
2022/03/20 00:01:32 - MainThread - ERROR: Uncaught exception
Traceback (most recent call last):
  File "commandapp.py", line 68, in <module>
    CommandActions.movies_manager(mconfig['tmdb']['api_key'], args.file_mode, args.use_country_folder,
  File "yee/commandactions.py", line 19, in yee.commandactions.CommandActions.movies_manager
  File "yee/core/moviefilemanager.py", line 92, in yee.core.moviefilemanager.MovieFileManager.walk_link_movies
  File "yee/core/moviefilemanager.py", line 103, in yee.core.moviefilemanager.MovieFileManager.walk_link_movies
  File "yee/core/moviefilemanager.py", line 334, in yee.core.moviefilemanager.MovieFileManager.link_movie
TypeError: list indices must be integers or slices, not str
==========================

**Comment by pofey** [comment]
这其实是个挺没意义的需求，因为存量数据一次性工作，后续任何新增都托管了，没太有使用存量的需求。
