### ISSUE TITLE
[缺陷]: 生成nfo异常

### ISSUE THREAD

**Issue by axunrun** [pofey/movie_robot#542]
### 当前程序版本

0.9.99.0729

### 问题描述

整理采用移动或复制方式，当下载的剧集超过两季，先下载完的一季会在目标位置建立新目录并正常复制，但是后下载完成的剧集季无法复制进去。通过手动操作，在下载记录内点击重新识别，会得到以下日志，并且企业微信会通知下载完成，但文件无实际操作。

### 重现步骤

1、应用设置-设置媒体文件夹-复制到目标路径；2、通过搜索或豆瓣订阅下载大于两季的剧，如“灵能百分百”“西部世界”；3、剧集下载完第一季后会正常识别并建立目录复制到目标位置；4、第二季下载完成后无任何提示；5、在下载记录中通过手动点击第二季重新识别得到以下日志，得到企业微信提醒完成，但文件没有复制。
![image](https://user-images.githubusercontent.com/97007105/181876041-84149b00-19eb-49de-8ecc-938818b2440a.png)
![image](https://user-images.githubusercontent.com/97007105/181876083-62724858-5cce-4ef1-837c-e885a614aa8e.png)

### 发生问题时系统日志

```shell
I/O error : Function not implemented
2022/07/30 12:57:47 - Thread-170 - ERROR: 整理失败：[Errno 38] Function not implemented
Traceback (most recent call last):
  File "yee/media/link/medialink.py", line 185, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 133, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 285, in yee.media.link.tvlink.TvLink.__handle__
  File "yee/media/link/tvlink.py", line 167, in yee.media.link.tvlink.TvLink.__create_tv_nfo__
  File "yee/metadata/nfofile.py", line 788, in yee.metadata.nfofile.NFOFile.save
  File "src/lxml/etree.pyx", line 2074, in lxml.etree._ElementTree.write
  File "src/lxml/serializer.pxi", line 747, in lxml.etree._tofilelike
  File "src/lxml/serializer.pxi", line 815, in lxml.etree._create_output_buffer
  File "src/lxml/serializer.pxi", line 805, in lxml.etree._create_output_buffer
OSError: [Errno 38] Function not implemented
2022/07/30 12:57:47 - Thread-170 - INFO: 通知媒体库刷新完成，tmdb_id: 108303 save_path: /video/disk2/media/115/TV/纪录片剧集 item_id: 5077f5d28f32be04e5846713ff238c80
2022/07/30 12:57:47 - Thread-170 - INFO: Tiny World 2020 S02 1080p WEB-DL H264 AAC-PTerWEB处理完毕。
```

### 健康检查

![image](https://user-images.githubusercontent.com/97007105/181876129-e94cc80f-86c9-494e-86c9-c1f2d4829e8d.png)

**Comment by pofey** [comment]
你这是，什么硬件运行的机器人？？

**Comment by pofey** [comment]
我研究了一下这是一个非常底层的bug，不是应用程序可以简单修复的，而且我没法复现
