### ISSUE TITLE
[提问]: 免费种子获取任务出错, 请问这个我该这么排查比较好

### ISSUE THREAD

**Issue by broven** [pofey/movie_robot#548]
### 当前程序版本

0.9.99.0729

### 问题

开启了主动养站发现没有下种, 查看日志发现了一条报错
已经尝试了排查的手段:
- 更新最新的站点cookie(mteam), 报错依旧存在
- mteam tracker 以及论坛地址加入代理, 无果
想问问这个报错代表什么意思, 以及有没有修复的手段?

### 发生问题时系统日志

```shell
2022/07/31 00:35:47 - ThreadPoolExecutor-4_4 - INFO: 开始同步站点资源信息...
2022/07/31 00:35:58 - ThreadPoolExecutor-4_4 - INFO: 丐帮最新种子同步完成。
2022/07/31 00:36:09 - ThreadPoolExecutor-4_4 - INFO: 馒头最新种子同步完成。
2022/07/31 00:36:09 - ThreadPoolExecutor-4_4 - INFO: 所有站点资源信息已经更新完毕。
2022/07/31 00:36:09 - ThreadPoolExecutor-4_4 - ERROR: 免费种子获取任务出错：{'site_id': 'mteam', 'upload_kpi_mb': 4194304, 'gap': 2347761.66}
Traceback (most recent call last):
  File "yee/task/freedownloadtask.py", line 182, in yee.task.freedownloadtask.FreeDownloadTask.run
  File "yee/task/freedownloadtask.py", line 133, in yee.task.freedownloadtask.FreeDownloadTask.check_up_speed
  File "yee/task/freedownloadtask.py", line 114, in yee.task.freedownloadtask.FreeDownloadTask.full_up_speed
AttributeError: 'NoneType' object has no attribute 'transfer_info'
```

**Comment by pofey** [comment]
按着wiki好好配置 健康检查图呢

**Comment by broven** [comment]
@pofey 
![image](https://user-images.githubusercontent.com/12854613/182024456-df134369-7756-4e6a-b3bd-8f1ac94ffd5d.png)

**Comment by pofey** [comment]
你这个报错地址是因为下载器没配好
