### ISSUE TITLE
[提问]: unraid  PT学校登录失败，求助~~~

### ISSUE THREAD

**Issue by cszs1986** [pofey/movie_robot#558]
### 当前程序版本

0.9.99.0802

### 问题

cookie和user-agent都是填写正常的
但就是报错~

### 发生问题时系统日志

```shell
Traceback (most recent call last):
File "yee/controller/sitecontroller.py", line 33, in yee.controller.sitecontroller.save_site

File "yee/service/siteservice.py", line 397, in yee.service.siteservice.SiteService.set_site
File "yee/site/sitehelper.py", line 180, in yee.site.sitehelper.SiteHelper.get_userinfo
File "yee/site/siteparser.py", line 29, in yee.site.siteparser.SiteParser.parse_userinfo
yee.site.siteexceptions.LoginRequired: 学校登陆失败！
2022/08/03 22:22:46 - Thread-109 - ERROR: 错误码：400001 错误消息：登录错误，请检查登录状态是否已经过期，尝试重新登录

2022/08/03 22:23:46 - Thread-120 - ERROR: 错误码：400001 错误消息：登录错误，请检查登录状态是否已经过期，尝试重新登录

2022/08/03 22:24:29 - Thread-126 - ERROR: 站点设置失败：学校登陆失败！
```

**Comment by pofey** [comment]
删了

**Comment by 1455757504** [comment]
确保和主机在同一局域网然后重新获取cookie和agent就好了
