### ISSUE TITLE
[缺陷]: pt站点学校登陆失败

### ISSUE THREAD

**Issue by 1455757504** [pofey/movie_robot#562]
### 当前程序版本

1.0.0

### 问题描述

添加学校pt站点时,提示学校登陆失败。之前以为是开注➕站免导致的。现在站免快结束了依旧添加不上。

### 重现步骤

按照正常步骤添加pt站，cookie是通过kiwi浏览器获取的，useragent也按要求填了。别的pt站都可以正常添加

### 发生问题时系统日志

```shell
09:05:39
Traceback (most recent call last):
stdout
09:05:39
  File "yee/controller/sitecontroller.py", line 33, in yee.controller.sitecontroller.save_site
stdout
09:05:41
  File "yee/service/siteservice.py", line 397, in yee.service.siteservice.SiteService.set_site
stdout
09:05:41
  File "yee/site/sitehelper.py", line 180, in yee.site.sitehelper.SiteHelper.get_userinfo
stdout
09:05:41
  File "yee/site/siteparser.py", line 29, in yee.site.siteparser.SiteParser.parse_userinfo
stdout
09:05:41
yee.site.siteexceptions.LoginRequired: 学校登陆失败！
```

### 健康检查

系统运行状态良好

**Comment by pofey** [comment]
删了

**Comment by cszs1986** [comment]
这个根据日志排查，好像是5秒盾的问题，在同一网内，根据日志错误，刷新学校后获取cookie就行

**Comment by 1455757504** [comment]
应该就是这个问题，重新获取cookie并不管用。我甚至连useagent都填进去了

**Comment by cszs1986** [comment]
确保和机器同一局域网内，日志报错后，去学校刷新一下，然后再填cookie和useagent，我就是这样成功的

**Comment by 1455757504** [comment]
多谢了，怪不得我这不行。我是在外网获取的
