### ISSUE TITLE
[缺陷]: 搜索模版名称为空时导致搜索页不能用

### ISSUE THREAD

**Issue by sinosofti** [pofey/movie_robot#568]
### 当前程序版本

v1.0

### 问题描述

点击搜索搜索不了电影

### 重现步骤

点击搜索按钮时候
![image](https://user-images.githubusercontent.com/38282416/183297716-73edbc01-c4c2-4e1e-864b-ad12e1e32f6b.png)
****
点击修改保存的时候一片空白
![image](https://user-images.githubusercontent.com/38282416/183297741-9a9382ab-5440-4864-8a46-85f59f7ad165.png)
点击删除模板的时候
![image](https://user-images.githubusercontent.com/38282416/183297759-8d0b9364-4181-42d4-ac97-5e3bf7e7b896.png)

![image](https://user-images.githubusercontent.com/38282416/183297706-dce5c311-28b8-4515-aea3-e2d287bb0452.png)

### 发生问题时系统日志

```shell
2022/08/07 23:09:14 - MainThread - INFO: 新增任务：健康检查任务
2022/08/07 23:09:14 - MainThread - INFO: Emby连接正常，Tower版本为4.7.6.0
2022/08/07 23:09:14 - MainThread - INFO: 已经启动字幕下载处理任务。
2022/08/07 23:09:14 - MainThread - INFO: 当前版本: 1.0.0
2022/08/07 23:09:23 - Thread-44 - ERROR: 请求出错：'name'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 34, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/settingcontroller.py", line 591, in yee.controller.settingcontroller.get_search_template
KeyError: 'name'
2022/08/07 23:09:24 - Thread-46 - ERROR: 请求出错：'name'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 34, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/settingcontroller.py", line 591, in yee.controller.settingcontroller.get_search_template
KeyError: 'name'
2022/08/07 23:09:26 - Thread-47 - ERROR: 请求出错：'name'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 34, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/settingcontroller.py", line 591, in yee.controller.settingcontroller.get_search_template
KeyError: 'name'
2022/08/07 23:09:30 - Thread-48 - ERROR: 请求出错：'name'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 34, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/settingcontroller.py", line 591, in yee.controller.settingcontroller.get_search_template
KeyError: 'name'
2022/08/07 23:09:48 - Thread-52 - ERROR: 请求出错：'name'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 34, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/settingcontroller.py", line 591, in yee.controller.settingcontroller.get_search_template
KeyError: 'name'
2022/08/07 23:09:49 - Thread-54 - ERROR: 请求出错：'name'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 34, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/settingcontroller.py", line 591, in yee.controller.settingcontroller.get_search_template
KeyError: 'name'
2022/08/07 23:09:51 - Thread-55 - ERROR: 请求出错：'name'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 34, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/settingcontroller.py", line 591, in yee.controller.settingcontroller.get_search_template
KeyError: 'name'
2022/08/07 23:10:00 - ThreadPoolExecutor-0_1 - INFO: Emby连接正常，Tower版本为4.7.6.0
2022/08/07 23:10:08 - Thread-58 - ERROR: 请求出错：'name'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 34, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/settingcontroller.py", line 591, in yee.controller.settingcontroller.get_search_template
KeyError: 'name'
2022/08/07 23:10:12 - Thread-60 - ERROR: 请求出错：'name'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 34, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/settingcontroller.py", line 620, in yee.controller.settingcontroller.update_search_template.lambda2
  File "yee/controller/settingcontroller.py", line 620, in yee.controller.settingcontroller.update_search_template.lambda2
KeyError: 'name'
2022/08/07 23:10:45 - Thread-80 - ERROR: 请求出错：'name'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 34, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/settingcontroller.py", line 591, in yee.controller.settingcontroller.get_search_template
KeyError: 'name'
2022/08/07 23:10:46 - Thread-82 - ERROR: 请求出错：'name'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 34, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/settingcontroller.py", line 591, in yee.controller.settingcontroller.get_search_template
KeyError: 'name'
2022/08/07 23:10:48 - Thread-83 - ERROR: 请求出错：'name'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 34, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/settingcontroller.py", line 591, in yee.controller.settingcontroller.get_search_template
KeyError: 'name'
2022/08/07 23:10:52 - Thread-84 - ERROR: 请求出错：'name'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 34, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/settingcontroller.py", line 591, in yee.controller.settingcontroller.get_search_template
KeyError: 'name'
```

### 健康检查

![Uploading image.png…]()

**Comment by pofey** [comment]
baseconfig能否脱敏后发一个

**Comment by sinosofti** [comment]
download_client:
- is_default: true
  monitor_all_torrents: false
  name: qBittorrent
  need_login: true
  password: 1
  site_id: []
  status: 1
  type: qbittorrent
  url: http://192.168.68.119:8082/
  username: admin
free_download:
  available_space: 1024
  avg_statistics_period: 5
  enable: true
  save_path: /downloads/其他/
  upload_mbps_maximum: 30
frontend:
  search_template:
  - name: 默认
    option:
      category:
      - Movie
      - TV
      - Anime
      - Documentary
      searchContent:
      - searchDouban
      - searchMediaServer
      - searchSite
      site: null
  - option:
      category:
      - Movie
      - TV
      - Documentary
      - Anime
      - AV
      searchContent:
      - searchDouban
      - searchMediaServer
      - searchSite
      site:
      - mteam
      - pttime
      - pterclub
      - hdatmos
      - nicept
      - HDTime
      - joyhd
      - PTMSG
      - rarbg
media_path:
- download_path: /downloads/mv
  file_process_mode: link
  qbit_cate: mv
  source_dir: /downloads/mv
  target_dir: /downloads/emby_mv
  type: movie
  use_area_folder: false
- download_path: /downloads/公共综艺
  file_process_mode: move
  qbit_cate: 公共综艺
  source_dir: /downloads/公共综艺
  target_dir: /downloads/综艺
  type: tv
- download_path: /downloads/公共动漫
  file_process_mode: move
  qbit_cate: 公共动漫
  source_dir: /downloads/公共动漫
  target_dir: /downloads/动漫
  type: tv
- download_path: /downloads/tv
  file_process_mode: move
  qbit_cate: tv
  source_dir: /downloads/tv
  target_dir: /downloads/emby_tv
  type: tv
  use_area_folder: true
media_server:
  default: emby
  emby:
    api_key: 234
    host: 192.168.68.119
    https: false
    port: 8096
movie_metadata:
  douban:
    cookie: ' t.1659503917.1659600621.2;  __utmb=30149280.2.10.1659600621;  __utmc=30149280;  __utmt=1;  __utmv=30149280.17959;  __utmz=30149280.1659600621.2.2.utmcsr=m.baidu.com|utmccn=(referral)|utmcmd=referral|utmcct=/;  ap_v=0,6.0;  push_doumail_num=0;  push_noty_num=0;  ck=r8Ra;  frodotk="25b13c93011f227b7113b5b9035d6771";  talionusr="eyJpZCI6ICIxNzk1OTAzMDAiLCAibmFtZSI6ICJBbWVpZ2luZyJ9";  talionnav_show_app="0";  dbcl2="179590300:Hw4matJcfC0";  bid=BP34Jf3VhEU;  ll="108290";'
  link_template:
    disc_single_folder: false
    exact_year: true
    file_process_mode: link
    fix_emby_bdmv_bug: false
    movie:
      filename: '{{name}} ({{year}}) {%if version %} - {{version}}{% endif %}'
      folder: '{{name}} ({{year}}) [tmdbid={{tmdbid}}]'
    recognize: true
    tv:
      filename: '{{name}} S{{season}}E{{ep_start}}{%if ep_end %}-E{{ep_end}}{% endif
        %}{%if version %} - {{version}}{% endif %}'
      folder: '{{name}} ({{year}}) [tmdbid={{tmdbid}}]'
    use_unknown_dir: true
  tmdb:
    api_key: 79984e892e2b454f5d7bfa2d2b628e24
    proxies: http://127.0.0.1:20171/
notify_channel:
  qywx:
    aes_key: beQzGANzIVLoxscPpOAKDlFaL2odrzM6Jt6kHhYDNjp
    agentid: '1000003'
    corpid: wwc81d0bfa9ad355f5
    corpsecret: Wpmob0FB5WGlDA-SGr8QQ9wDonjwl4dSA44G5ctoSrY
    enable: true
    message_template:
      movie_completed:
        message: ${nickname}添加的电影 ${name}(${year})下载完毕
        title: ${name} (${year}) 评分:${rating}
      tv_completed:
        message: ${nickname}添加的剧集 ${name}(${year})第${episodes}集下载完毕
        title: ${name} (${year}) 评分:${rating}
    server_url: ''
    token: qk621
    touser: '@all'
    use_server_proxy: true
scraper:
  generate_nfo: true
  person_nfo_path: null
  use_cn_person_name: false
server:
  auth_search_result: true
  site_max_workers: 12
  web_search_default_cates:
  - Movie
  - TV
  - Anime
  - Documentary
  web_search_result_limit: 0
  web_search_timeout: 10
smart_download:
  douban:
    default_score_rule: compress
    download_paths:
    - area: []
      cate: []
      download_path: /downloads/mv
      score_rule: compress
      type: movie
    - area: []
      cate:
      - 真人秀
      download_path: /downloads/公共综艺
      score_rule: compress
      type: tv
    - area:
      - 日本
      - 中国大陆
      cate:
      - 动画
      download_path: /downloads/公共动漫
      score_rule: compress
      type: tv
    - area: []
      cate: []
      download_path: /downloads/tv
      score_rule: compress
      type: tv
    tags: []
    users:
    - id: '179590300'
      pull_time_range: '7'
subtitle:
  enable: true
  exclude_area:
  - 中国大陆
  - 中国台湾
  file_name_template: '{{ name }}.{{ language[0] }}{% if language[0] == "zh-cn" and
    language | length == 2 %}.default{% endif%}{{ subtitle_ext }}'
  filter_type:
  - srt
  - ass
  finder_type:
  - zimuku
  - subhd
  not_found_stop_minutes: 4320
  sync_language:
  - zh-cn
  - zh-tw
web:
  host: '::'
  port: 1329
  server_url: http://

**Comment by pofey** [comment]
注意看你的search_template 第二个配置，非默认那个，少了个name 名称的配置项，触发了bug，你先改配置文件，模仿默认，给加个name临时解决，下一个版本我搞上去

**Comment by sinosofti** [comment]
hao d

**Comment by pofey** [comment]
beta已经上线了
