### ISSUE TITLE
[缺陷]: 同步豆瓣想看列表失败

### ISSUE THREAD

**Issue by zxb7500644** [pofey/movie_robot#572]
### 当前程序版本

1.0.7

### 问题描述

更新后同步豆瓣想看列表失败

### 重现步骤

升级没动之前的配置

### 发生问题时系统日志

```shell
2022/08/10 20:18:40 - Thread-11 - ERROR: 同步豆瓣想看列表失败：RetryError[<Future at 0x7ffb2c228ac0 state=finished raised TypeError>]
Traceback (most recent call last):
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
TypeError: 'staticmethod' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yee/task/syncdoubanwishtask.py", line 42, in yee.task.syncdoubanwishtask.SyncDoubanWishTask.run
  File "yee/task/syncdoubanwishtask.py", line 25, in yee.task.syncdoubanwishtask.SyncDoubanWishTask.get_user_interests
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7ffb2c228ac0 state=finished raised TypeError>]
```

### 健康检查

![image](https://user-images.githubusercontent.com/75072634/183900660-e03648e3-2c23-4efa-ab3d-1b574bcf8456.png)

**Comment by zzj6666** [comment]
![image](https://user-images.githubusercontent.com/101039599/183904355-9fc78081-242f-438c-b004-d9e5a979744f.png)
同样问题

**Comment by pofey** [comment]
试一下最新版是不是好了
