### ISSUE TITLE
[缺陷]: 资源没有图片导致处理下载任务失败

### ISSUE THREAD

**Issue by Decade1993** [pofey/movie_robot#575]
### 当前程序版本

1.0.0

### 问题描述

自定义订阅了一部剧，qb下载器里有完成下载，但mr的下载记录里没有信息，后续qb下载完了也没有进行硬链接整理
download_record.thumb_image_url 看日志是这个属性没有值导致处理下载任务失败

### 重现步骤

不太好重现，但遇到过几次了，download_record.thumb_image_url是null的问题

### 发生问题时系统日志

```shell
2022/08/11 14:07:09 - ThreadPoolExecutor-4_5 - INFO: 馒头拉取种子超时，请耐心等待...
 2022/08/11 14:08:09 - ThreadPoolExecutor-4_5 - INFO: 馒头拉取种子超时，请耐心等待...
 2022/08/11 14:09:06 - ThreadPoolExecutor-5_7 - ERROR: 馒头检测到CloudFlare 5秒盾，请浏览器访问跳过拿到新Cookie重新配置。
 2022/08/11 14:09:06 - ThreadPoolExecutor-5_7 - ERROR: 访问馒头失败: RetryError[<Future at 0x7f91692965e0 state=finished raised LoginRequired>]
 2022/08/11 14:09:06 - ThreadPoolExecutor-4_5 - INFO: 所有站点资源信息已经更新完毕。
 2022/08/11 14:09:06 - ThreadPoolExecutor-4_5 - INFO: 有2个启用的自定义订阅规则，开始处理。
 2022/08/11 14:09:07 - ThreadPoolExecutor-4_5 - INFO: 来自自定义订阅密室大逃脱的资源已经提交下载，种子标题：密室大逃脱 第四季 | 第5期：天使学园（上）| TJUPT小组作品 转载请注明北洋园PT [每周三四五更新] 链接：https://tjupt.org/details.php?id=309717&hit=1 站点：tjupt 种子编号：309717 record: 0
 2022/08/11 14:09:07 - tjupt-downloader - INFO: 开始处理来自Web的下载: [tjupt][大陆][20220811][密室大逃脱 第四季][Room.Escape.S04E05.2022.1080p.WEB-DL.H264.AAC-TJUPT][MP4]
 2022/08/11 14:09:07 - ThreadPoolExecutor-4_5 - INFO: 没有配置或开启流量管理设置，不会开始运行：{'available_space': 300, 'avg_statistics_period': 10, 'enable': False, 'save_path': '/share/CACHEDEV3_DATA/Download2/', 'upload_mbps_maximum': 40}
 2022/08/11 14:09:11 - tjupt-downloader - ERROR: 处理下载任务失败：(sqlite3.IntegrityError) NOT NULL constraint failed: download_record.thumb_image_url
[SQL: INSERT INTO download_record (gmt_create, source_id, source_type, movie_name, movie_year, movie_type, site_name, torrent_id, torrent_name, torrent_subject, torrent_hash, download_status, season_index, season_year, episodes, link_path, user_id, thumb_image_url, "desc", sub_id, torrent_url, better_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('2022-08-11 14:09:11', '', 'download_client', '[大陆][20220811][密室大逃脱 第四季][Room.Escape.S04E05.2022.1080p.WEB-DL.H264.AAC-TJUPT][MP4]', 0, 'Series', 'tjupt', 309717, 'Room.Escape.S04.2022.1080p.WEB-DL.H264.AAC-TJUPT', '密室大逃脱 第四季 | 第5期：天使学园（上）| TJUPT小组作品 转载请注明北洋园PT [每周三四五更新]', '0c3405016d90151a7704b47470889b8e45640615', 0, None, None, '5', '/res/link/TV', '1', None, '密室大逃脱 第四季 | 第5期：天使学园（上）| TJUPT小组作品 转载请注明北洋园PT [每周三四五更新]', '', 'https://tjupt.org/details.php?id=309717&hit=1', 1)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
Traceback (most recent call last):
  File "/dependencies/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: download_record.thumb_image_url

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yee/task/consumer/downloadconsumer.py", line 29, in yee.task.consumer.downloadconsumer.DownloadConsumer.run
  File "yee/service/downloadservice.py", line 548, in yee.service.downloadservice.DownloadService.download_from_web
  File "yee/common/basemodel.py", line 88, in yee.common.basemodel.BaseModel.save
  File "yee/common/basemodel.py", line 85, in yee.common.basemodel.BaseModel.save
  File "<string>", line 2, in commit
  File "/dependencies/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/dependencies/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/dependencies/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/dependencies/sqlalchemy/orm/session.py", line 3383, in flush
    self._flush(objects)
  File "/dependencies/sqlalchemy/orm/session.py", line 3523, in _flush
    transaction.rollback(_capture_exception=True)
  File "/dependencies/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/orm/session.py", line 3483, in _flush
    flush_context.execute()
  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/dependencies/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/dependencies/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/dependencies/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/dependencies/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/dependencies/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/dependencies/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/dependencies/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: download_record.thumb_image_url
[SQL: INSERT INTO download_record (gmt_create, source_id, source_type, movie_name, movie_year, movie_type, site_name, torrent_id, torrent_name, torrent_subject, torrent_hash, download_status, season_index, season_year, episodes, link_path, user_id, thumb_image_url, "desc", sub_id, torrent_url, better_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('2022-08-11 14:09:11', '', 'download_client', '[大陆][20220811][密室大逃脱 第四季][Room.Escape.S04E05.2022.1080p.WEB-DL.H264.AAC-TJUPT][MP4]', 0, 'Series', 'tjupt', 309717, 'Room.Escape.S04.2022.1080p.WEB-DL.H264.AAC-TJUPT', '密室大逃脱 第四季 | 第5期：天使学园（上）| TJUPT小组作品 转载请注明北洋园PT [每周三四五更新]', '0c3405016d90151a7704b47470889b8e45640615', 0, None, None, '5', '/res/link/TV', '1', None, '密室大逃脱 第四季 | 第5期：天使学园（上）| TJUPT小组作品 转载请注明北洋园PT [每周三四五更新]', '', 'https://tjupt.org/details.php?id=309717&hit=1', 1)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
 2022/08/11 14:27:44 - ThreadPoolExecutor-4_1 - INFO: 开始同步站点资源信息...
```

### 健康检查

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/5979343/184093986-0f302d30-7724-459c-af19-8beffa661e0e.png">

**Comment by pofey** [comment]
这东西为啥没图 看过tmdb的数据不

**Comment by Decade1993** [comment]
tmdb有图的，而且现在mr默认代理了tmdb的数据，我以前出现这个问题想着可能我网络问题，现在我连mbot.vip很稳定应该也不是网络问题吧

**Comment by pofey** [comment]
做了一下容错处理，但是我没法复线

**Comment by Decade1993** [comment]
请问容错处理是不是还没上线？
我现在更新到1.1.1还是有这个问题：
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/5979343/185025377-61a3b289-250d-4b0f-b3c9-cfb48f12ebac.png">
09:59:44 - Thread-361的那个访问图片失败是另一部剧的

**Comment by pofey** [comment]
latest就还没发布过呢

**Comment by Decade1993** [comment]
```
2022/08/25 11:21:42 - Thread-79 - INFO: 已经开始在站点: 观众,彩虹岛,天空,瓷器,北洋园,家园,不可说,猫站,朋友,柠檬,我堡,听听歌,备胎,馒头 搜索: 壮志凌云2
2022/08/25 11:22:01 - Thread-79 - INFO: 共在14个站点搜索到89条结果，其中猫站最慢，耗费18.5秒
2022/08/25 11:23:19 - chdbits-downloader - INFO: 开始处理来自Web的下载: [chdbits]Top Gun Maverick 2022.1080p WEB-DL DDP5.1 Atmos H.264-KKYY@CHDBits
2022/08/25 11:23:22 - chdbits-downloader - ERROR: 处理下载任务失败：(sqlite3.IntegrityError) NOT NULL constraint failed: download_record.thumb_image_url
[SQL: INSERT INTO download_record (gmt_create, source_id, douban_id, source_type, movie_name, movie_year, movie_type, site_name, torrent_id, torrent_name, torrent_subject, torrent_hash, download_status, season_index, season_year, episodes, link_path, user_id, thumb_image_url, "desc", sub_id, torrent_url, better_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('2022-08-25 11:23:22', '', None, 'download_client', 'Top Gun Maverick 2022.1080p WEB-DL DDP5.1 Atmos H.264-KKYY@CHDBits', 0, 'Movie', 'chdbits', 201748, 'Top.Gun.Maverick.2022.1080p.WEB-DL.DDP5.1.Atmos.H.264-KKYY@CHDBits', '壮志凌云2：独行侠 [内封SDR简英特效字幕+SDR繁英特效字幕] 官方独占中字特效', '0483af75a904c52c8b00fcb3a026b5c2733a164e', 0, None, None, '', '/res/link/Movie', '1', None, '壮志凌云2：独行侠 [内封SDR简英特效字幕+SDR繁英特效字幕] 官方独占中字特效', '', 'https://chdbits.co/details.php?id=201748&hit=1', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
Traceback (most recent call last):
  File "/dependencies/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: download_record.thumb_image_url

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mbot/task/consumer/downloadconsumer.py", line 29, in mbot.task.consumer.downloadconsumer.DownloadConsumer.run
  File "mbot/service/downloadservice.py", line 576, in mbot.service.downloadservice.DownloadService.download_from_web
  File "mbot/common/basemodel.py", line 88, in mbot.common.basemodel.BaseModel.save
  File "mbot/common/basemodel.py", line 85, in mbot.common.basemodel.BaseModel.save
  File "<string>", line 2, in commit
  File "/dependencies/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/dependencies/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/dependencies/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/dependencies/sqlalchemy/orm/session.py", line 3383, in flush
    self._flush(objects)
  File "/dependencies/sqlalchemy/orm/session.py", line 3523, in _flush
    transaction.rollback(_capture_exception=True)
  File "/dependencies/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/orm/session.py", line 3483, in _flush
    flush_context.execute()
  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/dependencies/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/dependencies/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/dependencies/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/dependencies/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/dependencies/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/dependencies/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/dependencies/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: download_record.thumb_image_url
[SQL: INSERT INTO download_record (gmt_create, source_id, douban_id, source_type, movie_name, movie_year, movie_type, site_name, torrent_id, torrent_name, torrent_subject, torrent_hash, download_status, season_index, season_year, episodes, link_path, user_id, thumb_image_url, "desc", sub_id, torrent_url, better_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('2022-08-25 11:23:22', '', None, 'download_client', 'Top Gun Maverick 2022.1080p WEB-DL DDP5.1 Atmos H.264-KKYY@CHDBits', 0, 'Movie', 'chdbits', 201748, 'Top.Gun.Maverick.2022.1080p.WEB-DL.DDP5.1.Atmos.H.264-KKYY@CHDBits', '壮志凌云2：独行侠 [内封SDR简英特效字幕+SDR繁英特效字幕] 官方独占中字特效', '0483af75a904c52c8b00fcb3a026b5c2733a164e', 0, None, None, '', '/res/link/Movie', '1', None, '壮志凌云2：独行侠 [内封SDR简英特效字幕+SDR繁英特效字幕] 官方独占中字特效', '', 'https://chdbits.co/details.php?id=201748&hit=1', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022/08/25 11:30:00 - ThreadPoolExecutor-4_3 - INFO: 开始获取18****049(do) 1天内的电影
2022/08/25 11:30:00 - ThreadPoolExecutor-4_3 - INFO: 开始获取18****049(wish) 1天内的电影
2022/08/25 11:30:01 - ThreadPoolExecutor-4_3 - INFO: 豆瓣用户189559049的想看列表开始同步到订阅记录。 
2022/08/25 11:30:01 - ThreadPoolExecutor-4_3 - INFO: 开始获取19****768(do) 1天内的电影
2022/08/25 11:30:02 - ThreadPoolExecutor-4_3 - INFO: 开始获取19****768(wish) 1天内的电影
2022/08/25 11:30:02 - ThreadPoolExecutor-4_3 - INFO: 豆瓣用户194610768的想看列表开始同步到订阅记录。 
2022/08/25 11:30:03 - ThreadPoolExecutor-4_3 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
```

我拉了beta分支，版本1.1.11，多了 https://sqlalche.me/e/14/gkpj  这条日志，不知有没有帮助。
感觉可能是访问图片不太稳定，我发现我订阅的项目可能也不是立即就有图片显示，过了好一会才有图片显示

**Comment by Decade1993** [comment]
我把内置识别分析开启之后，就不会报这个错了，虽然下载记录里那个图片还是没有，但能有下载记录了。
