### ISSUE TITLE
[缺陷]: MR通过web搜索下载添加失败

### ISSUE THREAD

**Issue by w905581962** [pofey/movie_robot#580]
### 当前程序版本

1.1.1

### 问题描述

MR搜索下载失败，但qb上已添加种子并下载
但后续不会识别并硬链接

### 重现步骤

在web页面搜索种子，添加下载，MR报添加失败，qb已在下载

### 发生问题时系统日志

```shell
2022-08-14 05:43:58	stdout	[parameters: ('2022-08-14 13:43:55', '', 'download_client', 'TVB Xing He Justice Bao The First Year 2019 COMPLETE 1080i HDTV H264-NGB  粤语 | 简体硬字幕', 0, 'Series', 'ttg', 577924, 'TVB.Xing.He.Justice.Bao.The.First.Year.2019.COMPLETE.1080i.HDTV.H264-NGB', 'TVB星河频道 包青天再起风云 全30集', '71f6aa69107b09408832aa87e4cf4db62c2d0612', 0, None, None, '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30', '/video/电视剧', '1', None, 'TVB星河频道 包青天再起风云 全30集', '', 'https://totheglory.im//t/577924/', 0)]
2022-08-14 05:43:58	stdout	[SQL: INSERT INTO download_record (gmt_create, source_id, source_type, movie_name, movie_year, movie_type, site_name, torrent_id, torrent_name, torrent_subject, torrent_hash, download_status, season_index, season_year, episodes, link_path, user_id, thumb_image_url, "desc", sub_id, torrent_url, better_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
2022-08-14 05:43:58	stdout	sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: download_record.thumb_image_url
2022-08-14 05:43:58	stdout	    cursor.execute(statement, parameters)
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
2022-08-14 05:43:58	stdout	    self.dialect.do_execute(
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/engine/base.py", line 1819, in _execute_context
2022-08-14 05:43:58	stdout	    raise exception
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
2022-08-14 05:43:58	stdout	    util.raise_(
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
2022-08-14 05:43:58	stdout	    self._handle_dbapi_exception(
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/engine/base.py", line 1862, in _execute_context
2022-08-14 05:43:58	stdout	    ret = self._execute_context(
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
2022-08-14 05:43:58	stdout	    return connection._execute_clauseelement(
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
2022-08-14 05:43:58	stdout	    return meth(self, args_10style, kwargs_10style, execution_options)
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/engine/base.py", line 1631, in _execute_20
2022-08-14 05:43:58	stdout	    result = connection._execute_20(
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
2022-08-14 05:43:58	stdout	    _emit_insert_statements(
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/orm/persistence.py", line 245, in save_obj
2022-08-14 05:43:58	stdout	    util.preloaded.orm_persistence.save_obj(
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 630, in execute
2022-08-14 05:43:58	stdout	    rec.execute(self)
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 456, in execute
2022-08-14 05:43:58	stdout	    flush_context.execute()
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/orm/session.py", line 3483, in _flush
2022-08-14 05:43:58	stdout	    raise exception
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
2022-08-14 05:43:58	stdout	    compat.raise_(
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/util/langhelpers.py", line 70, in __exit__
2022-08-14 05:43:58	stdout	    transaction.rollback(_capture_exception=True)
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/orm/session.py", line 3523, in _flush
2022-08-14 05:43:58	stdout	    self._flush(objects)
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/orm/session.py", line 3383, in flush
2022-08-14 05:43:58	stdout	    self.session.flush()
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/orm/session.py", line 808, in _prepare_impl
2022-08-14 05:43:58	stdout	    self._prepare_impl()
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/orm/session.py", line 829, in commit
2022-08-14 05:43:58	stdout	    self._transaction.commit(_to_root=self.future)
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/orm/session.py", line 1451, in commit
2022-08-14 05:43:58	stdout	  File "<string>", line 2, in commit
2022-08-14 05:43:58	stdout	  File "yee/common/basemodel.py", line 85, in yee.common.basemodel.BaseModel.save
2022-08-14 05:43:58	stdout	  File "yee/common/basemodel.py", line 88, in yee.common.basemodel.BaseModel.save
2022-08-14 05:43:58	stdout	  File "yee/service/downloadservice.py", line 548, in yee.service.downloadservice.DownloadService.download_from_web
2022-08-14 05:43:58	stdout	  File "yee/task/consumer/downloadconsumer.py", line 29, in yee.task.consumer.downloadconsumer.DownloadConsumer.run
2022-08-14 05:43:58	stdout	Traceback (most recent call last):
2022-08-14 05:43:58	stdout	
2022-08-14 05:43:58	stdout	The above exception was the direct cause of the following exception:
2022-08-14 05:43:58	stdout	
2022-08-14 05:43:58	stdout	sqlite3.IntegrityError: NOT NULL constraint failed: download_record.thumb_image_url
2022-08-14 05:43:58	stdout	    cursor.execute(statement, parameters)
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
2022-08-14 05:43:58	stdout	    self.dialect.do_execute(
2022-08-14 05:43:58	stdout	  File "/dependencies/sqlalchemy/engine/base.py", line 1819, in _execute_context
2022-08-14 05:43:58	stdout	Traceback (most recent call last):
2022-08-14 05:43:58	stdout	(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-08-14 05:43:58	stdout	[parameters: ('2022-08-14 13:43:55', '', 'download_client', 'TVB Xing He Justice Bao The First Year 2019 COMPLETE 1080i HDTV H264-NGB  粤语 | 简体硬字幕', 0, 'Series', 'ttg', 577924, 'TVB.Xing.He.Justice.Bao.The.First.Year.2019.COMPLETE.1080i.HDTV.H264-NGB', 'TVB星河频道 包青天再起风云 全30集', '71f6aa69107b09408832aa87e4cf4db62c2d0612', 0, None, None, '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30', '/video/电视剧', '1', None, 'TVB星河频道 包青天再起风云 全30集', '', 'https://totheglory.im//t/577924/', 0)]
2022-08-14 05:43:58	stdout	[SQL: INSERT INTO download_record (gmt_create, source_id, source_type, movie_name, movie_year, movie_type, site_name, torrent_id, torrent_name, torrent_subject, torrent_hash, download_status, season_index, season_year, episodes, link_path, user_id, thumb_image_url, "desc", sub_id, torrent_url, better_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
2022-08-14 05:43:58	stdout	2022/08/14 13:43:57 - ttg-downloader - ERROR: 处理下载任务失败：(sqlite3.IntegrityError) NOT NULL constraint failed: download_record.thumb_image_url
2022-08-14 05:43:54	stdout	2022/08/14 13:43:54 - ttg-downloader - INFO: 开始处理来自Web的下载: [ttg]TVB Xing He Justice Bao The First Year 2019 COMPLETE 1080i HDTV H264-NGB  粤语 | 简体硬字幕
2022-08-14 05:43:47	stdout	2022/08/14 13:43:47 - Thread-51 - INFO: 共在4个站点搜索到1条结果，其中听听歌最慢，耗费3.54秒
2022-08-14 05:43:44	stdout	2022/08/14 13:43:44 - Thread-48 - ERROR: 没有检索到结果元素: https://m.douban.com/search/?query=TVB+Xing+He+Justice+Bao+The+First+Year+2019+COMPLETE+1080i+HDTV+H264-NGB&type=1002
2022-08-14 05:43:43	stdout	2022/08/14 13:43:43 - Thread-51 - INFO: 已经开始在站点: 我堡,阿童木,馒头,听听歌 搜索: TVB Xing He Justice Bao The First Year 2019 COMPLETE 1080i HDTV H264-NGB
```

### 健康检查

![image](https://user-images.githubusercontent.com/40052692/184524396-d65116f9-6983-4632-8e6c-3a21c8006356.png)

**Comment by xmumeyu** [comment]
我这里也出现相同的故障，有故障的种子在 多台服务器、多网络、多用户 上测试，识别上会出问题，最终插入数据库的时候报错
NOT NULL constraint failed: download_record.thumb_image_url

比如这个种子  Battle.Bots.S01.2015.Complete.1080p.Netflix.Webdl.AVC.DDP2.0-DBTV （ https://www.hddolby.com/details.php?id=39861&hit=1）

**Comment by pofey** [comment]
根据你的重现步骤无法重现，描述详细一点重现过程吧。我从web搜索，下载，正常得很。

**Comment by pofey** [comment]
但是 thumb_image_url null的问题，兼容修复了

**Comment by xmumeyu** [comment]
老大要是有hddolby这个站点， 搜索  机器人大战 ， 手动下载
这个种子 Battle.Bots.S01.2015.Complete.1080p.Netflix.Webdl.AVC.DDP2.0-DBTV （ [https://www.hddolby.com/details.php?id=39861&hit=1）](https://www.hddolby.com/details.php?id=39861&hit=1%EF%BC%89)
