### ISSUE TITLE
[提问]: 查看日志持续报错，一天10W多个项目，具体如下

### ISSUE THREAD

**Issue by 30507103** [pofey/movie_robot#582]
### 当前程序版本

1.1.1

### 问题

刚买了永久激活，去日志查看信息，发现今天一天刷了很多错误提示，一直提示解析错误，节选部分如下，22:33分停止容器更换永久激活码。

### 发生问题时系统日志

```shell
2022-08-14 14:35:32	stdout	UnboundLocalError: local variable 'result' referenced before assignment
2022-08-14 14:35:32	stdout	  File "yee/media/douban.py", line 529, in yee.media.douban.DoubanMovie.ranking_list
2022-08-14 14:35:32	stdout	  File "yee/service/mediametadataservice.py", line 209, in yee.service.mediametadataservice.MovieMetadataService.get_trending_list
2022-08-14 14:35:32	stdout	  File "yee/task/mediatrendingtask.py", line 71, in yee.task.mediatrendingtask.MediaTrendingTask.run
2022-08-14 14:35:32	stdout	    self._target(*self._args, **self._kwargs)
2022-08-14 14:35:32	stdout	  File "/usr/local/lib/python3.8/threading.py", line 870, in run
2022-08-14 14:35:32	stdout	    self.run()
2022-08-14 14:35:32	stdout	  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2022-08-14 14:35:32	stdout	Traceback (most recent call last):
2022-08-14 14:35:32	stdout	
2022-08-14 14:35:32	stdout	During handling of the above exception, another exception occurred:
2022-08-14 14:35:32	stdout	
2022-08-14 14:35:32	stdout	httpx.ConnectError: [Errno -3] Temporary failure in name resolution
2022-08-14 14:35:32	stdout	    raise mapped_exc(message) from exc
2022-08-14 14:35:32	stdout	  File "/dependencies/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
2022-08-14 14:35:32	stdout	    self.gen.throw(type, value, traceback)
2022-08-14 14:35:32	stdout	  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
2022-08-14 14:35:32	stdout	    resp = self._pool.handle_request(req)
2022-08-14 14:35:32	stdout	  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
2022-08-14 14:35:32	stdout	    response = transport.handle_request(request)
2022-08-14 14:35:32	stdout	  File "/dependencies/httpx/_client.py", line 990, in _send_single_request
2022-08-14 14:35:32	stdout	    response = self._send_single_request(request)
2022-08-14 14:35:32	stdout	  File "/dependencies/httpx/_client.py", line 954, in _send_handling_redirects
2022-08-14 14:35:32	stdout	    response = self._send_handling_redirects(
2022-08-14 14:35:32	stdout	  File "/dependencies/httpx/_client.py", line 917, in _send_handling_auth
2022-08-14 14:35:32	stdout	    response = self._send_handling_auth(
2022-08-14 14:35:32	stdout	  File "/dependencies/httpx/_client.py", line 889, in send
2022-08-14 14:35:32	stdout	    return self.send(request, auth=auth, follow_redirects=follow_redirects)
2022-08-14 14:35:32	stdout	  File "/dependencies/httpx/_client.py", line 802, in request
2022-08-14 14:35:32	stdout	    return self.request(
2022-08-14 14:35:32	stdout	  File "/dependencies/httpx/_client.py", line 1025, in get
2022-08-14 14:35:32	stdout	  File "yee/media/douban.py", line 466, in yee.media.douban.DoubanMovie.ranking_list
2022-08-14 14:35:32	stdout	  File "yee/media/douban.py", line 461, in yee.media.douban.DoubanMovie.ranking_list
2022-08-14 14:35:32	stdout	Traceback (most recent call last):
2022-08-14 14:35:32	stdout	
2022-08-14 14:35:32	stdout	The above exception was the direct cause of the following exception:
2022-08-14 14:35:32	stdout	
2022-08-14 14:35:32	stdout	httpcore.ConnectError: [Errno -3] Temporary failure in name resolution
2022-08-14 14:35:32	stdout	    raise to_exc(exc)
2022-08-14 14:35:32	stdout	  File "/dependencies/httpcore/_exceptions.py", line 12, in map_exceptions
2022-08-14 14:35:32	stdout	    self.gen.throw(type, value, traceback)
2022-08-14 14:35:32	stdout	  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
2022-08-14 14:35:32	stdout	    sock = socket.create_connection(
2022-08-14 14:35:32	stdout	  File "/dependencies/httpcore/backends/sync.py", line 82, in connect_tcp
2022-08-14 14:35:32	stdout	    stream = self._network_backend.connect_tcp(**kwargs)
2022-08-14 14:35:32	stdout	  File "/dependencies/httpcore/_sync/connection.py", line 111, in _connect
2022-08-14 14:35:32	stdout	    stream = self._connect(request)
2022-08-14 14:35:32	stdout	  File "/dependencies/httpcore/_sync/connection.py", line 63, in handle_request
2022-08-14 14:35:32	stdout	    raise exc
2022-08-14 14:35:32	stdout	  File "/dependencies/httpcore/_sync/connection.py", line 86, in handle_request
2022-08-14 14:35:32	stdout	    response = connection.handle_request(request)
2022-08-14 14:35:32	stdout	  File "/dependencies/httpcore/_sync/connection_pool.py", line 237, in handle_request
2022-08-14 14:35:32	stdout	    raise exc
2022-08-14 14:35:32	stdout	  File "/dependencies/httpcore/_sync/connection_pool.py", line 253, in handle_request
2022-08-14 14:35:32	stdout	    resp = self._pool.handle_request(req)
2022-08-14 14:35:32	stdout	  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
2022-08-14 14:35:32	stdout	    yield
2022-08-14 14:35:32	stdout	  File "/dependencies/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
2022-08-14 14:35:32	stdout	Traceback (most recent call last):
2022-08-14 14:35:32	stdout	
2022-08-14 14:35:32	stdout	During handling of the above exception, another exception occurred:
2022-08-14 14:35:32	stdout	
2022-08-14 14:35:32	stdout	socket.gaierror: [Errno -3] Temporary failure in name resolution
2022-08-14 14:35:32	stdout	    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2022-08-14 14:35:32	stdout	  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
2022-08-14 14:35:32	stdout	    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
2022-08-14 14:35:32	stdout	  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
2022-08-14 14:35:32	stdout	    sock = socket.create_connection(
2022-08-14 14:35:32	stdout	  File "/dependencies/httpcore/backends/sync.py", line 82, in connect_tcp
2022-08-14 14:35:32	stdout	    yield
2022-08-14 14:35:32	stdout	  File "/dependencies/httpcore/_exceptions.py", line 8, in map_exceptions
2022-08-14 14:35:32	stdout	Traceback (most recent call last):
2022-08-14 14:35:31	stdout	Exception in thread Thread-39:
2022-08-14 14:35:29	stdout	2022/08/14 22:35:29 - Thread-39 - ERROR: 请求豆瓣榜单出错：[Errno -3] Temporary failure in name resolution
2022-08-14 14:33:15	stdout	2022/08/14 22:33:15 - Thread-45 - ERROR: 错误码：400001 错误消息：登录错误，请检查登录状态是否已经过期，尝试重新登录
2022-08-14 14:33:07	stdout	2022/08/14 22:33:07 - MainThread - INFO: 当前版本: 1.1.1
2022-08-14 14:33:07	stdout	2022/08/14 22:33:07 - MainThread - INFO: 已经启动字幕下载处理任务。
2022-08-14 14:33:07	stdout	2022/08/14 22:33:07 - MainThread - INFO: Emby连接正常，9cc344b03366版本为4.6.7.0
2022-08-14 14:33:06	stdout	2022/08/14 22:33:06 - ThreadPoolExecutor-0_1 - INFO: Emby连接正常，9cc344b03366版本为4.6.7.0
2022-08-14 14:33:06	stdout	2022/08/14 22:33:06 - MainThread - INFO: 新增任务：健康检查任务
2022-08-14 14:33:06	stdout	2022/08/14 22:33:06 - MainThread - INFO: 新增任务：媒体趋势榜单任务
2022-08-14 14:33:06	stdout	2022/08/14 22:33:06 - Thread-39 - INFO: 开始更新媒体趋势榜单数据
2022-08-14 14:33:06	stdout	2022/08/14 22:33:06 - MainThread - INFO: 新增任务：新版本检测任务
2022-08-14 14:33:06	stdout	2022/08/14 22:33:06 - MainThread - INFO: 新增任务：订阅元数据检查更新任务
2022-08-14 14:33:06	stdout	2022/08/14 22:33:06 - MainThread - INFO: 新增任务：监听下载客户端下载状态
2022-08-14 14:33:06	stdout	2022/08/14 22:33:06 - MainThread - INFO: 新增任务：自定义任务调度
2022-08-14 14:33:06	stdout	2022/08/14 22:33:06 - Thread-38 - INFO: 同步豆瓣想看数据的任务已经启动
2022-08-14 14:33:06	stdout	2022/08/14 22:33:06 - MainThread - INFO: 新增任务：站点资源同步任务
2022-08-14 14:33:06	stdout	2022/08/14 22:33:06 - MainThread - INFO: 新增任务：免费下载种子监测任务
2022-08-14 14:33:06	stdout	2022/08/14 22:33:06 - MainThread - INFO: 新增任务：PT站点登陆有效性检查及分享数据更新任务
2022-08-14 14:33:02	stdout	2022/08/14 22:33:02 - MainThread - INFO: Emby连接正常，9cc344b03366版本为4.6.7.0
2022-08-14 14:33:01	stdout	2022/08/14 22:33:01 - MainThread - INFO: 已开启企业微信接收消息配置
2022-08-14 14:33:01	stdout	2022/08/14 22:33:01 - MainThread - INFO: 站点并发线程数：6
2022-08-14 14:32:48	stdout	2022-08-14 22:32:48,678 INFO success: mbots entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2022-08-14 14:32:43	stdout	2022-08-14 22:32:43,673 INFO spawned: 'mbots' with pid 14
2022-08-14 14:32:42	stdout	2022-08-14 22:32:42,669 INFO supervisord started with pid 12
2022-08-14 14:32:42	stdout	2022-08-14 22:32:42,665 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-08-14 14:32:39	stdout	mbot exists
2022-08-14 14:27:01	stdout	ValueError: time data '31.68GB' does not match format '%Y-%m-%d %H:%M:%S'
2022-08-14 14:27:01	stdout	    raise ValueError("time data %r does not match format %r" %
2022-08-14 14:27:01	stdout	  File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
2022-08-14 14:27:01	stdout	    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
2022-08-14 14:27:01	stdout	  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
2022-08-14 14:27:01	stdout	  File "yee/site/htmlparser.py", line 84, in yee.site.htmlparser.filter_dateparse
2022-08-14 14:27:01	stdout	  File "yee/site/htmlparser.py", line 156, in yee.site.htmlparser.HtmlParser.__filter_value__
2022-08-14 14:27:01	stdout	  File "yee/site/htmlparser.py", line 193, in yee.site.htmlparser.HtmlParser.parse_item_fields
2022-08-14 14:27:01	stdout	Traceback (most recent call last):
2022-08-14 14:27:01	stdout	2022/08/14 22:27:01 - ThreadPoolExecutor-5_5 - ERROR: date解析出错 values: {'id': '33252', 'category': '401', 'title_default': 'Body Slam 1986 1080p Blu-ray AVC TrueHD 5 0-NiXFLiX', 'title_optional': 'Body Slam 1986 1080p Blu-ray AVC TrueHD 5 0-NiXFLiX', 'title': 'Body Slam 1986 1080p Blu-ray AVC TrueHD 5 0-NiXFLiX', 'details': 'details.php?id=33252&hit=1', 'download': 'download.php?id=33252& ', 'size': '3', 'grabs': 'xiaojiameier', 'seeders': '0', 'leechers': '36', 'date_elapsed': None, 'date_added': '31.68GB'} tag: <tr class="torrent_table" id="tid_33252"><td class="rowfollow nowrap" id="torrents_td" style="padding: 0px" valign="middle"><a href="torrents.php?cat=401"><img alt="电影" class="c_movies" src="pic/cattrans.gif" style="background-image: url(pic/category/CHD/scenetorrents/chs/movies_dvdr.png); height:60px; width:48px" title="电影"/></a><a href="torrents.php?cat=401&amp;source=55"><img alt="电影-原盘" src="pic/cattrans.gif" style="width:48px;height:60px;background-image: url(pic/category/CHD/scenetorrents/chs//sec/55.png);background-position: top left;" title="电影-原盘"/></a></td><td align="left" class="rowfollow" id="torrents_td" width="100%"><table class="torrentname" style="background-color:transparent" width="100%"><td class="embedded"><span class="browse new">新</span><a href="details.php?id=33252&amp;hit=1" title="Body Slam 1986 1080p Blu-ray AVC TrueHD 5 0-NiXFLiX"><b>Body Slam 1986 1080p Blu-ray AVC TrueHD 5 0-NiXFLiX</b></a> <b>[<font class="hot">热门</font>]</b><font color="#888888"> <img alt="Free" class="pro_free" src="pic/trans.gif" title="Free"/> <b>[剩余时间：<span title="2022-08-15 02:17:46">3时51分</span>]</b></font><br/>抱摔 | 类别：喜剧 音乐 运动</td><td class="embedded" style="text-align: right; " valign="middle" width="80"> <a href="download.php?id=33252&amp; "><img alt="download" class="download" src="pic/trans.gif" style="padding-bottom: 2px;" title="下载本种"/></a> <a href="javascript: bookmark(33252,99,1);" id="bookmark99"><img alt="Unbookmarked" class="delbookmark" src="pic/trans.gif" title="收藏"/></a> <a href="javascript: truckmark(33252,99,1);" id="truckmark99"><img alt="Untruckmarked" class="truckmark" src="pic/trans.gif" title="放进小货车"/></a><br/> <span></span></td></table></td><td class="rowfollow" id="torrents_td">103</td><td class="rowfollow" id="torrents_td"><a href="comment.php?action=add&amp;pid=33252&amp;type=torrent" title="添加评论">0</a></td><td class="rowfollow nowrap" id="torrents_td"><span title="2022-08-14 02:17:45">20时<br/>8分</span></td><td class="rowfollow" id="torrents_td">31.68<br/>GB</td><td class="rowfollow" id="torrents_td"><b><a href="details.php?id=33252&amp;hit=1&amp;dllist=1#seeders">3</a></b></td><td class="rowfollow" id="torrents_td">0</td><td class="rowfollow" id="torrents_td"><a href="viewsnatches.php?id=33252"><b>36</b></a></td><td class="rowfollow" id="torrents_td"><span class="nowrap"><a class="ExtremeUser_Name" href="userdetails.php?id=16399"><b>xiaojiameier</b></a></span></td></tr>
2022-08-14 14:27:01	stdout	ValueError: time data '31.32GB' does not match format '%Y-%m-%d %H:%M:%S'
2022-08-14 14:27:01	stdout	    raise ValueError("time data %r does not match format %r" %
2022-08-14 14:27:01	stdout	  File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
2022-08-14 14:27:01	stdout	    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
2022-08-14 14:27:01	stdout	  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
2022-08-14 14:27:01	stdout	  File "yee/site/htmlparser.py", line 84, in yee.site.htmlparser.filter_dateparse
2022-08-14 14:27:01	stdout	  File "yee/site/htmlparser.py", line 156, in yee.site.htmlparser.HtmlParser.__filter_value__
2022-08-14 14:27:01	stdout	  File "yee/site/htmlparser.py", line 193, in yee.site.htmlparser.HtmlParser.parse_item_fields
2022-08-14 14:27:01	stdout	Traceback (most recent call last):
2022-08-14 14:27:01	stdout	2022/08/14 22:27:01 - ThreadPoolExecutor-5_5 - ERROR: date解析出错 values: {'id': '33253', 'category': '401', 'title_default': 'Wuthering Heights 2011 1080p Blu-ray AVC DTS-HD MA 5.1-HDChina', 'title_optional': 'Wuthering Heights 2011 1080p Blu-ray AVC DTS-HD MA 5.1-HDChina', 'title': 'Wuthering Heights 2011 1080p Blu-ray AVC DTS-HD MA 5.1-HDChina', 'details': 'details.php?id=33253&hit=1', 'download': 'download.php?id=33253& ', 'size': '4', 'grabs': 'xiaojiameier', 'seeders': '0', 'leechers': '23', 'date_elapsed': None, 'date_added': '31.32GB'} tag: <tr class="torrent_table" id="tid_33253"><td class="rowfollow nowrap" id="torrents_td" style="padding: 0px" valign="middle"><a href="torrents.php?cat=401"><img alt="电影" class="c_movies" src="pic/cattrans.gif" style="background-image: url(pic/category/CHD/scenetorrents/chs/movies_dvdr.png); height:60px; width:48px" title="电影"/></a><a href="torrents.php?cat=401&amp;source=55"><img alt="电影-原盘" src="pic/cattrans.gif" style="width:48px;height:60px;background-image: url(pic/category/CHD/scenetorrents/chs//sec/55.png);background-position: top left;" title="电影-原盘"/></a></td><td align="left" class="rowfollow" id="torrents_td" width="100%"><table class="torrentname" style="background-color:transparent" width="100%"><td class="embedded"><span class="browse new">新</span><a href="details.php?id=33253&amp;hit=1" title="Wuthering Heights 2011 1080p Blu-ray AVC DTS-HD MA 5.1-HDChina"><b>Wuthering Heights 2011 1080p Blu-ray AVC DTS-HD MA 5.1-HDChina</b></a><font color="#888888"> <img alt="Free" class="pro_free" src="pic/trans.gif" title="Free"/> <b>[剩余时间：<span title="2022-08-15 02:49:27">4时22分</span>]</b></font><br/>呼啸山庄/咆哮山庄(港/台)</td><td class="embedded" style="text-align: right; " valign="middle" width="80"> <a href=" "><img alt="download" class="download" src="pic/trans.gif" style="padding-bottom: 2px;" title="下载本种"/></a> <a href="javascript: bookmark(33253,98,1);" id="bookmark98"><img alt="Unbookmarked" class="delbookmark" src="pic/trans.gif" title="收藏"/></a> <a href="javascript: truckmark(33253,98,1);" id="truckmark98"><img alt="Untruckmarked" class="truckmark" src="pic/trans.gif" title="放进小货车"/></a><br/> <span></span></td></table></td><td class="rowfollow" id="torrents_td">134</td><td class="rowfollow" id="torrents_td"><a href="comment.php?action=add&amp;pid=33253&amp;type=torrent" title="添加评论">0</a></td><td class="rowfollow nowrap" id="torrents_td"><span title="2022-08-14 02:49:25">19时<br/>37分</span></td><td class="rowfollow" id="torrents_td">31.32<br/>GB</td><td class="rowfollow" id="torrents_td"><b><a href="details.php?id=33253&amp;hit=1&amp;dllist=1#seeders">4</a></b></td><td class="rowfollow" id="torrents_td">0</td><td class="rowfollow" id="torrents_td"><a href="viewsnatches.php?id=33253"><b>23</b></a></td><td class="rowfollow" id="torrents_td"><span class="nowrap"><a class="ExtremeUser_Name" href="userdetails.php?id=16399"><b>xiaojiameier</b></a></span></td></tr>
2022-08-14 14:27:01	stdout	ValueError: time data '135.40GB' does not match format '%Y-%m-%d %H:%M:%S'
2022-08-14 14:27:01	stdout	    raise ValueError("time data %r does not match format %r" %
2022-08-14 14:27:01	stdout	  File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
2022-08-14 14:27:01	stdout	    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
2022-08-14 14:27:01	stdout	  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
2022-08-14 14:27:01	stdout	  File "yee/site/htmlparser.py", line 84, in yee.site.htmlparser.filter_dateparse
2022-08-14 14:27:01	stdout	  File "yee/site/htmlparser.py", line 156, in yee.site.htmlparser.HtmlParser.__filter_value__
2022-08-14 14:27:01	stdout	  File "yee/site/htmlparser.py", line 193, in yee.site.htmlparser.HtmlParser.parse_item_fields
2022-08-14 14:27:01	stdout	Traceback (most recent call last):
2022-08-14 14:27:01	stdout	2022/08/14 22:27:01 - ThreadPoolExecutor-5_5 - ERROR: date解析出错 values: {'id': '33254', 'category': '402', 'title_default': '12 Monkeys S01 1080p EUR Blu-ray AVC DTS-HD MA 5.1-SHeNTo', 'title_optional': '12 Monkeys S01 1080p EUR Blu-ray AVC DTS-HD MA 5.1-SHeNTo', 'title': '12 Monkeys S01 1080p EUR Blu-ray AVC DTS-HD MA 5.1-SHeNTo', 'details': 'details.php?id=33254&hit=1', 'download': '', 'size': '1', 'grabs': '匿名', 'seeders': '5', 'leechers': '0', 'date_elapsed': None, 'date_added': '135.40GB'} tag: <tr class="torrent_table" id="tid_33254"><td class="rowfollow nowrap" id="torrents_td" style="padding: 0px" valign="middle"><a href="torrents.php?cat=402"><img alt="剧集" class="c_tvseries" src="pic/cattrans.gif" style="background-image: url(pic/category/CHD/scenetorrents/chs/tvseries_xvid.png); height:60px; width:48px" title="剧集"/></a><a href="torrents.php?cat=402&amp;source=25"><img alt="剧集-美剧" src="pic/cattrans.gif" style="width:48px;height:60px;background-image: url(pic/category/CHD/scenetorrents/chs//sec/25.png);background-position: top left;" title="剧集-美剧"/></a></td><td align="left" class="rowfollow" id="torrents_td" width="100%"><table class="torrentname" style="background-color:transparent" width="100%"><td class="embedded"><span class="browse new">新</span><a href="details.php?id=33254&amp;hit=1" title="12 Monkeys S01 1080p EUR Blu-ray AVC DTS-HD MA 5.1-SHeNTo"><b>12 Monkeys S01 1080p EUR Blu-ray AVC DTS-HD MA 5.1-SHeNTo</b></a> <img alt="Free" class="pro_free" src="pic/trans.gif" title="Free"/><br/>十二猴子 第一季 / 12 Maymun *第一季 全13集* | 类别：剧情  科幻  悬疑  惊悚  冒险    欧版原盘</td><td class="embedded" style="text-align: right; " valign="middle" width="80"> <a href=" e"><img alt="download" class="download" src="pic/trans.gif" style="padding-bottom: 2px;" title="下载本种"/></a> <a href="javascript: bookmark(33254,97,1);" id="bookmark97"><img alt="Unbookmarked" class="delbookmark" src="pic/trans.gif" title="收藏"/></a> <a href="javascript: truckmark(33254,97,1);" id="truckmark97"><img alt="Untruckmarked" class="truckmark" src="pic/trans.gif" title="放进小货车"/></a><br/> <span></span> <a href="details.php?id=33254&amp;hit=1"><img src="styles/img/imdb.gif" style="vertical-align: text-bottom;" title="IMDb评分：7.7"/> <span style="vertical-align: text-bottom;">7.7</span></a></td></table></td><td class="rowfollow" id="torrents_td">1011</td><td class="rowfollow" id="torrents_td"><a href="comment.php?action=add&amp;pid=33254&amp;type=torrent" title="添加评论">0</a></td><td class="rowfollow nowrap" id="torrents_td"><span title="2022-08-14 05:20:51">17时<br/>5分</span></td><td class="rowfollow" id="torrents_td">135.40<br/>GB</td><td class="rowfollow" id="torrents_td"><b><a href="details.php?id=33254&amp;hit=1&amp;dllist=1#seeders">1</a></b></td><td class="rowfollow" id="torrents_td"><b><a href="details.php?id=33254&amp;hit=1&amp;dllist=1#leechers">5</a></b></td><td class="rowfollow" id="torrents_td">0</td><td class="rowfollow" id="torrents_td"><i>匿名</i></td></tr>
2022-08-14 14:27:01	stdout	ValueError: time data '20.80GB' does not match format '%Y-%m-%d %H:%M:%S'
2022-08-14 14:27:01	stdout	    raise ValueError("time data %r does not match format %r" %
2022-08-14 14:27:01	stdout	  File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
2022-08-14 14:27:01	stdout	    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
2022-08-14 14:27:01	stdout	  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
2022-08-14 14:27:01	stdout	  File "yee/site/htmlparser.py", line 84, in yee.site.htmlparser.filter_dateparse
2022-08-14 14:27:01	stdout	  File "yee/site/htmlparser.py", line 156, in yee.site.htmlparser.HtmlParser.__filter_value__
2022-08-14 14:27:01	stdout	  File "yee/site/htmlparser.py", line 193, in yee.site.htmlparser.HtmlParser.parse_item_fields
2022-08-14 14:27:01	stdout	Traceback (most recent call last):

**Comment by pofey** [comment]
Temporary failure in name resolution
这个是网络问题 解析不了dns
底下的报错是你用的站点适配有问题 我也不知道是哪个

**Comment by 30507103** [comment]
> Temporary failure in name resolution 这个是网络问题 解析不了dns 底下的报错是你用的站点适配有问题 我也不知道是哪个

感谢大佬解答，你是说我设备所在网络的问题吗。
那么这句是什么意思呢？

2022-08-14 14:27:01	stdout	  File "yee/site/htmlparser.py", line 84, in yee.site.htmlparser.filter_dateparse
2022-08-14 14:27:01	stdout	  File "yee/site/htmlparser.py", line 156, in yee.site.htmlparser.HtmlParser.__filter_value__
2022-08-14 14:27:01	stdout	  File "yee/site/htmlparser.py", line 193, in yee.site.htmlparser.HtmlParser.parse_item_fields
2022-08-14 14:27:01	stdout	Traceback (most recent call last):

**Comment by pofey** [comment]
> > Temporary failure in name resolution 这个是网络问题 解析不了dns 底下的报错是你用的站点适配有问题 我也不知道是哪个
> 
> 感谢大佬解答，你是说我设备所在网络的问题吗。 那么这句是什么意思呢？
> 
> 2022-08-14 14:27:01 stdout File "yee/site/htmlparser.py", line 84, in yee.site.htmlparser.filter_dateparse 2022-08-14 14:27:01 stdout File "yee/site/htmlparser.py", line 156, in yee.site.htmlparser.HtmlParser.**filter_value** 2022-08-14 14:27:01 stdout File "yee/site/htmlparser.py", line 193, in yee.site.htmlparser.HtmlParser.parse_item_fields 2022-08-14 14:27:01 stdout Traceback (most recent call last):

不知道你用的什么栈适配有问题
