### ISSUE TITLE
[缺陷]: 

### ISSUE THREAD

**Issue by Tracy1984** [pofey/movie_robot#585]
### 当前程序版本

1.1.1

### 问题描述

unraid下安装突然出现这个问题，反复删除配置文件重新安装，依然出现这个问题

### 重现步骤

1，请求豆瓣榜单出错，导致首页刚打开就变成一片空白
2，豆瓣COOKIE也报错，重新添加也报错 EOF occurred in violation of protocol (_ssl.c:1125)
3，本人还有一台极空间，在极空间上正常使用

### 发生问题时系统日志

```shell
问题日志：
create mbot(0): mbot(0)
启动升级脚本
初始化数据库目录：/data/db
初始化日志目录：/data/logs
完成系统默认配置初始化。
完成数据表升级。
2022-08-15 22:04:56,584 CRIT Supervisor is running as root. Privileges were not dropped because no user is specified in the config file. If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-08-15 22:04:56,589 INFO supervisord started with pid 35
2022-08-15 22:04:57,591 INFO spawned: 'mbots' with pid 37
2022/08/15 22:04:58 - MainThread - INFO: 首次启动应用，请尽快访问页面进行初始化设置http://ip:1329/setup/admin
2022/08/15 22:05:00 - MainThread - ERROR: 错误码：401002 错误消息：没有配置豆瓣信息

2022/08/15 22:05:00 - MainThread - ERROR: 错误码：401001 错误消息：没有配置TMDB信息

2022/08/15 22:05:01 - MainThread - INFO: 站点并发线程数：6
2022/08/15 22:05:01 - MainThread - INFO: 新增任务：自定义任务调度
2022/08/15 22:05:01 - MainThread - INFO: 新增任务：监听下载客户端下载状态
2022/08/15 22:05:01 - MainThread - INFO: 新增任务：订阅元数据检查更新任务
2022/08/15 22:05:01 - MainThread - INFO: 新增任务：新版本检测任务
2022/08/15 22:05:01 - Thread-5 - INFO: 开始更新媒体趋势榜单数据
2022/08/15 22:05:01 - MainThread - INFO: 新增任务：媒体趋势榜单任务
2022/08/15 22:05:01 - MainThread - INFO: 新增任务：健康检查任务
2022/08/15 22:05:01 - MainThread - INFO: 已经启动字幕下载处理任务。
2022/08/15 22:05:01 - MainThread - INFO: 当前版本: 1.1.1
2022-08-15 22:05:02,859 INFO success: mbots entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2022/08/15 22:05:02 - Thread-5 - ERROR: 请求豆瓣榜单出错：EOF occurred in violation of protocol (_ssl.c:1125)

Exception in thread Thread-5:
Traceback (most recent call last):
File "/dependencies/httpcore/_exceptions.py", line 8, in map_exceptions


File "/dependencies/httpcore/backends/sync.py", line 57, in start_tls
raise exc
File "/dependencies/httpcore/backends/sync.py", line 52, in start_tls
sock = ssl_context.wrap_socket(
File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
self.do_handshake()
File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/dependencies/httpx/_transports/default.py", line 60, in map_httpcore_exceptions


File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
resp = self._pool.handle_request(req)
File "/dependencies/httpcore/_sync/connection_pool.py", line 253, in handle_request
raise exc
File "/dependencies/httpcore/_sync/connection_pool.py", line 237, in handle_request
response = connection.handle_request(request)
File "/dependencies/httpcore/_sync/connection.py", line 86, in handle_request
raise exc
File "/dependencies/httpcore/_sync/connection.py", line 63, in handle_request
stream = self._connect(request)
File "/dependencies/httpcore/_sync/connection.py", line 150, in _connect
stream = stream.start_tls(**kwargs)
File "/dependencies/httpcore/backends/sync.py", line 57, in start_tls
raise exc
File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
self.gen.throw(type, value, traceback)
File "/dependencies/httpcore/_exceptions.py", line 12, in map_exceptions
raise to_exc(exc)
httpcore.ConnectError: EOF occurred in violation of protocol (_ssl.c:1125)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "yee/media/douban.py", line 461, in yee.media.douban.DoubanMovie.ranking_list
File "yee/media/douban.py", line 466, in yee.media.douban.DoubanMovie.ranking_list
File "/dependencies/httpx/_client.py", line 1025, in get
return self.request(
File "/dependencies/httpx/_client.py", line 802, in request
return self.send(request, auth=auth, follow_redirects=follow_redirects)
File "/dependencies/httpx/_client.py", line 889, in send
response = self._send_handling_auth(
File "/dependencies/httpx/_client.py", line 917, in _send_handling_auth
response = self._send_handling_redirects(
File "/dependencies/httpx/_client.py", line 954, in _send_handling_redirects
response = self._send_single_request(request)
File "/dependencies/httpx/_client.py", line 990, in _send_single_request
response = transport.handle_request(request)
File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
resp = self._pool.handle_request(req)
File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
self.gen.throw(type, value, traceback)
File "/dependencies/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
raise mapped_exc(message) from exc
httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "yee/task/mediatrendingtask.py", line 71, in yee.task.mediatrendingtask.MediaTrendingTask.run
File "yee/service/mediametadataservice.py", line 209, in yee.service.mediametadataservice.MovieMetadataService.get_trending_list
File "yee/media/douban.py", line 529, in yee.media.douban.DoubanMovie.ranking_list
UnboundLocalError: local variable 'result' referenced before assignment
```

### 健康检查

没了

**Comment by pofey** [comment]
自己检查容器网络是否可以访问豆瓣，以及自己ip是否被豆瓣ban了吧
