### ISSUE TITLE
[提问]: 请求 mbot.vip/api/license/verify失败，但是ssh下能ping通

### ISSUE THREAD

**Issue by ShakeChanDev** [pofey/movie_robot#590]
### 当前程序版本

1.1.1

### 问题

请求 mbot.vip/api/license/verify失败，但是ssh下能ping通
因他个人在不同地区有两台nas，分别尝试了都无法成功

<img width="561" alt="615daafe68296b5f2a41f4ed8569ada" src="https://user-images.githubusercontent.com/2718231/184847813-99a9af92-65ab-412d-abd3-1028935325a3.png">
<img width="1134" alt="afd2503780cd6b0b22cf7983d7c5e0d" src="https://user-images.githubusercontent.com/2718231/184847849-10da60ec-2ada-4cf3-8669-d84fc927f99b.png">

### 发生问题时系统日志

```shell
2-08-16T09:30:21.278573336Z	stdout	tenacity.RetryError: RetryError[<Future at 0x7f670265f280 state=finished raised ProcessLookupError>]
2022-08-16T09:30:21.278561880Z	stdout	    raise retry_exc from fut.exception()
2022-08-16T09:30:21.278549871Z	stdout	  File "/dependencies/tenacity/__init__.py", line 361, in iter
2022-08-16T09:30:21.278538994Z	stdout	    do = self.iter(retry_state=retry_state)
2022-08-16T09:30:21.278525844Z	stdout	  File "/dependencies/tenacity/__init__.py", line 404, in __call__
2022-08-16T09:30:21.278514665Z	stdout	    return self(f, *args, **kw)
2022-08-16T09:30:21.278501604Z	stdout	  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
2022-08-16T09:30:21.278488472Z	stdout	  File "yee/task/appchecknewversiontask.py", line 23, in yee.task.appchecknewversiontask.AppCheckNewVersionTask.run
2022-08-16T09:30:21.278476702Z	stdout	    retval = job.func(*job.args, **job.kwargs)
2022-08-16T09:30:21.278463626Z	stdout	  File "/dependencies/apscheduler/executors/base.py", line 125, in run_job
2022-08-16T09:30:21.278453113Z	stdout	Traceback (most recent call last):
2022-08-16T09:30:21.278443616Z	stdout	
2022-08-16T09:30:21.278430940Z	stdout	The above exception was the direct cause of the following exception:
2022-08-16T09:30:21.278421693Z	stdout	
2022-08-16T09:30:21.278409944Z	stdout	ProcessLookupError: [Errno 3] No such process
2022-08-16T09:30:21.278397757Z	stdout	  File "yee/task/taskrun.py", line 33, in yee.task.taskrun.TaskRun.kill_app
2022-08-16T09:30:21.278384266Z	stdout	  File "yee/task/taskrun.py", line 31, in yee.task.taskrun.TaskRun.kill_app
2022-08-16T09:30:21.278371622Z	stdout	  File "yee/task/taskrun.py", line 70, in yee.task.taskrun.TaskRun.__init__
2022-08-16T09:30:21.278356823Z	stdout	  File "yee/core/remoteapi.py", line 50, in yee.core.remoteapi.RemoteApi.check_access_token
2022-08-16T09:30:21.278343543Z	stdout	  File "yee/core/remoteapi.py", line 140, in yee.core.remoteapi.RemoteApi.get_new_version
2022-08-16T09:30:21.278332854Z	stdout	    result = fn(*args, **kwargs)
2022-08-16T09:30:21.278320641Z	stdout	  File "/dependencies/tenacity/__init__.py", line 407, in __call__
2022-08-16T09:30:21.278309852Z	stdout	Traceback (most recent call last):
2022-08-16T09:30:21.278300455Z	stdout	
2022-08-16T09:30:21.278287855Z	stdout	During handling of the above exception, another exception occurred:
2022-08-16T09:30:21.278278508Z	stdout	
2022-08-16T09:30:21.278266746Z	stdout	AttributeError: 'NoneType' object has no attribute 'text'
2022-08-16T09:30:21.278253882Z	stdout	  File "yee/task/taskrun.py", line 50, in yee.task.taskrun.TaskRun.__init__
2022-08-16T09:30:21.278242106Z	stdout	Traceback (most recent call last):
2022-08-16T09:30:21.278222341Z	stdout	2022/08/16 17:30:21 - ThreadPoolExecutor-3_0 - ERROR: Job "app_check_new_version_task (trigger: cron[month='*', day='*', day_of_week='*', hour='*', minute='*/30'], next run at: 2022-08-16 18:00:00 CST)" raised an exception
2022-08-16T09:30:21.278198065Z	stdout	tenacity.RetryError: RetryError[<Future at 0x7f670265f280 state=finished raised ProcessLookupError>]
2022-08-16T09:30:21.278183337Z	stdout	    raise retry_exc from fut.exception()
2022-08-16T09:30:21.278169196Z	stdout	  File "/dependencies/tenacity/__init__.py", line 361, in iter
2022-08-16T09:30:21.278156274Z	stdout	    do = self.iter(retry_state=retry_state)
2022-08-16T09:30:21.278143707Z	stdout	  File "/dependencies/tenacity/__init__.py", line 404, in __call__
2022-08-16T09:30:21.278129438Z	stdout	    return self(f, *args, **kw)
2022-08-16T09:30:21.278102894Z	stdout	  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
2022-08-16T09:30:21.278087358Z	stdout	  File "yee/task/appchecknewversiontask.py", line 23, in yee.task.appchecknewversiontask.AppCheckNewVersionTask.run
2022-08-16T09:30:21.278074444Z	stdout	    retval = job.func(*job.args, **job.kwargs)
2022-08-16T09:30:21.278057981Z	stdout	  File "/dependencies/apscheduler/executors/base.py", line 125, in run_job
2022-08-16T09:30:21.278047090Z	stdout	Traceback (most recent call last):
2022-08-16T09:30:21.278037727Z	stdout	
2022-08-16T09:30:21.278023169Z	stdout	The above exception was the direct cause of the following exception:
2022-08-16T09:30:21.278013668Z	stdout	
2022-08-16T09:30:21.278000369Z	stdout	ProcessLookupError: [Errno 3] No such process
2022-08-16T09:30:21.277986329Z	stdout	  File "yee/task/taskrun.py", line 33, in yee.task.taskrun.TaskRun.kill_app
2022-08-16T09:30:21.277971201Z	stdout	  File "yee/task/taskrun.py", line 31, in yee.task.taskrun.TaskRun.kill_app
2022-08-16T09:30:21.277956836Z	stdout	  File "yee/task/taskrun.py", line 70, in yee.task.taskrun.TaskRun.__init__
2022-08-16T09:30:21.277943279Z	stdout	  File "yee/core/remoteapi.py", line 50, in yee.core.remoteapi.RemoteApi.check_access_token
2022-08-16T09:30:21.277927343Z	stdout	  File "yee/core/remoteapi.py", line 140, in yee.core.remoteapi.RemoteApi.get_new_version
2022-08-16T09:30:21.277915209Z	stdout	    result = fn(*args, **kwargs)
2022-08-16T09:30:21.277900080Z	stdout	  File "/dependencies/tenacity/__init__.py", line 407, in __call__
2022-08-16T09:30:21.277888523Z	stdout	Traceback (most recent call last):
2022-08-16T09:30:21.277877603Z	stdout	
2022-08-16T09:30:21.277856803Z	stdout	During handling of the above exception, another exception occurred:
2022-08-16T09:30:21.277846583Z	stdout	
2022-08-16T09:30:21.277828289Z	stdout	AttributeError: 'NoneType' object has no attribute 'text'
2022-08-16T09:30:21.277808057Z	stdout	  File "yee/task/taskrun.py", line 50, in yee.task.taskrun.TaskRun.__init__
2022-08-16T09:30:21.277788114Z	stdout	Traceback (most recent call last):
2022-08-16T09:30:21.277733580Z	stdout	2022/08/16 17:30:21 - ThreadPoolExecutor-3_0 - ERROR: Job "app_check_new_version_task (trigger: cron[month='*', day='*', day_of_week='*', hour='*', minute='*/30'], next run at: 2022-08-16 18:00:00 CST)" raised an exception
2022-08-16T09:30:21.276137641Z	stdout	2022/08/16 17:30:21 - ThreadPoolExecutor-3_0 - INFO: 无法连接到服务器正常提供服务，请稍后再试。
2022-08-16T09:30:21.276103874Z	stdout	2022/08/16 17:30:21 - ThreadPoolExecutor-3_0 - INFO: 错误信息：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-08-16T09:30:21.276024558Z	stdout	2022/08/16 17:30:21 - ThreadPoolExecutor-3_0 - INFO: 请求http://mbot.vip/api/license/verify 失败，开始准备重试(3/3)
2022-08-16T09:30:21.141242710Z	stdout	2022/08/16 17:30:21 - ThreadPoolExecutor-3_0 - INFO: 错误信息：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-08-16T09:30:21.141153032Z	stdout	2022/08/16 17:30:21 - ThreadPoolExecutor-3_0 - INFO: 请求http://mbot.vip/api/license/verify 失败，开始准备重试(2/3)
2022-08-16T09:30:20.957025674Z	stdout	2022/08/16 17:30:20 - ThreadPoolExecutor-3_0 - INFO: 错误信息：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-08-16T09:30:20.956808330Z	stdout	2022/08/16 17:30:20 - ThreadPoolExecutor-3_0 - INFO: 请求http://mbot.vip/api/license/verify 失败，开始准备重试(1/3)
2022-08-16T09:30:10.753683786Z	stdout	2022/08/16 17:30:10 - ThreadPoolExecutor-3_0 - INFO: 无法连接到服务器正常提供服务，请稍后再试。
2022-08-16T09:30:10.753657300Z	stdout	2022/08/16 17:30:10 - ThreadPoolExecutor-3_0 - INFO: 错误信息：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-08-16T09:30:10.753580404Z	stdout	2022/08/16 17:30:10 - ThreadPoolExecutor-3_0 - INFO: 请求http://mbot.vip/api/license/verify 失败，开始准备重试(3/3)
2022-08-16T09:30:10.627947870Z	stdout	2022/08/16 17:30:10 - ThreadPoolExecutor-3_0 - INFO: 错误信息：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-08-16T09:30:10.627861883Z	stdout	2022/08/16 17:30:10 - ThreadPoolExecutor-3_0 - INFO: 请求http://mbot.vip/api/license/verify 失败，开始准备重试(2/3)
2022-08-16T09:30:10.522986358Z	stdout	2022/08/16 17:30:10 - ThreadPoolExecutor-3_0 - INFO: 错误信息：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-08-16T09:30:10.522716349Z	stdout	2022/08/16 17:30:10 - ThreadPoolExecutor-3_0 - INFO: 请求http://mbot.vip/api/license/verify 失败，开始准备重试(1/3)
2022-08-16T09:30:00.393869362Z	stdout	2022/08/16 17:30:00 - ThreadPoolExecutor-3_0 - INFO: 无法连接到服务器正常提供服务，请稍后再试。
2022-08-16T09:30:00.393843845Z	stdout	2022/08/16 17:30:00 - ThreadPoolExecutor-3_0 - INFO: 错误信息：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-08-16T09:30:00.393769775Z	stdout	2022/08/16 17:30:00 - ThreadPoolExecutor-3_0 - INFO: 请求http://mbot.vip/api/license/verify 失败，开始准备重试(3/3)
2022-08-16T09:30:00.278256701Z	stdout	2022/08/16 17:30:00 - ThreadPoolExecutor-3_0 - INFO: 错误信息：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-08-16T09:30:00.278168862Z	stdout	2022/08/16 17:30:00 - ThreadPoolExecutor-3_0 - INFO: 请求http://mbot.vip/api/license/verify 失败，开始准备重试(2/3)
2022-08-16T09:30:00.146312071Z	stdout	2022/08/16 17:30:00 - ThreadPoolExecutor-3_0 - INFO: 错误信息：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-08-16T09:30:00.146078977Z	stdout	2022/08/16 17:30:00 - ThreadPoolExecutor-3_0 - INFO: 请求http://mbot.vip/api/license/verify 失败，开始准备重试(1/3)
2022-08-16T09:26:59.632992082Z	stdout	2022-08-16 17:26:59,632 INFO success: mbots entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2022-08-16T09:26:57.632262268Z	stdout	ProcessLookupError: [Errno 3] No such process
2022-08-16T09:26:57.632248912Z	stdout	  File "yee/task/taskrun.py", line 33, in yee.task.taskrun.TaskRun.kill_app
2022-08-16T09:26:57.632231324Z	stdout	  File "yee/task/taskrun.py", line 31, in yee.task.taskrun.TaskRun.kill_app
2022-08-16T09:26:57.632218055Z	stdout	  File "yee/task/taskrun.py", line 70, in yee.task.taskrun.TaskRun.__init__
2022-08-16T09:26:57.632204787Z	stdout	  File "yee/app.py", line 130, in yee.app.start
2022-08-16T09:26:57.632193953Z	stdout	    app.start()
2022-08-16T09:26:57.632179462Z	stdout	  File "start.py", line 30, in <module>
2022-08-16T09:26:57.632166371Z	stdout	Traceback (most recent call last):
2022-08-16T09:26:57.632156094Z	stdout	
2022-08-16T09:26:57.632138718Z	stdout	During handling of the above exception, another exception occurred:
2022-08-16T09:26:57.632108996Z	stdout	
2022-08-16T09:26:57.632069259Z	stdout	AttributeError: 'NoneType' object has no attribute 'text'
2022-08-16T09:26:57.632049798Z	stdout	  File "yee/task/taskrun.py", line 50, in yee.task.taskrun.TaskRun.__init__
2022-08-16T09:26:57.632030615Z	stdout	Traceback (most recent call last):
2022-08-16T09:26:57.631996040Z	stdout	2022/08/16 17:26:57 - MainThread - ERROR: Uncaught exception
2022-08-16T09:26:57.631431630Z	stdout	2022/08/16 17:26:57 - MainThread - INFO: 无法连接到服务器正常提供服务，请稍后再试。
2022-08-16T09:26:57.631406365Z	stdout	2022/08/16 17:26:57 - MainThread - INFO: 错误信息：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-08-16T09:26:57.631324895Z	stdout	2022/08/16 17:26:57 - MainThread - INFO: 请求http://mbot.vip/api/license/verify 失败，开始准备重试(3/3)
2022-08-16T09:26:57.515877971Z	stdout	2022/08/16 17:26:57 - MainThread - INFO: 错误信息：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-08-16T09:26:57.515677943Z	stdout	2022/08/16 17:26:57 - MainThread - INFO: 请求http://mbot.vip/api/license/verify 失败，开始准备重试(2/3)
2022-08-16T09:26:57.376298382Z	stdout	2022/08/16 17:26:57 - MainThread - INFO: 错误信息：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-08-16T09:26:57.376205519Z	stdout	2022/08/16 17:26:57 - MainThread - INFO: 请求http://mbot.vip/api/license/verify 失败，开始准备重试(1/3)
2022-08-16T09:26:57.212861712Z	stdout	2022/08/16 17:26:57 - MainThread - INFO: 当前版本: 1.1.1
2022-08-16T09:26:57.210602357Z	stdout	2022/08/16 17:26:57 - MainThread - INFO: 已经启动字幕下载处理任务。
2022-08-16T09:26:57.198773039Z	stdout	2022/08/16 17:26:57 - MainThread - INFO: 新增任务：健康检查任务
2022-08-16T09:26:57.196785442Z	stdout	2022/08/16 17:26:57 - MainThread - INFO: 新增任务：媒体趋势榜单任务
2022-08-16T09:26:57.196191569Z	stdout	2022/08/16 17:26:57 - Thread-5 - INFO: 开始更新媒体趋势榜单数据
2022-08-16T09:26:57.195721446Z	stdout	2022/08/16 17:26:57 - MainThread - INFO: 新增任务：新版本检测任务
2022-08-16T09:26:57.195503681Z	stdout	2022/08/16 17:26:57 - MainThread - INFO: 新增任务：订阅元数据检查更新任务
2022-08-16T09:26:57.195315284Z	stdout	2022/08/16 17:26:57 - MainThread - INFO: 新增任务：监听下载客户端下载状态
2022-08-16T09:26:57.193580354Z	stdout	2022/08/16 17:26:57 - MainThread - INFO: 新增任务：自定义任务调度
2022-08-16T09:26:56.652618254Z	stdout	2022/08/16 17:26:56 - MainThread - INFO: 站点并发线程数：12
2022-08-16T09:26:56.632463707Z	stdout	2022/08/16 17:26:56 - MainThread - ERROR: 错误码：401001 错误消息：没有配置TMDB信息
2022-08-16T09:26:56.632200660Z	stdout	2022/08/16 17:26:56 - MainThread - ERROR: 错误码：401002 错误消息：没有配置豆瓣信息
2022-08-16T09:26:55.265832111Z	stdout	2022/08/16 17:26:55 - MainThread - INFO: 首次启动应用，请尽快访问页面进行初始化设置http://ip:1329/setup/admin
2022-08-16T09:26:54.334445502Z	stdout	2022-08-16 17:26:54,333 INFO spawned: 'mbots' with pid 37
2022-08-16T09:26:53.332157860Z	stdout	2022-08-16 17:26:53,332 INFO supervisord started with pid 35
2022-08-16T09:26:53.329824412Z	stdout	2022-08-16 17:26:53,329 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-08-16T09:26:53.037777020Z	stdout	完成数据表升级。
2022-08-16T09:26:53.036926321Z	stdout	完成系统默认配置初始化。
2022-08-16T09:26:51.726040626Z	stdout	启动升级脚本
2022-08-16T09:26:51.603109312Z	stdout	create mbot(0): mbot(0)
```
```

**Comment by pofey** [comment]
不要过梯子
