### ISSUE TITLE
[缺陷]: 文件不存在报错死循环无法跳出导致无法继续整理挂削

### ISSUE THREAD

**Issue by MisakaF0406** [pofey/movie_robot#591]
### 当前程序版本

1.1.1

### 问题描述

当qb下载完，但movie-robot还未整理时，这个资源被手动删除或移动了，程序就会循环报错找不到此文件，并且无法开始对新的已下载资源进行整理挂削。
我的解决方法是创建一个空文件，文件名为movie-robot找不到的文件，他就会认为这个资源存在，不管他对这个资源怎么整，反正不再卡在这儿了，可以继续整理挂削新的资源。

后续追加：
翻日志发现当日凌晨2点开始报这个错，从此往后就没有再整理挂削任何一部资源了。虽然报错期间搜索下载正常，但就是无法开始整理。并非我人为干预已下载的文件导致的这个问题。或许可以优化下异常处理，报错超过多少次多长时间自动跳过之类的。

### 重现步骤

暂时还没摸索出来重现的步骤，或许可以在下载完以后立即删除或移动下载好的文件，从而产生文件不存在的报错。

### 发生问题时系统日志

```shell
2022/08/16 20:23:00 - ThreadPoolExecutor-5_0 - ERROR: 文件转移失败：找不到内容路径或无权限访问：/video/temp/tv/Back.To.Field.S06.2022.1080p.WEB-DL.H264.AAC-TJUPT/Back.To.Field.S06E08.2022.1080p.WEB-DL.H264.AAC-TJUPT.mp4
2022/08/16 20:23:00 - ThreadPoolExecutor-5_0 - ERROR: 监控种子任务出现错误：找不到内容路径或无权限访问：/video/temp/tv/Back.To.Field.S06.2022.1080p.WEB-DL.H264.AAC-TJUPT/Back.To.Field.S06E08.2022.1080p.WEB-DL.H264.AAC-TJUPT.mp4
Traceback (most recent call last):
  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
  File "yee/service/downloadservice.py", line 407, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/downloadservice.py", line 385, in yee.service.downloadservice.DownloadService.download_completed
  File "yee/service/filemanagerservice.py", line 81, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/tvlink.py", line 25, in yee.media.link.tvlink.TvLink.__init__
  File "yee/media/link/medialink.py", line 92, in yee.media.link.medialink.MediaLink.__init__
FileNotFoundError: 找不到内容路径或无权限访问：/video/temp/tv/Back.To.Field.S06.2022.1080p.WEB-DL.H264.AAC-TJUPT/Back.To.Field.S06E08.2022.1080p.WEB-DL.H264.AAC-TJUPT.mp4
```

### 健康检查

极好

**Comment by pofey** [comment]
删下载记录
