### ISSUE TITLE
[提问]: 处理免费种子淘汰任务出错：(sqlite3.OperationalError) database is locked)

### ISSUE THREAD

**Issue by xwh4git** [pofey/movie_robot#592]
### 当前程序版本

1.1.1

### 问题

![G$O4}J{BPO6RYW0D`5_Q _0](https://user-images.githubusercontent.com/26497752/184911475-3a13b276-0658-4b21-a6e7-d8732e0a02c3.png)
![L`Q72PFZ IM_0AQT~@V_XFH](https://user-images.githubusercontent.com/26497752/184911738-c050eca0-77ea-4e8e-93af-545921289bcf.png)
![image](https://user-images.githubusercontent.com/26497752/184913937-28b81907-468a-42fd-b0cb-100a8ca8e14d.png)

百度了报错,说是权限问题,权限是给了的.这个错误已经持续好几天了.

### 发生问题时系统日志

```shell
[SQL: SELECT free_download_record.id AS free_download_record_id, free_download_record.gmt_create AS free_download_record_gmt_create, free_download_record.gmt_modified AS free_download_record_gmt_modified, free_download_record.site_id AS free_download_record_site_id, free_download_record.torrent_id AS free_download_record_torrent_id, free_download_record.name AS free_download_record_name, free_download_record.subject AS free_download_record_subject, free_download_record.size_mb AS free_download_record_size_mb, free_download_record.upload_count AS free_download_record_upload_count, free_download_record.downloading_count AS free_download_record_downloading_count, free_download_record.download_count AS free_download_record_download_count, free_download_record.download_volume_factor AS free_download_record_download_volume_factor, free_download_record.upload_volume_factor AS free_download_record_upload_volume_factor, free_download_record.minimum_ratio AS free_download_record_minimum_ratio, free_download_record.minimum_seed_time AS free_download_record_minimum_seed_time, free_download_record.free_deadline AS free_download_record_free_deadline, free_download_record.torrent_hash AS free_download_record_torrent_hash, free_download_record.delete_status AS free_download_record_delete_status 
FROM free_download_record 
WHERE free_download_record.id = ?]
[parameters: (7988,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/dependencies/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "yee/task/freedownloadmonitortask.py", line 185, in yee.task.freedownloadmonitortask.FreeDownloadMonitor.run
  File "yee/task/freedownloadmonitortask.py", line 35, in yee.task.freedownloadmonitortask.FreeDownloadMonitor.update_data
  File "/dependencies/sqlalchemy/orm/attributes.py", line 481, in __get__
    return self.impl.get(state, dict_)
  File "/dependencies/sqlalchemy/orm/attributes.py", line 941, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/dependencies/sqlalchemy/orm/attributes.py", line 972, in _fire_loader_callables
    return state._load_expired(state, passive)
  File "/dependencies/sqlalchemy/orm/state.py", line 712, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/dependencies/sqlalchemy/orm/loading.py", line 1451, in load_scalar_attributes
    result = load_on_ident(
  File "/dependencies/sqlalchemy/orm/loading.py", line 407, in load_on_ident
    return load_on_pk_identity(
  File "/dependencies/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/dependencies/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/dependencies/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/dependencies/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/dependencies/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/dependencies/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/dependencies/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT free_download_record.id AS free_download_record_id, free_download_record.gmt_create AS free_download_record_gmt_create, free_download_record.gmt_modified AS free_download_record_gmt_modified, free_download_record.site_id AS free_download_record_site_id, free_download_record.torrent_id AS free_download_record_torrent_id, free_download_record.name AS free_download_record_name, free_download_record.subject AS free_download_record_subject, free_download_record.size_mb AS free_download_record_size_mb, free_download_record.upload_count AS free_download_record_upload_count, free_download_record.downloading_count AS free_download_record_downloading_count, free_download_record.download_count AS free_download_record_download_count, free_download_record.download_volume_factor AS free_download_record_download_volume_factor, free_download_record.upload_volume_factor AS free_download_record_upload_volume_factor, free_download_record.minimum_ratio AS free_download_record_minimum_ratio, free_download_record.minimum_seed_time AS free_download_record_minimum_seed_time, free_download_record.free_deadline AS free_download_record_free_deadline, free_download_record.torrent_hash AS free_download_record_torrent_hash, free_download_record.delete_status AS free_download_record_delete_status 
FROM free_download_record 
WHERE free_download_record.id = ?]
[parameters: (7988,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by pofey** [comment]
把配置目录放到稳定的硬盘存储区就好了
