### ISSUE TITLE
[缺陷]: 本地资源整理，剧集整理失败

### ISSUE THREAD

**Issue by xmumeyu** [pofey/movie_robot#597]
### 当前程序版本

beta 1.1.3

### 问题描述

本地资源整理，类别为电影时，整理功能可以正常使用
类别为剧集时，整理失败，试过动画、剧集、综艺等均如此
版本从1.0正式版和1.0之后的beta的多个版本都试过
报错完全一致，均为
2022/08/17 17:53:25 - Thread-90 - INFO: 完成剧集 黑袍纠察队 的NFO文件生成，路径：/hometheater1/media1/tv/黑袍纠察队 (2019) [tmdbid=76479]/tvshow.nfo
2022/08/17 17:53:35 - Thread-90 - ERROR: 整理失败：expected str, bytes or os.PathLike object, not int
Traceback (most recent call last):
  File "yee/media/link/medialink.py", line 190, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 126, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 364, in yee.media.link.tvlink.TvLink.__handle__
  File "yee/media/link/tvlink.py", line 92, in yee.media.link.tvlink.TvLink.link_tv_season_folder
  File "yee/media/link/tvlink.py", line 244, in yee.media.link.tvlink.TvLink.__create_episode_nfo__
  File "/usr/local/lib/python3.8/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not int

### 重现步骤

打开 本地资源整理， 选择剧集，选择源目录和目标目录，确认两目录的权限均正常，全选剧，点击识别整理，报错。
识别程序的结果：目标文件夹已生成，nfo已生成，Season x文件夹内无视频文件

![QQ截图20220817180330](https://user-images.githubusercontent.com/92902322/185093451-a9410a7b-4aba-4834-926e-d7f7209f31c2.png)
![QQ截图20220817180344](https://user-images.githubusercontent.com/92902322/185093458-77314b69-dc60-4789-85ee-11bd840ec618.png)
![QQ截图20220817180536](https://user-images.githubusercontent.com/92902322/185093464-64d134d5-196c-4c31-8896-bda3e71e8d3c.png)
![QQ截图20220817180744](https://user-images.githubusercontent.com/92902322/185093469-faa78b3a-352d-415e-9f1f-398d79443e14.png)
![QQ截图20220817180833](https://user-images.githubusercontent.com/92902322/185093473-12e6fb48-63c3-4bba-b1d8-8ec9606955f9.png)

### 发生问题时系统日志

```shell
2022/08/17 17:50:23 - Thread-90 - INFO: 完成剧集 英雄联盟：双城之战 的NFO文件生成，路径：/hometheater1/media1/tv/英雄联盟：双城之战 (2021) [tmdbid=94605]/tvshow.nfo
2022/08/17 17:50:29 - Thread-90 - INFO: 完成剧集 第1季 季 1 的NFO文件生成，路径：/hometheater1/media1/tv/英雄联盟：双城之战 (2021) [tmdbid=94605]/Season 1/season.nfo
2022/08/17 17:50:31 - Thread-90 - ERROR: 整理失败：expected str, bytes or os.PathLike object, not int
Traceback (most recent call last):
  File "yee/media/link/medialink.py", line 190, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 126, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 364, in yee.media.link.tvlink.TvLink.__handle__
  File "yee/media/link/tvlink.py", line 92, in yee.media.link.tvlink.TvLink.link_tv_season_folder
  File "yee/media/link/tvlink.py", line 244, in yee.media.link.tvlink.TvLink.__create_episode_nfo__
  File "/usr/local/lib/python3.8/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not int
2022/08/17 17:50:33 - Thread-90 - INFO: 完成剧集 黑镜 的NFO文件生成，路径：/hometheater1/media1/tv/黑镜 (2011) [tmdbid=42009]/tvshow.nfo
2022/08/17 17:50:38 - Thread-90 - INFO: 完成剧集 第2季 季 2 的NFO文件生成，路径：/hometheater1/media1/tv/黑镜 (2011) [tmdbid=42009]/Season 2/season.nfo
2022/08/17 17:50:40 - Thread-90 - ERROR: 整理失败：expected str, bytes or os.PathLike object, not int
Traceback (most recent call last):
  File "yee/media/link/medialink.py", line 190, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 126, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 364, in yee.media.link.tvlink.TvLink.__handle__
  File "yee/media/link/tvlink.py", line 92, in yee.media.link.tvlink.TvLink.link_tv_season_folder
  File "yee/media/link/tvlink.py", line 244, in yee.media.link.tvlink.TvLink.__create_episode_nfo__
  File "/usr/local/lib/python3.8/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not int
2022/08/17 17:50:41 - Thread-90 - INFO: 完成剧集 猎鹰与冬兵 的NFO文件生成，路径：/hometheater1/media1/tv/猎鹰与冬兵 (2021) [tmdbid=88396]/tvshow.nfo
2022/08/17 17:50:49 - Thread-90 - ERROR: 整理失败：expected str, bytes or os.PathLike object, not int
Traceback (most recent call last):
  File "yee/media/link/medialink.py", line 190, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 126, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 364, in yee.media.link.tvlink.TvLink.__handle__
  File "yee/media/link/tvlink.py", line 92, in yee.media.link.tvlink.TvLink.link_tv_season_folder
  File "yee/media/link/tvlink.py", line 244, in yee.media.link.tvlink.TvLink.__create_episode_nfo__
  File "/usr/local/lib/python3.8/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not int
2022/08/17 17:53:25 - Thread-90 - INFO: 完成剧集 黑袍纠察队 的NFO文件生成，路径：/hometheater1/media1/tv/黑袍纠察队 (2019) [tmdbid=76479]/tvshow.nfo
2022/08/17 17:53:35 - Thread-90 - ERROR: 整理失败：expected str, bytes or os.PathLike object, not int
Traceback (most recent call last):
  File "yee/media/link/medialink.py", line 190, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 126, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 364, in yee.media.link.tvlink.TvLink.__handle__
  File "yee/media/link/tvlink.py", line 92, in yee.media.link.tvlink.TvLink.link_tv_season_folder
  File "yee/media/link/tvlink.py", line 244, in yee.media.link.tvlink.TvLink.__create_episode_nfo__
  File "/usr/local/lib/python3.8/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not int
```

### 健康检查

![网页捕获_17-8-2022_18143_192 168 20 46](https://user-images.githubusercontent.com/92902322/185092292-05382c3c-87d2-4831-88f5-306676344905.jpeg)

**Comment by pofey** [comment]
你给转移设置的模版是什么呢，剧集的

**Comment by xmumeyu** [comment]
识别和整理设置是默认的，没改动
![网页捕获_17-8-2022_18579_192 168 20 46](https://user-images.githubusercontent.com/92902322/185102250-b1056460-91d9-4877-92ae-4776fcc1c44c.jpeg)

**Comment by pofey** [comment]
做了个兼容，等下一版测试吧

**Comment by xmumeyu** [comment]
ok，收到。

**Comment by xmumeyu** [comment]
最新的1.1.6 错误提示变了，
2022/08/20 22:01:23 - Thread-94 - INFO: 完成剧集 第 1 集(2014) 第风骚律师 S02E01季第1集的NFO文件生成，路径：/hometheater1/media1/tv/风骚律师 (2015) [tmdbid=60059]/Season 2/2.nfo
2022/08/20 22:01:23 - Thread-94 - ERROR: 下载剧集集数图片失败
Traceback (most recent call last):
  File "yee/media/link/tvlink.py", line 291, in yee.media.link.tvlink.TvLink.__create_episode_nfo__
  File "yee/metadata/scraper.py", line 207, in yee.metadata.scraper.Scraper.download_image
  File "/usr/local/lib/python3.8/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not int
2022/08/20 22:01:23 - Thread-94 - ERROR: ffmpeg解码失败：/hometheater1/media1/tv/风骚律师 (2015) [tmdbid=60059]/Season 2/2
Traceback (most recent call last):
  File "yee/media/link/tvlink.py", line 279, in yee.media.link.tvlink.TvLink.__create_episode_nfo__
  File "yee/media/videofileinfo.py", line 19, in yee.media.videofileinfo.VideoFileInfo.__init__
  File "/dependencies/ffmpeg/_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1639, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType

源文件
![QQ截图20220820220403](https://user-images.githubusercontent.com/92902322/185749963-2e62ea3b-8b92-476c-8cbb-1516d1831565.png)
整理后的目录内容
![QQ截图20220820220338](https://user-images.githubusercontent.com/92902322/185749981-f1ac272f-7ccc-4e08-b3c8-311631162b49.png)
