### ISSUE TITLE
[缺陷]: 下载胆小鬼整理时报错

### ISSUE THREAD

**Issue by happyhaha1** [pofey/movie_robot#598]
### 当前程序版本

1.1.3

### 问题描述

下载胆小鬼1-5集
![image](https://user-images.githubusercontent.com/10184254/185145163-095685b2-aa0c-4664-bdaa-f74e42a297b6.png)
自动整理时时候报错

### 重现步骤

1.订阅胆小鬼
2.下载胆小鬼
3.下载完成后整理报错

### 发生问题时系统日志

```shell
2022/08/17 21:21:45 - Thread-64 - INFO: 开始自动用TMDB数据搜索豆瓣数据
2022/08/17 21:21:45 - Thread-64 - INFO: 成功从CMDB取得TMDB编号207712对应的ID映射关系：{'mediaType': 'TV', 'doubanId': 34429670, 'doubanSeasonNumber': 1, 'tmdbId': 207712, 'imdbId': 'tt18382378', 'tvdbId': None}
2022/08/17 21:21:45 - Thread-64 - ERROR: 请求出错：local variable 'douban_meta' referenced before assignment
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 34, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/downloadcontroller.py", line 243, in yee.controller.downloadcontroller.reanalyse
  File "yee/service/downloadservice.py", line 288, in yee.service.downloadservice.DownloadService.analyze_and_setmodel
  File "yee/metadata/mediarecognize.py", line 445, in yee.metadata.mediarecognize.MediaRecognize.recognize_tv
  File "yee/metadata/mediarecognize.py", line 386, in yee.metadata.mediarecognize.MediaRecognize.tmdb_to_douban
UnboundLocalError: local variable 'douban_meta' referenced before assignment
```

### 健康检查

![Uploading image.png…]()

**Comment by pofey** [comment]
下一版修复
