### ISSUE TITLE
[缺陷]: 普通用户无法搜索

### ISSUE THREAD

**Issue by bjgetite** [pofey/movie_robot#602]
### 当前程序版本

1.0.0

### 问题描述

普通用户搜索点击无反应，回车也没反应，f12日志报错，看和豆瓣相关，给该用户设置了豆瓣id后依然不行，把该用户设置为管理员后搜索正常。

### 重现步骤

1.添加普通用户
2.普通用户登录并搜索电影，搜索无反应
3.把普通用户设置为管理员，搜索正常

### 发生问题时系统日志

```shell
前端日志：
11.efa5d7b3.chunk.js:2 
 Uncaught TypeError: Cannot read properties of undefined (reading 'searchDouban')
    at s (13.9262a22d.chunk.js:2:54590)
    at onKeyUp (13.9262a22d.chunk.js:2:55145)
    at Object.Ht (11.efa5d7b3.chunk.js:2:960111)
    at Gt (11.efa5d7b3.chunk.js:2:960265)
    at 11.efa5d7b3.chunk.js:2:978490
    at jr (11.efa5d7b3.chunk.js:2:978584)
    at Ar (11.efa5d7b3.chunk.js:2:978999)
    at 11.efa5d7b3.chunk.js:2:984640
    at Nt (11.efa5d7b3.chunk.js:2:1060317)
    at 11.efa5d7b3.chunk.js:2:980460
```

### 健康检查

无

**Comment by pofey** [comment]
升级啊
