### ISSUE TITLE
[缺陷]: 下载电影资源后无法显示下载记录

### ISSUE THREAD

**Issue by wensiwei** [pofey/movie_robot#606]
### 当前程序版本

1.1.1

### 问题描述

下载电影资源后无法显示下载记录

### 重现步骤

1、搜索资源
2、选择种子下载
3、提示成功
4、查看日志如图

### 发生问题时系统日志

```shell
date	stream	content
2022-08-18T15:34:13.642840504Z	stdout	(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-08-18T15:34:13.642795848Z	stdout	[parameters: ('2022-08-18 23:34:13', '', 'download_client', "Hachiko A Dog's Story 2010 Repack BDRip 1080p Hi10P DTS-HD MA5.1-HDTime", 0, 'Movie', 'HDTime', 716, "Hachiko.A.Dog's.Story.2010.Repack.BDRip.1080p.Hi10P.DTS-HD.MA5.1-HDTime", '', 'fb2724fe9a24ab7f46dd9d628da55aa00f9812a9', 0, None, None, '', '/video/link/movie', '1', None, '', '', 'https://hdtime.org/details.php?id=716&hit=1', 0)]
2022-08-18T15:34:13.642759048Z	stdout	[SQL: INSERT INTO download_record (gmt_create, source_id, source_type, movie_name, movie_year, movie_type, site_name, torrent_id, torrent_name, torrent_subject, torrent_hash, download_status, season_index, season_year, episodes, link_path, user_id, thumb_image_url, "desc", sub_id, torrent_url, better_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
2022-08-18T15:34:13.642728090Z	stdout	sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: download_record.thumb_image_url
2022-08-18T15:34:13.642702538Z	stdout	    cursor.execute(statement, parameters)
2022-08-18T15:34:13.642676632Z	stdout	  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
2022-08-18T15:34:13.642653088Z	stdout	    self.dialect.do_execute(
2022-08-18T15:34:13.642626725Z	stdout	  File "/dependencies/sqlalchemy/engine/base.py", line 1819, in _execute_context
2022-08-18T15:34:13.642603657Z	stdout	    raise exception
2022-08-18T15:34:13.642577763Z	stdout	  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
2022-08-18T15:34:13.642550361Z	stdout	    util.raise_(
2022-08-18T15:34:13.642523196Z	stdout	  File "/dependencies/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
2022-08-18T15:34:13.642499364Z	stdout	    self._handle_dbapi_exception(
2022-08-18T15:34:13.642461470Z	stdout	  File "/dependencies/sqlalchemy/engine/base.py", line 1862, in _execute_context
2022-08-18T15:34:13.642436171Z	stdout	    ret = self._execute_context(
2022-08-18T15:34:13.642393495Z	stdout	  File "/dependencies/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
2022-08-18T15:34:13.642364703Z	stdout	    return connection._execute_clauseelement(
2022-08-18T15:34:13.642336079Z	stdout	  File "/dependencies/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
2022-08-18T15:34:13.642306982Z	stdout	    return meth(self, args_10style, kwargs_10style, execution_options)
2022-08-18T15:34:13.642280445Z	stdout	  File "/dependencies/sqlalchemy/engine/base.py", line 1631, in _execute_20
2022-08-18T15:34:13.642254639Z	stdout	    result = connection._execute_20(
2022-08-18T15:34:13.642227106Z	stdout	  File "/dependencies/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
2022-08-18T15:34:13.642201159Z	stdout	    _emit_insert_statements(
2022-08-18T15:34:13.642173501Z	stdout	  File "/dependencies/sqlalchemy/orm/persistence.py", line 245, in save_obj
2022-08-18T15:34:13.642145677Z	stdout	    util.preloaded.orm_persistence.save_obj(
2022-08-18T15:34:13.642119017Z	stdout	  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 630, in execute
2022-08-18T15:34:13.642094823Z	stdout	    rec.execute(self)
2022-08-18T15:34:13.642067165Z	stdout	  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 456, in execute
2022-08-18T15:34:13.642043841Z	stdout	    flush_context.execute()
2022-08-18T15:34:13.642017560Z	stdout	  File "/dependencies/sqlalchemy/orm/session.py", line 3483, in _flush
2022-08-18T15:34:13.641994241Z	stdout	    raise exception
2022-08-18T15:34:13.641968144Z	stdout	  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
2022-08-18T15:34:13.641944378Z	stdout	    compat.raise_(
2022-08-18T15:34:13.641916680Z	stdout	  File "/dependencies/sqlalchemy/util/langhelpers.py", line 70, in __exit__
2022-08-18T15:34:13.641890283Z	stdout	    transaction.rollback(_capture_exception=True)
2022-08-18T15:34:13.641863734Z	stdout	  File "/dependencies/sqlalchemy/orm/session.py", line 3523, in _flush
2022-08-18T15:34:13.641839999Z	stdout	    self._flush(objects)
2022-08-18T15:34:13.641813362Z	stdout	  File "/dependencies/sqlalchemy/orm/session.py", line 3383, in flush
2022-08-18T15:34:13.641789595Z	stdout	    self.session.flush()
2022-08-18T15:34:13.641762357Z	stdout	  File "/dependencies/sqlalchemy/orm/session.py", line 808, in _prepare_impl
2022-08-18T15:34:13.641737400Z	stdout	    self._prepare_impl()
2022-08-18T15:34:13.641708196Z	stdout	  File "/dependencies/sqlalchemy/orm/session.py", line 829, in commit
2022-08-18T15:34:13.641678333Z	stdout	    self._transaction.commit(_to_root=self.future)
2022-08-18T15:34:13.641641085Z	stdout	  File "/dependencies/sqlalchemy/orm/session.py", line 1451, in commit
2022-08-18T15:34:13.641614216Z	stdout	  File "<string>", line 2, in commit
2022-08-18T15:34:13.641585471Z	stdout	  File "yee/common/basemodel.py", line 85, in yee.common.basemodel.BaseModel.save
2022-08-18T15:34:13.641547600Z	stdout	  File "yee/common/basemodel.py", line 88, in yee.common.basemodel.BaseModel.save
2022-08-18T15:34:13.641516810Z	stdout	  File "yee/service/downloadservice.py", line 548, in yee.service.downloadservice.DownloadService.download_from_web
2022-08-18T15:34:13.641481276Z	stdout	  File "yee/task/consumer/downloadconsumer.py", line 29, in yee.task.consumer.downloadconsumer.DownloadConsumer.run
2022-08-18T15:34:13.641442869Z	stdout	Traceback (most recent call last):
2022-08-18T15:34:13.641415689Z	stdout	
2022-08-18T15:34:13.641384375Z	stdout	The above exception was the direct cause of the following exception:
2022-08-18T15:34:13.641359628Z	stdout	
2022-08-18T15:34:13.641332620Z	stdout	sqlite3.IntegrityError: NOT NULL constraint failed: download_record.thumb_image_url
2022-08-18T15:34:13.641305639Z	stdout	    cursor.execute(statement, parameters)
2022-08-18T15:34:13.641276605Z	stdout	  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
2022-08-18T15:34:13.641249997Z	stdout	    self.dialect.do_execute(
2022-08-18T15:34:13.641204708Z	stdout	  File "/dependencies/sqlalchemy/engine/base.py", line 1819, in _execute_context
2022-08-18T15:34:13.641172396Z	stdout	Traceback (most recent call last):
2022-08-18T15:34:13.641135519Z	stdout	(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-08-18T15:34:13.640983432Z	stdout	[parameters: ('2022-08-18 23:34:13', '', 'download_client', "Hachiko A Dog's Story 2010 Repack BDRip 1080p Hi10P DTS-HD MA5.1-HDTime", 0, 'Movie', 'HDTime', 716, "Hachiko.A.Dog's.Story.2010.Repack.BDRip.1080p.Hi10P.DTS-HD.MA5.1-HDTime", '', 'fb2724fe9a24ab7f46dd9d628da55aa00f9812a9', 0, None, None, '', '/video/link/movie', '1', None, '', '', 'https://hdtime.org/details.php?id=716&hit=1', 0)]
2022-08-18T15:34:13.640918869Z	stdout	[SQL: INSERT INTO download_record (gmt_create, source_id, source_type, movie_name, movie_year, movie_type, site_name, torrent_id, torrent_name, torrent_subject, torrent_hash, download_status, season_index, season_year, episodes, link_path, user_id, thumb_image_url, "desc", sub_id, torrent_url, better_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
2022-08-18T15:34:13.640759779Z	stdout	2022/08/18 23:34:13 - HDTime-downloader - ERROR: 处理下载任务失败：(sqlite3.IntegrityError) NOT NULL constraint failed: download_record.thumb_image_url
2022-08-18T15:34:12.772321736Z	stdout	2022/08/18 23:34:12 - HDTime-downloader - INFO: 开始处理来自Web的下载: [HDTime]Hachiko A Dog's Story 2010 Repack BDRip 1080p Hi10P DTS-HD MA5.1-HDTime
2022-08-18T15:33:54.982014323Z	stdout	2022/08/18 23:33:54 - Thread-112 - INFO: 共在1个站点搜索到3条结果，其中高清时间最慢，耗费3.92秒
2022-08-18T15:33:51.061950572Z	stdout	2022/08/18 23:33:51 - Thread-112 - INFO: 已经开始在站点: 高清时间 搜索: 忠犬八公的故事
```

### 健康检查

暂无

**Comment by pofey** [comment]
重复问题了 beta解决了 等合并吧

**Comment by pofey** [comment]
> 所以现在怎么解决呢，没记录不能移动/硬链 @pofey

等着
