### ISSUE TITLE
[缺陷]: 下载资源后，因为权限问题无法移动文件目录，随后再qbittorrent删除资源，并且在记录中也删除，随后疯狂刷日志

### ISSUE THREAD

**Issue by wensiwei** [pofey/movie_robot#607]
### 当前程序版本

1.1.1

### 问题描述

载资源后，无法移动文件目录，随后再qbittorrent删除资源，并且在记录中也删除，随后疯狂刷日志，文件已经都不存在应该需要删除掉定时任务中的对应项

### 重现步骤

1、下载资源
2、提示文件转移失败：找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
3、删除记录和资源
4、疯狂刷日志

### 发生问题时系统日志

```shell
2022-08-18T12:45:00.020225701Z	stdout	2022/08/18 20:45:00 - ThreadPoolExecutor-4_2 - ERROR: 文件转移失败：找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:44:00.021981918Z	stdout	FileNotFoundError: 找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:44:00.021951986Z	stdout	  File "yee/media/link/medialink.py", line 92, in yee.media.link.medialink.MediaLink.__init__
2022-08-18T12:44:00.021918673Z	stdout	  File "yee/media/link/movielink.py", line 24, in yee.media.link.movielink.MovieLink.__init__
2022-08-18T12:44:00.021882474Z	stdout	  File "yee/service/filemanagerservice.py", line 69, in yee.service.filemanagerservice.FileManagerService.link
2022-08-18T12:44:00.021849616Z	stdout	  File "yee/service/downloadservice.py", line 385, in yee.service.downloadservice.DownloadService.download_completed
2022-08-18T12:44:00.021771013Z	stdout	  File "yee/service/downloadservice.py", line 407, in yee.service.downloadservice.DownloadService.download_completed
2022-08-18T12:44:00.021730413Z	stdout	  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
2022-08-18T12:44:00.021697365Z	stdout	Traceback (most recent call last):
2022-08-18T12:44:00.021625163Z	stdout	2022/08/18 20:44:00 - ThreadPoolExecutor-4_0 - ERROR: 监控种子任务出现错误：找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:44:00.020781254Z	stdout	2022/08/18 20:44:00 - ThreadPoolExecutor-4_0 - ERROR: 文件转移失败：找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:43:00.020708195Z	stdout	FileNotFoundError: 找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:43:00.020679566Z	stdout	  File "yee/media/link/medialink.py", line 92, in yee.media.link.medialink.MediaLink.__init__
2022-08-18T12:43:00.020647971Z	stdout	  File "yee/media/link/movielink.py", line 24, in yee.media.link.movielink.MovieLink.__init__
2022-08-18T12:43:00.020616200Z	stdout	  File "yee/service/filemanagerservice.py", line 69, in yee.service.filemanagerservice.FileManagerService.link
2022-08-18T12:43:00.020586135Z	stdout	  File "yee/service/downloadservice.py", line 385, in yee.service.downloadservice.DownloadService.download_completed
2022-08-18T12:43:00.020551702Z	stdout	  File "yee/service/downloadservice.py", line 407, in yee.service.downloadservice.DownloadService.download_completed
2022-08-18T12:43:00.020508946Z	stdout	  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
2022-08-18T12:43:00.020463025Z	stdout	Traceback (most recent call last):
2022-08-18T12:43:00.020393055Z	stdout	2022/08/18 20:43:00 - ThreadPoolExecutor-4_2 - ERROR: 监控种子任务出现错误：找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:43:00.019555026Z	stdout	2022/08/18 20:43:00 - ThreadPoolExecutor-4_2 - ERROR: 文件转移失败：找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:42:00.021583475Z	stdout	FileNotFoundError: 找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:42:00.021553056Z	stdout	  File "yee/media/link/medialink.py", line 92, in yee.media.link.medialink.MediaLink.__init__
2022-08-18T12:42:00.021520189Z	stdout	  File "yee/media/link/movielink.py", line 24, in yee.media.link.movielink.MovieLink.__init__
2022-08-18T12:42:00.021488193Z	stdout	  File "yee/service/filemanagerservice.py", line 69, in yee.service.filemanagerservice.FileManagerService.link
2022-08-18T12:42:00.021445254Z	stdout	  File "yee/service/downloadservice.py", line 385, in yee.service.downloadservice.DownloadService.download_completed
2022-08-18T12:42:00.021410130Z	stdout	  File "yee/service/downloadservice.py", line 407, in yee.service.downloadservice.DownloadService.download_completed
2022-08-18T12:42:00.021366565Z	stdout	  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
2022-08-18T12:42:00.021331778Z	stdout	Traceback (most recent call last):
2022-08-18T12:42:00.021184850Z	stdout	2022/08/18 20:42:00 - ThreadPoolExecutor-4_0 - ERROR: 监控种子任务出现错误：找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:42:00.020120259Z	stdout	2022/08/18 20:42:00 - ThreadPoolExecutor-4_0 - ERROR: 文件转移失败：找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:41:00.021604500Z	stdout	FileNotFoundError: 找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:41:00.021574545Z	stdout	  File "yee/media/link/medialink.py", line 92, in yee.media.link.medialink.MediaLink.__init__
2022-08-18T12:41:00.021542263Z	stdout	  File "yee/media/link/movielink.py", line 24, in yee.media.link.movielink.MovieLink.__init__
2022-08-18T12:41:00.021509964Z	stdout	  File "yee/service/filemanagerservice.py", line 69, in yee.service.filemanagerservice.FileManagerService.link
2022-08-18T12:41:00.021477368Z	stdout	  File "yee/service/downloadservice.py", line 385, in yee.service.downloadservice.DownloadService.download_completed
2022-08-18T12:41:00.021430040Z	stdout	  File "yee/service/downloadservice.py", line 407, in yee.service.downloadservice.DownloadService.download_completed
2022-08-18T12:41:00.021389141Z	stdout	  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
2022-08-18T12:41:00.021354605Z	stdout	Traceback (most recent call last):
2022-08-18T12:41:00.021285619Z	stdout	2022/08/18 20:41:00 - ThreadPoolExecutor-4_2 - ERROR: 监控种子任务出现错误：找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:41:00.020246184Z	stdout	2022/08/18 20:41:00 - ThreadPoolExecutor-4_2 - ERROR: 文件转移失败：找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:40:00.021265767Z	stdout	FileNotFoundError: 找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:40:00.021236138Z	stdout	  File "yee/media/link/medialink.py", line 92, in yee.media.link.medialink.MediaLink.__init__
2022-08-18T12:40:00.021204000Z	stdout	  File "yee/media/link/movielink.py", line 24, in yee.media.link.movielink.MovieLink.__init__
2022-08-18T12:40:00.021170387Z	stdout	  File "yee/service/filemanagerservice.py", line 69, in yee.service.filemanagerservice.FileManagerService.link
2022-08-18T12:40:00.021138743Z	stdout	  File "yee/service/downloadservice.py", line 385, in yee.service.downloadservice.DownloadService.download_completed
2022-08-18T12:40:00.021100227Z	stdout	  File "yee/service/downloadservice.py", line 407, in yee.service.downloadservice.DownloadService.download_completed
2022-08-18T12:40:00.021060269Z	stdout	  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
2022-08-18T12:40:00.021023844Z	stdout	Traceback (most recent call last):
2022-08-18T12:40:00.020948159Z	stdout	2022/08/18 20:40:00 - ThreadPoolExecutor-4_0 - ERROR: 监控种子任务出现错误：找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:40:00.019862949Z	stdout	2022/08/18 20:40:00 - ThreadPoolExecutor-4_0 - ERROR: 文件转移失败：找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:39:00.101332104Z	stdout	FileNotFoundError: 找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:39:00.101233514Z	stdout	  File "yee/media/link/medialink.py", line 92, in yee.media.link.medialink.MediaLink.__init__
2022-08-18T12:39:00.101199132Z	stdout	  File "yee/media/link/movielink.py", line 24, in yee.media.link.movielink.MovieLink.__init__
2022-08-18T12:39:00.101163288Z	stdout	  File "yee/service/filemanagerservice.py", line 69, in yee.service.filemanagerservice.FileManagerService.link
2022-08-18T12:39:00.101130147Z	stdout	  File "yee/service/downloadservice.py", line 385, in yee.service.downloadservice.DownloadService.download_completed
2022-08-18T12:39:00.101097094Z	stdout	  File "yee/service/downloadservice.py", line 407, in yee.service.downloadservice.DownloadService.download_completed
2022-08-18T12:39:00.101055213Z	stdout	  File "yee/task/monitortorrenttask.py", line 55, in yee.task.monitortorrenttask.MonitorTorrentTask.run
2022-08-18T12:39:00.101020063Z	stdout	Traceback (most recent call last):
2022-08-18T12:39:00.100843241Z	stdout	2022/08/18 20:39:00 - ThreadPoolExecutor-4_2 - ERROR: 监控种子任务出现错误：找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:39:00.037507853Z	stdout	2022/08/18 20:39:00 - ThreadPoolExecutor-4_2 - ERROR: 文件转移失败：找不到内容路径或无权限访问：/video/movie/飞屋环游记.Up.2009.UHD.BluRay.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS
2022-08-18T12:37:07.816009634Z	stdout	2022/08/18 20:37:07 - ThreadPoolExecutor-4_2 - INFO: 没有配置或开启流量管理设置，不会开始运行：{'avg_statistics_period': 5, 'enable': False}
2022-08-18T12:37:07.802622942Z	stdout	2022/08/18 20:37:07 - ThreadPoolExecutor-4_2 - INFO: 没有任何订阅记录需要进行智能下载。
2022-08-18T12:37:07.729255651Z	stdout	2022/08/18 20:37:07 - ThreadPoolExecutor-4_2 - INFO: 所有站点资源信息已经更新完毕。
2022-08-18T12:35:45.036631554Z	stdout	2022/08/18 20:35:45 - ThreadPoolExecutor-4_2 - INFO: 高清时间拉取种子超时，请耐心等待...
2022-08-18T12:34:45.034876154Z	stdout	2022/08/18 20:34:44 - ThreadPoolExecutor-4_2 - INFO: 开始同步站点资源信息...
2022-08-18T12:15:05.794917626Z	stdout	2022/08/18 20:15:05 - ThreadPoolExecutor-4_4 - INFO: 没有配置或开启流量管理设置，不会开始运行：{'avg_statistics_period': 5, 'enable': False}
2022-08-18T12:15:05.765906480Z	stdout	2022/08/18 20:15:05 - ThreadPoolExecutor-4_4 - INFO: 没有任何订阅记录需要进行智能下载。
2022-08-18T12:15:05.722880975Z	stdout	2022/08/18 20:15:05 - ThreadPoolExecutor-4_4 - INFO: 所有站点资源信息已经更新完毕。
2022-08-18T12:13:57.788616652Z	stdout	2022/08/18 20:13:57 - ThreadPoolExecutor-4_4 - INFO: 开始同步站点资源信息...
2022-08-18T12:13:50.463261310Z	stdout	2022/08/18 20:13:50 - HDTime-downloader - INFO: 成功从CMDB取得TMDB编号14160对应的ID映射关系：{'mediaType': 'Movie', 'doubanId': 2129039, 'doubanSeasonNumber': None, 'tmdbId': 14160, 'imdbId': 'tt1049413', 'tvdbId': None}
2022-08-18T12:13:50.351759731Z	stdout	2022/08/18 20:13:50 - HDTime-downloader - INFO: 开始自动用TMDB数据搜索豆瓣数据
2022-08-18T12:13:35.373589535Z	stdout	2022/08/18 20:13:35 - HDTime-downloader - INFO: 开始处理来自Web的下载: [HDTime]Up 2009 2160p UHD BluRay x265 10bit HDR 4Audios mUHD-FRDS
2022-08-18T12:13:22.689712319Z	stdout	2022/08/18 20:13:22 - Thread-74 - INFO: 共在1个站点搜索到6条结果，其中高清时间最慢，耗费1.69秒
```

### 健康检查

暂无

**Comment by pofey** [comment]
这个问题怎么说呢 可优化可不优化 先留着吧

**Comment by pofey** [comment]
还是决定不优化这里了，你这个操作路径，出现的可能性太低，而且目前你把下载记录删了，他也就不会再处理了。
对有些人来说，如果真的是权限没搞好，修复权限后，现在的逻辑还能保证自动去充实。
