### ISSUE TITLE
[提问]: 某部剧集订阅出错

### ISSUE THREAD

**Issue by lalakers1986** [pofey/movie_robot#615]
### 当前程序版本

1.1.1

### 问题

其他订阅都正常，只有这部she hulk订阅时出错
重启container后也出错=0=
（log在下面 麻烦看看是哪里出现了问题 谢谢衣总

### 发生问题时系统日志

```shell
2022/08/20 20:21:09 - SubRequestConsumer - INFO: 成功从CMDB取得豆瓣编号34803800对应的ID映射关系：{'mediaType': 'TV', 'doubanId': 34803800, 'doubanSeasonNumber': 1, 'tmdbId': 92783, 'imdbId': 'tt10857160', 'tvdbId': 368613}
2022/08/20 20:23:21 - SubRequestConsumer - ERROR: douban_id: 34803800 订阅失败，请查看日志分析原因。
Traceback (most recent call last):
  File "yee/service/smartdownloadservice.py", line 317, in yee.service.smartdownloadservice.SmartDownloadService.sub_from_douban
  File "yee/service/smartdownloadservice.py", line 53, in yee.service.smartdownloadservice.SmartDownloadService.exists
  File "yee/service/smartdownloadservice.py", line 81, in yee.service.smartdownloadservice.SmartDownloadService.get_missing_episodes
  File "yee/media/server/plexmediaserver.py", line 258, in yee.media.server.plexmediaserver.PlexMediaServer.get_missing_episodes
  File "/dependencies/plexapi/library.py", line 599, in get
    return self.fetchItem(key, title__iexact=title)
  File "/dependencies/plexapi/base.py", line 176, in fetchItem
    raise NotFound('Unable to find elem: cls=%s, attrs=%s' % (clsname, kwargs))
plexapi.exceptions.NotFound: Unable to find elem: cls=None, attrs={'title__iexact': 'She-Hulk'}
```

**Comment by pofey** [comment]
plex报错 有什么其他信息可以提供？

**Comment by lalakers1986** [comment]
> plex报错 有什么其他信息可以提供？

没发现问题 不过我的plex是挂云盘的超大库 可能有问题我也找不出来 哈哈。。。
使用没啥问题 个别我就手动web下载吧～
只要知道是plex的问题就行了哈哈哈哈哈哈 那肯定是gd的问题
谢谢

**Comment by pofey** [comment]
看起来是plex里She-Hulk有问题

**Comment by lalakers1986** [comment]
没错 plex刮出来还是英文😆

yipengfei ***@***.***>于2022年8月21日 周日10:12写道：
