### ISSUE TITLE
[缺陷]: 资源下载成功，未出现微信推送，日志显示error

### ISSUE THREAD

**Issue by EasonGaoDevelop** [pofey/movie_robot#626]
### 当前程序版本

1.1.10

### 问题描述

电影资源下载成功，通知里面已开启开始下载，下载完成的通知，微信未收到推送

### 重现步骤

1、微信企业号开启电影订阅
2、微信推送已订阅成功
3、微信未收到下载的消息推送，实际电影资源已下载成功
4、查看日志有报错

### 发生问题时系统日志

```shell
已经提交下载。
2022/08/24 17:47:46 - chdbits-downloader - INFO: 开始处理来自订阅的下载: [chdbits]Child's Play 1988 2160p UHD Blu-ray HEVC TrueHD 7.1-Stars@CHDBits
2022/08/24 17:47:47 - chdbits-downloader - INFO: [chdbits]Child's Play 1988 2160p UHD Blu-ray HEVC TrueHD 7.1-Stars@CHDBits已经开始下载,路径：/downloads/Movie-Robot/download-movie/ 分类：未设置 
2022/08/24 17:47:47 - chdbits-downloader - ERROR: on_event error: NotifyListener event: <mbot.event.events.Event object at 0x149f9cf65d90>
Traceback (most recent call last):
  File "mbot/event/eventbus.py", line 44, in mbot.event.eventbus.EventBus.publish_event
  File "/app/mbot/event/listener/notifylistener.py", line 92, in on_event
    media_image: MediaImage = api_holder.get_fanart_api().get_media_image(tmdb_meta.get('id'),
AttributeError: 'NoneType' object has no attribute 'get_media_image'
2022/08/24 17:51:26 - Thread-210 - INFO: 已开启企业微信接收消息配置
2022/08/24 18:00:00 - ThreadPoolExecutor-5_1 - INFO: 开始更新媒体趋势榜单数据
2022/08/24 18:00:00 - ThreadPoolExecutor-5_4 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
2022/08/24 18:00:00 - ThreadPoolExecutor-5_3 - INFO: 内容：/Video/Movie-Robot/download-movie/Child's.Play.1988.2160p.UHD.Blu-ray.HEVC.TrueHD.7.1-Stars@CHDBits 识别为：鬼娃回魂 1988-11-08
2022/08/24 18:00:03 - ThreadPoolExecutor-5_3 - INFO: 完成电影 鬼娃回魂(1988) 的NFO文件生成，路径：/Video/Movie-Robot/robot-movie/欧美/鬼娃回魂 (1988) [tmdbid=10585]/欧美/鬼娃回魂 (1988) [tmdbid=10585] - 2160p HEVC TrueHD CHD/BDMV/index.nfo
2022/08/24 18:00:10 - ThreadPoolExecutor-5_3 - ERROR: TMDB ID: 10585没有找到在影音库的对应媒体库，路径: /Video/Movie-Robot/robot-movie/欧美/鬼娃回魂 (1988) [tmdbid=10585]/欧美
2022/08/24 18:00:10 - ThreadPoolExecutor-5_3 - INFO: 鬼娃回魂(1988)字幕下载 任务已经创建。
2022/08/24 18:00:10 - ThreadPoolExecutor-5_3 - ERROR: on_event error: NotifyListener event: <mbot.event.events.Event object at 0x149f9c8fdcd0>
```

### 健康检查

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/12585454/186394121-87622b8c-901f-4bf9-a4e7-fc8fea9765ee.png">

**Comment by pofey** [comment]
没配置fanart
