### ISSUE TITLE
[缺陷]: 建议添加FlareSolverr来进行站点访问

### ISSUE THREAD

**Issue by haig233** [pofey/movie_robot#632]
### 当前程序版本

1.1.1

### 问题描述

建议使用FlareSolverr来进行站点信息获取，因为部分站点使用了Cloudflare五秒盾，有时候的cookie信息里面的CF盾cookie已经过期，程序爬取的时候会撞到五秒盾上导致登录/获取信息失败。
https://github.com/FlareSolverr/FlareSolverr

### 重现步骤

添加学校站点时

### 发生问题时系统日志

```shell
Traceback (most recent call last):
  File "yee/controller/sitecontroller.py", line 33, in yee.controller.sitecontroller.save_site
  File "yee/service/siteservice.py", line 397, in yee.service.siteservice.SiteService.set_site
  File "yee/site/sitehelper.py", line 180, in yee.site.sitehelper.SiteHelper.get_userinfo
  File "yee/site/siteparser.py", line 29, in yee.site.siteparser.SiteParser.parse_userinfo
yee.site.siteexceptions.LoginRequired: 学校登陆失败！
2022/08/25 17:48:08 - Thread-81 - ERROR: 站点设置失败：学校登陆失败！
Traceback (most recent call last):
  File "yee/controller/sitecontroller.py", line 33, in yee.controller.sitecontroller.save_site
  File "yee/service/siteservice.py", line 397, in yee.service.siteservice.SiteService.set_site
  File "yee/site/sitehelper.py", line 180, in yee.site.sitehelper.SiteHelper.get_userinfo
  File "yee/site/siteparser.py", line 29, in yee.site.siteparser.SiteParser.parse_userinfo
yee.site.siteexceptions.LoginRequired: 学校登陆失败！
```

### 健康检查

![image](https://user-images.githubusercontent.com/25719719/186634065-6416f975-fe59-47cf-bcf6-2a61dd486c6e.png)

**Comment by pofey** [comment]
删了学校
