### ISSUE TITLE
[BUG]1.11版本企业微信搜索影片失败

### ISSUE THREAD

**Issue by jayling1111** [pofey/movie_robot#634]

**Comment by jayling1111** [comment]
2022/08/25 23:30:31 - Thread-392 - ERROR: 处理微信消息出错。
Traceback (most recent call last):
  File "mbot/controller/qywxcontroller.py", line 126, in mbot.controller.qywxcontroller.receive
AttributeError: 'NoneType' object has no attribute 'text'
 2022/08/25 23:30:31 - Thread-393 - ERROR: 处理微信消息出错。
Traceback (most recent call last):
  File "mbot/controller/qywxcontroller.py", line 126, in mbot.controller.qywxcontroller.receive
AttributeError: 'NoneType' object has no attribute 'text'
 2022/08/25 23:30:33 - qywx-search - ERROR: 企业微信搜索失败：'NoneType' object is not iterable
Traceback (most recent call last):
  File "mbot/controller/qywxcontroller.py", line 49, in mbot.controller.qywxcontroller.QywxSearchThread.run
TypeError: 'NoneType' object is not iterable
 2022/08/25 23:30:46 - qywx-search - ERROR: 企业微信搜索失败：'NoneType' object is not iterable
Traceback (most recent call last):
  File "mbot/controller/qywxcontroller.py", line 49, in mbot.controller.qywxcontroller.QywxSearchThread.run
TypeError: 'NoneType' object is not iterable
