### ISSUE TITLE
[缺陷]: 最新版本微信通知问题

### ISSUE THREAD

**Issue by CloudEnjoy** [pofey/movie_robot#661]
### 当前程序版本

1.2.1

### 问题描述

上个版本微信通知正常，然后升级到新版本1.2.1微信通知没法通知。

### 重现步骤

上个版本微信通知设置好了的，也能正常通知。然后升级到目前新版本1.2.1就失效了，设置没动。

### 发生问题时系统日志

```shell
2022-08-31 11:38:31	stdout	2022/08/31 19:38:31 - Thread-137 - ERROR: 推送测试消息失败：RetryError[<Future at 0x7ff42813efd0 state=finished raised UnsupportedProtocol>]
2022-08-31 11:38:23	stdout	2022/08/31 19:38:23 - Thread-140 - INFO: 已开启企业微信接收消息配置
2022-08-31 11:38:23	stdout	2022/08/31 19:38:23 - Thread-139 - INFO: 已开启企业微信接收消息配置
2022-08-31 11:38:22	stdout	2022/08/31 19:38:22 - Thread-138 - INFO: 已开启企业微信接收消息配置
2022-08-31 11:38:21	stdout	2022/08/31 19:38:20 - Thread-137 - INFO: 已开启企业微信接收消息配置
2022-08-31 11:33:17	stdout	tenacity.RetryError: RetryError[<Future at 0x7ff42813c580 state=finished raised UnsupportedProtocol>]
2022-08-31 11:33:17	stdout	    raise retry_exc from fut.exception()
2022-08-31 11:33:17	stdout	  File "/dependencies/tenacity/__init__.py", line 361, in iter
2022-08-31 11:33:17	stdout	    do = self.iter(retry_state=retry_state)
2022-08-31 11:33:17	stdout	  File "/dependencies/tenacity/__init__.py", line 404, in __call__
2022-08-31 11:33:17	stdout	    return self(f, *args, **kw)
2022-08-31 11:33:17	stdout	  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
2022-08-31 11:33:17	stdout	  File "mbot/notify/qywechat.py", line 77, in mbot.notify.qywechat.QywechatNotify.send_by_template
2022-08-31 11:33:17	stdout	  File "mbot/service/notifyservice.py", line 214, in mbot.service.notifyservice.NotifyService.send_app_message_by_template
2022-08-31 11:33:17	stdout	  File "mbot/service/notifyservice.py", line 201, in mbot.service.notifyservice.NotifyService.send_app_message_by_template_name
2022-08-31 11:33:17	stdout	  File "mbot/controller/settingcontroller.py", line 429, in mbot.controller.settingcontroller.test_notify
2022-08-31 11:33:17	stdout	Traceback (most recent call last):
2022-08-31 11:33:17	stdout	
2022-08-31 11:33:17	stdout	The above exception was the direct cause of the following exception:
2022-08-31 11:33:17	stdout	
2022-08-31 11:33:17	stdout	httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
2022-08-31 11:33:17	stdout	    raise mapped_exc(message) from exc
2022-08-31 11:33:17	stdout	  File "/dependencies/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
2022-08-31 11:33:17	stdout	    self.gen.throw(type, value, traceback)
2022-08-31 11:33:17	stdout	  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
2022-08-31 11:33:17	stdout	    resp = self._pool.handle_request(req)
2022-08-31 11:33:17	stdout	  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
2022-08-31 11:33:17	stdout	    response = transport.handle_request(request)
2022-08-31 11:33:17	stdout	  File "/dependencies/httpx/_client.py", line 990, in _send_single_request
2022-08-31 11:33:17	stdout	    response = self._send_single_request(request)
2022-08-31 11:33:17	stdout	  File "/dependencies/httpx/_client.py", line 954, in _send_handling_redirects
2022-08-31 11:33:17	stdout	    response = self._send_handling_redirects(
2022-08-31 11:33:17	stdout	  File "/dependencies/httpx/_client.py", line 917, in _send_handling_auth
2022-08-31 11:33:17	stdout	    response = self._send_handling_auth(
2022-08-31 11:33:17	stdout	  File "/dependencies/httpx/_client.py", line 889, in send
2022-08-31 11:33:17	stdout	    return self.send(request, auth=auth, follow_redirects=follow_redirects)
2022-08-31 11:33:17	stdout	  File "/dependencies/httpx/_client.py", line 802, in request
2022-08-31 11:33:17	stdout	    return client.request(
2022-08-31 11:33:17	stdout	  File "/dependencies/httpx/_api.py", line 100, in request
2022-08-31 11:33:17	stdout	    return request(
2022-08-31 11:33:17	stdout	  File "/dependencies/httpx/_api.py", line 304, in post
2022-08-31 11:33:17	stdout	  File "mbot/notify/qywechat.py", line 33, in mbot.notify.qywechat.QywechatNotify.__do_send_message__
2022-08-31 11:33:17	stdout	    result = fn(*args, **kwargs)
2022-08-31 11:33:17	stdout	  File "/dependencies/tenacity/__init__.py", line 407, in __call__
2022-08-31 11:33:17	stdout	Traceback (most recent call last):
2022-08-31 11:33:17	stdout	
2022-08-31 11:33:17	stdout	The above exception was the direct cause of the following exception:
2022-08-31 11:33:17	stdout	
2022-08-31 11:33:17	stdout	httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
2022-08-31 11:33:17	stdout	    raise UnsupportedProtocol(
2022-08-31 11:33:17	stdout	  File "/dependencies/httpcore/_sync/connection_pool.py", line 208, in handle_request
2022-08-31 11:33:17	stdout	    resp = self._pool.handle_request(req)
2022-08-31 11:33:17	stdout	  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
2022-08-31 11:33:17	stdout	    yield
2022-08-31 11:33:17	stdout	  File "/dependencies/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
2022-08-31 11:33:17	stdout	Traceback (most recent call last):
2022-08-31 11:33:17	stdout	2022/08/31 19:33:17 - Thread-119 - ERROR: 推送测试消息失败：RetryError[<Future at 0x7ff42813c580 state=finished raised UnsupportedProtocol>]
2022-08-31 11:33:06	stdout	2022/08/31 19:33:06 - Thread-119 - INFO: 已开启企业微信接收消息配置
```

### 健康检查

![Uploading 1F5B4843-06AC-44E8-9807-773DB6ABE11C.png…]()

**Comment by pofey** [comment]
配置有问题，要么截图出来，要么自己看wiki研究

**Comment by CloudEnjoy** [comment]
但是微信发送绑定用户有回应，搜索电影提示搜索中，但是无法搜索出电影。

**Comment by CloudEnjoy** [comment]
按道理微信通知配置错误不应该有回应才是。

**Comment by CloudEnjoy** [comment]
好吧，原来是没打开。
"开启Movie Robot自建代理通过白名单验证"
