### ISSUE TITLE
[提问]: 自定义关键字订阅下载后不能 硬链/复制/移动

### ISSUE THREAD

**Issue by mymoonyue** [pofey/movie_robot#662]
### 当前程序版本

1.2.13

### 问题

自定义关键字订阅**可以正常下载**，但是下载后**不能 硬链/复制/移动**，请问下这个报错是哪里的问题。

### 发生问题时系统日志

```shell
2022/09/01 08:29:27 - ThreadPoolExecutor-4_2 - INFO: 来自自定义订阅AV热门系列的资源已经提交下载，种子标题：4K 链接：https://kp.m-team.cc/details.php?id=606615&hit=1 站点：mteam 种子编号：606615 record: 0
 2022/09/01 08:29:27 - mteam-downloader - INFO: 开始处理来自Web的下载: [mteam]STARS-665 僕のお姉ちゃんは、チ〇ポしゃぶり大好き女子マネージャーです。放課後の部活終わりに誰かをこっそりフェラ誘惑して射精させまくっていて…最後は僕も誘惑されて…。 工藤ゆら
 2022/09/01 08:29:30 - mteam-downloader - ERROR: 处理下载任务失败：'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "mbot/task/consumer/downloadconsumer.py", line 29, in mbot.task.consumer.downloadconsumer.DownloadConsumer.run
  File "mbot/service/downloadservice.py", line 518, in mbot.service.downloadservice.DownloadService.download_from_web
  File "mbot/service/downloadservice.py", line 585, in mbot.service.downloadservice.DownloadService.download_from_web
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by pofey** [comment]
bug 下一版本修复
