### ISSUE TITLE
[提问]: 手动提交下载报错并且没有下载记录

### ISSUE THREAD

**Issue by mymoonyue** [pofey/movie_robot#665]
### 当前程序版本

1.3.0

### 问题

mr上手动提交了一个下载，mr报错并且没有下载记录，但是qb是下载了的下载完没有硬链

### 发生问题时系统日志

```shell
2022/09/01 20:02:14 - hdchina-downloader - INFO: 开始处理来自Web的下载: [hdchina]JoJos.Bizarre.Adventure.S05.2021.Netflix.WEB-DL.1080p.x264.DDP-HDCTV

2022/09/01 20:02:25 - hdchina-downloader - ERROR: 处理下载任务失败：(sqlite3.IntegrityError) NOT NULL constraint failed: download_record.thumb_image_url

[SQL: INSERT INTO download_record (gmt_create, source_id, douban_id, source_type, movie_name, movie_year, movie_type, site_name, torrent_id, torrent_name, torrent_subject, torrent_hash, download_status, season_index, season_year, episodes, link_path, user_id, thumb_image_url, "desc", sub_id, torrent_url, better_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]

[parameters: ('2022-09-01 20:02:15', '', None, 'download_client', 'JoJos.Bizarre.Adventure.S05.2021.Netflix.WEB-DL.1080p.x264.DDP-HDCTV', 0, 'Series', 'hdchina', 634664, 'JoJos.Bizarre.Adventure.S05.2021.Netflix.WEB-DL.1080p.x264.DDP-HDCTV', '日漫 JOJO的奇妙冒险 石之海 全24话 | 声优：菲鲁兹·蓝 小野大辅 *内封中字*', 'e7aeb1448d65c1c259ff9de23632561dae45b570', 0, None, None, '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24', '/rclone/p5/Anime Series', '2', None, '日漫 JOJO的奇妙冒险 石之海 全24话 | 声优：菲鲁兹·蓝 小野大辅 *内封中字*', '', 'https://hdchina.org/details.php?id=634664&hit=1', 0)]

(Background on this error at: https://sqlalche.me/e/14/gkpj)

Traceback (most recent call last):

  File "/dependencies/sqlalchemy/engine/base.py", line 1900, in _execute_context

    self.dialect.do_execute(

  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute

    cursor.execute(statement, parameters)

sqlite3.IntegrityError: NOT NULL constraint failed: download_record.thumb_image_url



The above exception was the direct cause of the following exception:



Traceback (most recent call last):
```

**Comment by pofey** [comment]
应该是没获取到剧照图，加了个兼容，下一版上线
