### ISSUE TITLE
[提问]: 在配置文件里修改了保存整理路径，启动后一直报错：找不到旧路径

### ISSUE THREAD

**Issue by leverule** [pofey/movie_robot#670]
### 当前程序版本

1.3.0

### 问题

1. 检查了所有配置文件，已经不存在旧路径
2. 这是新路径，其实就是把硬链接路径类似/Media/Links/TVs/TV_shows改成了/Media/TVs/Links/TV_shows
![image](https://user-images.githubusercontent.com/57491211/188053538-bee8ad64-5de4-4fca-a978-7d2295ff5949.png)

3. 在web里点击保存，提示修改成功，仍然报错
4. 尝试手动整理了一个剧集，实际使用正常，只是日志里频繁报错，每分钟报一次
5. 这个问题除了重装有其他解决方式吗。。。

### 发生问题时系统日志

```shell
2022/09/02 11:22:00 - ThreadPoolExecutor-5_1 - ERROR: 文件转移失败：找不到目标链接路径或无权限访问：/Media/Links/TVs/TV_shows
2022/09/02 11:22:00 - ThreadPoolExecutor-5_1 - ERROR: 监控种子任务出现错误：找不到目标链接路径或无权限访问：/Media/Links/TVs/TV_shows
Traceback (most recent call last):
  File "mbot/task/monitortorrenttask.py", line 55, in mbot.task.monitortorrenttask.MonitorTorrentTask.run
  File "mbot/service/downloadservice.py", line 436, in mbot.service.downloadservice.DownloadService.download_completed
  File "mbot/service/downloadservice.py", line 401, in mbot.service.downloadservice.DownloadService.download_completed
  File "mbot/service/filemanagerservice.py", line 79, in mbot.service.filemanagerservice.FileManagerService.link
  File "mbot/media/link/tvlink.py", line 27, in mbot.media.link.tvlink.TvLink.__init__
  File "mbot/media/link/medialink.py", line 95, in mbot.media.link.medialink.MediaLink.__init__
FileNotFoundError: 找不到目标链接路径或无权限访问：/Media/Links/TVs/TV_shows
2022/09/02 11:23:00 - ThreadPoolExecutor-5_0 - ERROR: 文件转移失败：找不到目标链接路径或无权限访问：/Media/Links/TVs/TV_shows
2022/09/02 11:23:00 - ThreadPoolExecutor-5_0 - ERROR: 监控种子任务出现错误：找不到目标链接路径或无权限访问：/Media/Links/TVs/TV_shows
Traceback (most recent call last):
  File "mbot/task/monitortorrenttask.py", line 55, in mbot.task.monitortorrenttask.MonitorTorrentTask.run
  File "mbot/service/downloadservice.py", line 436, in mbot.service.downloadservice.DownloadService.download_completed
  File "mbot/service/downloadservice.py", line 401, in mbot.service.downloadservice.DownloadService.download_completed
  File "mbot/service/filemanagerservice.py", line 79, in mbot.service.filemanagerservice.FileManagerService.link
  File "mbot/media/link/tvlink.py", line 27, in mbot.media.link.tvlink.TvLink.__init__
  File "mbot/media/link/medialink.py", line 95, in mbot.media.link.medialink.MediaLink.__init__
FileNotFoundError: 找不到目标链接路径或无权限访问：/Media/Links/TVs/TV_shows
```

**Comment by htnanako** [comment]
还有个地方有路径配置的你知道吗

**Comment by leverule** [comment]
> 还有个地方有路径配置的你知道吗

不会是数据库吧..我进去找了一圈，晕晕乎乎出来了233

**Comment by htnanako** [comment]
> > 还有个地方有路径配置的你知道吗
> 
> 不会是数据库吧..我进去找了一圈，晕晕乎乎出来了233

下载保存规则

**Comment by leverule** [comment]
> > > 还有个地方有路径配置的你知道吗
> > 
> > 
> > 不会是数据库吧..我进去找了一圈，晕晕乎乎出来了233
> 
> 下载保存规则

不是这里吗
![image](https://user-images.githubusercontent.com/57491211/188116147-f35748b3-f746-4f8d-af5a-77d0654e6c5c.png)

**Comment by leverule** [comment]
> > > 还有个地方有路径配置的你知道吗
> > 
> > 
> > 不会是数据库吧..我进去找了一圈，晕晕乎乎出来了233
> 
> 下载保存规则

噢是说这里，这里没动，因为只改了硬链路径，刚才web里这个页面手动保存完重启，还是报错。。。
![image](https://user-images.githubusercontent.com/57491211/188118585-9c5c8db7-f1cf-412c-b81a-f9dc926ebe3d.png)

**Comment by pofey** [comment]
删掉那条下载记录
