### ISSUE TITLE
[提问]: 更新1.3.0后一直复现的两个报错，是啥问题呢

### ISSUE THREAD

**Issue by 522654518** [pofey/movie_robot#671]
### 当前程序版本

1.3.0

### 问题

media_trending_task 一直报错，是电影趋势之类的嘛。
刷新电影榜单时，也一直报错。

### 发生问题时系统日志

```shell
2022/09/02 15:01:51 - ThreadPoolExecutor-4_4 - ERROR: Job "media_trending_task (trigger: cron[month='*', day='*', day_of_week='*', hour='*/3', minute='0'], next run at: 2022-09-02 18:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/dependencies/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/dependencies/httpcore/backends/sync.py", line 26, in read
    return self._sock.recv(max_bytes)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/dependencies/httpx/_transports/default.py", line 104, in __iter__
    for part in self._httpcore_stream:
  File "/dependencies/httpcore/_sync/connection_pool.py", line 346, in __iter__
    for part in self._stream:
  File "/dependencies/httpcore/_sync/http11.py", line 295, in __iter__
    raise exc
  File "/dependencies/httpcore/_sync/http11.py", line 288, in __iter__
    for chunk in self._connection._receive_response_body(**kwargs):
  File "/dependencies/httpcore/_sync/http11.py", line 160, in _receive_response_body
    event = self._receive_event(timeout=timeout)
  File "/dependencies/httpcore/_sync/http11.py", line 172, in _receive_event
    data = self._network_stream.read(
  File "/dependencies/httpcore/backends/sync.py", line 26, in read
    return self._sock.recv(max_bytes)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "mbot/core/remoteapi.py", line 218, in mbot.core.remoteapi.RemoteApi.get_trending_by_type
  File "mbot/core/remoteapi.py", line 111, in mbot.core.remoteapi.RemoteApi.request_with_access_token
  File "/dependencies/httpx/_api.py", line 189, in get
    return request(
  File "/dependencies/httpx/_api.py", line 100, in request
    return client.request(
  File "/dependencies/httpx/_client.py", line 802, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/dependencies/httpx/_client.py", line 903, in send
    raise exc
  File "/dependencies/httpx/_client.py", line 897, in send
    response.read()
  File "/dependencies/httpx/_models.py", line 1566, in read
    self._content = b"".join(self.iter_bytes())
  File "/dependencies/httpx/_models.py", line 1582, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "/dependencies/httpx/_models.py", line 1636, in iter_raw
    for raw_stream_bytes in self.stream:
  File "/dependencies/httpx/_client.py", line 122, in __iter__
    for chunk in self._stream:
  File "/dependencies/httpx/_transports/default.py", line 105, in __iter__
    yield part
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dependencies/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "mbot/task/mediatrendingtask.py", line 71, in mbot.task.mediatrendingtask.MediaTrendingTask.run
  File "mbot/service/mediametadataservice.py", line 173, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7fdcea8daac0 state=finished raised ReadTimeout>]
2022/09/02 15:01:51 - ThreadPoolExecutor-4_4 - ERROR: Job "media_trending_task (trigger: cron[month='*', day='*', day_of_week='*', hour='*/3', minute='0'], next run at: 2022-09-02 18:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/dependencies/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/dependencies/httpcore/backends/sync.py", line 26, in read
    return self._sock.recv(max_bytes)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/dependencies/httpx/_transports/default.py", line 104, in __iter__
    for part in self._httpcore_stream:
  File "/dependencies/httpcore/_sync/connection_pool.py", line 346, in __iter__
    for part in self._stream:
  File "/dependencies/httpcore/_sync/http11.py", line 295, in __iter__
    raise exc
  File "/dependencies/httpcore/_sync/http11.py", line 288, in __iter__
    for chunk in self._connection._receive_response_body(**kwargs):
  File "/dependencies/httpcore/_sync/http11.py", line 160, in _receive_response_body
    event = self._receive_event(timeout=timeout)
  File "/dependencies/httpcore/_sync/http11.py", line 172, in _receive_event
    data = self._network_stream.read(
  File "/dependencies/httpcore/backends/sync.py", line 26, in read
    return self._sock.recv(max_bytes)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "mbot/core/remoteapi.py", line 218, in mbot.core.remoteapi.RemoteApi.get_trending_by_type
  File "mbot/core/remoteapi.py", line 111, in mbot.core.remoteapi.RemoteApi.request_with_access_token
  File "/dependencies/httpx/_api.py", line 189, in get
    return request(
  File "/dependencies/httpx/_api.py", line 100, in request
    return client.request(
  File "/dependencies/httpx/_client.py", line 802, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/dependencies/httpx/_client.py", line 903, in send
    raise exc
  File "/dependencies/httpx/_client.py", line 897, in send
    response.read()
  File "/dependencies/httpx/_models.py", line 1566, in read
    self._content = b"".join(self.iter_bytes())
  File "/dependencies/httpx/_models.py", line 1582, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "/dependencies/httpx/_models.py", line 1636, in iter_raw
    for raw_stream_bytes in self.stream:
  File "/dependencies/httpx/_client.py", line 122, in __iter__
    for chunk in self._stream:
  File "/dependencies/httpx/_transports/default.py", line 105, in __iter__
    yield part
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dependencies/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "mbot/task/mediatrendingtask.py", line 71, in mbot.task.mediatrendingtask.MediaTrendingTask.run
  File "mbot/service/mediametadataservice.py", line 173, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7fdcea8daac0 state=finished raised ReadTimeout>]
```
-----------------------------------------分割线-----------此为刷新电影榜单时的报错
2022/09/02 17:48:33 - Thread-248 - ERROR: 请求出错：'list' object has no attribute 'get'
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 166, in mbot.controller.moviecontroller.douban_rank_list
  File "mbot/service/mediametadataservice.py", line 204, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
AttributeError: 'list' object has no attribute 'get'
2022/09/02 17:48:35 - Thread-254 - ERROR: 请求出错：'list' object has no attribute 'get'
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 166, in mbot.controller.moviecontroller.douban_rank_list
  File "mbot/service/mediametadataservice.py", line 204, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
AttributeError: 'list' object has no attribute 'get'
2022/09/02 17:48:43 - ThreadPoolExecutor-4_1 - INFO: 当前在下载中刷流任务6个，上限5个
2022/09/02 17:48:43 - ThreadPoolExecutor-4_1 - INFO: 已经达到设定的刷流种子量上限，停止新增。
2022/09/02 17:48:58 - Thread-342 - ERROR: 请求出错：'list' object has no attribute 'get'
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 166, in mbot.controller.moviecontroller.douban_rank_list
  File "mbot/service/mediametadataservice.py", line 204, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
AttributeError: 'list' object has no attribute 'get'
2022/09/02 17:48:59 - Thread-354 - ERROR: 请求出错：'list' object has no attribute 'get'
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 166, in mbot.controller.moviecontroller.douban_rank_list
  File "mbot/service/mediametadataservice.py", line 204, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
AttributeError: 'list' object has no attribute 'get'
2022/09/02 17:49:02 - Thread-362 - ERROR: 请求出错：'list' object has no attribute 'get'
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 166, in mbot.controller.moviecontroller.douban_rank_list
  File "mbot/service/mediametadataservice.py", line 204, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
AttributeError: 'list' object has no attribute 'get'
2022/09/02 17:49:06 - Thread-377 - ERROR: 请求出错：'list' object has no attribute 'get'
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 166, in mbot.controller.moviecontroller.douban_rank_list
  File "mbot/service/mediametadataservice.py", line 204, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
AttributeError: 'list' object has no attribute 'get'
2022/09/02 17:50:44 - Thread-452 - ERROR: 请求出错：'list' object has no attribute 'get'
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 166, in mbot.controller.moviecontroller.douban_rank_list
  File "mbot/service/mediametadataservice.py", line 204, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
AttributeError: 'list' object has no attribute 'get'
2022/09/02 17:50:45 - Thread-460 - ERROR: 请求出错：'list' object has no attribute 'get'
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 166, in mbot.controller.moviecontroller.douban_rank_list
  File "mbot/service/mediametadataservice.py", line 204, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
AttributeError: 'list' object has no attribute 'get'
2022/09/02 17:51:03 - Thread-462 - ERROR: 请求出错：'list' object has no attribute 'get'
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 166, in mbot.controller.moviecontroller.douban_rank_list
  File "mbot/service/mediametadataservice.py", line 204, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
AttributeError: 'list' object has no attribute 'get'
2022/09/02 17:51:07 - Thread-464 - ERROR: 请求出错：'list' object has no attribute 'get'
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 166, in mbot.controller.moviecontroller.douban_rank_list
  File "mbot/service/mediametadataservice.py", line 204, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
AttributeError: 'list' object has no attribute 'get'

**Comment by pofey** [comment]
豆瓣榜单今天有单问题，一会发一版，1.3.1
