### ISSUE TITLE
[提问]: 《指环王：力量之戒》订阅报错

### ISSUE THREAD

**Issue by henryl46** [pofey/movie_robot#673]
### 当前程序版本

1.3.0

### 问题

今天早上订阅了《指环王：力量之戒》这部剧集，mr正常订阅与下载。但是下午开始频繁报错 **订阅失败**，重新尝试订阅依然报错，按照指示检查了docker日志如下，请教一下该如何解决这样的问题呢？看到一行关于plexmedia的报错，是否是因为添加了两个媒体服务器的原因？

谢谢

### 发生问题时系统日志

```shell
2022/09/02 21:09:13 - SubRequestConsumer - INFO: 成功从CMDB取得豆瓣编号27190093对应的ID映射关系：{'mediaType': 'TV', 'doubanId': 27190093, 'doubanSeasonNumber': 1, 'tmdbId': 84773, 'imdbId': 'tt7631058', 'tvdbId': 367506}

2022/09/02 21:09:15 - SubRequestConsumer - ERROR: douban_id: 27190093 订阅失败，请查看日志分析原因。

Traceback (most recent call last):

  File "mbot/service/smartdownloadservice.py", line 321, in mbot.service.smartdownloadservice.SmartDownloadService.sub_from_douban

  File "mbot/service/smartdownloadservice.py", line 55, in mbot.service.smartdownloadservice.SmartDownloadService.exists

  File "mbot/service/smartdownloadservice.py", line 83, in mbot.service.smartdownloadservice.SmartDownloadService.get_missing_episodes

  File "mbot/media/server/plexmediaserver.py", line 256, in mbot.media.server.plexmediaserver.PlexMediaServer.get_missing_episodes

  File "/dependencies/plexapi/library.py", line 599, in get

    return self.fetchItem(key, title__iexact=title)

  File "/dependencies/plexapi/base.py", line 176, in fetchItem

    raise NotFound('Unable to find elem: cls=%s, attrs=%s' % (clsname, kwargs))

plexapi.exceptions.NotFound: Unable to find elem: cls=None, attrs={'title__iexact': 'The Lord of the Rings'}
```

**Comment by pofey** [comment]
获取plex缺少的集数出错，具体原因不详

**Comment by Zayia** [comment]
我这边订阅指环王：力量之戒没事，订阅女浩克和你问题一样
