### ISSUE TITLE
[提问]: 下载电影后不会硬链，日志不知道什么意思，该怎么解决

### ISSUE THREAD

**Issue by phinleyfei** [pofey/movie_robot#675]
### 当前程序版本

1.2.0和1.3.0

### 问题

订阅电影，自动下载完成后，不会自动做硬链，问题日志每分钟都会报。（以前没问题的）

### 发生问题时系统日志

```shell
2022/09/02 21:40:01 - ThreadPoolExecutor-5_4 - ERROR: 监控种子任务出现错误：Can't mix strings and bytes in path components                                  
Traceback (most recent call last):                                                                                                                          
  File "mbot/task/monitortorrenttask.py", line 55, in mbot.task.monitortorrenttask.MonitorTorrentTask.run                                                   
  File "mbot/service/downloadservice.py", line 359, in mbot.service.downloadservice.DownloadService.download_completed                                      
  File "mbot/torrent/torrentfileinfo.py", line 40, in mbot.torrent.torrentfileinfo.TorrentFileInfo.parse_episode                                            
  File "mbot/torrent/torrentfileinfo.py", line 74, in mbot.torrent.torrentfileinfo.TorrentFileInfo.parse_files                                              
  File "/usr/local/lib/python3.8/posixpath.py", line 90, in join                                                                                            
    genericpath._check_arg_types('join', a, *p)                                                                                                             
  File "/usr/local/lib/python3.8/genericpath.py", line 155, in _check_arg_types                                                                             
    raise TypeError("Can't mix strings and bytes in path components") from None                                                                             
TypeError: Can't mix strings and bytes in path components
```

**Comment by pofey** [comment]
原因不详，但是对报错我加了个兼容

**Comment by phinleyfei** [comment]
哪个版本能更新兼容？我试试。

**Comment by pofey** [comment]
还没发布
