### ISSUE TITLE
[提问]: TG推送失败

### ISSUE THREAD

**Issue by x87797697** [pofey/movie_robot#677]
### 当前程序版本

1.3.0

### 问题

tg推送失败。不知道啥原因，求指教

### 发生问题时系统日志

```shell
2022/09/02 22:10:23 - Thread-239 - ERROR: telegram推送失败：Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 69
 2022/09/02 22:10:35 - Thread-239 - ERROR: 推送测试消息失败：RetryError[<Future at 0x7f4e51bff640 state=finished raised ConnectError>]
Traceback (most recent call last):
  File "/dependencies/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/dependencies/httpcore/backends/sync.py", line 57, in start_tls
    raise exc
  File "/dependencies/httpcore/backends/sync.py", line 52, in start_tls
    sock = ssl_context.wrap_socket(
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/dependencies/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/dependencies/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/dependencies/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/dependencies/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/dependencies/httpcore/_sync/connection.py", line 150, in _connect
    stream = stream.start_tls(**kwargs)
  File "/dependencies/httpcore/backends/sync.py", line 57, in start_tls
    raise exc
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "mbot/notify/telegram.py", line 83, in mbot.notify.telegram.TelegramNotify.send_by_template
  File "/dependencies/httpx/_api.py", line 304, in post
    return request(
  File "/dependencies/httpx/_api.py", line 100, in request
    return client.request(
  File "/dependencies/httpx/_client.py", line 802, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/dependencies/httpx/_client.py", line 889, in send
    response = self._send_handling_auth(
  File "/dependencies/httpx/_client.py", line 917, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/dependencies/httpx/_client.py", line 954, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/dependencies/httpx/_client.py", line 990, in _send_single_request
    response = transport.handle_request(request)
  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mbot/controller/settingcontroller.py", line 432, in mbot.controller.settingcontroller.test_notify
  File "mbot/service/notifyservice.py", line 207, in mbot.service.notifyservice.NotifyService.send_app_message_by_template_name
  File "mbot/service/notifyservice.py", line 220, in mbot.service.notifyservice.NotifyService.send_app_message_by_template
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f4e51bff640 state=finished raised ConnectError>]
```

**Comment by x87797697** [comment]
2022/09/03 00:44:45 - Thread-100 - ERROR: telegram推送失败：Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 69
 2022/09/03 00:44:47 - Thread-100 - ERROR: telegram推送失败：Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 104


zheshi
