### ISSUE TITLE
[优化]: 外部依赖错误时推送通知

### ISSUE THREAD

**Issue by Decade1993** [pofey/movie_robot#678]
### 当前现状

有时候下载器可能挂了，导致整个订阅服务不可用，加个通知推送会好很多

### 你的建议

下载器或者其他依赖出错了可以配置通知推送

### 优先级

一般

### 受众范围

一般

**Comment by nocmt** [comment]
目前会报错，导致也不知道哪个依赖不可用。

2023/04/13 17:08:00 - Thread-516 - ERROR: Exception on /api/health/get_health_indicator [GET]
Traceback (most recent call last):
  File "/dependencies/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/dependencies/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/dependencies/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/dependencies/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/dependencies/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "mbot/register/controller_register.py", line 69, in mbot.register.controller_register.login_required.wrapper.decorator
  File "mbot/controller/healthcontroller.py", line 88, in mbot.controller.healthcontroller.get_health_indicator
KeyError: ('00',)
