### ISSUE TITLE
[缺陷]: 推送通知错误

### ISSUE THREAD

**Issue by Migflyway** [pofey/movie_robot#680]
### 当前程序版本

1.31

### 问题描述

推送反馈错误 AttributeError: 'int' object has no attribute 'get'

### 重现步骤

1、删掉conf中的notify
2、更新版本到1.31
3、推送测试bark和企业微信无法推送，报错 AttributeError: 'int' object has no attribute 'get'
4、排除推送配置问题

### 发生问题时系统日志

```shell
2022/09/02 10:16:10 - ThreadPoolExecutor-5_1 - ERROR: on_event error: NotifyListener event: {'event_type': 'DownloadCompleted', 'data': {'x_meta': {'id': 100752, 'doubanId': 35700395, 'tmdbId': 985939, 'imdbId': 'tt15325794', 'tvdbId': None, 'gmtModified': '2022-09-01 01:32:18', 'needUpdate': False, 'mediaType': 'Movie', 'title': '坠落', 'enTitle': 'Fall', 'originalTitle': 'Fall', 'intro': '贝琪（格蕾丝·富尔顿 饰）和亨特（维吉尼亚·加德纳 饰）是一对喜欢追求刺激的好友，某天，她们攀上一座高达610米的电视塔后，意外受困于顶端，面对恶劣天气和物资短缺，她们必须设法在令人晕眩的高度上活下去。', 'rating': 7.6, 'releaseYear': 2022, 'premiereDate': 20220811, 'duration': 107, 'posterUrl': 'http://assets.fanart.tv/fanart/movies/985939/movieposter/fall-6302305de5f06.jpg', 'backgroundUrl': 'http://assets.fanart.tv/fanart/movies/985939/moviebackground/fall-6301ba06811f6.jpg', 'genres': ['惊悚'], 'country': ['英国', '美国']}, 'douban_id': None, 'tmdb_meta': None, 'douban_meta': None, 'target_path': '/Video/movieLink/欧美/坠落 (2022) [tmdbid=985939]', 'sub_id': 116, 'uid': '1', 'tmdb_id': '985939', 'media_type': 'Movie', 'season_number': None, 'season_year': None, 'year': 2022, 'episodes': None, 'file_size': '5.02 GB', 'media_stream': {'resolution': '1080p', 'media_source': 'WEB-DL', 'media_codec': 'H.264', 'media_audio': ['DD5.1'], 'release_team': 'EVO'}, 'source_path': '/Video/电影/Fall.2022.1080p.WEB-DL.DD5.1.H.264-EVO/Fall.2022.1080p.WEB-DL.DD5.1.H.264-EVO.mkv', 'torrent_name': 'Fall.2022.1080p.WEB-DL.DD5.1.H.264-EVO', 'torrent_subject': '坠落 / 坠(台) / 跌落 / 下坠 / The Fall', 'torrent_id': 606622, 'torrent_hash': '74a4725ce41dfaa206e37374f0e3e0b8b06c204b', 'torrent_url': 'https://kp.m-team.cc/details.php?id=606622&hit=1', 'site_id': 'mteam', 'site_name': '馒头'}}
Traceback (most recent call last):
  File "mbot/event/eventbus.py", line 44, in mbot.event.eventbus.EventBus.publish_event
  File "/app/mbot/event/listener/notifylistener.py", line 136, in on_event
    self.notify_download_completed(data)
  File "/app/mbot/event/listener/notifylistener.py", line 34, in notify_download_completed
    notify_service.send_app_message_by_template_name(data.get('uid'), 'download_completed_movie', data)
  File "mbot/service/notifyservice.py", line 207, in mbot.service.notifyservice.NotifyService.send_app_message_by_template_name
  File "mbot/service/notifyservice.py", line 220, in mbot.service.notifyservice.NotifyService.send_app_message_by_template
  File "mbot/notify/qywechat.py", line 78, in mbot.notify.qywechat.QywechatNotify.send_by_template
AttributeError: 'int' object has no attribute 'get'
```

### 健康检查

![image](https://user-images.githubusercontent.com/4063598/188205506-039a79ac-84fd-4702-bdc3-81c6d3cd5109.png)

**Comment by Migflyway** [comment]
已经弄好，白名单没打勾！
