### ISSUE TITLE
[提问]: 频繁弹出订阅下载出错

### ISSUE THREAD

**Issue by Zayia** [pofey/movie_robot#683]
### 当前程序版本

1.3.1

### 问题

订阅女浩克，前三集下载成功，然后就频繁弹出订阅下载出错
![950598B2-29E6-4D49-9677-7078BC89DAC7](https://user-images.githubusercontent.com/35530837/188253937-14b6fece-ed5e-4656-815c-451a8ab59c55.png)

### 发生问题时系统日志

```shell
2022/09/03 10:44:00 - ThreadPoolExecutor-4_3 - INFO: 女浩克 第1季(2022) 第2集字幕下载已经提交启动。
2022/09/03 10:44:00 - SubRequestConsumer - INFO: 女浩克 第1季(2022) 第2集字幕下载 下次运行时间：2022-09-03 11:44:00
2022/09/03 10:45:52 - ThreadPoolExecutor-4_3 - INFO: [ttg]ViuTV Miss Mask Pageant 2 COMPLETE 1080i HDTV H264-NGB  粤语 | 繁体DvbSub字幕 无需HR，立即删除。种子站点编号：580453
2022/09/03 10:45:52 - ThreadPoolExecutor-4_3 - INFO: 种子hash 29b93be747210bf773c6f5c23c4ba185bb704cf5 将被淘汰
2022/09/03 10:45:52 - ThreadPoolExecutor-4_3 - INFO: [HDHome]Guardians of the Galaxy Vol 2 2017 UHD BluRay REMUX 2160p HEVC TrueHD Atmos 7.1-HDH 无需HR，立即删除。种子站点编号：33760
2022/09/03 10:45:52 - ThreadPoolExecutor-4_3 - INFO: 种子hash 3e51ebc3c9e2c0d0365db93baec266442ba1229b 将被淘汰
2022/09/03 10:45:52 - ThreadPoolExecutor-4_3 - INFO: [soulvoice]Orange Is the New Black S01 720p WEB-DL DD5.1 H.264-jAh 无需HR，立即删除。种子站点编号：88559
2022/09/03 10:45:52 - ThreadPoolExecutor-4_3 - INFO: 种子hash f3471de68e60763990290945658aaca2de2d412d 将被淘汰
2022/09/03 10:46:52 - ThreadPoolExecutor-4_5 - INFO: [pthome]Orange Is the New Black S01 720p BluRay DD5.1 x264-NTb 无需HR，立即删除。种子站点编号：144756
2022/09/03 10:46:52 - ThreadPoolExecutor-4_5 - INFO: 种子hash feb2bc2bbf49e3b6b446386a186443b281c79e04 将被淘汰
2022/09/03 10:47:06 - ThreadPoolExecutor-4_2 - INFO: 开始同步站点资源信息...
2022/09/03 10:48:06 - ThreadPoolExecutor-4_2 - INFO: 家园拉取种子超时，请耐心等待...
2022/09/03 10:49:52 - ThreadPoolExecutor-4_5 - INFO: [HDHome]Cliffhanger 1993 1080p BluRay DTS-HD MA 5.1 x264-HDH 无需HR，立即删除。种子站点编号：46016
2022/09/03 10:49:52 - ThreadPoolExecutor-4_5 - INFO: 种子hash a923fdc59bb24b8f432766de6feeb6b6f0b09c3b 将被淘汰
2022/09/03 10:49:53 - ThreadPoolExecutor-4_5 - INFO: [soulvoice]Orange Is the New Black S01 720p BluRay DD5.1 x264-NTb 无需HR，立即删除。种子站点编号：88558
2022/09/03 10:49:53 - ThreadPoolExecutor-4_5 - INFO: 种子hash 0129a74b2d55db181383a8cc4c87f70a220f8c3c 将被淘汰
2022/09/03 10:51:54 - ThreadPoolExecutor-4_2 - INFO: 所有站点资源信息已经更新完毕。
2022/09/03 10:51:54 - SubConsumer - INFO: 龙之家族(2022) 已经有搜索结果，但经过你设定的过滤器后，无任何结果。
2022/09/03 10:51:54 - SubConsumer - INFO: 指环王：力量之戒(2022) 没有搜索到缺失的[3, 4, 5, 6, 7, 8]集
2022/09/03 10:51:54 - SubConsumer - ERROR: 女浩克(2022) 订阅下载出错！
Traceback (most recent call last):
  File "mbot/task/consumer/subconsumer.py", line 209, in mbot.task.consumer.subconsumer.SubConsumer.handle_sub
  File "mbot/service/smartdownloadservice.py", line 83, in mbot.service.smartdownloadservice.SmartDownloadService.get_missing_episodes
  File "mbot/media/server/plexmediaserver.py", line 256, in mbot.media.server.plexmediaserver.PlexMediaServer.get_missing_episodes
  File "/dependencies/plexapi/library.py", line 599, in get
    return self.fetchItem(key, title__iexact=title)
  File "/dependencies/plexapi/base.py", line 176, in fetchItem
    raise NotFound('Unable to find elem: cls=%s, attrs=%s' % (clsname, kwargs))
plexapi.exceptions.NotFound: Unable to find elem: cls=None, attrs={'title__iexact': 'She-Hulk'}
2022/09/03 10:51:55 - SubConsumer - INFO: 独行月球(2022) 经过系统分析后，没有搜到有效结果。
2022/09/03 10:52:49 - ThreadPoolExecutor-4_2 - INFO: 开始筛选免费种子，未筛选前共280个。
2022/09/03 10:52:49 - ThreadPoolExecutor-4_2 - INFO: 经过筛选后，还剩12个种子，按上传质量打分排序后提交上传，还可以再提交99999999个种子到下载器。
2022/09/03 10:52:49 - ThreadPoolExecutor-4_2 - INFO: 有12个免费种子需要下载，开始提交到下载器。
2022/09/03 10:52:49 - ThreadPoolExecutor-4_2 - ERROR: 剩余可用空间不足，跳过下载 [soulvoice]Engineering Project Management ---- Tongji University 大小：818319.36MB
2022/09/03 10:52:49 - ThreadPoolExecutor-4_2 - ERROR: 剩余可用空间不足，跳过下载 [pthome]Orange Is the New Black S03 1080p BluRay Remux AVC DTS-HD MA 5.1-DTHD 大小：120320.0MB
2022/09/03 10:52:49 - ThreadPoolExecutor-4_2 - ERROR: 剩余可用空间不足，跳过下载 [pterclub]Survivor Romania S03 1080i HDTV DD5.1 H.264-playTV 大小：767703.04MB
2022/09/03 10:52:49 - ThreadPoolExecutor-4_2 - ERROR: 剩余可用空间不足，跳过下载 [soulvoice]One Piece Collection 1999 EP01-EP1000 WEB-DL H.264 AAC -Black two 大小：699668.48MB
2022/09/03 10:52:49 - ThreadPoolExecutor-4_2 - INFO: 免费种子提交下载队列完成，本轮共提交8个免费种子
2022/09/03 10:52:49 - soulvoice-downloader - INFO: 开始处理免费种子下载任务: [soulvoice]Midnight Mass 2021 S01 DV 2160p NF WEB-DL DDPA5.1 H.265-SiC
2022/09/03 10:52:49 - HDHome-downloader - INFO: 开始处理免费种子下载任务: [HDHome]Rocketman 2019 UHD BluRay 2160p x265 HDR 10bit Atmos TrueHD 7.1-HDH
2022/09/03 10:52:49 - pthome-downloader - INFO: 开始处理免费种子下载任务: [pthome]Orange Is the New Black S03 1080p BluRay AVC DTS-HD MA 5.1-NOGRP
2022/09/03 10:52:49 - ttg-downloader - INFO: 开始处理免费种子下载任务: [ttg]She Likes That 2021 Blu-ray 1080p AVC TrueHD 5.1-DIY@TTG  「DIY 简繁中字」
2022/09/03 10:53:00 - ThreadPoolExecutor-4_4 - INFO: 女浩克 第1季(2022) 第1集字幕下载已经提交启动。
2022/09/03 10:53:00 - SubRequestConsumer - INFO: 女浩克 第1季(2022) 第1集字幕下载 下次运行时间：2022-09-03 11:53:00
2022/09/03 10:55:38 - soulvoice-downloader - INFO: 开始处理免费种子下载任务: [soulvoice]Orange Is the New Black S03 1080p BluRay DD5.1 x264-SA89
2022/09/03 10:55:49 - soulvoice-downloader - INFO: 开始处理免费种子下载任务: [soulvoice]Orange Is the New Black S03 1080p BluRay Remux AVC DTS-HD MA 5.1-DTHD
2022/09/03 10:55:56 - soulvoice-downloader - INFO: 开始处理免费种子下载任务: [soulvoice]Midnight Mass S01 1080p NF WEB-DL DDPA5.1 H.264-NTb
2022/09/03 10:57:52 - ThreadPoolExecutor-4_4 - INFO: [pthome]Orange Is the New Black S03 1080p BluRay AVC DTS-HD MA 5.1-NOGRP 无需HR，立即删除。种子站点编号：144760
2022/09/03 10:57:52 - ThreadPoolExecutor-4_4 - INFO: 种子hash 0db92fef701aab9af50be337b708edf62518d1d1 将被淘汰
2022/09/03 10:57:53 - ThreadPoolExecutor-4_4 - INFO: [ttg]She Likes That 2021 Blu-ray 1080p AVC TrueHD 5.1-DIY@TTG  「DIY 简繁中字」 无需HR，立即删除。种子站点编号：580457
2022/09/03 10:57:53 - ThreadPoolExecutor-4_4 - INFO: 种子hash c4374b33a88dda5cd1999c4b6c816a03d2a53a7f 将被淘汰
2022/09/03 10:58:40 - HDHome-downloader - ERROR: 从HDHome下载种子失败：https://hdhome.org/download.php?id=55363
2022/09/03 10:58:40 - HDHome-downloader - INFO: 开始处理免费种子下载任务: [HDHome]Birdman 2014 BluRay 1080p REMUX AVC DTS-HD MA 5.1-HDH
2022/09/03 10:59:52 - ThreadPoolExecutor-4_2 - INFO: [soulvoice]Midnight Mass 2021 S01 DV 2160p NF WEB-DL DDPA5.1 H.265-SiC 无需HR，立即删除。种子站点编号：88564
2022/09/03 10:59:52 - ThreadPoolExecutor-4_2 - INFO: 种子hash 3fbf049e5b2b4b106bc6699922a6a0c4012e2441 将被淘汰
2022/09/03 10:59:52 - ThreadPoolExecutor-4_2 - INFO: [soulvoice]Orange Is the New Black S03 1080p BluRay DD5.1 x264-SA89 无需HR，立即删除。种子站点编号：88560
2022/09/03 10:59:52 - ThreadPoolExecutor-4_2 - INFO: 种子hash 7a2b70d6dc71593fdf06639cfa9111d7ad898ded 将被淘汰
2022/09/03 11:00:00 - ThreadPoolExecutor-4_4 - INFO: 开始获取za**a(do) 365天内的电影
2022/09/03 11:00:00 - ThreadPoolExecutor-4_4 - INFO: 开始获取za**a(wish) 365天内的电影
2022/09/03 11:00:06 - ThreadPoolExecutor-4_4 - INFO: 豆瓣用户zayia的想看列表开始同步到订阅记录。 
2022/09/03 11:00:06 - ThreadPoolExecutor-4_4 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
2022/09/03 11:00:52 - ThreadPoolExecutor-4_2 - INFO: [soulvoice]Orange Is the New Black S03 1080p BluRay Remux AVC DTS-HD MA 5.1-DTHD 无需HR，立即删除。种子站点编号：88562
2022/09/03 11:00:52 - ThreadPoolExecutor-4_2 - INFO: 种子hash 36d814a2724726c23eec8118af6e12d9dac2a295 将被淘汰
2022/09/03 11:04:52 - ThreadPoolExecutor-4_4 - INFO: [soulvoice]Midnight Mass S01 1080p NF WEB-DL DDPA5.1 H.264-NTb 无需HR，立即删除。种子站点编号：88563
2022/09/03 11:04:52 - ThreadPoolExecutor-4_4 - INFO: 种子hash 7fa97b7d9c39a4eed6e0bba1d79fc7cf1858bc21 将被淘汰
2022/09/03 11:06:52 - ThreadPoolExecutor-4_3 - INFO: [HDHome]Birdman 2014 BluRay 1080p REMUX AVC DTS-HD MA 5.1-HDH 无需HR，立即删除。种子站点编号：67418
2022/09/03 11:06:52 - ThreadPoolExecutor-4_3 - INFO: 种子hash 6bb6d5227f970ec9b930795e7cdbb5f69366bdf2 将被淘汰
2022/09/03 11:07:51 - ThreadPoolExecutor-4_5 - INFO: 开始同步站点资源信息...
2022/09/03 11:12:23 - ThreadPoolExecutor-4_5 - INFO: 所有站点资源信息已经更新完毕。
2022/09/03 11:12:31 - SubConsumer - INFO: 龙之家族(2022) 已经有搜索结果，但经过你设定的过滤器后，无任何结果。
2022/09/03 11:12:32 - SubConsumer - INFO: 指环王：力量之戒(2022) 没有搜索到缺失的[3, 4, 5, 6, 7, 8]集
2022/09/03 11:12:32 - SubConsumer - ERROR: 女浩克(2022) 订阅下载出错！
Traceback (most recent call last):
  File "mbot/task/consumer/subconsumer.py", line 209, in mbot.task.consumer.subconsumer.SubConsumer.handle_sub
  File "mbot/service/smartdownloadservice.py", line 83, in mbot.service.smartdownloadservice.SmartDownloadService.get_missing_episodes
  File "mbot/media/server/plexmediaserver.py", line 256, in mbot.media.server.plexmediaserver.PlexMediaServer.get_missing_episodes
  File "/dependencies/plexapi/library.py", line 599, in get
    return self.fetchItem(key, title__iexact=title)
  File "/dependencies/plexapi/base.py", line 176, in fetchItem
    raise NotFound('Unable to find elem: cls=%s, attrs=%s' % (clsname, kwargs))
plexapi.exceptions.NotFound: Unable to find elem: cls=None, attrs={'title__iexact': 'She-Hulk'}
2022/09/03 11:12:32 - SubConsumer - INFO: 独行月球(2022) 经过系统分析后，没有搜到有效结果。
2022/09/03 11:13:27 - ThreadPoolExecutor-4_5 - INFO: 开始筛选免费种子，未筛选前共278个。
2022/09/03 11:13:27 - ThreadPoolExecutor-4_5 - INFO: 经过筛选后，还剩12个种子，按上传质量打分排序后提交上传，还可以再提交99999999个种子到下载器。
2022/09/03 11:13:27 - ThreadPoolExecutor-4_5 - INFO: 有12个免费种子需要下载，开始提交到下载器。
2022/09/03 11:13:27 - ThreadPoolExecutor-4_5 - ERROR: 剩余可用空间不足，跳过下载 [pterclub]Survivor Romania S03 1080i HDTV DD5.1 H.264-playTV 大小：767703.04MB
2022/09/03 11:13:27 - ThreadPoolExecutor-4_5 - ERROR: 剩余可用空间不足，跳过下载 [soulvoice]One Piece Collection 1999 EP01-EP1000 WEB-DL H.264 AAC -Black two 大小：699668.48MB
2022/09/03 11:13:27 - ThreadPoolExecutor-4_5 - INFO: 免费种子提交下载队列完成，本轮共提交10个免费种子
2022/09/03 11:13:27 - pthome-downloader - INFO: 开始处理免费种子下载任务: [pthome]Orange Is the New Black S03 1080p BluRay Remux AVC DTS-HD MA 5.1-DTHD
2022/09/03 11:13:27 - pterclub-downloader - INFO: 开始处理免费种子下载任务: [pterclub]Universal Vision 2022 E244 1080p HDTV H264 AAC-PTerTV
2022/09/03 11:13:27 - HDHome-downloader - INFO: 开始处理免费种子下载任务: [HDHome]Rocketman 2019 UHD BluRay 2160p x265 HDR 10bit Atmos TrueHD 7.1-HDH
2022/09/03 11:13:27 - soulvoice-downloader - INFO: 开始处理免费种子下载任务: [soulvoice]Banlieue 13 Ultimatum 2009 Blu-ray 1080p AVC DTS-HD MA 6 1-TTG
2022/09/03 11:13:30 - HDHome-downloader - INFO: 开始处理免费种子下载任务: [HDHome]Jack Ryan Shadow Recruit 2014 BluRay 1080p REMUX AVC DTS-HD MA 7.1-HDH
2022/09/03 11:14:32 - pterclub-downloader - INFO: 开始处理免费种子下载任务: [pterclub]Mei Li Wan Xiang 2022 E244 1080p HDTV H264 AAC-PTerTV
2022/09/03 11:14:42 - pterclub-downloader - INFO: 开始处理免费种子下载任务: [pterclub]Quan Jing Zi Ran 2022 E244 1080p HDTV H264 AAC-PTerTV
2022/09/03 11:14:43 - HDHome-downloader - INFO: 开始处理免费种子下载任务: [HDHome]Shot Caller 2017 1080p BluRay TrueHD 5.1 x264-HDH
2022/09/03 11:15:03 - pterclub-downloader - INFO: 开始处理免费种子下载任务: [pterclub]My Ages Apart 2017 S01E07-E15 1080i HDTV H264 DD5.1-PTerTV
2022/09/03 11:15:38 - pthome-downloader - INFO: 开始处理免费种子下载任务: [pthome]Ley Lines 1999 Arrow Blu-ray 1080p AVC LPCM 2.0-blucook#333@CHDBits
2022/09/03 11:17:53 - ThreadPoolExecutor-4_5 - INFO: [HDHome]Rocketman 2019 UHD BluRay 2160p x265 HDR 10bit Atmos TrueHD 7.1-HDH 无需HR，立即删除。种子站点编号：55363
2022/09/03 11:17:53 - ThreadPoolExecutor-4_5 - INFO: 种子hash 6a23f45adb504e72d12e725d619c1e25f4b7d278 将被淘汰
```

**Comment by pofey** [comment]
plex云库？

**Comment by Zayia** [comment]
本地库，影视文件放在本地NAS上面
除了这部剧，其他剧暂时没发现问题

**Comment by pofey** [comment]
plex里这部剧She-Hulk 截图我看看是什么样

**Comment by Zayia** [comment]
![1662208471472](https://user-images.githubusercontent.com/35530837/188270594-b229b28f-9ae0-4360-9d8f-a216b7aa4a98.jpg)

**Comment by pofey** [comment]
原因不详 但看起来plex这部剧的数据有点问题

**Comment by Zayia** [comment]
用的是MR自动生成的NFO文件信息

**Comment by pofey** [comment]
plex 也不读nfo
