### ISSUE TITLE
[提问]: 登录页面一直闪退

### ISSUE THREAD

**Issue by 0683X** [pofey/movie_robot#684]
### 当前程序版本

1.3.1

### 问题

换了几个版本都是这样，不知道是哪里的问题，请教一下

### 发生问题时系统日志

```shell
File "mbot/media/douban.py", line 641, in mbot.media.douban.DoubanMovie.suggestion
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 11:51:43 - Thread-49 - ERROR: 请求出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 185, in mbot.controller.moviecontroller.douban_suggestion
  File "mbot/media/douban.py", line 641, in mbot.media.douban.DoubanMovie.suggestion
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 11:52:03 - Thread-66 - ERROR: 请求出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 185, in mbot.controller.moviecontroller.douban_suggestion
  File "mbot/media/douban.py", line 641, in mbot.media.douban.DoubanMovie.suggestion
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 11:53:02 - Thread-86 - ERROR: 请求出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 185, in mbot.controller.moviecontroller.douban_suggestion
  File "mbot/media/douban.py", line 641, in mbot.media.douban.DoubanMovie.suggestion
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 11:54:28 - Thread-103 - ERROR: 请求出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 185, in mbot.controller.moviecontroller.douban_suggestion
  File "mbot/media/douban.py", line 641, in mbot.media.douban.DoubanMovie.suggestion
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
mbot exists
2022-09-03 12:00:09,048 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-09-03 12:00:09,054 INFO supervisord started with pid 11
2022-09-03 12:00:10,057 INFO spawned: 'mbots' with pid 13
2022/09/03 12:00:13 - MainThread - INFO: 添加事件(下载完成)监听器：NotifyListener
2022/09/03 12:00:13 - MainThread - INFO: 添加事件(订阅影片)监听器：NotifyListener
2022/09/03 12:00:13 - MainThread - INFO: 添加事件(开始下载)监听器：NotifyListener
2022/09/03 12:00:13 - MainThread - INFO: 添加事件(站点异常)监听器：NotifyListener
2022/09/03 12:00:13 - MainThread - ERROR: 错误码：401002 错误消息：没有配置豆瓣信息
2022/09/03 12:00:13 - MainThread - INFO: 站点并发线程数：6
2022/09/03 12:00:13 - MainThread - INFO: 新增任务：自定义任务调度
2022/09/03 12:00:13 - MainThread - INFO: 新增任务：监听下载客户端下载状态
2022/09/03 12:00:13 - MainThread - INFO: 新增任务：订阅元数据检查更新任务
2022/09/03 12:00:13 - MainThread - INFO: 新增任务：新版本检测任务
2022/09/03 12:00:13 - Thread-4 - INFO: 开始更新媒体趋势榜单数据
2022/09/03 12:00:13 - MainThread - INFO: 新增任务：媒体趋势榜单任务
2022/09/03 12:00:13 - MainThread - INFO: 新增任务：健康检查任务
2022/09/03 12:00:13 - MainThread - INFO: 已经启动字幕下载处理任务。
2022/09/03 12:00:13 - MainThread - INFO: 当前版本: 1.3.1
2022-09-03 12:00:15,580 INFO success: mbots entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2022/09/03 12:00:50 - Thread-25 - ERROR: 请求出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 185, in mbot.controller.moviecontroller.douban_suggestion
  File "mbot/media/douban.py", line 641, in mbot.media.douban.DoubanMovie.suggestion
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 12:01:12 - Thread-4 - ERROR: 请求豆瓣榜单出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 12:01:12 - Thread-4 - ERROR: 获取榜单出错
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/task/mediatrendingtask.py", line 72, in mbot.task.mediatrendingtask.MediaTrendingTask.run
  File "mbot/service/mediametadataservice.py", line 170, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
  File "mbot/media/douban.py", line 626, in mbot.media.douban.DoubanMovie.ranking_list
UnboundLocalError: local variable 'result' referenced before assignment
2022/09/03 12:01:12 - Thread-4 - ERROR: 请求豆瓣榜单出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 12:01:12 - Thread-4 - ERROR: 获取榜单出错
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/task/mediatrendingtask.py", line 72, in mbot.task.mediatrendingtask.MediaTrendingTask.run
  File "mbot/service/mediametadataservice.py", line 170, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
  File "mbot/media/douban.py", line 626, in mbot.media.douban.DoubanMovie.ranking_list
UnboundLocalError: local variable 'result' referenced before assignment
2022/09/03 12:01:13 - Thread-4 - ERROR: 请求豆瓣榜单出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 12:01:13 - Thread-4 - ERROR: 获取榜单出错
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/task/mediatrendingtask.py", line 72, in mbot.task.mediatrendingtask.MediaTrendingTask.run
  File "mbot/service/mediametadataservice.py", line 170, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
  File "mbot/media/douban.py", line 626, in mbot.media.douban.DoubanMovie.ranking_list
UnboundLocalError: local variable 'result' referenced before assignment
2022/09/03 12:01:13 - Thread-4 - ERROR: 请求豆瓣榜单出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 12:01:13 - Thread-4 - ERROR: 获取榜单出错
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/task/mediatrendingtask.py", line 72, in mbot.task.mediatrendingtask.MediaTrendingTask.run
  File "mbot/service/mediametadataservice.py", line 170, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
  File "mbot/media/douban.py", line 626, in mbot.media.douban.DoubanMovie.ranking_list
UnboundLocalError: local variable 'result' referenced before assignment
2022/09/03 12:01:13 - Thread-4 - ERROR: 请求豆瓣榜单出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 12:01:13 - Thread-4 - ERROR: 获取榜单出错
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/task/mediatrendingtask.py", line 72, in mbot.task.mediatrendingtask.MediaTrendingTask.run
  File "mbot/service/mediametadataservice.py", line 170, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
  File "mbot/media/douban.py", line 626, in mbot.media.douban.DoubanMovie.ranking_list
UnboundLocalError: local variable 'result' referenced before assignment
2022/09/03 12:01:13 - Thread-4 - ERROR: 请求豆瓣榜单出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 12:01:13 - Thread-4 - ERROR: 获取榜单出错
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/task/mediatrendingtask.py", line 72, in mbot.task.mediatrendingtask.MediaTrendingTask.run
  File "mbot/service/mediametadataservice.py", line 170, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
  File "mbot/media/douban.py", line 626, in mbot.media.douban.DoubanMovie.ranking_list
UnboundLocalError: local variable 'result' referenced before assignment
2022/09/03 12:01:13 - Thread-4 - ERROR: 请求豆瓣榜单出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 12:01:13 - Thread-4 - ERROR: 获取榜单出错
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/task/mediatrendingtask.py", line 72, in mbot.task.mediatrendingtask.MediaTrendingTask.run
  File "mbot/service/mediametadataservice.py", line 170, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
  File "mbot/media/douban.py", line 626, in mbot.media.douban.DoubanMovie.ranking_list
UnboundLocalError: local variable 'result' referenced before assignment
2022/09/03 12:01:14 - Thread-4 - ERROR: 请求豆瓣榜单出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 12:01:14 - Thread-4 - ERROR: 获取榜单出错
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/task/mediatrendingtask.py", line 72, in mbot.task.mediatrendingtask.MediaTrendingTask.run
  File "mbot/service/mediametadataservice.py", line 170, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
  File "mbot/media/douban.py", line 626, in mbot.media.douban.DoubanMovie.ranking_list
UnboundLocalError: local variable 'result' referenced before assignment
2022/09/03 12:01:14 - Thread-4 - ERROR: 请求豆瓣榜单出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 12:01:14 - Thread-4 - ERROR: 获取榜单出错
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/task/mediatrendingtask.py", line 72, in mbot.task.mediatrendingtask.MediaTrendingTask.run
  File "mbot/service/mediametadataservice.py", line 170, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
  File "mbot/media/douban.py", line 626, in mbot.media.douban.DoubanMovie.ranking_list
UnboundLocalError: local variable 'result' referenced before assignment
2022/09/03 12:01:14 - Thread-4 - ERROR: 请求豆瓣榜单出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 12:01:14 - Thread-4 - ERROR: 获取榜单出错
Traceback (most recent call last):
  File "mbot/media/douban.py", line 556, in mbot.media.douban.DoubanMovie.ranking_list
  File "mbot/media/douban.py", line 568, in mbot.media.douban.DoubanMovie.ranking_list
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/task/mediatrendingtask.py", line 72, in mbot.task.mediatrendingtask.MediaTrendingTask.run
  File "mbot/service/mediametadataservice.py", line 170, in mbot.service.mediametadataservice.MovieMetadataService.get_trending_list
  File "mbot/media/douban.py", line 626, in mbot.media.douban.DoubanMovie.ranking_list
UnboundLocalError: local variable 'result' referenced before assignment
2022/09/03 12:01:15 - Thread-4 - INFO: 媒体趋势榜单更新完毕
```

**Comment by 0683X** [comment]
已解决
