### ISSUE TITLE
[提问]: 登录界面闪退

### ISSUE THREAD

**Issue by 0683X** [pofey/movie_robot#687]
### 当前程序版本

1.3.0

### 问题

尝试安装了其他版本，还是一样闪退，请教一下是哪里的问题

### 发生问题时系统日志

```shell
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 19:33:41 - Thread-63 - ERROR: 请求出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 185, in mbot.controller.moviecontroller.douban_suggestion
  File "mbot/media/douban.py", line 639, in mbot.media.douban.DoubanMovie.suggestion
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 19:35:23 - Thread-85 - ERROR: 请求出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 185, in mbot.controller.moviecontroller.douban_suggestion
  File "mbot/media/douban.py", line 639, in mbot.media.douban.DoubanMovie.suggestion
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 19:35:43 - Thread-103 - ERROR: 请求出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 185, in mbot.controller.moviecontroller.douban_suggestion
  File "mbot/media/douban.py", line 639, in mbot.media.douban.DoubanMovie.suggestion
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 19:35:48 - Thread-121 - ERROR: 请求出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 185, in mbot.controller.moviecontroller.douban_suggestion
  File "mbot/media/douban.py", line 639, in mbot.media.douban.DoubanMovie.suggestion
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 19:39:02 - Thread-146 - ERROR: 请求出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 185, in mbot.controller.moviecontroller.douban_suggestion
  File "mbot/media/douban.py", line 639, in mbot.media.douban.DoubanMovie.suggestion
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 19:39:09 - Thread-166 - ERROR: 请求出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 185, in mbot.controller.moviecontroller.douban_suggestion
  File "mbot/media/douban.py", line 639, in mbot.media.douban.DoubanMovie.suggestion
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/09/03 19:39:30 - Thread-183 - ERROR: 请求出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/moviecontroller.py", line 185, in mbot.controller.moviecontroller.douban_suggestion
  File "mbot/media/douban.py", line 639, in mbot.media.douban.DoubanMovie.suggestion
  File "/dependencies/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by pofey** [comment]
你家ip被豆瓣ban了？

**Comment by 0683X** [comment]
这是导致登录一直闪退的原因吗？请问怎么解决？谢谢

**Comment by pofey** [comment]
重新拨号换ip试试
