### ISSUE TITLE
[缺陷]:添加 学校站点报错

### ISSUE THREAD

**Issue by tianjian110** [pofey/movie_robot#690]
### 当前程序版本

1.3.1

### 问题描述

添加学校提示添加失败

### 重现步骤

添加学校站点

### 发生问题时系统日志

```shell
2022/09/04 17:29:21 - Thread-82 - ERROR: 站点设置失败：学校登陆失败！
 stdout 
17:29:21 Traceback (most recent call last):
 stdout 
17:29:21   File "mbot/controller/sitecontroller.py", line 33, in mbot.controller.sitecontroller.save_site
 stdout 
17:29:21   File "mbot/service/siteservice.py", line 419, in mbot.service.siteservice.SiteService.set_site
 stdout 
17:29:21   File "mbot/site/sitehelper.py", line 180, in mbot.site.sitehelper.SiteHelper.get_userinfo
 stdout 
17:29:21   File "mbot/site/siteparser.py", line 29, in mbot.site.siteparser.SiteParser.parse_userinfo
 stdout 
17:29:21 mbot.site.siteexceptions.LoginRequired: 学校登陆失败！
```

### 健康检查

100%

**Comment by pofey** [comment]
删了

**Comment by tianjian110** [comment]
学校不支持了？

**Comment by pofey** [comment]
我没有支持过任何站点

**Comment by tianjian110** [comment]
怎么就我反馈的问题都是不支持的，动漫问题说动漫不支持，综艺问题说不支持综艺，站点添加问题又是不支持站点…………
