### ISSUE TITLE
[缺陷]: 个别订阅不会自动下载

### ISSUE THREAD

**Issue by simon428** [pofey/movie_robot#691]
### 当前程序版本

1.3.1

### 问题描述

订阅“流浪地球”和“昨日的美食 电影版”都遇到订阅成功，但是不会下载的情况，手动搜索有资源。有设置兜底下载规则

### 重现步骤

微信或者webui订阅

### 发生问题时系统日志

```shell
2022/09/05 10:16:22 - SubRequestConsumer - INFO: 新增来自amo的订阅: 昨日的美食 剧场版(2022)
 2022/09/05 10:17:11 - SubConsumer - INFO: 共在26个站点搜索到30条结果，其中兽站最慢，耗费93.52秒
 2022/09/05 10:17:11 - SubConsumer - ERROR: 处理订阅消息出错：This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)
Traceback (most recent call last):
  File "mbot/task/consumer/subconsumer.py", line 207, in mbot.task.consumer.subconsumer.SubConsumer.handle_sub
  File "mbot/task/consumer/subconsumer.py", line 145, in mbot.task.consumer.subconsumer.SubConsumer.__handle_movie__
  File "mbot/task/consumer/subconsumer.py", line 71, in mbot.task.consumer.subconsumer.SubConsumer.search_by_subscribe
  File "mbot/torrent/torrentsystemfilters.py", line 276, in mbot.torrent.torrentsystemfilters.filter_torrents
  File "mbot/torrent/torrentsystemfilters.py", line 83, in mbot.torrent.torrentsystemfilters.filter_torrent_blacklist
  File "mbot/models/blacklistmodel.py", line 28, in mbot.models.blacklistmodel.BlacklistModel.get_torrent_blacklist
```

### 健康检查

![image](https://user-images.githubusercontent.com/59998037/188349090-61175c29-df15-4ad1-96ae-73b0be9bd8ec.png)

**Comment by pofey** [comment]
日志不过
