### ISSUE TITLE
[提问]: 添加下载失败

### ISSUE THREAD

**Issue by shenshangshang** [pofey/movie_robot#692]
### 当前程序版本

1.3.1

### 问题

请问教程里的媒体元数据接口设置在哪呀，我把设置翻遍了也没找到，具体问题是添加下载后下载器中没有开始下载，而且经常搜索不到资源站的资源

### 发生问题时系统日志

```shell
2022/09/05 15:59:29 - tjupt-downloader - INFO: 开始处理来自Web的下载: [tjupt][日本][哆啦A梦：伴我同行2][Stand.by.Me.2.2020.2160p.60FPS.WEB-DL.H265.DDP2.0.2Audio-OurTV]
2022/09/05 15:59:29 - tjupt-downloader - ERROR: 处理下载任务失败：'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "mbot/task/consumer/downloadconsumer.py", line 29, in mbot.task.consumer.downloadconsumer.DownloadConsumer.run
  File "mbot/service/downloadservice.py", line 518, in mbot.service.downloadservice.DownloadService.download_from_web
  File "mbot/service/downloadservice.py", line 526, in mbot.service.downloadservice.DownloadService.download_from_web
AttributeError: 'NoneType' object has no attribute 'startswith'
2022/09/05 15:59:38 - Thread-118 - ERROR: 馒头站点数据更新出错：RetryError[<Future at 0x7f1bd14e2a90 state=finished raised ConnectError>]
Traceback (most recent call last):
  File "/dependencies/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/dependencies/httpcore/backends/sync.py", line 82, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/dependencies/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/dependencies/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/dependencies/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/dependencies/httpcore/_sync/http_proxy.py", line 255, in handle_request
    connect_response = self._connection.handle_request(
  File "/dependencies/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/dependencies/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/dependencies/httpcore/_sync/connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/dependencies/httpcore/backends/sync.py", line 82, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
```

**Comment by pofey** [comment]
元数据已经不需要设置了，你这从哪弄的站点配置文件，看着地址解析有问题
