### ISSUE TITLE
[提问]: 搜索下载报错

### ISSUE THREAD

**Issue by shenshangshang** [pofey/movie_robot#695]
### 当前程序版本

1.3.1

### 问题

手动搜索经常报错，订阅下载就没有问题，不太清楚是什么问题

### 发生问题时系统日志

```shell
2022/09/07 10:53:13 - tjupt-downloader - INFO: 开始处理来自Web的下载: [tjupt][大陆][破事精英][The.Lord.of.Losers.2022.V2.WEB-DL.4k.H.265.AAC-HDCTV]
2022/09/07 10:53:13 - tjupt-downloader - ERROR: 处理下载任务失败：'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "mbot/task/consumer/downloadconsumer.py", line 29, in mbot.task.consumer.downloadconsumer.DownloadConsumer.run
  File "mbot/service/downloadservice.py", line 518, in mbot.service.downloadservice.DownloadService.download_from_web
  File "mbot/service/downloadservice.py", line 526, in mbot.service.downloadservice.DownloadService.download_from_web
AttributeError: 'NoneType' object has no attribute 'startswith'
2022/09/07 10:53:54 - mteam-downloader - INFO: 开始处理来自Web的下载: [mteam]The Lord of Losers 2022 WEB-DL 4k H265 AAC-HDCTV
2022/09/07 10:53:58 - SubConsumer - INFO: 共在2个站点搜索到30条结果，其中馒头最慢，耗费63.23秒
2022/09/07 10:53:59 - SubConsumer - INFO: [tjupt][大陆][破事精英][The.Lord.of.Losers.2022.V2.WEB-DL.4k.H.265.AAC-HDCTV] 破事精英 全24集 | 主演：李佳航 成果 *内封中字*是个全集种子，需要预分析可靠性...
2022/09/07 10:53:59 - SubConsumer - ERROR: 破事精英(2022) 订阅下载出错！
Traceback (most recent call last):
  File "mbot/task/consumer/subconsumer.py", line 223, in mbot.task.consumer.subconsumer.SubConsumer.handle_sub
  File "mbot/task/consumer/subconsumer.py", line 110, in mbot.task.consumer.subconsumer.SubConsumer.__handle_tv__
  File "mbot/torrent/torrentsystemfilters.py", line 208, in mbot.torrent.torrentsystemfilters.find_missing_episodes
  File "mbot/torrent/torrentsystemfilters.py", line 114, in mbot.torrent.torrentsystemfilters.get_ended_torrent
AttributeError: 'NoneType' object has no attribute 'is_disc_folder
```

**Comment by shenshangshang** [comment]
这是自动养站吧，也会报错

<div class="x-grid3-row" role="row" id="ext-gen4943" style="margin: 0px; padding: 0px; cursor: default; border-width: 0px 0px 1px; border-style: solid; border-top-color: initial; border-right-color: initial; border-bottom-color: rgba(198, 212, 224, 0.4); border-left-color: initial; border-image: initial; width: 1647px; background-color: rgb(255, 255, 255); color: rgb(65, 75, 85); font-size: 13px; font-family: Verdana, Arial, &quot;Microsoft YaHei&quot;, sans-serif; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: torrent_info.download_url | stdout
-- | --


</div>
</body>
</html>

**Comment by pofey** [comment]
不知道你为啥没拉到种子下载链接 北洋园 改版了么
