### ISSUE TITLE
[提问]: 下载图片失败，ffmpeg处理失败，emby库通知但不刷新

### ISSUE THREAD

**Issue by AdoShan** [pofey/movie_robot#704]
### 当前程序版本

1.3.0

### 问题

1、我这下载图片经常会失败(添加了代理的变量之后仍旧如此)，目前，失败的话好像并没有通知
2、不知为何通知Emby刷新实际并不会刷新(等了好久都没出现在库里面)
3、目前ffmpeg不知为何解码失败，之前是好着的

### 发生问题时系统日志

```shell
2022/09/10 17:48:03 - Thread-225 - INFO: 内容：/downloads/MovieRobot/Movie/Big.Fish.2003.Remastered.1080p.EUR.Blu-ray.AVC.DTS-HD.MA.5.1-DiY@HDHome 识别为：大鱼 2003-12-25
2022/09/10 17:48:10 - Thread-225 - INFO: 完成电影 大鱼(2003) 的NFO文件生成，路径：/downloads/Emby/Movie/大鱼 (2003) [tmdbid=587]/BDMV/index.nfo
2022/09/10 17:48:10 - Thread-225 - INFO: 开始刮削图片数据，影片信息：{'tmdb_id': 'tt0319061', 'imdb_id': None, 'douban_id': '1291545', 'media_type': 'Movie', 'content_path': '/downloads/Emby/Movie/大鱼 (2003) [tmdbid=587]', 'season_index': None, 'episode_index': None, 'episode_filename': None, 'tvdb_id': None}
2022/09/10 17:48:17 - Thread-225 - INFO: 开始下载图片：https://image.tmdb.org/t/p/original/tjK063yCgaBAluVU72rZ6PKPH2l.jpg 保存至：/downloads/Emby/Movie/大鱼 (2003) [tmdbid=587]/poster.jpg
2022/09/10 17:48:17 - Thread-225 - INFO: 开始下载图片：https://image.tmdb.org/t/p/original/684tP1QeKrgHWvNKlCYpu7zD1cv.png 保存至：/downloads/Emby/Movie/大鱼 (2003) [tmdbid=587]/clearlogo.png
2022/09/10 17:48:17 - Thread-225 - INFO: 开始下载图片：https://image.tmdb.org/t/p/original/bLqUd0tBvKezDr9MEla7k34i3rp.jpg 保存至：/downloads/Emby/Movie/大鱼 (2003) [tmdbid=587]/fanart.jpg
2022/09/10 17:49:21 - Thread-225 - ERROR: 下载电影图片失败
Traceback (most recent call last):
  File "/dependencies/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 501, in _sock_connect
    sock.connect(address)
OSError: [Errno 99] Cannot assign requested address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mbot/media/link/movielink.py", line 125, in mbot.media.link.movielink.MovieLink.__create_nfo__
  File "mbot/metadata/scraper.py", line 228, in mbot.metadata.scraper.Scraper.download_image
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "mbot/metadata/scraper.py", line 112, in __download_image_to_path__
  File "mbot/metadata/scraper.py", line 113, in mbot.metadata.scraper.Scraper.__download_image_to_path__
  File "/dependencies/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/dependencies/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/dependencies/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/dependencies/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/dependencies/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/dependencies/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/dependencies/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host image.tmdb.org:443 ssl:default [Cannot assign requested address]
2022/09/10 17:49:22 - Thread-225 - INFO: 内容：/downloads/MovieRobot/Movie/A Better Tomorrow.1986.TWN.BluRay.1080p.AVC.DTS.HD.5.1-PTsbao@至尊宝.iso 识别为：英雄本色 1986-08-02
2022/09/10 17:49:23 - Thread-225 - ERROR: ffmpeg解码失败：/downloads/Emby/Movie/英雄本色 (1986) [tmdbid=11471]/英雄本色 (1986) [tmdbid=11471] - 1080p AVC DTS Ao.iso
Traceback (most recent call last):
  File "mbot/media/link/movielink.py", line 115, in mbot.media.link.movielink.MovieLink.__create_nfo__
  File "mbot/media/videofileinfo.py", line 89, in mbot.media.videofileinfo.VideoFileInfo.get_video_format
  File "/dependencies/ffmpeg/_probe.py", line 23, in probe
    raise Error('ffprobe', out, err)
ffmpeg._run.Error: ffprobe error (see stderr output for detail)
2022/09/10 17:49:23 - Thread-225 - INFO: 完成电影 英雄本色(1986) 的NFO文件生成，路径：/downloads/Emby/Movie/英雄本色 (1986) [tmdbid=11471]/英雄本色 (1986) [tmdbid=11471] - 1080p AVC DTS Ao.nfo
2022/09/10 17:49:23 - Thread-225 - INFO: 开始刮削图片数据，影片信息：{'tmdb_id': 'tt0092263', 'imdb_id': None, 'douban_id': '1297574', 'media_type': 'Movie', 'content_path': '/downloads/Emby/Movie/英雄本色 (1986) [tmdbid=11471]', 'season_index': None, 'episode_index': None, 'episode_filename': None, 'tvdb_id': None}
2022/09/10 17:49:42 - Thread-225 - INFO: 开始下载图片：https://image.tmdb.org/t/p/original/bvkaWqq2txWdpxJC9tIvF3rbqxJ.jpg 保存至：/downloads/Emby/Movie/英雄本色 (1986) [tmdbid=11471]/poster.jpg
2022/09/10 17:49:42 - Thread-225 - INFO: 开始下载图片：https://image.tmdb.org/t/p/original/m8NHQh1hI3BsnA3DTLnitXl2fyd.png 保存至：/downloads/Emby/Movie/英雄本色 (1986) [tmdbid=11471]/clearlogo.png
2022/09/10 17:49:42 - Thread-225 - INFO: 开始下载图片：https://image.tmdb.org/t/p/original/vXys27x55jF3L3ziYXd1HfT9cFb.jpg 保存至：/downloads/Emby/Movie/英雄本色 (1986) [tmdbid=11471]/fanart.jpg
2022/09/10 17:49:45 - Thread-225 - INFO: Movie图片下载完毕。
```

**Comment by pofey** [comment]
iso 解不了
