### ISSUE TITLE
[提问]: (sqlite3.OperationalError) database is locked

### ISSUE THREAD

**Issue by mymoonyue** [pofey/movie_robot#708]
### 当前程序版本

1.3.2

### 问题

之前总遇到处理免费种子淘汰任务出错：(sqlite3.OperationalError) database is locked
今天又遇到了站点数据更新出错 (sqlite3.OperationalError) database is locked

请问是什么原因？站点cookie更新过了，很多站都报错。

### 发生问题时系统日志

```shell
2022/09/12 16:04:31 - ThreadPoolExecutor-4_2 - ERROR: 北洋园站点数据更新出错：(sqlite3.OperationalError) database is locked
[SQL: UPDATE site SET gmt_modified=? WHERE site.id = ?]
[parameters: ('2022-09-12 16:03:31', 13)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/dependencies/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mbot/task/spidertask.py", line 119, in mbot.task.spidertask.SpiderTask.update_site_data
  File "mbot/service/siteservice.py", line 354, in mbot.service.siteservice.SiteService.update_site_data
  File "mbot/common/basemodel.py", line 99, in mbot.common.basemodel.BaseModel.update
  File "mbot/common/basemodel.py", line 96, in mbot.common.basemodel.BaseModel.update
  File "<string>", line 2, in commit
  File "/dependencies/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/dependencies/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/dependencies/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/dependencies/sqlalchemy/orm/session.py", line 3383, in flush
    self._flush(objects)
  File "/dependencies/sqlalchemy/orm/session.py", line 3523, in _flush
    transaction.rollback(_capture_exception=True)
  File "/dependencies/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/orm/session.py", line 3483, in _flush
    flush_context.execute()
  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/dependencies/sqlalchemy/orm/persistence.py", line 237, in save_obj
    _emit_update_statements(
  File "/dependencies/sqlalchemy/orm/persistence.py", line 1001, in _emit_update_statements
    c = connection._execute_20(
  File "/dependencies/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/dependencies/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/dependencies/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/dependencies/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/dependencies/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: UPDATE site SET gmt_modified=? WHERE site.id = ?]
[parameters: ('2022-09-12 16:03:31', 13)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)



2022/09/12 15:44:52 - ThreadPoolExecutor-4_2 - ERROR: 处理免费种子淘汰任务出错：(sqlite3.OperationalError) database is locked
[SQL: SELECT free_download_record.id AS free_download_record_id, free_download_record.gmt_create AS free_download_record_gmt_create, free_download_record.gmt_modified AS free_download_record_gmt_modified, free_download_record.site_id AS free_download_record_site_id, free_download_record.torrent_id AS free_download_record_torrent_id, free_download_record.name AS free_download_record_name, free_download_record.subject AS free_download_record_subject, free_download_record.size_mb AS free_download_record_size_mb, free_download_record.upload_count AS free_download_record_upload_count, free_download_record.downloading_count AS free_download_record_downloading_count, free_download_record.download_count AS free_download_record_download_count, free_download_record.download_volume_factor AS free_download_record_download_volume_factor, free_download_record.upload_volume_factor AS free_download_record_upload_volume_factor, free_download_record.minimum_ratio AS free_download_record_minimum_ratio, free_download_record.minimum_seed_time AS free_download_record_minimum_seed_time, free_download_record.free_deadline AS free_download_record_free_deadline, free_download_record.torrent_hash AS free_download_record_torrent_hash, free_download_record.delete_status AS free_download_record_delete_status 
FROM free_download_record 
WHERE free_download_record.id = ?]
[parameters: (22071,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/dependencies/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mbot/task/freedownloadmonitortask.py", line 185, in mbot.task.freedownloadmonitortask.FreeDownloadMonitor.run
  File "mbot/task/freedownloadmonitortask.py", line 35, in mbot.task.freedownloadmonitortask.FreeDownloadMonitor.update_data
  File "/dependencies/sqlalchemy/orm/attributes.py", line 482, in __get__
    return self.impl.get(state, dict_)
  File "/dependencies/sqlalchemy/orm/attributes.py", line 942, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/dependencies/sqlalchemy/orm/attributes.py", line 973, in _fire_loader_callables
    return state._load_expired(state, passive)
  File "/dependencies/sqlalchemy/orm/state.py", line 712, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/dependencies/sqlalchemy/orm/loading.py", line 1451, in load_scalar_attributes
    result = load_on_ident(
  File "/dependencies/sqlalchemy/orm/loading.py", line 407, in load_on_ident
    return load_on_pk_identity(
  File "/dependencies/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/dependencies/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/dependencies/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/dependencies/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/dependencies/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/dependencies/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/dependencies/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT free_download_record.id AS free_download_record_id, free_download_record.gmt_create AS free_download_record_gmt_create, free_download_record.gmt_modified AS free_download_record_gmt_modified, free_download_record.site_id AS free_download_record_site_id, free_download_record.torrent_id AS free_download_record_torrent_id, free_download_record.name AS free_download_record_name, free_download_record.subject AS free_download_record_subject, free_download_record.size_mb AS free_download_record_size_mb, free_download_record.upload_count AS free_download_record_upload_count, free_download_record.downloading_count AS free_download_record_downloading_count, free_download_record.download_count AS free_download_record_download_count, free_download_record.download_volume_factor AS free_download_record_download_volume_factor, free_download_record.upload_volume_factor AS free_download_record_upload_volume_factor, free_download_record.minimum_ratio AS free_download_record_minimum_ratio, free_download_record.minimum_seed_time AS free_download_record_minimum_seed_time, free_download_record.free_deadline AS free_download_record_free_deadline, free_download_record.torrent_hash AS free_download_record_torrent_hash, free_download_record.delete_status AS free_download_record_delete_status 
FROM free_download_record 
WHERE free_download_record.id = ?]
[parameters: (22071,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by htnanako** [comment]
换个固态硬盘

**Comment by pofey** [comment]
自己docker映射硬盘目录的问题
