### ISSUE TITLE
[提问]: 处理下载任务失败

### ISSUE THREAD

**Issue by mymoonyue** [pofey/movie_robot#710]
### 当前程序版本

1.3.2

### 问题

mr内搜索后手动下载失败，请问下什么原因

### 发生问题时系统日志

```shell
2022/09/12 18:02:04 - chdbits-downloader - INFO: 开始处理来自Web的下载: [chdbits]House of the Dragon S01 2160p HMAX WEB-DL DDP 5.1 Atmos HDR H.265-Lee@CHDWEB

2022/09/12 18:02:05 - chdbits-downloader - ERROR: 处理下载任务失败：

Traceback (most recent call last):

  File "mbot/task/consumer/downloadconsumer.py", line 29, in mbot.task.consumer.downloadconsumer.DownloadConsumer.run

  File "mbot/service/downloadservice.py", line 520, in mbot.service.downloadservice.DownloadService.download_from_web

  File "mbot/service/downloadservice.py", line 543, in mbot.service.downloadservice.DownloadService.download_from_web

  File "mbot/torrent/downloadclient.py", line 256, in mbot.torrent.downloadclient.QbittorrentClient.download_from_file

  File "mbot/torrent/downloadclient.py", line 257, in mbot.torrent.downloadclient.QbittorrentClient.download_from_file

  File "/dependencies/qbittorrentapi/decorators.py", line 128, in wrapper

    result = func(client, *args, **kwargs)

  File "/dependencies/qbittorrentapi/decorators.py", line 84, in wrapper

    return func(client, *args, **kwargs)

  File "/dependencies/qbittorrentapi/torrents.py", line 1197, in torrents_add

    return self._post(

  File "/dependencies/qbittorrentapi/request.py", line 183, in _post

    return self._request_manager(

  File "/dependencies/qbittorrentapi/request.py", line 231, in _request_manager

    return self._request(**kwargs)

  File "/dependencies/qbittorrentapi/request.py", line 264, in _request

    self._handle_error_responses(api_args, response)

  File "/dependencies/qbittorrentapi/request.py", line 596, in _handle_error_responses

    raise MissingRequiredParameters400Error()

qbittorrentapi.exceptions.MissingRequiredParameters400Error
```

**Comment by pofey** [comment]
不知道
