### ISSUE TITLE
[缺陷]: rarbg搜索出错

### ISSUE THREAD

**Issue by wustyu** [pofey/movie_robot#712]
### 当前程序版本

1.3.36

### 问题描述

rarbg 搜索后台日志提示报错

### 重现步骤

1. 开启rargb
2. 开始搜索

### 发生问题时系统日志

2022/09/15 00:18:05 - Thread-755 - ERROR: 从RARBG搜索 ['报丧女妖'] 失败了，错误信息: object list can't be used in 'await' expression
Traceback (most recent call last):
  File "mbot/site/sitesearcher.py", line 69, in mbot.site.sitesearcher.SiteSearcher.search
    r = await self.site_helper.search(**params)
TypeError: object list can't be used in 'await' expression

### 健康检查

![image](https://user-images.githubusercontent.com/9413400/190301929-549767c8-687b-4449-853a-289b7af46167.png)

**Comment by pofey** [comment]
改完了 下一版beta

**Comment by elic6699** [comment]
新版本rarbg仍旧报错
 2022/09/16 13:02:46 - Thread-1035 - ERROR: 从RARBG搜索 ['game of throne'] 失败了，错误信息: 
Traceback (most recent call last):
  File "mbot/site/sitesearcher.py", line 69, in mbot.site.sitesearcher.SiteSearcher.search
    r = await self.site_helper.search(**params)
  File "mbot/site/rarbg.py", line 121, in search
    raise RateLimitException()
mbot.exceptions.RateLimitException
 2022/09/16 13:02:46 - Thread-1035 - INFO: 共在1个站点搜索到0条结果，其中RARBG最慢，耗费0.52秒
 2022/09/16 13:04:15 - Thread-1050 - INFO: 已经开始在站点(1): RARBG 搜索: tt7631058
 2022/09/16 13:04:16 - Thread-1050 - ERROR: 从RARBG搜索 ['tt7631058'] 失败了，错误信息: 
Traceback (most recent call last):
  File "mbot/site/sitesearcher.py", line 69, in mbot.site.sitesearcher.SiteSearcher.search
    r = await self.site_helper.search(**params)
  File "mbot/site/rarbg.py", line 121, in search
    raise RateLimitException()
mbot.exceptions.RateLimitException
 2022/09/16 13:04:16 - Thread-1050 - INFO: 共在1个站点搜索到0条结果，其中RARBG最慢，耗费0.48秒
