### ISSUE TITLE
[缺陷]: 在搜索时，经常超时无结果，且再次搜索时因资源搜索命中缓存结果而无结果显示

### ISSUE THREAD

**Issue by yzbleaf** [pofey/movie_robot#719]
### 当前程序版本

1.3.1

### 问题描述

在mr搜索时（设置的网站是馒头），经常搜索不到结果，同样的电影名，在馒头官网可以正常搜索到，再次在mr中搜索，会提示“因资源搜索命中缓存结果”还是无结果。

### 重现步骤

网站设置的是馒头，在mr中正常搜索电影名，比如《被掩盖的时间》。

### 发生问题时系统日志

```shell
2022/09/16 19:47:12 - ThreadPoolExecutor-4_0 - INFO: 馒头拉取种子超时，请耐心等待...

2022/09/16 19:49:04 - ThreadPoolExecutor-2_0 - ERROR: 从馒头搜索['被掩盖的时间']失败了 错误：[Errno 104] Connection reset by peer

2022/09/16 19:59:13 - Thread-1470 - INFO: 被掩盖的时间 资源搜索命中缓存结果。

2022/09/16 20:02:32 - ThreadPoolExecutor-2_0 - ERROR: 从馒头搜索['被掩盖的时间']失败了 错误：_ssl.c:1108: The handshake operation timed out

2022/09/16 20:02:12 - ThreadPoolExecutor-4_0 - INFO: 馒头拉取种子超时，请耐心等待...

2022/09/16 20:02:08 - Thread-1624 - INFO: 已经开始在站点: 馒头 搜索: 被掩盖的时间

2022/09/16 20:02:32 - Thread-1624 - INFO: 共在1个站点搜索到0条结果，其中馒头最慢，耗费24.27秒

2022/09/16 20:03:12 - ThreadPoolExecutor-4_0 - INFO: 馒头拉取种子超时，请耐心等待...

```

### 健康检查

健康检查显示绿色的“系统运行状况极好”，与问题无关，就不截图了。

**Comment by pofey** [comment]
升beta

**Comment by yzbleaf** [comment]
> 升beta
已升级到beta，版本为1.3.38，《被掩盖的时间》在mr上仍然搜索不到，在官网可以正常搜索，日志显示如下：

2022/09/16 21:20:52 - Thread-152 - INFO: 已经开始在站点(1): 馒头 搜索: 被掩盖的时间
2022/09/16 21:20:57 - Thread-152 - ERROR: 从馒头搜索 ['被掩盖的时间'] 失败了，错误信息: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dependencies/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/dependencies/httpcore/backends/asyncio.py", line 76, in start_tls
    raise exc
  File "/dependencies/httpcore/backends/asyncio.py", line 67, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "/dependencies/anyio/streams/tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/dependencies/anyio/streams/tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/dependencies/anyio/_backends/_asyncio.py", line 1274, in receive
    raise self._protocol.exception
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/dependencies/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/dependencies/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/dependencies/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/dependencies/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/dependencies/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/dependencies/httpcore/_async/connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "/dependencies/httpcore/backends/asyncio.py", line 76, in start_tls
    raise exc
  File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mbot/site/sitesearcher.py", line 69, in mbot.site.sitesearcher.SiteSearcher.search
    r = await self.site_helper.search(**params)
  File "mbot/site/sitehelper.py", line 247, in search
    async with httpx.AsyncClient(
  File "mbot/site/sitehelper.py", line 256, in mbot.site.sitehelper.SiteHelper.search
    r = await client.get(url)
  File "/dependencies/httpx/_client.py", line 1751, in get
    return await self.request(
  File "/dependencies/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/dependencies/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/dependencies/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/dependencies/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/dependencies/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/dependencies/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError
2022/09/16 21:20:57 - Thread-152 - INFO: 共在1个站点搜索到0条结果，其中馒头最慢，耗费5.01秒

**Comment by pofey** [comment]
网络问题我就帮不了你了 程序没什么问题，自己解决吧

**Comment by yzbleaf** [comment]
> 网络问题我就帮不了你了 程序没什么问题，自己解决吧

原因找到了，在搜索中不能选择全分类，馒头有限制，全勾选会造成并发搜寻，就会搜不到。

**Comment by pofey** [comment]
> > 网络问题我就帮不了你了 程序没什么问题，自己解决吧
> 
> 原因找到了，在搜索中不能选择全分类，馒头有限制，全勾选会造成并发搜寻，就会搜不到。

嗯 还是要自己做分类 针对性的搜
