### ISSUE TITLE
[缺陷]: 字幕下载失败

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#724]
### 当前程序版本

1.3.38

### 问题描述

zmk字幕下载失败

### 重现步骤

zmk字幕下载失败

### 发生问题时系统日志

```shell
2022/09/17 07:19:00 - ThreadPoolExecutor-4_3 - INFO: 非常宣言(2022)字幕下载已经提交启动。
 2022/09/17 07:19:00 - SubtitleFinder - INFO: 收到字幕处理消息：{'task_id': 302, 'content_path': '/video2/电影-jellyfin/非常宣言 (2022) [tmdbid=626872]', 'media_info': {'tmdb_id': 626872, 'type': 'Movie', 'name': '非常宣言', 'year': 2022, 'season_year': None, 'season_index': None, 'episodes': None}}
 2022/09/17 07:19:00 - SubtitleFinder - INFO: 开始在Zimuku搜索 非常宣言
 2022/09/17 07:19:00 - SubtitleFinder - ERROR: Zimuku搜索 非常宣言 异常：Using http2=True, but the 'h2' package is not installed. Make sure to install httpx using `pip install httpx[http2]`.
 2022/09/17 07:19:00 - SubtitleFinder - INFO: 搜索到0条字幕信息
 2022/09/17 07:19:00 - SubtitleFinder - ERROR: 下载字幕出错：'DownloadSubtitleProcess' object has no attribute 'logger'
Traceback (most recent call last):
  File "mbot/task/process/downloadsubtitleprocess.py", line 156, in mbot.task.process.downloadsubtitleprocess.DownloadSubtitleProcess.run
    self.type_download_handler[media_info.type](self, task_id, content_path, media_info)
  File "mbot/task/process/downloadsubtitleprocess.py", line 87, in mbot.task.process.downloadsubtitleprocess.DownloadSubtitleProcess.__download_movie_sub__
    self.logger.info(f'{self.__log_msg_prefix__(media_info)} 现在搜索不到字幕，晚点继续下。')
AttributeError: 'DownloadSubtitleProcess' object has no attribute 'logger'
 2022/09/17 07:19:00 - SubRequestConsumer - INFO: 非常宣言(2022)字幕下载 下次运行时间：2022-09-17 10:04:00
```

### 健康检查

![截屏2022-09-17 10 37 04](https://user-images.githubusercontent.com/105474506/190837464-ba0c2297-4a46-47bb-9611-26ef2b692153.png)
![截屏2022-09-17 10 44 09](https://user-images.githubusercontent.com/105474506/190837559-b409b063-8094-4930-919c-0325349d7802.png)

**Comment by pofey** [comment]
上个版本改出来的bug 下一版发
