### ISSUE TITLE
[缺陷]: 后台日志报错

### ISSUE THREAD

**Issue by wustyu** [pofey/movie_robot#736]
### 当前程序版本

1.3.39

### 问题描述

日志报错

### 重现步骤

查看日志报错

### 发生问题时系统日志

```shell
2022/09/19 17:42:38 - ThreadPoolExecutor-3_0 - ERROR: Job "spider_task (trigger: interval[0:15:53], next run at: 2022-09-19 17:57:35 CST)" raised an exception
Traceback (most recent call last):
  File "/dependencies/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: torrent_info.download_url

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dependencies/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "mbot/register/__init__.py", line 388, in mbot.register.__init__.license_verify.wrapper.decorator
  File "mbot/task/spidertask.py", line 136, in mbot.task.spidertask.SpiderTask.run
  File "mbot/models/basemodel.py", line 99, in mbot.models.basemodel.BaseModel.update
  File "mbot/models/basemodel.py", line 96, in mbot.models.basemodel.BaseModel.update
  File "<string>", line 2, in commit
  File "/dependencies/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/dependencies/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/dependencies/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/dependencies/sqlalchemy/orm/session.py", line 3386, in flush
    self._flush(objects)
  File "/dependencies/sqlalchemy/orm/session.py", line 3526, in _flush
    transaction.rollback(_capture_exception=True)
  File "/dependencies/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/orm/session.py", line 3486, in _flush
    flush_context.execute()
  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/dependencies/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/dependencies/sqlalchemy/orm/persistence.py", line 237, in save_obj
    _emit_update_statements(
  File "/dependencies/sqlalchemy/orm/persistence.py", line 1001, in _emit_update_statements
    c = connection._execute_20(
  File "/dependencies/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/dependencies/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/dependencies/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/dependencies/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/dependencies/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: torrent_info.download_url
[SQL: UPDATE torrent_info SET gmt_modified=?, subject=?, cate_id=?, download_url=? WHERE torrent_info.id = ? AND torrent_info.site_id = ?]
[parameters: ('2022-09-19 17:42:38', '希望没打扰到你', '500', None, 34348, 'pttime')]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

### 健康检查

![image](https://user-images.githubusercontent.com/9413400/190994191-54fdf8a5-ad08-46e1-abb4-7fb23dd5eb43.png)

**Comment by pofey** [comment]
站点适配的问题
