### ISSUE TITLE
[缺陷]: 订阅添加下载失败

### ISSUE THREAD

**Issue by xmumeyu** [pofey/movie_robot#748]
### 当前程序版本

beta 1.4.0

### 问题描述

新安装的机器人，新增订阅成功，但是订阅后系统自动下载失败，在web搜索并下载可以成功下载并入库媒体（下载器运作正常、emby运作正常）。

机器人初次安装1.3.3x失败，手动选择1.3.1版本安装成功，但是订阅下载一直有问题，近期的几个版本都有在持续更新测试，错误一致，特来反馈。

之前运行的老机器人，同样在unraid上运行是正常的。可以正常订阅。

### 重现步骤

1、新安装机器人，新空目录，选择beta版本
2、配置系统，直接提交订阅（包括豆瓣、微信、web提交订阅均可）
3、提示订阅成功
4、提示订阅失败
![image](https://user-images.githubusercontent.com/92902322/191547755-8ae27e0d-0f49-468e-a82b-8f902d9b594c.png)

### 发生问题时系统日志

```shell
2022/09/21 23:12:07 - qywx-search - INFO: 成功从CMDB取得豆瓣编号35700395对应的ID映射关系：{'mediaType': 'Movie', 'doubanId': 35700395, 'doubanSeasonNumber': None, 'tmdbId': 985939, 'imdbId': 'tt15325794', 'tvdbId': None}
2022/09/21 23:12:09 - qywx-search - INFO: 坠落(2022) 选用过滤器：（默认）新国外电影（自动洗版） 排序规则：custom
2022/09/21 23:12:11 - SubConsumer - INFO: 已经开始在站点(5): 观众,彩虹岛,家园,高清时间,我堡 搜索: 坠落,Fall,tt15325794
2022/09/21 23:12:36 - SubConsumer - INFO: 共在5个站点搜索到603条结果，其中彩虹岛最慢，耗费25.3秒
2022/09/21 23:12:37 - SubConsumer - ERROR: 坠落(2022) 订阅下载出错！
Traceback (most recent call last):
  File "mbot/task/consumer/subconsumer.py", line 208, in mbot.task.consumer.subconsumer.SubConsumer.handle_sub
  File "mbot/task/consumer/subconsumer.py", line 158, in mbot.task.consumer.subconsumer.SubConsumer.__handle_movie__
  File "mbot/torrent/torrentuserfilters.py", line 318, in mbot.torrent.torrentuserfilters.filter_torrents_by_config
ValueError: could not convert string to float: ''
2022/09/21 23:15:02 - qywx-search - INFO: 成功从CMDB取得豆瓣编号6424756对应的ID映射关系：{'mediaType': 'Movie', 'doubanId': 6424756, 'doubanSeasonNumber': None, 'tmdbId': 414906, 'imdbId': 'tt1877830', 'tvdbId': None}
2022/09/21 23:15:05 - qywx-search - INFO: 新蝙蝠侠(2022) 选用过滤器：（默认）新国外电影（自动洗版） 排序规则：custom
2022/09/21 23:15:07 - SubConsumer - INFO: 已经开始在站点(5): 观众,彩虹岛,家园,高清时间,我堡 搜索: 新蝙蝠侠,The Batman,tt1877830
2022/09/21 23:15:27 - SubConsumer - INFO: 共在5个站点搜索到305条结果，其中彩虹岛最慢，耗费19.68秒
2022/09/21 23:15:27 - SubConsumer - ERROR: 新蝙蝠侠(2022) 订阅下载出错！
Traceback (most recent call last):
  File "mbot/task/consumer/subconsumer.py", line 208, in mbot.task.consumer.subconsumer.SubConsumer.handle_sub
  File "mbot/task/consumer/subconsumer.py", line 158, in mbot.task.consumer.subconsumer.SubConsumer.__handle_movie__
  File "mbot/torrent/torrentuserfilters.py", line 318, in mbot.torrent.torrentuserfilters.filter_torrents_by_config
ValueError: could not convert string to float: ''
2022/09/21 23:31:32 - SubRequestConsumer - INFO: 成功从CMDB取得豆瓣编号3097572对应的ID映射关系：{'mediaType': 'Movie', 'doubanId': 3097572, 'doubanSeasonNumber': None, 'tmdbId': 453405, 'imdbId': 'tt1025100', 'tvdbId': None}
2022/09/21 23:32:32 - SubRequestConsumer - INFO: 双子杀手(2019) 选用过滤器：（默认）国产电影（不洗版） 排序规则：custom
2022/09/21 23:32:34 - SubRequestConsumer - INFO: 新增来自admin的订阅: 双子杀手(2019) 选用过滤器：（默认）国产电影（不洗版） 排序规则：custom
2022/09/21 23:32:34 - SubConsumer - INFO: 已经开始在站点(5): 观众,彩虹岛,家园,高清时间,我堡 搜索: 双子杀手,Gemini Man,tt1025100
2022/09/21 23:32:53 - SubConsumer - INFO: 共在5个站点搜索到74条结果，其中彩虹岛最慢，耗费18.58秒
2022/09/21 23:32:53 - SubConsumer - ERROR: 双子杀手(2019) 订阅下载出错！
Traceback (most recent call last):
  File "mbot/task/consumer/subconsumer.py", line 208, in mbot.task.consumer.subconsumer.SubConsumer.handle_sub
  File "mbot/task/consumer/subconsumer.py", line 158, in mbot.task.consumer.subconsumer.SubConsumer.__handle_movie__
  File "mbot/torrent/torrentuserfilters.py", line 318, in mbot.torrent.torrentuserfilters.filter_torrents_by_config
ValueError: could not convert string to float: ''
```

### 健康检查

![image](https://user-images.githubusercontent.com/92902322/191549291-8ff8ece6-304d-4e79-9490-0b1c2065c8d0.png)

**Comment by xmumeyu** [comment]
疑似找到问题，衣总看下我有没有猜对。

看代码提示错误行在过滤器

我用的是疯子大佬的最后更新的过滤器版本，在删除了部分关键字后，配置保存成文本文件。

新安装的机器人直接复制的报错过的配置，未做任何修改，直接订阅下载就出错了。

现在，在系统里把每个订阅规则打开后什么都不用修改，直接保存。 订阅已正常工作。

**Comment by pofey** [comment]
看起来是过滤器里某个配置值有错误导致的 但是什么值你能猜到么
