### ISSUE TITLE
[提问]: 最新版升级以后的通知问题

### ISSUE THREAD

**Issue by eriflleh** [pofey/movie_robot#749]
### 当前程序版本

1.4.0

### 问题

升级以后出现mr推送测试可以收到，下载完成后无通知，但是刮削，整理入库无问题，后来整个删除mr重新安装配置，问题依旧

### 发生问题时系统日志

```shell
2022/09/22 11:43:06 - ThreadPoolExecutor-4_0 - ERROR: on_event error: NotifyListener event: {'event_type': 'DownloadCompleted', 'data': {'x_meta': {'id': 100459, 'doubanId': 35235813, 'tmdbId': 758330, 'imdbId': 'tt13352968', 'tvdbId': None, 'gmtModified': '2022-09-01 01:27:16', 'needUpdate': False, 'mediaType': 'Movie', 'title': '祝你好运，里奥·格兰德', 'enTitle': 'Good Luck to You, Leo Grande', 'originalTitle': 'Good Luck to You, Leo Grande', 'intro': '一部关于爱、欲、和满足的喜剧片。艾玛·汤普森饰演的55岁寡妇Nancy Stokes迫切渴望冒险、人类联结和性，渴望她人生中第一次很棒的性爱。丈夫Robert给了她住宅、家庭和看起来像样的生活，然而他已经走了，如今Nancy觉得“连有些修女都比我性生活更 丰富”，她一向是行动派，且当过老师，相当有条理，于是她马上开始实施计划：做了一些研究之后，Nancy雇佣了一个20岁出头的性心理治疗师Leo Grande，准备重启对自己身体的认识。', 'rating': 8.2, 'releaseYear': 2022, 'premiereDate': 20220617, 'duration': 97, 'posterUrl': 'http://assets.fanart.tv/fanart/movies/758330/movieposter/good-luck-to-you-leo-grande-62accead08c43.jpg', 'backgroundUrl': 'http://assets.fanart.tv/fanart/movies/758330/moviebackground/good-luck-to-you-leo-grande-62accee1b01f8.jpg', 'genres': ['剧情', '喜剧', '爱情'], 'country': ['英国']}, 'douban_id': None, 'tmdb_meta': None, 'douban_meta': None, 'target_path': '/downloads/movie2/祝你好运，里奥·格兰德 (2022)', 'sub_id': None, 'uid': '', 'tmdb_id': '758330', 'media_type': 'Movie', 'season_number': None, 'season_year': None, 'year': 2022, 'episodes': None, 'file_size': '1.19 GB', 'media_stream': {'resolution': None, 'media_source': None, 'media_codec': None, 'media_audio': [], 'release_team': None}, 'source_path': '/downloads/movie/祝你好运.里奥.格兰德/Good.Luck.to.You.Leo.Grande.2022.Blu-Ray.1080p.AC3.x265.10bit-Yumi@FRDS.mkv', 'torrent_name': '祝你好运.里奥.格兰德', 'torrent_subject': '', 'torrent_id': 0, 'torrent_hash': '027f79e9eea683298af3a37e0c0e90532778abc1', 'torrent_url': '', 'site_id': 'unknown', 'site_name': None}}

Traceback (most recent call last):
File "mbot/core/eventbus.py", line 65, in mbot.core.eventbus.EventBus.publish_event
File "mbot/plugin/notify/notifylistener.py", line 169, in mbot.plugin.notify.notifylistener.NotifyListener.on_event
File "mbot/plugin/notify/notifylistener.py", line 52, in mbot.plugin.notify.notifylistener.NotifyListener.notify_download_completed
File "mbot/plugin/notify/notifylistener.py", line 33, in mbot.plugin.notify.notifylistener.NotifyListener.send_app_message_by_template_name
ValueError: invalid literal for int() with base 10: ''
2022/09/22 11:43:06 - ThreadPoolExecutor-4_0 - INFO: 祝你好运.里奥.格兰德处理完毕。
```

**Comment by pofey** [comment]
good bug,next version fiex it!
