### ISSUE TITLE
[缺陷]: 提交下载后，日志报错：ERROR: 处理下载任务失败：RetryError

### ISSUE THREAD

**Issue by E4s0N** [pofey/movie_robot#753]
### 当前程序版本

1.4.3

### 问题描述

搜索一部电影，提交下载后，日志报错
`ERROR: 处理下载任务失败：RetryError[<Future at 0x1535fc967820 state=finished raised ReadError>]`

### 重现步骤

1. 在搜索框搜索一部电影
2. 提交下载
3. 日志报错

### 发生问题时系统日志

```shell
2022/09/23 22:30:36 - pterclub-downloader - INFO: 开始处理来自Web的下载: [pterclub]Kingdom of Heaven 2005 DC BluRay 1080P 10bit 3Audio DTS-HD MA 5 1 TrueHD 5 1 x265-beAst
2022/09/23 22:31:55 - pterclub-downloader - ERROR: 处理下载任务失败：RetryError[<Future at 0x1535fc967820 state=finished raised ReadError>]
Traceback (most recent call last):
  File "/dependencies/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/dependencies/httpcore/backends/sync.py", line 26, in read
    return self._sock.recv(max_bytes)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/dependencies/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/dependencies/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/dependencies/httpcore/_sync/connection.py", line 90, in handle_request
    return self._connection.handle_request(request)
  File "/dependencies/httpcore/_sync/http11.py", line 105, in handle_request
    raise exc
  File "/dependencies/httpcore/_sync/http11.py", line 84, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/dependencies/httpcore/_sync/http11.py", line 148, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/dependencies/httpcore/_sync/http11.py", line 177, in _receive_event
    data = self._network_stream.read(
  File "/dependencies/httpcore/backends/sync.py", line 26, in read
    return self._sock.recv(max_bytes)
  File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ReadError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "mbot/thirdparty/tmdbapi.py", line 141, in mbot.thirdparty.tmdbapi.TmdbApi.__do_get__
  File "/dependencies/httpx/_api.py", line 189, in get
    return request(
  File "/dependencies/httpx/_api.py", line 100, in request
    return client.request(
  File "/dependencies/httpx/_client.py", line 815, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/dependencies/httpx/_client.py", line 902, in send
    response = self._send_handling_auth(
  File "/dependencies/httpx/_client.py", line 930, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/dependencies/httpx/_client.py", line 967, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/dependencies/httpx/_client.py", line 1003, in _send_single_request
    response = transport.handle_request(request)
  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mbot/task/consumer/downloadconsumer.py", line 29, in mbot.task.consumer.downloadconsumer.DownloadConsumer.run
  File "mbot/service/downloadservice.py", line 528, in mbot.service.downloadservice.DownloadService.download_from_web
  File "mbot/service/downloadservice.py", line 585, in mbot.service.downloadservice.DownloadService.download_from_web
  File "mbot/service/downloadservice.py", line 292, in mbot.service.downloadservice.DownloadService.analyze_and_setmodel
  File "mbot/media/_scraper.py", line 259, in mbot.media._scraper._Scraper.get_media_image
  File "mbot/thirdparty/tmdbapi.py", line 347, in mbot.thirdparty.tmdbapi.TmdbApi.get_external_ids
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1535fc967820 state=finished raised ReadError>]
2022/09/23 22:32:00 - DownlaodCommander - INFO: 开始处理来自下载器的手动下载记录: Kingdom.of.Heaven.2005.DC.BluRay.1080P.10bit.3Audio.DTS-HD.MA.5.1.TrueHD 5.1.x265-beAst
2022/09/23 22:33:09 - DownlaodCommander - ERROR: 处理下载任务失败：RetryError[<Future at 0x1535c39b2d60 state=finished raised ReadError>]
Traceback (most recent call last):
  File "/dependencies/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/dependencies/httpcore/backends/sync.py", line 26, in read
    return self._sock.recv(max_bytes)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/dependencies/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/dependencies/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/dependencies/httpcore/_sync/connection.py", line 90, in handle_request
    return self._connection.handle_request(request)
  File "/dependencies/httpcore/_sync/http11.py", line 105, in handle_request
    raise exc
  File "/dependencies/httpcore/_sync/http11.py", line 84, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/dependencies/httpcore/_sync/http11.py", line 148, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/dependencies/httpcore/_sync/http11.py", line 177, in _receive_event
    data = self._network_stream.read(
  File "/dependencies/httpcore/backends/sync.py", line 26, in read
    return self._sock.recv(max_bytes)
  File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ReadError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dependencies/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "mbot/thirdparty/tmdbapi.py", line 141, in mbot.thirdparty.tmdbapi.TmdbApi.__do_get__
  File "/dependencies/httpx/_api.py", line 189, in get
    return request(
  File "/dependencies/httpx/_api.py", line 100, in request
    return client.request(
  File "/dependencies/httpx/_client.py", line 815, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/dependencies/httpx/_client.py", line 902, in send
    response = self._send_handling_auth(
  File "/dependencies/httpx/_client.py", line 930, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/dependencies/httpx/_client.py", line 967, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/dependencies/httpx/_client.py", line 1003, in _send_single_request
    response = transport.handle_request(request)
  File "/dependencies/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/dependencies/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mbot/task/consumer/downloadcommanderconsumer.py", line 30, in mbot.task.consumer.downloadcommanderconsumer.DownloadCommanderConsumer.run
  File "mbot/service/downloadservice.py", line 264, in mbot.service.downloadservice.DownloadService.new_download_record
  File "mbot/service/downloadservice.py", line 292, in mbot.service.downloadservice.DownloadService.analyze_and_setmodel
  File "mbot/media/_scraper.py", line 286, in mbot.media._scraper._Scraper.get_media_image
  File "mbot/thirdparty/tmdbapi.py", line 298, in mbot.thirdparty.tmdbapi.TmdbApi.get_media_image
  File "mbot/thirdparty/tmdbapi.py", line 268, in mbot.thirdparty.tmdbapi.TmdbApi.get_images
  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1535c39b2d60 state=finished raised ReadError>]
```

### 健康检查

<img width="1406" alt="截屏2022-09-23 22 49 34" src="https://user-images.githubusercontent.com/109868048/191988952-0d2fc0c3-641c-4f88-a3af-a89438ec8c47.png">

**Comment by pofey** [comment]
福建泉州？

**Comment by E4s0N** [comment]
是啊😂

**Comment by pofey** [comment]
屏蔽未备案网站…等我看看把备案的解析到香港吧，在此之前只能用梯子

**Comment by E4s0N** [comment]
现在新版的MR里面移除了代理选项，应该怎么样添加呢？
