### ISSUE TITLE
[缺陷]: 资源整理剧集选择报错

### ISSUE THREAD

**Issue by sinosofti** [pofey/movie_robot#758]
### 当前程序版本

beta 1.4.9

### 问题描述

选择资源整理剧集然后选择 公共动漫报错 页面变成空白的
除了选择公共动漫之外 选择 公共综艺、emby_tv、emby_mv等都正常
![image](https://user-images.githubusercontent.com/38282416/192774700-83c0f37e-e49b-46f9-93d6-7065d5f53afd.png)
![image](https://user-images.githubusercontent.com/38282416/192774409-d64508d2-d817-479d-b5e1-52915dd034de.png)

### 重现步骤

1

### 发生问题时系统日志

```shell
2022/09/28 20:01:20 - Thread-151 - ERROR: 请求出错：'str' object has no attribute 'get'
Traceback (most recent call last):
  File "mbot/register/controller_register.py", line 33, in mbot.register.controller_register.login_required.wrapper.decorator
  File "mbot/controller/mediacontroller.py", line 103, in mbot.controller.mediacontroller.get_media_library
  File "mbot/media/medialibrary.py", line 210, in mbot.media.medialibrary.MediaLibrary.init_media_item
  File "mbot/media/medialibrary.py", line 184, in mbot.media.medialibrary.MediaLibrary.parse_path
  File "mbot/media/_mediaparser.py", line 745, in mbot.media._mediaparser._MediaParser.is_collection
AttributeError: 'str' object has no attribute 'get'
```

### 健康检查

1

**Comment by pofey** [comment]
bug
