### ISSUE TITLE
[提问]: 下载完成后转移文件失败

### ISSUE THREAD

**Issue by youzongku** [pofey/movie_robot#760]
### 当前程序版本

1.4.12

### 问题

使用的是win docker desktop，下载完成后识别整理资源出现错误，配置应该都没问题
![uTools_1664412106212](https://user-images.githubusercontent.com/30069162/192913577-198d0a26-66fb-497b-a3de-77602c3e7117.png)
![uTools_1664412166660](https://user-images.githubusercontent.com/30069162/192913601-6eec55b3-6a78-42c5-b4ac-5960c6a5d7c6.png)
![uTools_1664412261721](https://user-images.githubusercontent.com/30069162/192913632-7889ddb6-372e-4f1c-8c7b-ace767e0b28d.png)
![uTools_1664412354013](https://user-images.githubusercontent.com/30069162/192913640-0316af45-c7c2-4ec6-8176-73189022ee8e.png)
![uTools_1664412504056](https://user-images.githubusercontent.com/30069162/192913774-5cc7dac9-a519-4275-98c8-0300e3b3c318.png)
![uTools_1664412526100](https://user-images.githubusercontent.com/30069162/192913786-98b98bd6-fe6e-4d5c-945f-c48bfb74b448.png)

### 发生问题时系统日志

```shell
2022/09/29 08:44:00 - ThreadPoolExecutor-3_2 - ERROR: 文件转移失败：找不到内容路径或无权限访问：/Thirteen.Lives.2022.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-CMRG.mkv
2022/09/29 08:44:00 - ThreadPoolExecutor-3_2 - ERROR: 监控种子任务出现错误：找不到内容路径或无权限访问：/Thirteen.Lives.2022.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-CMRG.mkv
Traceback (most recent call last):
  File "mbot/task/monitortorrenttask.py", line 48, in mbot.task.monitortorrenttask.MonitorTorrentTask.run
  File "mbot/service/downloadservice.py", line 446, in mbot.service.downloadservice.DownloadService.download_completed
  File "mbot/service/downloadservice.py", line 411, in mbot.service.downloadservice.DownloadService.download_completed
  File "mbot/service/filemanagerservice.py", line 65, in mbot.service.filemanagerservice.FileManagerService.link
  File "mbot/media/link/movielink.py", line 26, in mbot.media.link.movielink.MovieLink.__init__
  File "mbot/media/link/medialink.py", line 92, in mbot.media.link.medialink.MediaLink.__init__
FileNotFoundError: 找不到内容路径或无权限访问：/Thirteen.Lives.2022.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-CMRG.mkv
2022/09/29 08:45:00 - ThreadPoolExecutor-3_0 - ERROR: 文件转移失败：找不到内容路径或无权限访问：/Thirteen.Lives.2022.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-CMRG.mkv
2022/09/29 08:45:00 - ThreadPoolExecutor-3_0 - ERROR: 监控种子任务出现错误：找不到内容路径或无权限访问：/Thirteen.Lives.2022.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-CMRG.mkv
Traceback (most recent call last):
  File "mbot/task/monitortorrenttask.py", line 48, in mbot.task.monitortorrenttask.MonitorTorrentTask.run
  File "mbot/service/downloadservice.py", line 446, in mbot.service.downloadservice.DownloadService.download_completed
  File "mbot/service/downloadservice.py", line 411, in mbot.service.downloadservice.DownloadService.download_completed
  File "mbot/service/filemanagerservice.py", line 65, in mbot.service.filemanagerservice.FileManagerService.link
  File "mbot/media/link/movielink.py", line 26, in mbot.media.link.movielink.MovieLink.__init__
  File "mbot/media/link/medialink.py", line 92, in mbot.media.link.medialink.MediaLink.__init__
FileNotFoundError: 找不到内容路径或无权限访问：/Thirteen.Lives.2022.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-CMRG.mkv
2022/09/29 08:45:41 - ThreadPoolExecutor-3_1 - INFO: 开始同步站点资源信息...
2022/09/29 08:46:00 - ThreadPoolExecutor-3_3 - ERROR: 文件转移失败：找不到内容路径或无权限访问：/Thirteen.Lives.2022.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-CMRG.mkv
2022/09/29 08:46:00 - ThreadPoolExecutor-3_3 - ERROR: 监控种子任务出现错误：找不到内容路径或无权限访问：/Thirteen.Lives.2022.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-CMRG.mkv
Traceback (most recent call last):
  File "mbot/task/monitortorrenttask.py", line 48, in mbot.task.monitortorrenttask.MonitorTorrentTask.run
  File "mbot/service/downloadservice.py", line 446, in mbot.service.downloadservice.DownloadService.download_completed
  File "mbot/service/downloadservice.py", line 411, in mbot.service.downloadservice.DownloadService.download_completed
  File "mbot/service/filemanagerservice.py", line 65, in mbot.service.filemanagerservice.FileManagerService.link
  File "mbot/media/link/movielink.py", line 26, in mbot.media.link.movielink.MovieLink.__init__
  File "mbot/media/link/medialink.py", line 92, in mbot.media.link.medialink.MediaLink.__init__
FileNotFoundError: 找不到内容路径或无权限访问：/Thirteen.Lives.2022.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-CMRG.mkv
```

**Comment by pofey** [comment]
你自己进容器看看报错的路径在么

**Comment by youzongku** [comment]
> 你自己进容器看看报错的路径在么

主要是我没配置这个路径，订阅下载都成功了，有没可能路径识别问题？上面那个截图的内容路径那里有个\/

**Comment by pofey** [comment]
> > 你自己进容器看看报错的路径在么
> 
> `主要是我没配置这个路径，订阅下载都成功了，有没可能路径识别问题？上面那个截图的内容路径那里有个‘\/’`

那就是历史下载记录，给删了就行

**Comment by youzongku** [comment]
> > > 你自己进容器看看报错的路径在么
> > 
> > 
> > `主要是我没配置这个路径，订阅下载都成功了，有没可能路径识别问题？上面那个截图的内容路径那里有个‘\/’`
> 
> 那就是历史下载记录，给删了就行

应该不是历史记录的问题，我重新订阅下载试过好几次，一样的报错
