### ISSUE TITLE
[缺陷]: 龙之家族第一季第四集下载失败[彩虹岛]

### ISSUE THREAD

**Issue by jasonhorga** [pofey/movie_robot#766]
### 当前程序版本

1.5.7

### 问题描述

龙之家族彩虹岛第一季第四集下载失败

### 重现步骤

此链接下载失败(https://chdbits.co/details.php?id=207002&hit=1)

### 发生问题时系统日志

```shell
2022/10/08 22:08:29 - chdbits-downloader - INFO: [chdbits]House of the Dragon S01 2160p HMAX WEB-DL DDP 5.1 Atmos HDR H.265-Lee@CHDWEB提交下载失败: 
Traceback (most recent call last):
  File "mbot/service/downloadservice.py", line 692, in mbot.service.downloadservice.DownloadService.download_from_sub
  File "mbot/service/downloadservice.py", line 707, in mbot.service.downloadservice.DownloadService.download_from_sub
  File "mbot/service/downloadservice.py", line 655, in mbot.service.downloadservice.DownloadService.__check_and_submit_download__
  File "mbot/torrent/downloadclient.py", line 256, in mbot.torrent.downloadclient.QbittorrentClient.download_from_file
  File "mbot/torrent/downloadclient.py", line 257, in mbot.torrent.downloadclient.QbittorrentClient.download_from_file
  File "/dependencies/qbittorrentapi/decorators.py", line 135, in wrapper
    result = func(client, *args, **kwargs)
  File "/dependencies/qbittorrentapi/decorators.py", line 92, in wrapper
    return func(client, *args, **kwargs)
  File "/dependencies/qbittorrentapi/torrents.py", line 1203, in torrents_add
    return self._post(
  File "/dependencies/qbittorrentapi/request.py", line 350, in _post
    return self._request_manager(
  File "/dependencies/qbittorrentapi/request.py", line 401, in _request_manager
    return self._request(**kwargs)
  File "/dependencies/qbittorrentapi/request.py", line 463, in _request
    self._handle_error_responses(data, params, response)
  File "/dependencies/qbittorrentapi/request.py", line 634, in _handle_error_responses
    raise MissingRequiredParameters400Error()
qbittorrentapi.exceptions.MissingRequiredParameters400Error
2022/10/08 22:08:29 - chdbits-downloader - INFO: 开始处理来自订阅的下载: [chdbits]House of the Dragon S01 2160p HMAX WEB-DL DDP 5.1 Atmos HDR H.265-Lee@CHDWEB
```

### 健康检查

下载龙之家族，第一集从mteam下载，后面几集从chdbits下载，不知道什么逻辑，是不是可以把排序的得分也列一下

**Comment by pofey** [comment]
qbittorrentapi.exceptions.MissingRequiredParameters400Error

这是最近变更过qbit？

**Comment by jasonhorga** [comment]
只有这一个link无法下载，也是很奇怪，我手动试了一下也不行，其他种子都对

**Comment by pofey** [comment]
这也看不出来是缺啥参数

**Comment by jasonhorga** [comment]
怎么看呢，还能更详细debug么，你能下载这个torrent么


何佳

在 2022年10月9日，00:49，yipengfei ***@***.***> 写道：

﻿

这也看不出来是缺啥参数

**Comment by pofey** [comment]
我跟你一样的这个种子报错，也是qbittorrentapi.exceptions.MissingRequiredParameters400Error
debug看了参数提交给qbit的信息跟其他种子一样，qbit也没给出更多错误细节

**Comment by pofey** [comment]
你可以试试，手动下载这个种子，直接提交到qbit，也是一样的报错

**Comment by jasonhorga** [comment]
那估计还是pt或者qb的问题，不是mr的问题，关闭了
