### ISSUE TITLE
[缺陷]: 订阅下载错误 & 淘汰免费种子 database错误

### ISSUE THREAD

**Issue by jasonhorga** [pofey/movie_robot#768]
### 当前程序版本

1.6.0

### 问题描述

订阅下载错误，不知道是不是网络问题

### 重现步骤

这个...

### 发生问题时系统日志

```shell
2022/10/09 17:41:31 - SubConsumer - ERROR: 错误码：400004 错误消息：媒体服务器访问异常
2022/10/09 17:41:31 - SubConsumer - ERROR: 天空之眼(2016) 订阅下载出错！
Traceback (most recent call last):
  File "/dependencies/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/dependencies/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/dependencies/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/dependencies/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/dependencies/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/dependencies/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/dependencies/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa588d12820>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/dependencies/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/dependencies/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='horga.xyz', port=8096): Max retries exceeded with url: /emby/Items?AnyProviderIdEquals=tmdb.333352&Recursive=true&api_key=fdccdbca914c412fbd6f6c9f66c1136e (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa588d12820>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/service/smartdownloadservice.py", line 49, in mbot.service.smartdownloadservice.SmartDownloadService.exists
  File "mbot/media/server/embymediaserver.py", line 134, in mbot.media.server.embymediaserver.EmbyMediaServer.search_by_id
  File "mbot/media/server/embymediaserver.py", line 49, in mbot.media.server.embymediaserver.EmbyMediaServer.__do_get__
  File "/dependencies/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/dependencies/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/dependencies/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/dependencies/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/dependencies/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='horga.xyz', port=8096): Max retries exceeded with url: /emby/Items?AnyProviderIdEquals=tmdb.333352&Recursive=true&api_key=fdccdbca914c412fbd6f6c9f66c1136e (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa588d12820>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/task/consumer/subconsumer.py", line 222, in mbot.task.consumer.subconsumer.SubConsumer.handle_sub
  File "mbot/service/smartdownloadservice.py", line 52, in mbot.service.smartdownloadservice.SmartDownloadService.exists
mbot.exceptions.MediaServerError: 无法正常从媒体服务器搜索影片，tmdb_id: 333352 season_number: None
```

### 健康检查

这个...

**Comment by jasonhorga** [comment]
还发现了一个错误

```
2022/10/09 05:12:00 - SubConsumer - ERROR: 错误码：400004 错误消息：媒体服务器访问异常
 2022/10/09 05:12:00 - SubConsumer - ERROR: 龙之家族(2022) 订阅下载出错！
Traceback (most recent call last):
  File "/dependencies/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/dependencies/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/dependencies/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/dependencies/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/dependencies/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/dependencies/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/dependencies/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f35fc3e58b0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/dependencies/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/dependencies/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='horga.xyz', port=8096): Max retries exceeded with url: /emby/Shows/64458/Episodes?api_key=fdccdbca914c412fbd6f6c9f66c1136e (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f35fc3e58b0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/service/smartdownloadservice.py", line 81, in mbot.service.smartdownloadservice.SmartDownloadService.get_missing_episodes
  File "mbot/media/server/embymediaserver.py", line 405, in mbot.media.server.embymediaserver.EmbyMediaServer.get_missing_episodes
  File "mbot/media/server/embymediaserver.py", line 355, in mbot.media.server.embymediaserver.EmbyMediaServer.get_episodes
  File "mbot/media/server/embymediaserver.py", line 49, in mbot.media.server.embymediaserver.EmbyMediaServer.__do_get__
  File "/dependencies/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/dependencies/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/dependencies/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/dependencies/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/dependencies/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='horga.xyz', port=8096): Max retries exceeded with url: /emby/Shows/64458/Episodes?api_key=fdccdbca914c412fbd6f6c9f66c1136e (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f35fc3e58b0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/task/consumer/subconsumer.py", line 233, in mbot.task.consumer.subconsumer.SubConsumer.handle_sub
  File "mbot/service/smartdownloadservice.py", line 86, in mbot.service.smartdownloadservice.SmartDownloadService.get_missing_episodes
mbot.exceptions.MediaServerError: 无法正常从媒体服务器读取剧集信息，tmdb_id: 94997 season_number: 1
```

**Comment by jasonhorga** [comment]
另外，处理免费任务的database is locked是不是不用管，会自动好的吧？

```
2022/10/09 06:10:49 - ThreadPoolExecutor-3_5 - ERROR: 处理免费种子淘汰任务出错：(sqlite3.OperationalError) database is locked
[SQL: SELECT free_download_record.id AS free_download_record_id, free_download_record.gmt_create AS free_download_record_gmt_create, free_download_record.gmt_modified AS free_download_record_gmt_modified, free_download_record.site_id AS free_download_record_site_id, free_download_record.torrent_id AS free_download_record_torrent_id, free_download_record.name AS free_download_record_name, free_download_record.subject AS free_download_record_subject, free_download_record.size_mb AS free_download_record_size_mb, free_download_record.upload_count AS free_download_record_upload_count, free_download_record.downloading_count AS free_download_record_downloading_count, free_download_record.download_count AS free_download_record_download_count, free_download_record.download_volume_factor AS free_download_record_download_volume_factor, free_download_record.upload_volume_factor AS free_download_record_upload_volume_factor, free_download_record.minimum_ratio AS free_download_record_minimum_ratio, free_download_record.minimum_seed_time AS free_download_record_minimum_seed_time, free_download_record.free_deadline AS free_download_record_free_deadline, free_download_record.torrent_hash AS free_download_record_torrent_hash, free_download_record.delete_status AS free_download_record_delete_status 
FROM free_download_record 
WHERE free_download_record.delete_status = ?]
[parameters: (0,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/dependencies/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mbot/task/freedownloadmonitortask.py", line 182, in mbot.task.freedownloadmonitortask.FreeDownloadMonitor.run
  File "mbot/models/freedownloadmodel.py", line 45, in mbot.models.freedownloadmodel.FreeDownloadModel.list_by_status
  File "/dependencies/sqlalchemy/orm/query.py", line 2772, in all
    return self._iter().all()
  File "/dependencies/sqlalchemy/orm/query.py", line 2907, in _iter
    result = self.session.execute(
  File "/dependencies/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/dependencies/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/dependencies/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/dependencies/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/dependencies/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/dependencies/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT free_download_record.id AS free_download_record_id, free_download_record.gmt_create AS free_download_record_gmt_create, free_download_record.gmt_modified AS free_download_record_gmt_modified, free_download_record.site_id AS free_download_record_site_id, free_download_record.torrent_id AS free_download_record_torrent_id, free_download_record.name AS free_download_record_name, free_download_record.subject AS free_download_record_subject, free_download_record.size_mb AS free_download_record_size_mb, free_download_record.upload_count AS free_download_record_upload_count, free_download_record.downloading_count AS free_download_record_downloading_count, free_download_record.download_count AS free_download_record_download_count, free_download_record.download_volume_factor AS free_download_record_download_volume_factor, free_download_record.upload_volume_factor AS free_download_record_upload_volume_factor, free_download_record.minimum_ratio AS free_download_record_minimum_ratio, free_download_record.minimum_seed_time AS free_download_record_minimum_seed_time, free_download_record.free_deadline AS free_download_record_free_deadline, free_download_record.torrent_hash AS free_download_record_torrent_hash, free_download_record.delete_status AS free_download_record_delete_status 
FROM free_download_record 
WHERE free_download_record.delete_status = ?]
[parameters: (0,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by jasonhorga** [comment]
哦，还有个iso的问题
```
 2022/10/09 23:07:53 - ThreadPoolExecutor-3_4 - ERROR: ffmpeg解码失败：/video/movie/官方机密 (2019)/官方机密 (2019) - 1080p Remux HDS.iso
Traceback (most recent call last):
  File "mbot/media/link/movielink.py", line 115, in mbot.media.link.movielink.MovieLink.__create_nfo__
  File "mbot/media/videofileinfo.py", line 89, in mbot.media.videofileinfo.VideoFileInfo.get_video_format
  File "/dependencies/ffmpeg/_probe.py", line 23, in probe
    raise Error('ffprobe', out, err)
ffmpeg._run.Error: ffprobe error (see stderr output for detail)
 2022/10/09 23:07:53 - ThreadPoolExecutor-3_4 - INFO: 完成电影 官方机密(2019) 的NFO文件生成，路径：/video/movie/官方机密 (2019)/官方机密 (2019) - 1080p Remux HDS.nfo

```
