### ISSUE TITLE
[缺陷]: 首页无法显示

### ISSUE THREAD

**Issue by AAlexDing** [pofey/movie_robot#770]
### 当前程序版本

1.6.6

### 问题描述

首页无法显示
![image](https://user-images.githubusercontent.com/30212143/195291922-35824d4b-b1c8-4802-8c9e-fd5ce68d597a.png)

### 重现步骤

1.打开首页
2.首页加载了侧栏和顶部日历以后整个页面就白了

### 发生问题时系统日志

```shell
2022/10/12 16:21:09 - Thread-26 - ERROR: 请求出错：'NoneType' object has no attribute 'get'

Traceback (most recent call last):
File "mbot/register/controller_register.py", line 33, in mbot.register.controller_register.login_required.wrapper.decorator
File "mbot/controller/moviecontroller.py", line 195, in mbot.controller.moviecontroller.douban_suggestion

AttributeError: 'NoneType' object has no attribute 'get'
```

### 健康检查

![image](https://user-images.githubusercontent.com/30212143/195292232-b1b0a82a-dcde-45d9-83e9-66f59530005e.png)

**Comment by pofey** [comment]
看下公告
