### ISSUE TITLE
订阅后下载出错

### ISSUE THREAD

**Issue by apple4105** [pofey/movie_robot#775]
### 当前程序版本

1.6.19

### 问题描述

订阅后，订阅下载出错，剧名是《黑话律师》

### 重现步骤

删除订阅重新搜索订阅，问题依旧

### 发生问题时系统日志

```shell
`2022/10/27 21:41:22 - INFO: 开始处理剧集订阅：绝命辩护
2022/10/27 21:41:22 - INFO: 开始使用订阅的元数据，搜索资源: [{'key': 'keyword', 'value': '绝命辩护', 'value_type': 'cn_name'}, {'key': 'keyword', 'value': 'Big Mouth', 'value_type': 'en_name'}, {'key': 'imdb_id', 'value': 'tt21195490', 'value_type': 'imdb_id'}]
2022/10/27 21:41:22 - INFO: 剧集搜索分类为：[<CateLevel1.TV: '剧集'>, <CateLevel1.Anime: '动漫'>, <CateLevel1.Documentary: '纪录片'>]
2022/10/27 21:41:22 - INFO: 搜索远程站点查找所需资源
2022/10/27 21:41:48 - INFO: 开始对资源搜索结果进行分析，找到匹配订阅的资源
2022/10/27 21:41:48 - INFO: 开始分析种子列表中媒体类型是否为 TV
2022/10/27 21:41:48 - INFO: 媒体类型过滤器完成，过滤前42个种子，过滤后42个
2022/10/27 21:41:48 - INFO: 开始进行季度信息筛选，需要第1季
2022/10/27 21:41:48 - INFO: 季度信息分析过滤完毕，过滤前42个种子，过滤后42个
2022/10/27 21:41:48 - INFO: 开始使用中文、英文名、其他别名，对种子进行筛选，正确片名：{'律战江湖(港)', '黑话律师', 'Big Mouth', '绝命辩护', '贱口律师'}
2022/10/27 21:41:48 - INFO: 中英文影片名种子筛选结束，过滤前42个种子，过滤后42个
2022/10/27 21:41:48 - INFO: 开始分析种子包含的年份信息是否等于所需的[2022, 2022]
2022/10/27 21:41:48 - INFO: 完成年份过滤 过滤前：42个 过滤后：42个
2022/10/27 21:41:48 - INFO: 开始对筛选后的资源结果，用compress规则排序，特别优先关键字：[]
2022/10/27 21:41:48 - INFO: 开始查找本地媒体库缺失的分集资源：{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}
2022/10/27 21:41:48 - INFO: 所需电视剧的总集数为：16
2022/10/27 21:41:48 - INFO: 分析种子列表中单集资源文件的平均大小为：3045.7173333333335
2022/10/27 21:41:48 - INFO: 单集资源不能完全覆盖本地媒体库缺失的分集资源，刚好有完结的剧集包，将选择有效的完结剧集进行下载
2022/10/27 21:41:48 - INFO: [btschool]Big Mouth S01 2022 Disney+ WEB-DL 1080p H.264 AAC-HDCTV 韩剧 黑话律师 全16集 | 主演：李钟硕 林允儿 *内封中字*是个全集种子，需要预分析可靠性...
2022/10/27 21:41:52 - ERROR: 绝命辩护(2022) 订阅下载出错！
Traceback (most recent call last):
  File "mbot/task/consumer/subconsumer.py", line 247, in mbot.task.consumer.subconsumer.SubConsumer.handle_sub
  File "mbot/task/consumer/subconsumer.py", line 125, in mbot.task.consumer.subconsumer.SubConsumer.__handle_tv__
  File "mbot/torrent/torrentsystemfilters.py", line 233, in mbot.torrent.torrentsystemfilters.find_missing_episodes
  File "mbot/torrent/torrentsystemfilters.py", line 130, in mbot.torrent.torrentsystemfilters.get_ended_torrent
  File "mbot/torrent/torrentfileinfo.py", line 54, in mbot.torrent.torrentfileinfo.TorrentFileInfo.is_disc_folder
  File "mbot/torrent/torrentfileinfo.py", line 68, in mbot.torrent.torrentfileinfo.TorrentFileInfo.parse_files
  File "mbot/torrent/torrentfileinfo.py", line 32, in mbot.torrent.torrentfileinfo.TorrentFileInfo.info_hash
  File "mbot/torrent/torrentfileinfo.py", line 27, in mbot.torrent.torrentfileinfo.TorrentFileInfo.info_hash
  File "mbot/torrent/torrentfileinfo.py", line 28, in mbot.torrent.torrentfileinfo.TorrentFileInfo.info_hash
  File "/dependencies/bencoder.py", line 93, in decode
    ret, rest = decode_first(s)
  File "/dependencies/bencoder.py", line 88, in decode_first
    assert False
AssertionError`
```

### 健康检查

![WX20221027-065310](https://user-images.githubusercontent.com/42332443/198303743-053c99ca-3e97-4a18-8403-bd3f7fe080bb.png)

**Comment by pofey** [comment]
下载失败
