### ISSUE TITLE
[缺陷]: 下载完成后，文件整理失败

### ISSUE THREAD

**Issue by kolicime** [pofey/movie_robot#780]
### 当前程序版本

1.7.0（猜测是1.6.40版本开始出现的问题）

### 问题描述

自定义订阅下载到的文件整理失败，整理方式为复制到目标文件夹（google drive挂载），但到“资源整理”中手动整理却可以正常工作

### 重现步骤

并未额外做什么步骤。但根据google drive的操作记录，可以看到是在10月27日晚上十点多之后就没有新文件上传了（在当天晚上十一点半升级到了1.6.40版本）。但是期间订阅在正常下载和通知，所以也没有在第一时间发现。
下面日志为同一剧集的不同版本，是两个不同的种子。

### 发生问题时系统日志

```shell
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - INFO: 来自自定义订阅的下载，tmdb_id: 0 season_number:  douban_id: 0
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - INFO: 启用自动重命名整理
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - ERROR: 整理失败：'<' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "mbot/media/link/medialink.py", line 202, in mbot.media.link.medialink.MediaLink.link
  File "mbot/media/link/tvlink.py", line 357, in mbot.media.link.tvlink.TvLink.__handle__
  File "mbot/media/_mediarecognize.py", line 424, in mbot.media._mediarecognize._MediaRecognize.recognize_tv
  File "mbot/media/_mediarecognize.py", line 227, in mbot.media._mediarecognize._MediaRecognize.__search_query__
  File "mbot/media/_mediarecognize.py", line 171, in mbot.media._mediarecognize._MediaRecognize.__tv_multiple_result_filter__
TypeError: '<' not supported between instances of 'str' and 'int'
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - INFO: 已经通知plex重新扫描媒体库：动画
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - INFO: 通知媒体库刷新完成，tmdb_id: 97525 save_path: /plex/temp/动画-mr item_id: 2:致不灭的你
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - INFO: 致不灭的你 第季(2022) 第2集字幕下载 任务已经创建。
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - ERROR: Invalid data for service call scraper.get_image: {'tmdb_id': 97525, 'media_type': 'tv', 'season_number': ''}
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - ERROR: on_event error: NotifyListener event: {'event_type': 'DownloadCompleted', 'data': {'target_path': '/plex/temp/动画-mr', 'sub_id': 1, 'uid': '1', 'tmdb_id': '97525', 'media_type': 'TV', 'season_number': '', 'season_year': 2022, 'year': 2022, 'episodes': [2], 'file_size': '1.42 GB', 'media_stream': {'resolution': '1080p', 'media_source': 'WEB-DL', 'media_codec': 'x264', 'media_audio': ['AAC'], 'release_team': 'ADWeb'}, 'source_path': '/plex/download/动画/Fumetsu.no.Anata.e.S02.2022.1080p.CR.WEB-DL.x264.AAC-ADWeb/Fumetsu.no.Anata.e.S02E02.2022.1080p.CR.WEB-DL.x264.AAC-ADWeb.mkv', 'torrent_name': 'Fumetsu.no.Anata.e.S02.2022.1080p.CR.WEB-DL.x264.AAC-ADWeb', 'torrent_subject': '2022年10月新番 致不灭的你 第二季 / 不滅のあなたへ 第02集 *内封简繁英多国软字幕*', 'torrent_id': 78545, 'torrent_hash': '83138a7b0410dca228838bbaabec9628bff51049', 'torrent_url': 'https://audiences.me/details.php?id=78545&hit=1', 'site_id': 'audiences', 'site_name': '观众'}}
Traceback (most recent call last):
  File "mbot/core/eventbus.py", line 65, in mbot.core.eventbus.EventBus.publish_event
  File "mbot/plugin/notify/notifylistener.py", line 139, in mbot.plugin.notify.notifylistener.NotifyListener.on_event
  File "mbot/core/__init__.py", line 220, in mbot.core.__init__.ServiceRegistry.call
  File "mbot/core/__init__.py", line 215, in mbot.core.__init__.ServiceRegistry.call
  File "/dependencies/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/dependencies/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/dependencies/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected int for dictionary value @ data['season_number']
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - INFO: Fumetsu.no.Anata.e.S02.2022.1080p.CR.WEB-DL.x264.AAC-ADWeb处理完毕。
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - INFO: 来自自定义订阅的下载，tmdb_id: 0 season_number:  douban_id: 0
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - INFO: 启用自动重命名整理
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - ERROR: 整理失败：'<' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "mbot/media/link/medialink.py", line 202, in mbot.media.link.medialink.MediaLink.link
  File "mbot/media/link/tvlink.py", line 357, in mbot.media.link.tvlink.TvLink.__handle__
  File "mbot/media/_mediarecognize.py", line 424, in mbot.media._mediarecognize._MediaRecognize.recognize_tv
  File "mbot/media/_mediarecognize.py", line 227, in mbot.media._mediarecognize._MediaRecognize.__search_query__
  File "mbot/media/_mediarecognize.py", line 171, in mbot.media._mediarecognize._MediaRecognize.__tv_multiple_result_filter__
TypeError: '<' not supported between instances of 'str' and 'int'
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - INFO: 已经通知plex重新扫描媒体库：动画
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - INFO: 通知媒体库刷新完成，tmdb_id: 97525 save_path: /plex/temp/动画-mr item_id: 2:致不灭的你
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - INFO: 致不灭的你 第季(2022) 第2集字幕下载 任务已经创建。
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - ERROR: Invalid data for service call scraper.get_image: {'tmdb_id': 97525, 'media_type': 'tv', 'season_number': ''}
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - ERROR: on_event error: NotifyListener event: {'event_type': 'DownloadCompleted', 'data': {'target_path': '/plex/temp/动画-mr', 'sub_id': 1, 'uid': '1', 'tmdb_id': '97525', 'media_type': 'TV', 'season_number': '', 'season_year': 2022, 'year': 2022, 'episodes': [2], 'file_size': '475.42 MB', 'media_stream': {'resolution': '1080p', 'media_source': 'WEB-DL', 'media_codec': 'x264', 'media_audio': ['AAC'], 'release_team': 'ADWeb'}, 'source_path': '/plex/download/动画/Fumetsu.no.Anata.e.S02.2022.1080p.B-Global.WEB-DL.x264.AAC-ADWeb/Fumetsu.no.Anata.e.S02E02.2022.1080p.B-Global.WEB-DL.x264.AAC-ADWeb.mkv', 'torrent_name': 'Fumetsu.no.Anata.e.S02.2022.1080p.B-Global.WEB-DL.x264.AAC-ADWeb', 'torrent_subject': '2022年10月新番 致不灭的你 第二季 / 不滅のあなたへ 第02集 *内封简繁英多国软字幕*', 'torrent_id': 78544, 'torrent_hash': 'f9ac9392aec134a226ebd2b5af180e420804a882', 'torrent_url': 'https://audiences.me/details.php?id=78544&hit=1', 'site_id': 'audiences', 'site_name': '观众'}}
Traceback (most recent call last):
  File "mbot/core/eventbus.py", line 65, in mbot.core.eventbus.EventBus.publish_event
  File "mbot/plugin/notify/notifylistener.py", line 139, in mbot.plugin.notify.notifylistener.NotifyListener.on_event
  File "mbot/core/__init__.py", line 220, in mbot.core.__init__.ServiceRegistry.call
  File "mbot/core/__init__.py", line 215, in mbot.core.__init__.ServiceRegistry.call
  File "/dependencies/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/dependencies/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/dependencies/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected int for dictionary value @ data['season_number']
2022/10/31 18:31:01 - ThreadPoolExecutor-5_1 - INFO: Fumetsu.no.Anata.e.S02.2022.1080p.B-Global.WEB-DL.x264.AAC-ADWeb处理完毕。
```

### 健康检查

![](https://img.u8.pw/2022/10/31/4222898a888b6.png)

**Comment by kolicime** [comment]
找到原因了，是因为自定义下载季号留空导致的问题。希望后面能允许不设定季号。既然对标的是rss，还是超级版，那就应该允许类似rss全站的操作。目前测试的问题是，如果把季号填为0，在下载完之后会识别失败。但是下载记录里面却又是正确识别了的，我认为可以把这个强制指定季号的设置变为可选的，而非在不允许留空的情况下强制启用

**Comment by pofey** [comment]
你这个不像是留空，像是留了个空字符串？

**Comment by kolicime** [comment]
> 你这个不像是留空，像是留了个空字符串？

今天又确认了一下，确实是留空的

![IMG_20221105_095915.jpg](https://img.u8.pw/2022/11/05/198b41eed7cd3.jpg)
