### ISSUE TITLE
[缺陷]: 无法纠正《胜者即是正义》剧识别信息，日志报错提示“请联系作者”

### ISSUE THREAD

**Issue by tinymins** [pofey/movie_robot#782]
### 当前程序版本

1.7.5

### 问题描述

搜素下载 《胜者即是正义》 第二季后，识别错误，纠错无法正常就行，有错误提示“请联系作者”。

尝试对别的剧就行手动识别，未出现异常，说明不是通用逻辑异常。

### 重现步骤

资源： https://kp.m-team.cc/details.php?id=517095&hit=1
tmdb链接： https://www.themoviedb.org/tv/46234-legal-high?language=zh-CN

1. 搜索并下载上述资源
2. 识别错误

![image](https://user-images.githubusercontent.com/1808990/200186508-79617012-1538-446c-86a5-2b6b571fc589.png)

3. 点击纠正按钮填入正确数据

![image](https://user-images.githubusercontent.com/1808990/200186412-253385a2-52c0-4afc-8577-8ae989cf099f.png)

4. 点击确定，界面卡住，日志抛出异常

### 发生问题时系统日志

```shell
2022/11/07 01:45:21 - Thread-223 - ERROR: 请求出错：远程服务异常，请联系作者
Traceback (most recent call last):
  File "mbot/register/controller_register.py", line 43, in mbot.register.controller_register.login_required.wrapper.decorator
  File "mbot/controller/downloadcontroller.py", line 243, in mbot.controller.downloadcontroller.reanalyse
  File "mbot/service/downloadservice.py", line 139, in mbot.service.downloadservice.DownloadService._analyze_and_setmodel
  File "mbot/media/_mediarecognize.py", line 437, in mbot.media._mediarecognize._MediaRecognize.recognize_tv
  File "/dependencies/tenacity/__init__.py", line 326, in wrapped_f
    return self(f, *args, **kw)
  File "/dependencies/tenacity/__init__.py", line 406, in __call__
    do = self.iter(retry_state=retry_state)
  File "/dependencies/tenacity/__init__.py", line 351, in iter
    return fut.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/dependencies/tenacity/__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
  File "mbot/register/__init__.py", line 436, in mbot.register.__init__._RemoteApi.get_media_by_tmdb_id
  File "mbot/register/__init__.py", line 400, in mbot.register.__init__._RemoteApi.un_code
mbot.register.__init__.RemoteApiErrorException: 远程服务异常，请联系作者
```

### 健康检查

![image](https://user-images.githubusercontent.com/1808990/200186688-fdf22c26-a550-45f9-8c18-c21a71fd7b1b.png)

PS： 

1. 白天 plex 忘记启动。
2. 前天该资源开始下载就纠错异常。

**Comment by pofey** [comment]
可以了，跟韩版的剧冲突了
