### ISSUE TITLE
[缺陷]: 安装插件豆瓣片单订阅，重启mr后无法进入mr

### ISSUE THREAD

**Issue by zjgithub413** [pofey/movie_robot#785]
### 当前程序版本

1.7.13

### 问题描述

安装插件豆瓣片单订阅，重启mr后无法进入mr，在进入插件文件夹删除插件后恢复

### 重现步骤

1.安装豆瓣片单订阅插件；
2.重启mr；
3.重启后无法在浏览器进入mr，并在网页显示：
Service Unavailable   The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
4.查看日志显示：
2022/11/15 11:16:42 - MainThread - INFO: 插件豆瓣电影片单订阅新增功能指令：豆瓣片单订阅
2022/11/15 11:16:42 - MainThread - ERROR: Uncaught exception
Traceback (most recent call last):
  File "/app/start.py", line 79, in <module>
    Bootstrap(workdir).start()
  File "mbot/bootstrap.py", line 76, in mbot.bootstrap.Bootstrap.start
  File "mbot/register/mbot_register.py", line 75, in mbot.register.mbot_register.setup_movie_bot_plugin
  File "mbot/core/plugins/pluginloader.py", line 78, in mbot.core.plugins.pluginloader.PluginLoader.load
  File "mbot/core/plugins/pluginloader.py", line 135, in mbot.core.plugins.pluginloader.PluginLoader.setup
  File "/data/plugins/doubanlist_sub/douban_sub.py", line 23, in after_setup
    'Cookie': server.config.douban.cookie
AttributeError: 'MovieBotServer' object has no attribute 'config'
5.手动删除plugins中的插件；
6.重启mr后恢复正常。

### 发生问题时系统日志

```shell
2022/11/15 11:16:42 - MainThread - INFO: 插件豆瓣电影片单订阅新增功能指令：豆瓣片单订阅
2022/11/15 11:16:42 - MainThread - ERROR: Uncaught exception
Traceback (most recent call last):
  File "/app/start.py", line 79, in <module>
    Bootstrap(workdir).start()
  File "mbot/bootstrap.py", line 76, in mbot.bootstrap.Bootstrap.start
  File "mbot/register/mbot_register.py", line 75, in mbot.register.mbot_register.setup_movie_bot_plugin
  File "mbot/core/plugins/pluginloader.py", line 78, in mbot.core.plugins.pluginloader.PluginLoader.load
  File "mbot/core/plugins/pluginloader.py", line 135, in mbot.core.plugins.pluginloader.PluginLoader.setup
  File "/data/plugins/doubanlist_sub/douban_sub.py", line 23, in after_setup
    'Cookie': server.config.douban.cookie
AttributeError: 'MovieBotServer' object has no attribute 'config'
```

### 健康检查

![微信截图_20221115111902](https://user-images.githubusercontent.com/106440008/201818471-8afdf9d4-680e-42ed-bf55-e4ef3f0371e8.png)

**Comment by WWWWM03** [comment]
![image](https://user-images.githubusercontent.com/74545085/202191906-bd8dcf32-3e17-4957-b28a-c5afa9247657.png)
升级机器人版本
