### ISSUE TITLE
[缺陷]: 关于整理资源，文件无法硬链接到目标目录

### ISSUE THREAD

**Issue by cszs1986** [pofey/movie_robot#793]
### 当前程序版本

1.912

### 问题描述

我订阅的中国奇谭，更新到第五集的时候，从mikanani下载的，plex显示不可用，查看文件确是硬链接过去了，然后删除了硬链接文件，手动整理，显示整理成功，但目标文件夹没有文件，只有文件的图片和nfo文件。
![2](https://user-images.githubusercontent.com/30801827/213922155-61f96442-4a16-40db-8de1-edbe2cd379f4.png)

还有我plex有的订阅，下载后的播放显示转码失败，不知道是不是和ffmpeg解码失败有关？？？

### 重现步骤

整理整理，手动整理

### 发生问题时系统日志

```shell
2023/01/22 22:26:16 - Thread-14561 - INFO: 完成剧集 中国奇谭 的NFO文件生成，路径：/video/MovieRobot/plex_tv/中国奇谭 (2023)/tvshow.nfo
2023/01/22 22:26:16 - Thread-14561 - INFO: 开始刮削图片数据，影片信息：{'tmdb_id': '139162', 'imdb_id': None, 'douban_id': '35674355', 'media_type': 'TV', 'content_path': '/video/MovieRobot/plex_tv/中国奇谭 (2023)', 'season_index': None, 'episode_index': None, 'episode_filename': None, 'tvdb_id': None}
2023/01/22 22:26:16 - Thread-14561 - INFO: /video/MovieRobot/plex_tv/中国奇谭 (2023)已经存在图片，跳过下载
2023/01/22 22:26:18 - Thread-14561 - ERROR: ffmpeg解码失败：/video/MovieRobot/plex_tv/中国奇谭 (2023)/Season 1/中国奇谭 S01E05.mp4

Traceback (most recent call last):
File "mbot/media/link/tvlink.py", line 325, in mbot.media.link.tvlink.TvLink.__create_episode_nfo__
File "mbot/media/videofileinfo.py", line 46, in mbot.media.videofileinfo.VideoFileInfo.__init__
File "/dependencies/ffmpeg/_probe.py", line 23, in probe
raise Error('ffprobe', out, err)

ffmpeg._run.Error: ffprobe error (see stderr output for detail)

2023/01/22 22:26:18 - Thread-14561 - INFO: 完成剧集第1季第5集小满的NFO文件生成，路径：/video/MovieRobot/plex_tv/中国奇谭 (2023)/Season 1/中国奇谭 S01E05.nfo
2023/01/22 22:26:18 - Thread-14561 - INFO: 开始刮削图片数据，影片信息：{'tmdb_id': 139162, 'imdb_id': None, 'douban_id': None, 'media_type': 'TV', 'content_path': '/video/MovieRobot/plex_tv/中国奇谭 (2023)/Season 1', 'season_index': 1, 'episode_index': 5, 'episode_filename': '中国奇谭 S01E05.mp4', 'tvdb_id': None}
2023/01/22 22:26:18 - Thread-14561 - INFO: 开始下载图片：https://image.tmdb.org/t/p/original/nvj9xaDQAKFQtDUn5kYurjyA33E.jpg 保存至：/video/MovieRobot/plex_tv/中国奇谭 (2023)/Season 1/中国奇谭 S01E05-thumb.jpg
2023/01/22 22:26:20 - Thread-14561 - INFO: TV图片下载完毕。
```

### 健康检查

![1](https://user-images.githubusercontent.com/30801827/213921689-230f82e7-afbe-4805-bdc4-755a170d7c21.png)

**Comment by cszs1986** [comment]
第五话的视频信息：

General
Complete name                  : \\Truenas\e\MovieRobot\tv\第5话-小满.mp4
Format                         : MPEG-4
Format profile                 : Base Media
Codec ID                       : isom (isom/avc1)
File size                      : 1.52 GiB
Duration                       : 20 min 26 s
Overall bit rate mode          : Variable
Overall bit rate               : 10.6 Mb/s
Encoded date                   : UTC 2023-01-22 02:34:43
Tagged date                    : UTC 2023-01-22 02:34:43
Writing application            : GPAC-2.1-DEV-rev629-g50753f76-master

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L5.1
Format settings                : CABAC / 6 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 6 frames
Codec ID                       : avc1
Codec ID/Info                  : Advanced Video Coding
Duration                       : 20 min 26 s
Bit rate                       : 10.4 Mb/s
Maximum bit rate               : 41.5 Mb/s
Width                          : 4 096 pixels
Height                         : 1 716 pixels
Display aspect ratio           : 2.40:1
Frame rate mode                : Constant
Frame rate                     : 24.000 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.062
Stream size                    : 1.48 GiB (98%)
Title                          : avc#video@GPAC2.1-DEV-rev629-g50753f76-master
Encoded date                   : UTC 2023-01-22 02:34:43
Tagged date                    : UTC 2023-01-22 02:34:46
Color range                    : Limited
Color primaries                : BT.709
Transfer characteristics       : BT.709
Matrix coefficients            : BT.709
mdhd_Duration                  : 1227042
Codec configuration box        : avcC

Audio
ID                             : 2
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Codec ID                       : mp4a-40-2
Duration                       : 20 min 26 s
Bit rate mode                  : Variable
Bit rate                       : 231 kb/s
Maximum bit rate               : 313 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 46.875 FPS (1024 SPF)
Compression mode               : Lossy
Stream size                    : 33.7 MiB (2%)
Title                          : aac#audio@GPAC2.1-DEV-rev629-g50753f76-master
Default                        : Yes
Alternate group                : 1
Encoded date                   : UTC 2023-01-22 02:34:45
Tagged date                    : UTC 2023-01-22 02:34:46
